### ISSUE TITLE
Provide bespoke page summaries for Slack unfurls, instead of the first sentence of the article

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#1040]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

Most if not all articles use the default behaviour

### What changes are you suggesting?

Related to #1039. Slack unfurls appear to default to the first paragraph of an article, capped at the first few sentences. We often have a header (e.g. `## Overview` for [ref](https://docs.getdbt.com/reference/dbt-jinja-functions/ref)) which is then all that gets rendered.

Docs could be significantly more valuable if they were smarter about what they displayed. That could be either handcrafted text for each article, or a smarter automatic selection - I don't know enough about Docusaurus to make a recommendation. 

When this and #1039 are done, I would hope to see this 
![image](https://user-images.githubusercontent.com/7335046/150462050-6e99b396-d767-406f-900c-1a05466bdeca.png)

turn into this:
![image](https://user-images.githubusercontent.com/7335046/150462593-3c883d26-0cdd-4ad3-995b-975197e5e90e.png)

**Comment by runleonarun** [comment]
@joellabes I started to capture this in an overall project for [updating site metadata](https://github.com/dbt-labs/product-docs-team/issues/10) .

For example, this page has a description (which is added [in the Description metadata](https://github.com/dbt-labs/docs.getdbt.com/edit/current/website/docs/dbt-cli/cli-overview.md)): https://docs.getdbt.com/dbt-cli/cli-overview and looks like this in Slack:

<img width="489" alt="Screen Shot 2022-02-06 at 1 21 37 PM" src="https://user-images.githubusercontent.com/3880403/152701930-8de63481-51e5-49c5-a72a-0c631876511b.png">

**Comment by runleonarun** [comment]
I changed this to a "content" label.

**Comment by runleonarun** [comment]
The Docs team has been removing h1s from the beginning of pages as we go. I am closing this issue as an ongoing effort that we're onboard with. Let me know if I should reopen or if there's anything lingering here.
