### ISSUE TITLE
Adding warehouse-specific tutorials into the Getting Started tutorial

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#1072]
### Contributions

- [x] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/tutorial/setting-up

### What part(s) of the page would you like to see updated?

We are reorganizing this information to make it easier to digest and find, but mainly adding some great warehouse-specific content to make it accessible to different users. And to get them started using dbt. 

* @Amy C, @Bobby B, @pat, and @coap finalize the content and get it onto this branch
* @runleonarun check out the layout and coding to help anyone who needs it.

## Why and why now? 
dbt Fundamentals currently assumes that the learner has a functioning data platform that they have access to. We don’t currently have formal instruction on how to set up RS/DB/SF/BQ to be ready to connect to dbt Cloud. This can make the course/dbt Cloud inaccessible to new folks (“well I don’t know how to set up any of these so I guess I’ll just abandon the course”) The urgency for us is to provide support to set up those prerequisite tools to be successful in the course. We could have those guides live on courses.getdbt.com behind an email login, but I thought it would be better for everyone to have this in a public space (docs/devhub/etc) and then saying “If you need help setting up {{ warehouse }}, check out these resources and then come back to the course.”

The new guides will most closely resemble the setting up page of the GS tutorial (https://docs.getdbt.com/tutorial/setting-up) but broken up by warehouse/adapter/flavors.

Outline:
- Getting Started with dbt
- Setting up your Environment (open to other names)
  - Setting up Big Query
  - Setting up Snowflake
  - Setting up RS
- etc.
- Creating a Project
- etc.

Here's the original [slack conversation](https://dbt-labs.slack.com/archives/C02G5V9JBHV/p1641480782003500)

**Comment by runleonarun** [comment]
@coapacetic I'm bringing the next steps for the [warehouse quickstarts ](https://github.com/dbt-labs/docs.getdbt.com/pull/1062) over here so we can collaborate on a new PR. 

**For future us and others:** we changed direction to leverage a new feature in docusaurus where we can reuse content. This feature enables us to provide individual guides but share same content across them, streamlining not only the guides, but their upkeep. Future Us will love this :) 

Kyle, what do y ou think about this outline for the guides? Heavily influenced by the [quickstart content type](https://github.com/dbt-labs/product-docs-team/blob/main/content-types.md#quickstart-guide).

```
## Introduction
Intro paragraph from Get started page. 

### Prerequisites

## Procedural sections (steps): 
Possible sections (we should standardize as much as possible, though OK for some differences):
- Set up the warehouse
- Create a project
- Load sample data 
- Connect project to warehouse
- Test connection 

## Further reading
- Link to learning courses
- what else?
```

**Comment by coapacetic** [comment]
🙌 First off, love the content types that you have going. That's super helpful to read through and know how you are thinking about things for the future of docs.

This looks rock solid for warehouse set up guides.  Nailing the TOC up front will make everything easier later.  Pumped for the reusable snippets!

**Open question:** What is the connective tissue between each of these quickstarts to the existing Getting Started Tutorial?  I imagine that this would be a link in further reading.  A subsequent question there is, "do we recreate the GS tutorial for SF, RS, and DB since it currently is based on BQ?"  We don't _need_ to do that work now since that would turn into a bigger topic, but it might be worth nailing down what we would eventually do on that front.

**Comment by codingisforlosers** [comment]
Potentially silly question here: any reason why we wouldn't use on-page tabbed navigation within the current 'setting up' page (with one tab per warehouse), as we do for cloud / CLI elsewhere in the tutorial?

We could link in the left sidebar to those anchor tabs (setting up -> BigQuery, Databricks etc) for easy direct navigation. 

 ![image](https://user-images.githubusercontent.com/16282439/158272982-8ccf9be1-ec82-4dc9-9786-d15543f2af6c.jpeg)

**Comment by runleonarun** [comment]
> Potentially silly question here: any reason why we wouldn't use on-page tabbed navigation within the current 'setting up' page (with one tab per warehouse), as we do for cloud / CLI elsewhere in the tutorial?

@krevitt @codingisforlosers  Not silly at all! I think the tabbed navigation is really powerful for code samples and smaller blocks. For an entire guide (or four!), it would get pretty messy, which would make the page difficult to maintain and difficult to edit. 

With four or more pretty big blocks of code right after each other potentially in several places in the same guide would result in a huge file. I'm also imagining a lot of clicking if your warehouse is not the default tab.

**Comment by runleonarun** [comment]
> Open question: What is the connective tissue between each of these quickstarts to the existing Getting Started Tutorial? I imagine that this would be a link in further reading.

@coapacetic This is important to talk about! I think a link in further reading, or even listing it as a prerequisite would be helpful. 

 Do you think people will be confused if we keep it the way it is and pair it with the warehouse GS guides?


> A subsequent question there is, "do we recreate the GS tutorial for SF, RS, and DB since it currently is based on BQ?" We don't need to do that work now since that would turn into a bigger topic, but it might be worth nailing down what we would eventually do on that front.

Definitely think this would be the best experience, and least confusing.

**Comment by krevitt** [comment]
I was thinking single tab for the entirety of the “setting up” section, so at the top of the page you select a warehouse and you’re off.
