### ISSUE TITLE
Setting up redshift to get started with dbt

### ISSUE THREAD

**Issue by coapacetic** [fishtown-analytics/docs.getdbt.com#1087]
This post would be a stable guide for getting the minimum effective set up on Redshift to start using dbt. This would support any developer who is:
- setting up dbt with Redshift
- completing the GS tutorial
- learning on courses.getdbt.com

**Comment by amychen1776** [comment]
Docs for this: https://docs.google.com/document/d/1x505_Jr9lUjewfK0TJBxBhOo_Il5SE8kQTz_-6b-khs/edit#
