### ISSUE TITLE
Setting up databricks to get started with dbt

### ISSUE THREAD

**Issue by coapacetic** [fishtown-analytics/docs.getdbt.com#1088]
This post would be a stable guide for getting the minimum effective set up on Databricks to start using dbt. This would support any developer who is:
- setting up dbt with Databricks
- completing the GS tutorial
- learning on courses.getdbt.com

**Comment by amychen1776** [comment]
@coapacetic are you thinking of getting started with dbt only on Cloud or on the CLI as well (CLI from what I see can be very annoying depending on if you're connecting to an interactive cluster or a SQL endpoint)

**Comment by coapacetic** [comment]
hmmm great question - I'd love to support both in the final version. Our
immediate need on training is to support dbt Cloud.

There are two sections to this that I'm thinking of:
- setting up databricks *before* connecting dbt (I think this would be
agnostic for CLI and Cloud)
- connecting dbt to databricks (sounds like it is easier for Cloud than CLI)

**Comment by amychen1776** [comment]
That makes sense! One recommendation I would make is that you don't want to seed the data. From what Jeremy has told me, it's a lot easier to upload those csv files. https://docs.databricks.com/data/data.html

**Comment by coapacetic** [comment]
🙌  @amychen1776 and I met today to get started on this!

👀  Follow our progress in the Google Doc here: [Getting started with Databricks for dbt Cloud](https://docs.google.com/document/d/1po6G2CGPAMLyJzWVUnIpmPmrIbdbJGRXL1-wl-996Dw/edit#heading=h.9i76bel94w5a)

**Comment by jasnonaz** [comment]
Status: Amy C and Coap are 50% of the way through a draft here

**Comment by jasnonaz** [comment]
Todo: Sync with @runleonarun on whether the four setup posts here are suited for being in Docs.

**Comment by coapacetic** [comment]
Update from @amychen1776 and I: We just wrapped up a complete draft of this post.  We will both be doing an async review, would love to get someone who _has not_ used Databricks before to give this a try to make sure this is clear for a totally new user. (note: Our current set up assumes that the reader has an AWS account to set up databricks)

**Comment by patkearns10** [comment]
I have never used Databricks and would be interested in testing. End of this week?

**Comment by coapacetic** [comment]
That'd be great! be as picky as possible! I'll add a task in Asana for
visibility - thanks Pat!
