### ISSUE TITLE
Setting up snowflake to get started with dbt

### ISSUE THREAD

**Issue by coapacetic** [fishtown-analytics/docs.getdbt.com#1089]
This post would be a stable guide for getting the minimum effective set up on Snowflake to start using dbt. This would support any developer who is:
- setting up dbt with Snowflake
- completing the GS tutorial
- learning on courses.getdbt.com

**Comment by amychen1776** [comment]
@bobbybirstockdbtlabs would be great to do this one :)

**Comment by jasnonaz** [comment]
Bobby + Coap taking this one
