### ISSUE TITLE
Remove the on-premises dbt Cloud documentation

### ISSUE THREAD

**Issue by amychen1776** [fishtown-analytics/docs.getdbt.com#1094]
### Contributions

- [x ] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

Through some magic of search engines, potential clients are stumbling upon on our on-premise docs. We no longer offer this as an solution and thus should [remove pages like this.](https://docs.getdbt.com/docs/dbt-cloud/on-premises/
).  [See this internal slack thread for more information](https://dbt-labs.slack.com/archives/C02NCQ9483C/p1644331177367659
)

### What changes are you suggesting?

We have already unlisted the pages so we need to figure out how to remove them outright. We have zip files of the docs to share with existing on-prem deployments so there's no need for us to host this anymore. But open to other suggestions!

**Comment by runleonarun** [comment]
@amychen1776 or @drewbanin where should redirects go? Maybe to the Enterprise docs?

**Comment by amychen1776** [comment]
@runleonarun I think that would make sense. This might be a very silly question but do we need redirects (is it because of past caching or something like that?). It would be good to make sure if they are considering on-prem, they know they should talk to our sales team.

**Comment by runleonarun** [comment]
This work was done here: https://github.com/dbt-labs/docs.getdbt.com/pull/2956
