### ISSUE TITLE
Add `--quiet` flag docs and `print` macro

### ISSUE THREAD

**Issue by ehmartens** [fishtown-analytics/docs.getdbt.com#1102]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/reference/global-configs.md
https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/reference/dbt-jinja-functions.md

### What part(s) of the page would you like to see updated?

I'd like to update the documentation to add info about the new global config that [PR-4701](https://github.com/dbt-labs/dbt-core/pull/4701) will create. Additionally, I'd like to add documentation for the `print` Jinja function that the PR creates.

**Comment by emmyoop** [comment]
Making a note that this change will come out with dbt-core v1.1.0.

**Comment by runleonarun** [comment]
Thank you @ehmartens and @emmyoop! I've added this to the docs project board!

**Comment by runleonarun** [comment]
@ehmartens Hello! The beta for v1.1 will be cut next week for this. Did you want to draft docs for this? I can review and edit them. One caveat is that we are adding versioning so the docs would need to be encapsulated in versioning code like this:

```
<VersionBlock firstVersion="1.1">

New content for `-- quiet` flag

</VersionBlock>
```

cc: @jtcohen6

**Comment by ehmartens** [comment]
Hi @runleonarun ! I'm so sorry for the delay on this. I'm happy to do this tomorrow morning (Us Eastern time) if there is still a need. Let me know! I can have a PR done by Noon US Eastern Time.

**Comment by runleonarun** [comment]
@ehmartens Apologies from me while I try to figure out a process for features created from the dbt community 😄 Anything you could provide would be helpful, even if unpolished. I can clean it up and publish it.
