### ISSUE TITLE
Support for multiple `unique_key` columns

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#1105]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

> updating [these docs](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#defining-a-uniqueness-constraint-optional) to mention support for multiple unique_key columns (and being aware that support will depend on[ database + strategy](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#what-is-an-incremental_strategy))

### What part(s) of the page would you like to see updated?

* https://github.com/dbt-labs/dbt-core/pull/4154
* https://github.com/dbt-labs/dbt-core/issues/4738

### Additional information

https://dbt-labs.slack.com/archives/C0131TY7EEA/p1644324413792749

**Comment by runleonarun** [comment]
Starter content from @VersusFacit:
* https://docs.google.com/document/d/1EzPYtXwhoEXO35UoAdhOFcDYb5JfEYuyIJ8B8Zi4Yp4/edit?usp=sharing

**Comment by jtcohen6** [comment]
@runleonarun @VersusFacit That doc is a great starting point! Let's aim to get a first cut of this live, since the functionality is already available in v1.1.0b1. I'm happy to take a crack at translating the recommendations in that doc into markdown changes, unless one of you is already on the case

**Comment by runleonarun** [comment]
Thank you @VersusFacit for the thoughtful starter content! I will spin up a PR for this.
