### ISSUE TITLE
Remove `data build tool`

### ISSUE THREAD

**Issue by amychen1776** [fishtown-analytics/docs.getdbt.com#1111]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/introduction

### What part(s) of the page would you like to see updated?

We no longer refer to dbt as data build tool so we should remove it from the docs site outside of a historical reference/easter egg.

**Comment by matthewshaver** [comment]
No longer able to find any references to "data build tool" in the published doc pages.  This appears to have been remedied so I am closing the issue.
