### ISSUE TITLE
Autocomplete snippets and update noget documentet

### ISSUE THREAD

**Issue by andhebor** [fishtown-analytics/docs.getdbt.com#1154]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

The doc is missing for "autocomplete snippets" is missing

### What part(s) of the page would you like to see updated?

The autocomplete snippets `__` is not mention in the documentation, hence it is hard to know it exists.
What does it include? Is it possible to add custom snippet?

The [dbt Cloud v1.1.42 - v1.1.44](https://docs.getdbt.com/docs/dbt-cloud/cloud-changelog#dbt-cloud-v1143-january-19th-2022) mention a update to the autocomplete snippet, but no where to be found what that update include? 

### Additional information

base on this: https://getdbt.slack.com/archives/CMZ2V0X8V/p1645181729334719?thread_ts=1637529446.217300&cid=CMZ2V0X8V

**Comment by runleonarun** [comment]
We've written this up as a [release note](https://docs.getdbt.com/docs/dbt-versions/release-notes/january-2022/ide-timeout-message)
