### ISSUE TITLE
BigQuery dataset is not public 

### ISSUE THREAD

**Issue by bendiktv2** [fishtown-analytics/docs.getdbt.com#1156]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/tutorial/setting-up

### What part(s) of the page would you like to see updated?

From the docs: 
> For this tutorial, we've created a public dataset in BigQuery that anyone can select from.

This dataset is not public anymore, but it probably should be.

**Comment by joellabes** [comment]
Hi @bendiktv2, thanks for opening this and sorry you're having trouble! I just tried querying the dataset and succeeded: 
![image](https://user-images.githubusercontent.com/7335046/155032249-82b1e68a-7761-4d28-a7c7-6ef44da10031.png)

Can you share the query you're running, and the error message you're seeing?

**Comment by bendiktv2** [comment]
I tried again today, and it worked now, but only if I set the "Processing location" to `US`.
If I set it to `EU`, then I get the error:
> Access Denied: Table dbt-tutorial:jaffle_shop.customers: User does not have permission to query table dbt-tutorial:jaffle_shop.customers.

Either the dataset should be opened up to be processed in `EU`, or maybe the documentation should do a better job of explaining the importance of the location, or instructions on how to set it.

**Comment by runleonarun** [comment]
Closing but will note this issue and update the docs in the next refresh.

**Comment by runleonarun** [comment]
Re-opening issues so we can address this using the information in the[ PR here](https://github.com/dbt-labs/docs.getdbt.com/pull/2738). or by making the dataset open to other countries? @patkearns10 do you know if this is possible?

**Comment by patkearns10** [comment]
Not my area of expertise, but poking around the docs, it seems Google confirms this and doesn't suggest a workaround: https://cloud.google.com/bigquery/public-data#public_dataset_locations

**Comment by runleonarun** [comment]
Closing this as we now link to the BigQuery docs and they mention EU datasets: https://docs.getdbt.com/quickstarts/bigquery?step=3
