### ISSUE TITLE
Publish 'Founding an Analytics Engineering Team' Article

### ISSUE THREAD

**Issue by gwenwindflower** [fishtown-analytics/docs.getdbt.com#1163]
@natesooter has finished his article per this issue from our archived repo, we just need to publish it https://github.com/dbt-labs/dbt-technical-blog-writing/issues/76

**Comment by johnblust** [comment]
@gwenwindflower I'm on it! I'll submit the PR to ganz today for his final approval

**Comment by johnblust** [comment]
@gwenwindflower I ended up needing permission to the doc. Just noticed I had access to the draft doc today. Do you know if there is an author bio pic @natesooter prefers?

**Comment by natesooter** [comment]
![headshot](https://user-images.githubusercontent.com/8442512/155359116-b9c43955-c465-470d-ac59-84bb7f09622c.jpg)

@johnblust just uploaded a headshot here, let me know if you need anything else!

**Comment by natesooter** [comment]
@jasnonaz Do you have an estimate for when the blog will be published?

**Comment by jasnonaz** [comment]
Hi @natesooter! We should be ready to publish in the next few days (hopefully tomorrow) - just wrapping up the PR and getting ready to publish https://github.com/dbt-labs/docs.getdbt.com/pull/1172

**Comment by natesooter** [comment]
@jasnonaz That sounds great. Can't wait to see this full story shared and appreciate your partnership in getting the story ready for publishing!

**Comment by natesooter** [comment]
And @johnblust thank you for your work migrating this from the Google doc format onto the blog itself. It looks great!

**Comment by gwenwindflower** [comment]
Closed by #1172
