### ISSUE TITLE
Add workaround for run error when to upgrading to v 1.0

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#1166]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-1-0-0

### What part(s) of the page would you like to see updated?

Add a Troubleshooting section or page with the following information:

Snowflake connected users might receive the following errors in their prod runs after upgrading to 1.0:

```
Could not find profile named 'user'
Runtime Error
 Could not run dbt
```

Solution:
Re-enter the private key in the product environment -> production -> settings

### Additional information

[[Internal] Slack conversation link](https://dbt-labs.slack.com/archives/C02NCQ9483C/p1645533811005239) for context.

**Comment by mirnawong1** [comment]
dbt cloud issue is here: https://github.com/dbt-labs/dbt-cloud/issues/4943

**Comment by runleonarun** [comment]
This issue is no longer valid now that we've deprecated versions before 1.0
