### ISSUE TITLE
Re-work source freshness's "snapshot" wording in the docs as it's deprecated

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#1210]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Site wide effort

### What part(s) of the page would you like to see updated?

All mentions of snapshots or snapshotting.

@joellabes mentioned in his[ review here](https://github.com/dbt-labs/docs.getdbt.com/pull/1037#discussion_r793244822):
"Snapshotting" terminology is actually deprecated (we have another feature called snapshots and this was confusing - see [the info box on this page](https://docs.getdbt.com/reference/commands/source)). This might need a wider re-work?

**Comment by joellabes** [comment]
To be clear: there are still snapshots completed by the `dbt snapshot` command. But there used to be a thing called "source freshness snapshots" which had absolutely nothing to do with the SCD-2 creation process that `dbt snapshot` does. 

It's the second version (`dbt source snapshot-freshness`) which has been renamed for clarity
