### ISSUE TITLE
February #leading-data-teams discussion write-up

### ISSUE THREAD

**Issue by KiraFuruichi** [fishtown-analytics/docs.getdbt.com#1233]
### **Contact Details**

@KiraFuruichi 

### **This issue is being created to create a marketing approved community recap piece.**

- [x]  I am directly creating this issue for a marketing-approved community recap piece.

### **Link to the community artifact/source material you are referencing.**
Kira's Jamboard (https://jamboard.google.com/d/1V_3eq0YGsAFx4pwQ5029vKMpSW9al4abN3RH-HWY5ks/viewer?f=2) for the event

### **Link to the initial outline we will develop through this Issue.**
https://docs.google.com/document/d/1f6EmP_bRRiZ9IrYFe8LCw618kFUHcWljXcRAj6h9iy4/edit

**Comment by KiraFuruichi** [comment]
@johnblust the outlines were a little bare bones, so here's an actual draft with a little more content: https://docs.google.com/document/d/1nrb-Swg2cM4ualXfv5EBegHhG3pLyGH5vuP_JRuDaJc/edit

**Comment by KiraFuruichi** [comment]
@johnblust thank you for the awesome Loom and first editing pass. Finished watching the loom and totally agree that a graphic/image would be great to break up the text. I was thinking of stylizing the Jamboard that was used for discussion. What do you think?

**Comment by johnblust** [comment]
@KiraFuruichi Some questions I like to ask myself when considering a graphic is:

- Does this graphic help readers conceptualize something that would otherwise take a lot of words?
- Does increase the content's value?

In this case, while the whiteboard is a cool piece of history, I'm having trouble saying "Yes" to either of those questions. It feels like it would be an accessory piece to the content, rather than intrinsically adding value to it. For that reason, I'm going to suggest leaving it out. Let me know if I'm missing something and you disagree!

If we can't find an opportunity to use a graphic at all, that's okay too :) not every post calls for one

**Comment by KiraFuruichi** [comment]
Yeah that's a great point! I was thinking it could potentially aid in visualizing the Lean-Coffee format and voting system, but it's not directly relevant to the actual data content in the post. I'm always a fan of breaking up text content with something different, but considering this is ~1k words, I don't think we need them.

**Comment by KiraFuruichi** [comment]
@krevitt it would be great if you could take a look at the draft (second link in this thread) from a technical perspective to make sure everything sounds sound!

**Comment by krevitt** [comment]
> @krevitt it would be great if you could take a look at the draft (second link in this thread) from a technical perspective to make sure everything sounds sound!

Thanks gave it a read!  Overall is great, left a few comments - would be great to layer on your personal perspective here (since it's a blog post, feel free to inject your own opinions / experience / takeaways).

**Comment by KiraFuruichi** [comment]
Awesome, thanks for the feedback!

**Comment by johnblust** [comment]
Just finished going through! Looks good -- just suggested a few small changes. Also [made a short Loom](https://www.loom.com/share/889dc8d2916a4d0a9852477ec505fe12) to explain what I did this editing round to kind of close the loop on the process we got going here.

Let me know when you're done and I'll give it one last pass before it's ready to ship

**Comment by KiraFuruichi** [comment]
Hey @johnblust thanks for the great editing pass and loooooooom! Brought in most of your suggestions and responded to your questions, but have some follow-up questions I left in the doc. thx!

**Comment by johnblust** [comment]
I resolved those q's. This has a green light in my book!

**Comment by KiraFuruichi** [comment]
Closing this issue out for now
