### ISSUE TITLE
Q1 Community Slack Thread Write-Up

### ISSUE THREAD

**Issue by KiraFuruichi** [fishtown-analytics/docs.getdbt.com#1234]
### **Contact Details**

@KiraFuruichi

### **This issue is being created to create a marketing approved community recap piece.**

- [x]  I am directly creating this issue for a marketing-approved community recap piece.

### **Link to the community artifact/source material you are referencing.**
https://getdbt.slack.com/archives/C0VLZPLAE/p1643161237258600

### **Link to the initial outline we will develop through this Issue.**
https://docs.google.com/document/d/1k7LaPbJ0XHBaXQX-VK-MUSlQsfG1lbohCr-X9dcEDkM/edit

**Comment by KiraFuruichi** [comment]
@johnblust the outline was a little bare bones so here's a draft with a little more content: https://docs.google.com/document/d/1qymqm9yJBkQBXoqZhaxR8Z8FGwVZrZSnfU_wrIwNO7M/edit

**Comment by KiraFuruichi** [comment]
@krevitt it would be great if you could take a look at the draft (second link in this thread) from a technical perspective to make sure everything sounds sound! ty!

**Comment by krevitt** [comment]
Wow this is wonderful - something I could see data people handing off to their backend dev colleagues

**Comment by johnblust** [comment]
Did a line editing pass for this one! Lmk when it's ready for a final review, and then this can ship!!

**Comment by KiraFuruichi** [comment]
Thx @johnblust !! Left a handful of outstanding qs/comments -- lmk what you think!!

**Comment by johnblust** [comment]
This one has a green light for publication me as well!
