### ISSUE TITLE
[Ported from technical-writing repo] Making dbt Cloud API calls using dbt-cloud-cli

### ISSUE THREAD

**Issue by krevitt** [fishtown-analytics/docs.getdbt.com#1236]
### Contact Details

stumlelius

### This issue is being created to promote an approved Discussion.

- [ ] I am promoting this issue from an approved Discussion and will link it below.

### Link to the Discussion this Issue is promoting.

https://github.com/dbt-labs/dbt-technical-blog-writing/issues/79

### If you're promoting this from an 'I want to write about...' Discussion, you can copy over the answers to the following questions. Otherwise, please answer these questions below

What's your key point?
Discuss the topics that we agreed together with Amy and Jason. Also see the initial idea https://github.com/dbt-labs/dbt-technical-blog-writing/discussions/62.

Prior art:
https://discourse.getdbt.com/t/triggering-a-dbt-cloud-job-in-your-automated-workflow-with-python/2573
https://discourse.getdbt.com/t/making-dbt-cloud-api-calls-using-the-dbt-cloud-cli/3543
Link to notes / outline / draft:
https://docs.google.com/document/d/1_BhfeA36YyTtaydRXUkl-SZp1zplhDR5IjhoGIWXOiU/edit?usp=sharing

Any open questions / requests for help from the group?
I'm not yet sure how the example use case "Creating a data catalog from dbt Cloud artifacts" will be constructed and I'd love to hear your thoughts and ideas on the topic!

### Link to the initial outline we will develop through this Issue.

Completed first draft here:
https://docs.google.com/document/d/1_BhfeA36YyTtaydRXUkl-SZp1zplhDR5IjhoGIWXOiU/edit#heading=h.p7hgnl4qm52y

**Comment by krevitt** [comment]
@johnblust this is ready for an edit from you

**Comment by johnblust** [comment]
Hey @stumelius I gave your content a final editing pass, and I think it looks great! I left some suggestions for  small grammatical changes and some prompt questions at the end of the content to help you flesh out a short conclusion section for the article. Let me know your thoughts on those suggestions! If something doesn't make sense or you disagree, let's chat about it!

**Comment by stumelius** [comment]
Thanks for your review @johnblust! I accepted all your grammatical suggestions (I guess I need to level up my comma game 😁). Also, I reviewed your "Parting thoughts & other endpoints" suggestions and left a few comments in the Google Doc.

**Comment by stumelius** [comment]
Just added:

* a paragraph on composite commands under the Motivation section
* summary at the end

**Comment by johnblust** [comment]
@stumelius I went through and responded to your comments. After you take a look at those, I think we're ready to schedule this post for publication!!!! :)

**Comment by stumelius** [comment]
@johnblust Awesome! Let's move forward to publication 🙌

**Comment by johnblust** [comment]
Awesome!! Does May 3rd work for you as a release date?

Also, have you ever contributed content to dbt Labs before? If not, I'll not to create an author profile for you. To do that, I would need your preferred display name, headshot, Job title and company name, and social media handles.

**Comment by stumelius** [comment]
May 3rd works great! I haven't contributed before so I'll need a profile:


* Display name: Simo Tumelius
* Headshot:  ![simo_1500x1500](https://user-images.githubusercontent.com/11061506/163001430-c09f1ef8-f982-4113-b0af-7040cae6f115.jpg) (is this headshot-ty enough?)
* Job title: Freelance Data and Analytics Engineer
* Social media: not a fan of social media so just linkedin https://www.linkedin.com/in/simo-tumelius-00a27a162/ 😁

**Comment by johnblust** [comment]
That's a great headshot if I've ever seen one, @stumelius lol! I'll get a PR together this week and get this scheduled for publication :) Let me know if you have any questions in the meantime

**Comment by johnblust** [comment]
Just a reminder that we're publishing your piece tomorrow @stumelius :) We will be announcing your post's publication on our LinkedIn and Twitter on Thursday May 5th if you want to coordinate a social media push on your personal pages as well

**Comment by stumelius** [comment]
@johnblust Thanks for the reminder. Excited to have it published! :)
