### ISSUE TITLE
Optimizing dbt models with redshift

### ISSUE THREAD

**Issue by johnblust** [fishtown-analytics/docs.getdbt.com#1239]
### Contact Details
@christineberger 

### This issue is being created to promote an approved Discussion.

- [x]  I am promoting this issue from an approved Discussion and will link it below.

### Link to the Discussion this Issue is promoting.
Draft ready here, discussed in [this closed issue](https://github.com/dbt-labs/dbt-technical-blog-writing/issues/65#issuecomment-1068214152):
https://dbtlabs.notion.site/Optimizing-dbt-Models-with-Redshift-Configurations-3a9c46a0b84c462ebc8a188c562b3499

**Comment by johnblust** [comment]
Hey @christineberger, I'll be giving your draft an editing pass this week for structure & clarity. I'll let you know when I've finished up so you can take a look at some of my feedback :) Excited to get this one shipped!!

**Comment by christineberger** [comment]
Thanks @johnblust! 🙌  =)

**Comment by johnblust** [comment]
Porting over this comment from notion bc I should have left it here instead lol :):

> This content is fantastic!! Feel like we’re almost at the finish line. I left some comments throughout the doc for the line-by-line changes, but the big changes are structural. [I made this Loom video](https://www.loom.com/share/9463b054c1d940978a10d0bc3ee2b476) talking through the changes I made so they are (hopefully) easier to see why I made those. I am notorious for talking slow, so feel free to watch at 1.5x or 2x speed lol.
> 
> Two things I think we should talk about aside from the draft:
> 
> **The title** - feel like we can get more specific. Shared some thoughts at the end of the video. Lmk what you think.
> 
> **The images** — We could turn the busy ones (in the handling joins section) into gifs to make it more legible. Would love to get your thoughts on that.
> 
> Overall, super solid. Great job!!

**Comment by johnblust** [comment]
@christineberger I just went through and responded to some of your comments based on my suggestions. Let me know what ya think! Feeling like we're getting closer to published 🥳

**Comment by johnblust** [comment]
@christineberger Also, we should find some time next week to talk through how you would want these gifs/images to look. I'll need to write up a design brief for our web design agency & I want to make sure I'm conveying your vision correctly.
