### ISSUE TITLE
How to find under tested and under documented models and enforce dbt project quality rules

### ISSUE THREAD

**Issue by b-per** [fishtown-analytics/docs.getdbt.com#1243]
### Contact Details

benoit.perigaud@dbtlabs.com

### This issue is being created to promote an approved Discussion.

- [X] I am promoting this issue from an approved Discussion and will link it below.

### Link to the Discussion this Issue is promoting.

https://github.com/dbt-labs/docs.getdbt.com/discussions/1138

### If you're promoting this from an 'I want to write about...' Discussion, you can copy over the answers to the following questions. Otherwise, please answer these questions below

1. _What is the main problem you are solving? What is your solution?_
  Testing and documentation are the backbones of a healthy and reliable dbt project and we recommend to do a unique and not null test on all models at the minimum. The problem is that for large projects where the rules have not been enforced from the beginning it can be difficult to understand what needs to be done to bring the project to a better state and to avoid future issues.

3. _Why should the reader care about this problem? Why is your solution the right one?_
  Models untested and underdocumented can bring confusion and lead to wrong data being made available to end users. Having an approach and tools to go through the process of fixing the lack of tests and enforcing tests going forward will make dbt users more confident about the quality of their pipeline and will allow them to focus on more value added tasks 

5. _Can you list the steps of your solution for the reader here?_
  - find the current models that should be documented/tested
     - Decide what needs to be documented/tested (opinionated)
     - Document/test the models that are lacking such information. This can be done manually in YAML (potentially time consuming and error prone) or using the tool [Tangata](https://github.com/ciejer/tangata_local) created by Chris Jenkins
  - setup automated tests to prevent the rules to be broken, for example leveraging [pre-commit hooks](https://github.com/offbi/pre-commit-dbt)

4. _Are there any resources that helped inspire or inform your idea?_
Quite a few threads on the debt Slack that ask how to setup automated checks on the quality of a dbt project + personal experience of wanting to increase the test coverage of a big project without knowing where to start

5. _Are there other existing solutions that solve the problem, and if so, how is this solution better or different?_
Tools like dbt_meta_testing also allow users to check if a dbt project is following some predefined rules. This article is not so much about defining a new solution to a problem but more how to stitch together tools that have been created by the community

### Link to the initial outline we will develop through this Issue.

FigJam we can go through together
![image](https://user-images.githubusercontent.com/8754100/158602478-fa7dbe71-f186-4ae9-a782-25f7202fc6f9.png)

**Comment by jasnonaz** [comment]
@johnblust want to bump this one for when you're back from retreat - the [draft](https://docs.google.com/document/d/1b1fQWzWUUHLggtTix3TaS9HnVxUMfp5QVRt2TTPPcPE/edit) is super polished and would be awesome to get this into the world.

**Comment by johnblust** [comment]
This is fantastic, Benoit. Left a few comments in the draft, but otherwise I think this will be good to go!

**Comment by KiraFuruichi** [comment]
Hey @b-per @johnblust are we good to close this Issue since I think this is related the pre-commit article that was published a few months ago? :)

**Comment by b-per** [comment]
Yes. It was the article you mentioned
