### ISSUE TITLE
Glossary: CTE

### ISSUE THREAD

**Issue by KiraFuruichi** [fishtown-analytics/docs.getdbt.com#1246]
### **Contact Details**

@KiraFuruichi

### **This issue is being created to create a marketing approved community recap piece.**

- [x]  I am directly creating this issue for a marketing-approved community recap piece.

### **Link to the community artifact/source material you are referencing.**
N/A - The notion doc Content Briefs is where information for the different Glossary terms can be found.

### **Link to the initial outline we will develop through this Issue.**
https://docs.google.com/document/d/1yUgZoJod8QB0D5Yp6hxf1QjFBYSadj2scyB75T-e2OE/edit

I know I need to fix examples with whatever dataset we want to end up using, but want to get an outline I can build off of first.

**Comment by KiraFuruichi** [comment]
@krevitt can I get your thoughts on the main example I've got for this? TY in advance!! https://docs.google.com/document/d/1yUgZoJod8QB0D5Yp6hxf1QjFBYSadj2scyB75T-e2OE/edit#

**Comment by krevitt** [comment]
Added a couple notes there - in general that’s a great example, my comments are mostly recommendations to simplify even further
