### ISSUE TITLE
Don't show latest patch for the current released minor version of Core

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#1249]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/core-versions#future-versions

### What part(s) of the page would you like to see updated?

The current patch of 1.0.x is listed as 1.0.1, which is 3 patches behind. 

I doubt we're going to remember to keep this perfectly up to date with every patch release. What could we do instead? 
1. Remove the column altogether
1. Is there a link that will always resolve to 1.0.latest on PyPI or GitHub that we could use instead?
1. Only populate the column for a minor version when it transitions to Critical Support, at which point it will (hopefully) never need to change again
1. Set each one as a variable, if we need to use it in many places? Still needs to be manually managed, but perhaps the increased surface area increases the likelihood that it actually happens
2. Add updating this value to the release checklist for patch versions

My vote is for option 2 if it's possible, or otherwise option 3 seems the most pragmatic.

### Additional information

@jtcohen6 interested in your thoughts here!

**Comment by jtcohen6** [comment]
@joellabes Such a good callout. I'll spend 10 minutes trying to write JS for option 2, and then inevitably opt for 3. Assigning myself to tackle this at the same time I do #1217
