### ISSUE TITLE
Why Focus on Model Naming Conventions?

### ISSUE THREAD

**Issue by johnblust** [fishtown-analytics/docs.getdbt.com#1270]
### Contact Details

@patkearns10

### This issue is being created to promote an approved Discussion.

- [ ] I am promoting this issue from an approved Discussion and will link it below.

### Link to the Discussion this Issue is promoting.

This article predates the Discussion system, and has been outlined and drafted already. It's starting directly as an issue.

### If you're promoting this from an 'I want to write about...' Discussion, you can copy over the answers to the following questions. Otherwise, please answer these questions below

This article predates the Discussion system, and has been outlined and drafted already. It's starting directly as an issue. https://github.com/dbt-labs/dbt-technical-blog-writing/issues/68#event-5806117853

### Link to the initial outline we will develop through this Issue.

https://docs.google.com/document/d/1u4KUEdj_Ff0k6Llsal8eguPoQ2rQpE5Q2tQeRw8HGm0/edit?usp=sharing

**Comment by johnblust** [comment]
Hey @patkearns10, I went through and added some prompts throughout the draft to help you flesh out some areas of this content that are lacking due to the fact that this was originally part of another piece of content. I also [made a Loom](https://www.loom.com/share/292e3ba05b3c4193a952bbb029136737) running through how I made some of those decision. LMK if you have any questions :)!!

@ me here when you're ready for me to give this another editing pass.

**Comment by patkearns10** [comment]
@johnblust 
I completed the rest. Let me know how it reads!
The length of the article will decrease once we take out the prompts, but please let me know if you want me to add more or less context -- I tried to not over-elaborate on anything.

**Comment by johnblust** [comment]
@patkearns10 You crushed it!! This feels ready to share with some other engineers to get their two cents. Have them comment feedback/suggestions in the Doc and we'll go from there. I'll follow up at the end of the week and see where we stand. 

Otherwise, I'm feeling good about where this is and feeling like we're close to the finish line on this :)
