### ISSUE TITLE
Use Docker to install dbt

### ISSUE THREAD

**Issue by Sof31t** [fishtown-analytics/docs.getdbt.com#1274]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://github.com/dbt-labs/docs.getdbt.com/edit/current/website/docs/dbt-cli/install/docker.md

### What part(s) of the page would you like to see updated?

How to setup a docker environment with dbt

**Comment by runleonarun** [comment]
Closing because this won't be addressed any time soon. If you can help author content for this, then we might reopen!
