### ISSUE TITLE
Joining the modern data stack with the modern ML stack

### ISSUE THREAD

**Issue by jacopotagliabue** [fishtown-analytics/docs.getdbt.com#1314]
### Contact Details

jacopo.tagliabue@tooso.ai (@Jacopo Tagliabue on Slack)

### This issue is being created to promote an approved Discussion.

- [X] I am promoting this issue from an approved Discussion and will link it below.

### Link to the Discussion this Issue is promoting.

This started from my conversation with @sungchun12 wrt to a sequel to his great article: https://docs.getdbt.com/blog/maching-learning-dbt-baton-pass. In particular, we discussed bringing together dbt and Metaflow to show how dbt can be leveraged by teams running ML pipelines on Metaflow, to retrieve datasets and features prepared with SQL.

More generally, this is part of our OS evangelization for ML "at reasonable scale" (https://towardsdatascience.com/mlops-without-much-ops-d17f502f76e8), including DataOps (https://github.com/jacopotagliabue/you-dont-need-a-bigger-boat).

### If you're promoting this from an 'I want to write about...' Discussion, you can copy over the answers to the following questions. Otherwise, please answer these questions below

1. Combining dbt (and dbt cloud) with Metaflow (and SageMaker, and Comet) in a principled way. In particular, a major drawback of our pipeline (https://github.com/jacopotagliabue/you-dont-need-a-bigger-boat) is its complexity - we want to show a minimalist version of how dataOps and MLops play together: simple enough to be easy to try, complex enough to be realistic;
2. dbt is a powerful feature preparation language - if you subscribe to the end-2-end data scientist, preparing features is a crucial part of the job, and we show how that can be done inside the same Python tool you use for the ML part (Metaflow)
3. Building a ML pipeline, going from raw data in Snowflake, to run dbt transformation, to query a feature table, training a model and then deploying it. A small but complete life cycle of a modern data scientist job.

### Link to the initial outline we will develop through this Issue.

Some notes written for our TDS series are here (https://docs.google.com/document/d/1eebJZQ2yy096nfWIfoYnvBDnmmeW-itwHkLItzQgt-g/edit). A working repo has already been shared with @sungchun12.

**Comment by sungchun12** [comment]
Love the premise!

**Comment by sungchun12** [comment]
Going to close this for now in favor of starting the discussion first: https://github.com/dbt-labs/docs.getdbt.com/discussions/1316
