### ISSUE TITLE
Article on CI/CD with Bitbucket

### ISSUE THREAD

**Issue by gwenwindflower** [fishtown-analytics/docs.getdbt.com#1322]
### Contact Details

@shippy

### This issue is being created to promote an approved Discussion.

- [X] I am promoting this issue from an approved Discussion and will link it below.

### Link to the Discussion this Issue is promoting.

#1215 

### If you're promoting this from an 'I want to write about...' Discussion, you can copy over the answers to the following questions. Otherwise, please answer these questions below

Early entry into the system this wanted went straight to an outline, but these are all answered well in the doc.

### Link to the initial outline we will develop through this Issue.

Doc contains context, outline, and draft:
https://docs.google.com/document/d/1SRZmUvYOTocrL04zZcQ5R0XZU0MatXM7LcUnMaf8Y94/edit?usp=sharing

**Comment by gwenwindflower** [comment]
I'm editing this this morning, I've read it before and anticipate very minimal edits so hopefully will be able to PR the article for publish today or tomorrow.

**Comment by gwenwindflower** [comment]
@shippy editing is done whenever you're ready to take a pass at the suggestions! i love it -- to quote myself in the edits:

> i love it! changes are almost all just formatting nits -- the content is perfecto. this is my kind of article! pragmatic knowledge that uses a specific example to outline a broadly applicable process

**Comment by shippy** [comment]
@gwenwindflower Notes implemented - please take another look! And thank you for the kind words :)
