### ISSUE TITLE
Identify global configs that are dbt Core only

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#1364]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

We know at least this config is for Core only: 
https://docs.getdbt.com/reference/global-configs#writing-json-artifacts

* Research all configs and list whether they are Core & Cloud or Core only. 

### What part(s) of the page would you like to see updated?

Add context about in which product people can use these configs.

**Comment by mirnawong1** [comment]
closing this issue because it looks like the table indicates if supported in dbt cloud: https://docs.getdbt.com/reference/global-configs/about-global-configs#writing-json-artifacts

please let me know if you think otherwise @runleonarun !
