### ISSUE TITLE
add context to default incremental behavior 

### ISSUE THREAD

**Issue by dave-connors-3** [fishtown-analytics/docs.getdbt.com#1369]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#default-behavior

### What part(s) of the page would you like to see updated?

In working with a client, I discovered that the default setting of `on_schema_change: ignore` does not _truly_ ignore all changes -- there is still a step of DDL that dbt executes _specifically on data types_ to ensure that the data in the temporary relation created during an incremental run can still be merged to the target table. I think it's key to call out the what dbt is `ignoring` is not _every_ change to an incremental model, it's specifically in regards to column additions and removals. 

I think this is a nuance to the default behavior of an incremental model that is worth calling out in the docs!

**Comment by runleonarun** [comment]
Looks like this was [addressed in the docs](https://docs.getdbt.com/docs/build/incremental-models#default-behavior), so I will close this issue! Feel free to reopen, @dave-connors-3 if I'm missing something or wrong.
