### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by emmyoop** [fishtown-analytics/docs.getdbt.com#1377]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

[`dbt Jinja context`](https://docs.getdbt.com/docs/building-a-dbt-project/dbt-jinja-functions) link on https://docs.getdbt.com/docs/building-a-dbt-project/jinja-macros is broken.

### What changes are you suggesting?

I think the link should point to https://docs.getdbt.com/reference/dbt-jinja-functions

**Comment by runleonarun** [comment]
Note that we should  search all links to `dbt-jinja-functions` as the id is no longer in use in the sidebar.js

**Comment by bbrewington** [comment]
good call - here's github.com search results within this repo for "dbt-jinja-functions" https://github.com/dbt-labs/docs.getdbt.com/search?q=dbt-jinja-functions
