### ISSUE TITLE
Improve documentation for model-level tests

### ISSUE THREAD

**Issue by solomonshorser** [fishtown-analytics/docs.getdbt.com#1381]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/building-a-dbt-project/tests

https://docs.getdbt.com/docs/guides/writing-custom-generic-tests

### What part(s) of the page would you like to see updated?

These pages should indicate that it is possible to include tests at the model level in addition to the column level. When I searched the web for "DBT Tests" for guidance on how to write custom SQL for testing my models, the pages above were what came back, but they only discuss column-level tests. I (incorrectly) assumed that DBT did not have the ability to do model-level tests.

### Additional information

This issue was opened as a response to a request in https://github.com/dbt-labs/dbt-core/issues/5175#issuecomment-1111209353

**Comment by runleonarun** [comment]
Thank you for opening this @solomonshorser. It's been awhile, but this is still in our backlog. I moved it up a tick in priority.

Note to writer: We should also include this information on this tests page: https://docs.getdbt.com/docs/build/tests

**Comment by mirnawong1** [comment]
thanks so much @solomonshorser ! this is a great shout and the [updated data test documentation](https://arc.net/l/quote/mrtgsdik) does mention tests can be performed at the model level. I'll go ahead and close this issue but please let me now if you think otherwise and happy to. reopen and address it!
