### ISSUE TITLE
Update  init.md with new profile template target name and add versioning

### ISSUE THREAD

**Issue by alexrosenfeld10** [fishtown-analytics/docs.getdbt.com#1389]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

Kindly requesting that someone assist with proper versioning for https://github.com/dbt-labs/docs.getdbt.com/pull/1388

### What changes are you suggesting?

See https://github.com/dbt-labs/docs.getdbt.com/pull/1388

**Comment by runleonarun** [comment]
Note that this work is capture in https://github.com/dbt-labs/dbt-core/issues/5179

**Comment by runleonarun** [comment]
@matthewshaver I added the 1.6 label in case you wanted to address in Core v 1.6

**Comment by jtcohen6** [comment]
The associated PR was merged in May 2022, so the change has been included in all dbt-core versions v1.2+

I'm supportive of updating these docs - just want to be clear that this is not new in v1.6
