### ISSUE TITLE
'Details' toggl in snapshots page aren't displaying content.

### ISSUE THREAD

**Issue by jaypeedevlin** [fishtown-analytics/docs.getdbt.com#1398]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/docs/building-a-dbt-project/snapshots#snapshot-meta-fields

### What changes are you suggesting?

The two blue 'details' toggle's dont seem to reveal the content that should be there.

### Additional information

The content is in the source code but I was unable to work out why it wasn't rendering

**Comment by b-per** [comment]
Closed with #1514
