### ISSUE TITLE
Bug: FAQ previews don't show the Title

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/docs.getdbt.com#14]
e.g. https://tutorial.getdbt.com/tutorial/faqs/unique-model-names/
renders as:
![image](https://user-images.githubusercontent.com/20294432/73674085-c351dd80-467d-11ea-8f16-d4e88065abad.png)

Instead of: `dbt - Documentation · Your entire analytics engineering workflow` 
I'd like: `dbt - Documentation  · Do model names need to be unique?`

**Comment by VersusFacit** [comment]
<img width="435" alt="image" src="https://user-images.githubusercontent.com/67295367/104784682-a7840200-573d-11eb-915a-f5868ac97a90.png">

Evidence that this issue has effectively been solived ans so is no longer relevant. Closing it :)
