### ISSUE TITLE
Parsing Snowflake query history and query comments

### ISSUE THREAD

**Issue by johnblust** [fishtown-analytics/docs.getdbt.com#1413]
### Contact Details

@jtalmi

### This issue is being created to promote an approved Discussion.

- [X] I am promoting this issue from an approved Discussion and will link it below.

### Link to the Discussion this Issue is promoting.

https://github.com/dbt-labs/docs.getdbt.com/discussions/1323

### If you're promoting this from an 'I want to write about...' Discussion, you can copy over the answers to the following questions. Otherwise, please answer these questions below

1. What is the main problem you are solving? What is your solution? This should help form your core thesis.

>Optimize dbt models and track cloud spend efficiently using the data warehouse query log and dbt run metadata

2. Why should the reader care about this problem? Why is your solution the right one? This should help form your specific target audience.

>Tracking spend more efficiently
>Getting per dbt model cost and performance metrics

3. Can you list the steps of your solution for the reader here? This should help you form the overall narrative arc and sketch out an example use case to illustrate it.

>[Input needed]

4. Are there any resources that helped inspire or inform your idea? (eg slack discussions, articles, external product docs, etc. -- if so please link)
 
>https://roundup.getdbt.com/p/macroeconomics-and-the-data-industry?s=r

5. Are there other existing solutions that solve the problem, and if so, how is this solution better or different? If so please share any links here.

>[Input needed -- optional]

### Link to the initial outline we will develop through this Issue.

https://docs.google.com/document/d/1Z9KstD-1aV816Fk4DgQzuQA1fuuyRQLANokChbvNZfY/edit

**Comment by johnblust** [comment]
Hey @jtalmi I'll be working with you to take your rough outline into a publish article! As you can see, I've already promoted your from a GH Discussion to a GH Issue. This just means the real work now begins :) 

The next step for us is to take this initial outline and flesh it out further. A great outline should do most of the writing/research heavy lifting for you, then the draft phase is less focused on development and more focused on stylistic choices :) So ideally, once we're done with this outline, there shouldn't be much more writing you have to do. 

As a first step, let's start with the introduction. A strong introduction grabs the reader's interest by telling them why they should care to read the rest of your content. It also lets them know exactly will be presented in the content; in this case, that'll be presenting the steps to your solution.

I'll drop some prompt questions in the outline to help get the juices flowing. Drop some comments here or in the Doc if you have any questions!

**Comment by johnblust** [comment]
@jtalmi Hey, just following up on my last message! Let me know if you're still interested in publishing this piece

**Comment by jtalmi** [comment]
Hey John! Just got back from vacation. I am definitely still interested in publishing this piece. Let me respond to your replies in more detail on the weekend

Best,
Jonathan

**Comment by johnblust** [comment]
Awesome, welcome back from vacation! Hope you had a good one. 

No rush on this, Jonathan. Just wanted to make sure you were still interested! I'll keep this issue open. Just ping me here whenever you find time to work on this over the next few weeks.

**Comment by johnblust** [comment]
@jtalmi Hey Jonathan, how are things? Just giving you an old-school Facebook poke to see how you're feeling about working on this lol. If now's no longer a good time, no worries! Just lmk

**Comment by johnblust** [comment]
Going to close this issue for now. Feel free to reopen when you're ready to work on this again @jtalmi
