### ISSUE TITLE
Leverage core accounting principles when modeling financial data

### ISSUE THREAD

**Issue by johnblust** [fishtown-analytics/docs.getdbt.com#1415]
for Developer Blog
### Contact Details

@fivetran-joemarkiewicz

### This issue is being created to promote an approved Discussion.

- [X] I am promoting this issue from an approved Discussion and will link it below.

### Link to the Discussion this Issue is promoting.

https://github.com/dbt-labs/docs.getdbt.com/discussions/1311

### If you're promoting this from an 'I want to write about...' Discussion, you can copy over the answers to the following questions. Otherwise, please answer these questions below

1. What is the main problem you are solving? What is your solution? This should help form your core thesis.

>[Input needed]

2. Why should the reader care about this problem? Why is your solution the right one? This should help form your specific target audience.

>[Input needed]

3. Can you list the steps of your solution for the reader here? This should help you form the overall narrative arc and sketch out an example use case to illustrate it.

Optional

4. Are there any resources that helped inspire or inform your idea? (eg slack discussions, articles, external product docs, etc. -- if so please link)

>[Input needed]

5. Are there other existing solutions that solve the problem, and if so, how is this solution better or different? If so please share any links here.

>[Input needed]

### Link to the initial outline we will develop through this Issue.

https://docs.google.com/document/d/1S9xE_IJeE49IyhYu2CsgYgXFzUDpUTzbpTWEg00jNKw/edit

**Comment by fivetran-joemarkiewicz** [comment]
Thanks @johnblust I will get to updating this by the end of the week. Thanks for creating this and looking forward to contributing the blog post!

**Comment by fivetran-joemarkiewicz** [comment]
@johnblust I was able to respond to the questions below. Let me know if there is any more context you would like from me!

> What is the main problem you are solving? What is your solution? This should help form your core thesis.

The main problem this blog post will solve is the question of how to effectively and properly apply accounting principles when modeling financial data. The financial reports that are analyzed are commonly the General Ledger, Profit and Loss Statement, and the Balance Sheet. These core reports are provided within the Financial Fivetran dbt packages and all apply the same principles to be able to leverage the financial data from the source. I will show how this was done across our packages, and how you can replicate it with any other financial dataset you may work with in the future.

> Why should the reader care about this problem? Why is your solution the right one? This should help form your specific target audience.

Modeling financial data can be extremely difficult and there is always either a right or wrong answer. For example, the balance sheet either **does** or **does not** tie out. Applying the financial modeling principles outlined in this blog will help Analytics Engineers more easily recreate the core financial reports and ensure they are **correct**. Additionally, this will help free up more time for deeper analysis of your financial data outside of the core reports!

> Can you list the steps of your solution for the reader here? This should help you form the overall narrative arc and sketch out an example use case to illustrate it.

1. Understand the source data of your financial application. It most likely will have one of two schema designs: 
   - Provided transaction detail or general ledger table which lists every transaction
   - Single tables for each transaction type that must be combined to generate a GL/transaction detail table. 
3. Generate an enriched GL/Transaction Detail table by joining in appropriate dimensional tables such as account, customer, vendor, etc.
4. Confirm the classifications of your accounts are accurate. For example, ensure your Inventory accounts roll up into your Asset classification. This is imperative for proper tie out of the Balance Sheet and Profit and Loss reports. I can then link to how this is achieved within our dbt packages.
5. Add the finishing touches and voila ✨  you have your General Ledger/Transaction Detail model! 🎉 
6. Create a date spine at whichever grain you or your stakeholders prefer. Our Fivetran dbt packages choose a month grain as this is the most typical grain when creating financial reports.
7. Cross join this date spine with your General Ledger/Transaction Detail model and perform appropriate aggregations to generate the `period_net_change`, `period_beginning_amount`, and `period_ending_amount` for each of your account categories. 
   - A quick gotchya: make sure to recreate the Retained Earnings bucket for Net Income/Loss amount for your date grain!
8. You now have your General Ledger/Transaction Detail by [date grain] model! This is critical to create your final BS and P&L reports.
9. To create the Profit and Loss just reference your GL by [date grain] model and filter for `income statement` account classifications (this will have been identifier in step 3) and Bada Bing... you have your P&L and can slice and dice by period to your hearts content! ❤️  💸 
10. To create the Balance Sheet just reference your GL by [date grain] model and filter for `balance sheet` account classifications (this will have been identifier in step 3) and Bada Boom... you have your BS and can slice and dice by period to your hearts content! ❤️  ⚖️ 

> Are there any resources that helped inspire or inform your idea? (eg slack discussions, articles, external product docs, etc. -- if so please link)

The various dbt packages that I have helped create and also the past work I have written on this topic. See links below:
- [Netsuite dbt package](https://github.com/fivetran/dbt_netsuite)
- [QuickBooks dbt package](https://github.com/fivetran/dbt_quickbooks)
- [Xero dbt package](https://github.com/fivetran/dbt_xero) 
- [Sage Intacct dbt package](https://github.com/fivetran/dbt_sage_intacct)
- [Microsoft Dynamics GP Blog Post](https://www.analytics8.com/blog/microsoft-dynamics-gp-data-tables-in-power-bi/)

> Are there other existing solutions that solve the problem, and if so, how is this solution better or different? If so please share any links here.

The above mentioned dbt packages solve the solution for users leveraging Fivetran and on of those sources (with the exception of Microsoft Dynamics). However, this blog post will help highlight the steps taken in these dbt packages and how users can leverage this themselves in their own environments as well.

**Comment by johnblust** [comment]
Awesome, looks great!! Let's start by putting this information you just wrote into your outline (which is a great start by the way!). Ideally, a great outline will do most of the writing/research heavy lifting for you, and it makes sure that your main ideas all get approved up front and you don't have to do any major revisions in the draft stage.

Once we have this information in your skeleton outline, we can begin going a level deeper in your outline! @ me here when it is ready and I'll start diving into the outline and commenting on some areas where we can expand the outline further :)

**Comment by fivetran-joemarkiewicz** [comment]
@johnblust just wanted to post here and let you know I will be working on the outline over the course of the next two weeks. I hope to share more details then. I apologize about the delay, but hope to have the skeleton in place for you soon 😄

**Comment by johnblust** [comment]
@fivetran-joemarkiewicz Thanks for the heads up, Joe! No apologies, looking forward to reading your outline!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @johnblust I was able to consolidate my thoughts above into a more cohesive draft outline. See the outline in the [Google Doc](https://docs.google.com/document/d/1S9xE_IJeE49IyhYu2CsgYgXFzUDpUTzbpTWEg00jNKw/edit). Let me know your thoughts and happy to take any comments or edits where needed in this outline 😄

**Comment by johnblust** [comment]
Awesome, thanks @fivetran-joemarkiewicz! I'll be OOO Wed and Thurs so I won't get to reviewing your outline this week, but I'll review it early next week!

**Comment by johnblust** [comment]
@fivetran-joemarkiewicz Thanks for the hard work on this, it looks great! I left a few comments on the docs, but overall looks good. Let me know when you've responded to those comments and we can go from there :)

**Comment by fivetran-joemarkiewicz** [comment]
Thanks @johnblust! I just responded to your comments. Let me know what next steps should be from here 😺

**Comment by johnblust** [comment]
Looks good! Looks like we're ready to move this into draft based on the decisions made in the comments. For reference those decisions are:

- Each step of the solution will have it's own H3 section
- There will be a couple sentences/short section on some pitfalls to look out for that can throw off your reports in the conclusion.

Let me know if anything's unclear here, otherwise, you're off the races! 🏇

**Comment by johnblust** [comment]
Hey @fivetran-joemarkiewicz , checking in with you to see if you're still interested in writing this draft. If so lmk! Otherwise, I'll close this issue and you can reopen it when you have more time.

**Comment by fivetran-joemarkiewicz** [comment]
Hey @johnblust my apologies for the delayed response. I am still working on the draft and plan to have it sent over at the end of next week if that works for you?

**Comment by johnblust** [comment]
Yeah that works! Thanks for the update. No big rush, just wanted to make sure we still wanted to keep this issue open :)

**Comment by fivetran-joemarkiewicz** [comment]
@johnblust I just wanted to reach back out and let you know that I have made progress on the [Draft of the blog post](https://docs.google.com/document/d/1S9xE_IJeE49IyhYu2CsgYgXFzUDpUTzbpTWEg00jNKw). I am feeling pretty happy with it so far, but am worried it may be too lengthy for each step in the process. Would love your input there!

Additionally, I am struggling with the closing remarks. I will try and complete this section, but wanted to send the current state along to you in case you wanted to review or provide any insight while I finish out the closing paragraphs.

**Comment by johnblust** [comment]
Awesome, I'll take a look at this next week!

**Comment by johnblust** [comment]
Hey @fivetran-joemarkiewicz , this is a fantastic article! Overall, super solid. I made some small grammar changes and trimmed things where I could. Let me know if those suggestions make sense! I also left some prompt questions to help get the juices flowing for the closing paragraph. Feel free to use any or all of them, or don't!

Let me know when this is ready for another pass, and I'll have someone review this with me to make sure everything is good. After that, I think we can go ahead and create a PR for this :)

**Comment by fivetran-joemarkiewicz** [comment]
Thanks so much for giving it a review and adding your suggestions. I just accepted your suggestions and replied to your question. I will most likely get to the closing prompts this weekend and hope to have the updates applied early next week. I will post back here once they are ready!

**Comment by fivetran-joemarkiewicz** [comment]
Hey @johnblust I just put the finishing touches on the blog. Let me know if you have any notes 😄

**Comment by johnblust** [comment]
Looks great @fivetran-joemarkiewicz! Whenever you are ready, go ahead and spin up a PR for this! Make sure to add me as a reviewer and I'll add other folks as necessary. You can look at the other blog posts located in /website/blog/ as a reference for formatting. Be sure to also create an author profile in the /website/blog/author/ folder. All blog images should go in the /website/static/img/blog/ folder and your author image should go in the /website/static/img/blog/author/ folder. Let me know if you get stuck and I can help!

How does a September 7th release date sound to you?

**Comment by fivetran-joemarkiewicz** [comment]
Sounds good to me! I will spin up that PR this week!

**Comment by fivetran-joemarkiewicz** [comment]
@johnblust sorry for waiting until the very last moment of this week to open the PR. This week became busier than expected. Let me know if I missed anything when opening the PR 😄
