### ISSUE TITLE
The links to json schemas for the yaml file seems to point to the run_results json schema

### ISSUE THREAD

**Issue by giovanni-girelli-sdg** [fishtown-analytics/docs.getdbt.com#1441]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/artifacts/dbt-artifacts#notes

### What part(s) of the page would you like to see updated?

In the linked section, we find links to the json schemas. They have the correct names, but the fields are all from the run_results artifact.

**Comment by giovanni-girelli-sdg** [comment]
I looked for other issues relating to this but while there are issues with the absence of schemas, i could not find mentions of the wrong links. If this is known and I missed I apologize in advance.

**Comment by runleonarun** [comment]
Hello! Thank you for bringing this issue to our attention! It looks like all the links are correct now! Please let us know if you're seeing something different and re-open this issue, or open a new issue if you see another problem.
