### ISSUE TITLE
Enterprise permissions diagram is outdated

### ISSUE THREAD

**Issue by matt-winkler** [fishtown-analytics/docs.getdbt.com#1444]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/docs/dbt-cloud/access-control/enterprise-permissions

### What changes are you suggesting?

The "Developer" permission set was recently changed to disallow editing environments. However, the docs image shows that Developers attain the permissions from Job Admins, which ARE capable of editing environments. We should update the diagram to either a) call out environments as an exception or b) alter the diagram more holistically to minimize confusion.

[developer permissions](https://docs.getdbt.com/docs/dbt-cloud/access-control/enterprise-permissions#developer)
[job admin permissions permissions](https://docs.getdbt.com/docs/dbt-cloud/access-control/enterprise-permissions#job-admin)

Image that should be changed:

![image](https://user-images.githubusercontent.com/75497565/168112905-cfc5a978-abd9-4208-b684-8dfd4284c3ea.png)

The image for the diagram appears to live in `/img/docs/dbt-cloud/dbt-cloud-enterprise/enterprise-permission-sets-diagram.png`, but I have no idea where the original diagram is saved.

**Comment by runleonarun** [comment]
@matthewshaver once you figure out the network diagram, this one would also be helpful to update.

**Comment by mirnawong1** [comment]
hey @matthewshaver , i think you did some great work on the permissions page and wanted to flag the image that @matt-winkler raised. 

should we change the diagram or remove it altogether until a new one is created? https://docs.getdbt.com/docs/cloud/manage-access/enterprise-permissions#diagram-of-the-permission-sets

**Comment by runleonarun** [comment]
I think now that we have the tables, we can remove that diagram.

**Comment by matt-winkler** [comment]
Agree! Let's get rid of it!
