### ISSUE TITLE
Add more adapters to Available adapters page

### ISSUE THREAD

**Issue by dataders** [fishtown-analytics/docs.getdbt.com#1489]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/docs/available-adapters

### What changes are you suggesting?

Now that #1467 has been merged, we can share guidance on how to document all the adapters that aren't currently listed on the available adapters page. This underserves these undocumented adapters as well as the dbt community as a whole.

There are now issues open in each of the repos below where I share the new guidance and ask them to reach out should they encounter an issues or have questions.

### Adapters To Add
- [x] [dbt-clickhouse](https://github.com/silentsokolov/dbt-clickhouse)
- [ ] [dbt-mysql](https://github.com/dbeatty10/dbt-mysql)
- [x] [dbt-sqllite](https://github.com/codeforkjeff/dbt-sqlite)
- [ ] [dbt-netezza](https://github.com/chop-analytics/dbt-netezza)
- [x] [dbt-impala](https://github.com/cloudera/dbt-impala)
- [x] [dbt-oracle](https://github.com/oracle/dbt-oracle)
- [x] [dbt-vertica](https://github.com/ahedengren/dbt-vertica)
- [ ] [dbt-starrocks](https://github.com/StarRocks/dbt-starrocks)
- [x] [dbt-mindsdb](https://github.com/mindsdb/dbt-mindsdb)
- [ ] [dbt-doris](https://github.com/qiulin/dbt-doris)
- [ ] [dbt-splitgraph](https://github.com/splitgraph/splitgraph/tree/master/examples/dbt_adapter)
- [x] [dbt-tidb](https://github.com/pingcap/dbt-tidb)
- [x] [dbt-duckdb](https://github.com/jwills/dbt-duckdb)
- [ ] [dbt-ibmdb2](https://github.com/aurany/dbt-ibmdb2)
- [ ] [dbt-hive](https://github.com/a-pollo/dbt-hive)
- [x] [dbt-greenplum](https://github.com/markporoshin/dbt-greenplum)
- [x] [dbt-layer](https://github.com/layerai/dbt-adapters)

**Comment by dataders** [comment]
@TylerHillery totally optional, but if you're interested dbt-mysql and dbt-netezza and dbt-ibmdb2 are up for grabs!

**Comment by TylerHillery** [comment]
@dataders Sounds good! I will work on these over the next couple of weeks.

**Comment by runleonarun** [comment]
@dataders Is this still an issue we should keep open?

**Comment by dataders** [comment]
closing because not requirement
