### ISSUE TITLE
Columns with nulls are not good candidates for incremental model `unique_id`

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#1502]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#defining-a-uniqueness-constraint-optional

### What part(s) of the page would you like to see updated?

If using one or more columns _by name_ to form a `unique_key`, those columns must be:
- never null
- unique in combination

It's on the user to verify that those are true, e.g. with tests defined on upstream sources / models.

(On some databases, there may even be considerable performance benefits for database optimizers if those columns are _defined_ as required / not nullable, via constraints)

If an incremental model lacks a reliable single unique column, or a set of reliable columns that are unique in combination and never null individually, we should recommend the same as we did before: create a surrogate key within the incremental model (e.g. via `dbt_utils.surrogate_key`, which handles nulls), and pass that single surrogate key as the `unique_key` for incremental processing.

### Additional information

(Internal) Slack threads:
- https://dbt-labs.slack.com/archives/C0131TY7EEA/p1653433069997309
- https://dbt-labs.slack.com/archives/C017GDLAF7D/p1653355805756599

**Comment by runleonarun** [comment]
This seems to have been addressed in [this page](https://docs.getdbt.com/docs/build/incremental-models#defining-a-uniqueness-constraint-optional), but please re-open if I'm wrong!
