### ISSUE TITLE
break out Databricks configuration info from Spark into standalone config page

### ISSUE THREAD

**Issue by dataders** [fishtown-analytics/docs.getdbt.com#1525]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-configs/spark-configs#databricks-configurations

### What part(s) of the page would you like to see updated?

Right now, Databricks configurations only exist as [a footnote on the Apache Spark configuration page](https://docs.getdbt.com/reference/resource-configs/spark-configs#databricks-configurations). Given that we expect greater configuration divergence moving forward, I recommend that we make a dedicated Databricks configuration page as described in [Documenting an Adapter page](https://docs.getdbt.com/docs/contributing/documenting-a-new-adapter#topics-and-pages-to-cover).

Additionally, we should mention the following (or improve error throwing on the adapter itself)
- the default configurations for snapshot and incremental materializations
- `unique_key` doesn't do anything when `incremental_strategy="append"` is specified
- `file_format = ‘parquet’` is not supported on dbt-databricks
- Snapshots fail if Delta format isn't specified

👀 @superdupershant @ueshin @asteichen @schottj

**Comment by runleonarun** [comment]
Donzo! https://docs.getdbt.com/reference/resource-configs/databricks-configs (But if I am wrong, feel free to re-open)
