### ISSUE TITLE
`grants` as configs, run during materializations

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#1527]
### Contributions

- [X] I am a PM or subject matter expert at dbt who is responsible for this feature.

### Where does this content belong?

**Main location:** New page in "general configs," similar to the page for [`meta`](https://docs.getdbt.com/reference/resource-configs/meta)

Update copy in:
- [Hooks & operations](https://docs.getdbt.com/docs/building-a-dbt-project/hooks-operations), specifically the recommendations + examples that these are for granting privileges. We want to turn these hooks into an "advanced" feature, for people who know what they're doing, since there are a lot of gotchas.
- Snowflake `copy grants` config: https://docs.getdbt.com/reference/resource-configs/snowflake-configs#copying-grants
- ["Building a new adapter"](https://docs.getdbt.com/docs/contributing/building-a-new-adapter): there are 4 new macros, and adapter maintainers may need to reimplement anywhere between none and all of them to support `grants` on their database

Longer term: We should update ["Creating new materializations"](https://docs.getdbt.com/guides/legacy/creating-new-materializations), since features like `persist_docs` + `grants` are not reflected there currently.

## Who will use this feature?

dbt developers who want to manage access to the valuable datasets they're producing with dbt. Oftentimes, that means _restricting_ access on upstream/intermediate models, and granting access to reporting / BI / downstream querying tools on final models that are ready for primetime.

## Feature description: how it will help people

Traditionally, the way you had to do this was pretty jank:
```sql
{{ config(post_hook = 'grant select on {{ this }} to role reporter') }}
```
(See those nested curlies? [Ew!](https://docs.getdbt.com/docs/building-a-dbt-project/dont-nest-your-curlies#an-exception))

This feature will enable people to define grants as configs—the way they know & love—and dbt takes care of the rest.

## Customer research

Hooks applying grants ends up being some of the gnarliest code in advanced/mature dbt projects. Yet, people have A Bad Time using hooks. See the issues linked from https://github.com/dbt-labs/dbt-core/issues/5090.

More background for dbt Labs employees: https://www.notion.so/dbtlabs/Grants-permissions-becbe54d4a444ede9baf46078e5e69ef

## How can we test or use this feature?

See the example code below! Once the feature is merged, and available from source / in a beta, it should all Just Work on any of our supported databases.

## Source material

- https://github.com/dbt-labs/dbt-core/issues/5189
- https://github.com/dbt-labs/dbt-core/issues/5263

---

### Configuring the grant

Grants will be supported as node configs, in all the usual places:
```yml
# dbt_project.yml
models:
  export:
    +grants:
      select: ['reporter', 'bi']
```
```yml
# models/model.yml
models:
  - name: specific_model
    config:
      grants:
        select: ['reporter', 'bi']
```
```sql
-- models/specific_model.sql

{{ config(grants = {'select': ['other_user']}) }}
```

---

Per-adapter behavior: Most databases support a simple privilege named `select`, and recipients (users/groups/roles) with plaintext names. **BigQuery** is a little different for both naming conventions. There, this needs to be:
```yml
# models/model.yml
models:
  - name: specific_model
    config:
      grants:
        'roles/bigquery.dataViewer': ['user:jeremy@example.com']
```

We should just link to these docs: https://cloud.google.com/bigquery/docs/access-control

---

**There's one special behavior that we're experimenting with.** This will be supported for `grants` only to get started. If a user has configured some `grants` for all models in their project (in `dbt_project.yml`), and then they reconfigure certain `grants` for a specific model, the default behavior is to "clobber" one config with another: to completely replace the project-level grants with the model-level grants.

We're optionally supporting a `+` prefix (different from [the other "+" prefix that everyone hates](https://docs.getdbt.com/reference/resource-configs/plus-prefix)) to make that model-level config "additive" instead of "clobbering". E.g.:

```yml
# dbt_project.yml
models:
  +grants:
    select: ['reporter', 'bi']
```
```sql
-- models/specific_model.sql

{{ config(grants = {'+select': ['other_user']}) }}
```

This would "add" to the `select` list, instead of replacing it, and thereby return `select: ['reporter', 'bi', 'other_user']`. More conversation about why this is valuable, and speculation about extending it to other config types, in https://github.com/dbt-labs/dbt-core/issues/4108.

---

### Runtime behavior

A lot of this doesn't need documentation, since it's something that dbt handles behind the scenes. But there will be some opinionated judgment calls that we want to make clear.

dbt's goal in this feature is to always ensure that the grants actually applied on the database object match up exactly with the `grants` that the user has configured. No more, no less.

Depending on the database adapter, and the materialization of the resource, dbt may or may not need to do more complicated work: figure out grants on the preexisting object, and figure out if any have been added/removed. 

On Snowflake, if `copy_grants` is enabled, then dbt will NOT try to do this work. The presumption is that the end user knows what they're doing, and may be applying grants in an external system. dbt will ONLY add grants, not remove them.

If people need their `grants` to do other fancier things, they can always revert back to the current recommendation, of using a pre/post hook.

**Comment by boxysean** [comment]
@jtcohen6 I was chatting with @Nerdenberger about the boundary between Terraform and dbt. Encoding grants will help our tool adopt Infrastructure As Code principles. I believe your vision is to apply grants per database object (Table or View). One nuance to consider is: some organizations manage permissions at the Database or Schema object level, especially people who are responsible for managing infrastructure, but not data management. Have you considered this capability at the Database or Schema level? Thanks!

**Comment by jtcohen6** [comment]
@boxysean Thanks for the comment! This initial feature will be limited to database objects which dbt is creating in the course of its normal events. We've definitely thought about it a future extension of the feature to other types of objects which dbt does not manage directly (logical databases), or which users do not define as first-class objects in the same manner (schemas) — and eventually other object types (https://github.com/dbt-labs/dbt-core/discussions/5099).

**Comment by jtcohen6** [comment]
Note during Language/Adapters meeting: Make sure to document that grants only appear to be supported in Databricks runtime, not yet OSS Apache Spark... or maybe I just can't find the docs for the latter.

https://docs.databricks.com/sql/language-manual/security-grant.html
https://docs.databricks.com/spark/latest/spark-sql/language-manual/security-grant.html
