### ISSUE TITLE
Improve documentation on unique_key in incremental models

### ISSUE THREAD

**Issue by sdebruyn** [fishtown-analytics/docs.getdbt.com#1528]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Definitely here: https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models
Maybe also here: https://docs.getdbt.com/reference/model-configs

### What part(s) of the page would you like to see updated?

Cfr. https://github.com/dbt-msft/dbt-sqlserver/issues/241#issuecomment-1147464620

While this is not documented, the `unique_key` in an incremental model can also be a sequence. dbt-core does seem to support this, but the bug above is to add support for it in the dbt-sqlserver adapter.

I think the documentation should also state that this is valid behaviour and that unique keys can be sequences referencing multiple columns.

**Comment by sdebruyn** [comment]
This was the PR introducing the feature: https://github.com/dbt-labs/dbt-core/issues/4738

**Comment by runleonarun** [comment]
👋🏻 @sdebruyn I'm going to close this issue because it looks like it was addressed in [this PR](https://github.com/dbt-labs/docs.getdbt.com/pull/1298). Please reopen if this is wrong and further docs are needed!
