### ISSUE TITLE
[BUG] "dbt Cloud" header sometimes splits over two lines

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/docs.getdbt.com#155]
## Steps to reproduce:
At a certain window size, the "dbt Cloud" item in the header bar splits over two lines.

Also the dbt logo gets stretched?

<img width="1041" alt="Screen Shot 2020-05-15 at 8 33 48 AM" src="https://user-images.githubusercontent.com/20294432/82050849-d6197c80-9686-11ea-8142-6135d9a6e0a8.png">

**Comment by drewbanin** [comment]
dang, good catch, will fix this
