### ISSUE TITLE
Change database and warehouse caused permission issues

### ISSUE THREAD

**Issue by alexfeng2017** [fishtown-analytics/docs.getdbt.com#1574]
### Contributions

- [x] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates
https://docs.getdbt.com/guides/getting-started/getting-set-up/setting-up-snowflake

For option 1 - Option 1: Connect dbt Cloud and Snowflake with partner connect
-------
"We have one slight tweak to make to dbt Cloud interface to account for the analytics database and transforming warehouse created earlier. Click the hamburger menu in the top left and choose account settings. Select the project titled, "Partner Connection Trial" and select snowflake in the overview table. Select edit and update the fields database and warehouse to be analytics and transforming respectively."

After we did this, the deployment failed with "  Insufficient privileges to operate on database 'ANALYTICS'"

### What part(s) of the page would you like to see updated?

"We have one slight tweak to make to dbt Cloud interface to account for the analytics database and transforming warehouse created earlier. Click the hamburger menu in the top left and choose account settings. Select the project titled, "Partner Connection Trial" and select snowflake in the overview table. Select edit and update the fields database and warehouse to be analytics and transforming respectively."

**Comment by amychen1776** [comment]
@alexfeng2017 Can I double-check with you that you did completed  step 3 of granting permissions to the analytic and raw database?

![image](https://user-images.githubusercontent.com/46451573/176016445-7fa79138-5a8d-44cb-ae5f-40114529f517.png)

**Comment by runleonarun** [comment]
We've updated and tested [this quickstart](https://docs.getdbt.com/docs/quickstarts/dbt-cloud/snowflake), but please do let us know if you see anything else by creating a new issue. 🙇🏻‍♀️
