### ISSUE TITLE
FAQs not displaying properly

### ISSUE THREAD

**Issue by Elliot2718** [fishtown-analytics/docs.getdbt.com#1575]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

Any pages (out of several I checked) with a FAQs section are not displaying any content. I tests several pages in Chrome, Firefox and Edge. Here are some example screenshots:
https://docs.getdbt.com/docs/building-a-dbt-project/tests#faqs
![image](https://user-images.githubusercontent.com/49532242/173453173-39452d93-366a-41f3-9a8b-bd8f38ec7493.png)

https://docs.getdbt.com/docs/building-a-dbt-project/building-models#additional-faqs
![image](https://user-images.githubusercontent.com/49532242/173453238-085ba4d7-d006-4e8d-b429-54a17d5a0056.png)

https://docs.getdbt.com/docs/building-a-dbt-project/building-models#faqs
![image](https://user-images.githubusercontent.com/49532242/173453248-0087a2c4-da16-4e20-b655-7b9fa6feee5e.png)

### What changes are you suggesting?

Have the content actually display!

**Comment by gwenwindflower** [comment]
fixed by #1578
