### ISSUE TITLE
Documentation unclear on insert_overwrite and unique_key

### ISSUE THREAD

**Issue by nik-hinge** [fishtown-analytics/docs.getdbt.com#1584]
### Discussed in https://github.com/dbt-labs/docs.getdbt.com/discussions/1583

<div type='discussions-op-text'>

<sup>Originally posted by **nik-hinge** June 15, 2022</sup>
Hey all, I've got a question about `insert_overwrite` and `unique_key`. I tried to look at the documentation for this, but the documentation on docs.getdbt.com seem to be unclear and maybe contradictory on the page for [Configuring Incremental Models](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models).

Specifically, the following two sections have lines that appear to be at-odds with each other:
- [Defining a Uniqueness Constraint (Optional)](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#defining-a-uniqueness-constraint-optional)
- [Configuring Incremental Strategy](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#configuring-incremental-strategy)

The info box in the section "Defining a Uniqueness Constraint (Optional)" says 
> ... For example, the `insert_overwrite` strategy does not use `unique_key` , because it operates on partitions of data rather than individual rows. For more information, see [About incremental_strategy](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#about-incremental_strategy).
<img width="1015" alt="Screen Shot 2022-06-15 at 1 24 13 PM" src="https://user-images.githubusercontent.com/96435996/173888733-88286365-a298-40f3-8dc6-5b4016a1d77e.png">

And section it links to contains the subsection "Configuring Incremental Strategy" which has the following example for `insert_overwrite` that also defines the `unique_key` parameter.
<img width="1015" alt="Screen Shot 2022-06-15 at 1 23 50 PM" src="https://user-images.githubusercontent.com/96435996/173888694-92b8e555-1414-4adb-8358-4d4a4c6188ec.png">

If `insert_overwrite` does not use the `unique_key` parameter (as is stated in the first info box), this seems like an unclear example to show for it.

I've also found these three commits that edited the lines on the docs:
- https://github.com/dbt-labs/docs.getdbt.com/commit/e0c745e2d8d9ee35ad94fc2e5e28d4c5367d73b7
- https://github.com/dbt-labs/docs.getdbt.com/commit/6120444f0e3039c06eefc8b3f66d0e96691b39cc
- https://github.com/dbt-labs/docs.getdbt.com/commit/c9e8dbc60b427cf82fee2ceec57a7d729bd1af21

Maybe one of the authors on these commits could help shed some light? @runleonarun @jtcohen6 @nickyspitz 

Thanks!</div>

**Comment by gwenwindflower** [comment]
Ah, yes, that should be delete+insert! 👍🏻 not insert_overwrite -- you're absolutely right, thanks!

I deleted the Discussion on this to keep things clean, the Issue here was the right spot for this, we'll get it fixed!

**Comment by nik-hinge** [comment]
Thanks @gwenwindflower, do you mean that the `models/my_model.sql` example should say `delete+insert` ?

**Comment by matthewshaver** [comment]
The text is fixed as part of https://github.com/dbt-labs/docs.getdbt.com/pull/1922
