### ISSUE TITLE
Clarify "quoting" section in manifest.json for node 

### ISSUE THREAD

**Issue by vvkh** [fishtown-analytics/docs.getdbt.com#1616]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/model-configs

### What part(s) of the page would you like to see updated?

In `manifest.json`, there is a `quoting` attribute in the `config` section for each node. For example:
```json
{
        "model.dbt_valentin_bigquery.my_second_dbt_model": {
            "raw_sql": "-- Use the `ref` function to select from other models\n\nselect *\nfrom {{ ref('my_first_dbt_model') }}\nwhere id = 1",
            "compiled": true,
            "resource_type": "model",
            "depends_on": {
                "macros": [],
                "nodes": [
                    "model.dbt_valentin_bigquery.my_first_dbt_model"
                ]
            },
            "config": {
                "enabled": true,
                "alias": null,
                "schema": null,
                "database": null,
                "tags": [],
                "meta": {},
                "materialized": "view",
                "persist_docs": {},
                "quoting": {},
                "column_types": {},
                "full_refresh": null,
                "unique_key": null,
                "on_schema_change": "ignore",
                "post-hook": [],
                "pre-hook": []
            }
...
}
```

However, it's unclear what this attribute is responsible for. It's not mentioned on the [Model configuration page](https://docs.getdbt.com/reference/model-configs). However, it's mentioned in [manifest.json schema](https://schemas.getdbt.com/dbt/manifest/v5/index.html#nodes_additionalProperties_oneOf_i0_config_quoting).

Initially, I thought It had something to do with [quoting configuration in dbt_project.yml](https://docs.getdbt.com/reference/project-configs/quoting). However, I tried setting different quoting policies and the`" quoting"` attribute would always remain empty in `manifest.json` after compilation.

It would be great to clarify what the attribute is responsible for.

**Comment by runleonarun** [comment]
Hey there, @vvkh I'm not sure why quoting is empty in your manifest.json. I would expect it to be `true` or `false`. Here's [another page](https://docs.getdbt.com/reference/resource-properties/quoting) that describes configuring `quoting` in sources. I hope that helps!

I am going to put this project in the backlog to revisit at a later time. Please reopen or reach out if this has been closed in error.
