### ISSUE TITLE
explain how to enable the PM team of a database to get telemetry data about dbt invocation volume

### ISSUE THREAD

**Issue by dataders** [fishtown-analytics/docs.getdbt.com#1625]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/contributing/building-a-new-adapter#opencls-connection

### What part(s) of the page would you like to see updated?

specifically the section about `ConnectionManager.open()` should at least note that the developer should consider the possibility of logging the adapter version via the connection information when opening a Connection

https://github.com/dbt-labs/docs.getdbt.com/blame/current/website/docs/docs/contributing/building-a-new-adapter.md#L150-L165

### Additional information

related to https://github.com/dbt-labs/dbt-database-adapter-scaffold/issues/41

_No response_

**Comment by runleonarun** [comment]
@dataders Is this still valid? Should I close an put in the #icebox?

**Comment by mirnawong1** [comment]
adding an icebox label and closing issue. we can reopen if needed
