### ISSUE TITLE
Incorrect link in docs (full_refresh, should_full_refresh(), helper.sql --> configs.sql)

### ISSUE THREAD

**Issue by dsmdavid** [fishtown-analytics/docs.getdbt.com#1655]
The full refresh section refers to a missing file "helpers.sql" as the source of the `should_full_refresh()` macro. I think it should point to `https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/configs.sql` instead.

https://github.com/dbt-labs/docs.getdbt.com/blob/3f96e055043d81f9c39628970b62bb5920a9218a/website/docs/reference/resource-configs/full_refresh.md?plain=1#L70

**Comment by runleonarun** [comment]
Thanks for opening this issue! It looks like [this was fixed](https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/reference/resource-configs/full_refresh.md), so closing this issue. Feel free to reopen if you're seeing something different,
