### ISSUE TITLE
Align Snowflake docs content

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#1672]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

In the dbt docs [(here)](https://docs.getdbt.com/reference/warehouse-profiles/snowflake-profile#sso-authentication) for the 'Overview of dbt-Snowflake' base configs for client_session_keep_alive and the Snowflake docs ([here](https://docs.snowflake.com/en/sql-reference/parameters.html#client-session-keep-alive)) for 'CLIENT_SESSION_KEEP_ALIVE' seem to offer differing descriptions. 

### What part(s) of the page would you like to see updated?

We should get these docs aligned. Thank you @amychen1776 for looking into this!

**Comment by amychen1776** [comment]
Closed with this PR https://github.com/dbt-labs/docs.getdbt.com/pull/1705
