### ISSUE TITLE
Add a dbt syntax page

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#1686]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Follow up work for 1.2:

* Add or update a syntax page. 
> As with most configs in dbt that accept lists (e.g. [sort keys on Redshift](https://docs.getdbt.com/reference/resource-configs/redshift-configs#using-sortkey-and-distkey)), if the user is specifying only a single entry in the list, they can also provide the argument as a string, and dbt will "listify" it for them:

 > 'select': 'other_user'
 >  (That is, without the [] brackets around 'other_user')
  
>   IMO it's always better/clearer to provide the argument as an explicit list, though!

> (The right place to note this is wherever seems easiest — but I think it's worth noting somewhere, rather than leaving the behavior totally implicit / undocumented)

Reference [this issue](https://github.com/dbt-labs/docs.getdbt.com/pull/1642#discussion_r913660517)

### What part(s) of the page would you like to see updated?

Let's capture syntax standards somewhere to clarify best syntax practices that apply globally in dbt.

**Comment by jtcohen6** [comment]
Copy-pasting from the linked comment:

> As with most configs in dbt that accept lists (e.g. [sort keys on Redshift](https://docs.getdbt.com/reference/resource-configs/redshift-configs#using-sortkey-and-distkey)), if the user is specifying only a single entry in the list, they can also provide the argument as a string, and dbt will "listify" it for them:
> 
> `{{ config(grants = {'select': 'other_user'}) }}`
> (That is, without the `[]` brackets around `'other_user'`)
> 
> IMO it's always better/clearer to provide the argument as an explicit list, though!
> 
> (The right place to note this is wherever seems easiest — but I think it's worth noting somewhere, rather than leaving the behavior totally implicit / undocumented)

I could totally see this falling under a larger set of "general dbt syntax" guidelines — but also want to note that the scope for this specific comment was pretty narrow!
