### ISSUE TITLE
Update metrics.md to remove 'experimental' and 'new' language

### ISSUE THREAD

**Issue by callum-mcdata** [fishtown-analytics/docs.getdbt.com#1690]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

**Page Link:** https://docs.getdbt.com/docs/building-a-dbt-project/metrics

### What part(s) of the page would you like to see updated?

Lines 16 - 22 contain the following language around metrics being `new` and `experimental`. This isn't as relevant as it was at time of release now that 6 months have passed.

```md
:::info Metrics are new
v1.0.0 includes an initial version of metrics, following a [vibrant community discussion](https://github.com/dbt-labs/dbt-core/issues/4071). Try them out, and let us know what you think!
:::

:::caution Metrics are experimental
v1.0 includes metrics, but they should be considered an _unstable_ API because they are experimental and subject to change. We reserve the right to make breaking changes to the metrics schema in future **minor** versions, but will aim for backwards compatibility when possible.
:::

```
Line 30:

```
In v1.0, dbt supports metric definitions as a new node type. Like [exposures](exposures), metrics participate in the dbt DAG and can be expressed in YAML files. By defining metrics in dbt projects, you encode crucial business logic in tested, version-controlled code. Further, you can expose these metrics definitions to downstream tooling, which drives consistency and precision in metric reporting.
```

I propose (based on feedback from @jtcohen6 in #1676) that we update this language to reflect that metrics are in a more stable state.

**Comment by jtcohen6** [comment]
@callum-mcdata Thanks for opening!

> reflect that metrics are in a more stable state

Up to us if we want to make this declaration now, or closer to v1.3 (October / Coalesce). I'm going to label this for v1.3 just to make sure we don't lose track of it.

**Comment by jtcohen6** [comment]
Should also update / remove the "Ongoing discussions" section at the bottom
