### ISSUE TITLE
Unit testing your dbt package

### ISSUE THREAD

**Issue by yu-iskw** [fishtown-analytics/docs.getdbt.com#1694]
### Contact Details

yu-iskw

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [x] I am a dbt Community member or partner contributing to the Developer Blog
- [x] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

The topic is about best practice of unit testing macros in a dbt package. The motivation is that our dbt community can ensure higher quality of dbt packages by not only integration tests using "public" macros and generic tests, but also unit testing even "private" macros. Moreover, we take advantage of the `adapter.dispatch` macro to test a macro which supports multiple adapters, by switching dbt profiles. It would make us group related unit tests together so that we easily manage. Lastly, I published a dbt package like python's `unittest`. It enables us to implement assertions at ease. 

In general, as we develop software, the interface of a function / method / macro can get better, as they get easy to test. Besides, we can technically decouple a large macro, which are tested with integration tests, by calling "private" macros with unit tests. That enables us to break down larger macros. As a result, I am sure the quality of a software becomes better.  I would think the knowledge enhances dbt developers publish new high quality dbt package from the beginning. I love the idea that dbt has brought the concept of unit testing from the software world to the data world. Similarly, we can bring it to dbt package development. 

### Link to an initial outline.

I have already posted the article with my Medium account. @jasnonaz suggested me to crosspost it to the dbt developer blog. I would be honor to do that. As we messaged, some expression can get better to the community blog. To be honest, English is not my first language. Some expressions look impolite or a bit too casual to the community. I would like to improve them together. Any feedback welcome. Thanks!

https://yu-ishikawa.medium.com/unit-testing-your-dbt-package-148e04634ba0

**Comment by jasnonaz** [comment]
Hi @yu-iskw - this is such an awesome post thank you for creating the issue. Do you have a google doc version of this you can share with me at jason.ganz@dbtlabs.com? We can give it a quick editing pass, run the suggestions by you and then get this live!

**Comment by yu-iskw** [comment]
@jasnonaz I have shared the Google Docs with you and send a notification to you. Can you check your email? If you don't find the email, please let me know.

**Comment by yu-iskw** [comment]
@jasnonaz Thank you for the feedback. I took your proposals and replied about the unclear point. After resolving it, I will pin a version at v1.1.0. 

Apart from that, I made a proposal to add the detail about how we implement integration tests for a dbt pacakge like dbt-utils. That would be useful for dbt users who are interested in implementing their own custom dbt packages. If it sounds good to you, I will describes more details about integration tests.

**Comment by jasnonaz** [comment]
Great - thank you! I'll do another pass early this week and hopefully we can get this into the world

**Comment by yu-iskw** [comment]
@jasnonaz Sounds awesome. I look forward to the feedback. Thanks for the support.

**Comment by jasnonaz** [comment]
@yu-iskw thank you for adding in the section on integration tests! This is coming together nicely - I dropped in another round of edits - can you take a look and approve the ones you think are helpful when you get the chance.

**Comment by yu-iskw** [comment]
@jasnonaz Thank you for your feedback. I took your improvements and suggestions and I added a note about the dbt_datamocktool package at the end of the "Introduce dbt-unittest" section. If it would look ok with you, I would like to make it the released version.  So, can you tell me the next action?

**Comment by yu-iskw** [comment]
@jasnonaz By the way, I posted some blog articles about dbt. If any of them would be useful to share on dbt developer blog, I would like to crosspostt them. To do that, I can create another github issue.

The example articles are as the following:

- https://yu-ishikawa.medium.com/automate-dbt-review-on-github-7bc1c70ebca3
- https://yu-ishikawa.medium.com/understanding-the-scopes-of-dbt-tags-691d0286f3aa

**Comment by jasnonaz** [comment]
Hi - thanks for bearing with us here! Just put a few notes in -  I'm going to ask someone on the team that's implemented a project similuar to this recently to take a read through then we should be ready to go!

**Comment by yu-iskw** [comment]
@jasnonaz Thank you for the feedback. I have taken the suggestions. I look forward to publishing it.

**Comment by jasnonaz** [comment]
Just noting here as agreed on in the doc this is good to go and we'll be loading up this week for a scheduled launch next week

**Comment by yu-iskw** [comment]
@jasnonaz Thank you for making sure of it. I look forward to publishing it!
