### ISSUE TITLE
[Core v1.2] follow-up tasks for grants in v1.2

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#1695]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

The following task need to be completed for Core v1.2:
- [ ] Update dedicated pages for pre/post/on-run-* hooks, using language similar to the language we used in the "Hooks & Operations" topic page
- [ ]  Additive vs. clobber behavior when merging grants configured in multiple places. Jeremy explains [it here](https://github.com/dbt-labs/docs.getdbt.com/pull/1642#discussion_r913657517).
- [ ] Add links to BigQuery docs per [this comment](https://github.com/dbt-labs/docs.getdbt.com/pull/1642#discussion_r918803426). 
  > Understanding GCP "roles" (what we call "privileges"): https://cloud.google.com/iam/docs/understanding-roles
  How to format grantees: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-control-language#user_list

### What part(s) of the page would you like to see updated?

 Need to decide where to add the + behavior.

**Comment by jtcohen6** [comment]
@runleonarun I just realized / remembered that there are a whole separate pages for `pre-hook`, `post-hook`, and `on-run-*` hooks, separate from the ["Hooks & Operations"](https://docs.getdbt.com/docs/building-a-dbt-project/hooks-operations) landing page, and they have `grant` examples galore
- https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook
- https://docs.getdbt.com/reference/project-configs/on-run-start-on-run-end

Added a TODO above to update those pages, in the same way that we updated Hooks & Operations
