### ISSUE TITLE
Article: The Case Against Cherry Picking Your dbt Code Changes

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#1704]
### Contact Details

grace.goheen@dbtlabs.com

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

Why to avoid cherry picking branches and commits when using a branching strategy that uses multiple primary branches for your dbt project repository.

See related [discussion](https://github.com/dbt-labs/docs.getdbt.com/discussions/1315) for more detail.

### Link to an initial outline.

https://docs.google.com/document/d/1T6W3h2m5ROsTwWLbbPh3RFhyrE9tIvuhAbPevZvoHso/edit?usp=sharing

**Comment by KiraFuruichi** [comment]
Hey @graciegoheen took a quick look—I'm so hyped for this piece! My biggest feedback is around simplifying the scenarios a bit and formalizing what cherry picking really means, but I think your visuals are great. If you want to collaborate more on clearing out scenarios/simplifying the examples a bit, I'm happy to do more hands-on work!

**Comment by graciegoheen** [comment]
Thanks so much @KiraFuruichi - the scenarios is the part I'm struggling with the most. I want to make them easy to read and understand, but not 100% sure the best way to simplify. Better visuals? Less moving parts? Would love to collaborate on that piece and get your ideas!

**Comment by KiraFuruichi** [comment]
Cool, sounds great. Let me know what you prefer (async or sync) to work on this:
1. Let me play around with a few formats for the scenarios in a section below your draft and I'll ping you for your thoughts
2. A sync session where we work through the scenarios

Either works for me!

**Comment by graciegoheen** [comment]
Let's do async and see how far we can go (I just added one idea to the bottom of the draft) - if we need to come together to discuss we can schedule a meeting! Thank you so much for your help.
