### ISSUE TITLE
Migration guides shouldn't be hidden based on currently selected project version

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#1706]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.2

### What changes are you suggesting?

I dont think that the migration guides should be hidden when your current version is lower. Almost by definition, people who are looking for the v1.2 upgrade guide are on some version < 1.2

![image](https://user-images.githubusercontent.com/7335046/178882181-7b1b2b0d-ec8b-4c2d-b277-00df475866e3.png)
![image](https://user-images.githubusercontent.com/7335046/178882207-94e6088e-aba6-497f-84d2-20e2d8f24a7e.png)

**Comment by jtcohen6** [comment]
This was a call I made for the v1.1 migration guide initially, but I think I agree. Just a matter of deleting this + this:
https://github.com/dbt-labs/docs.getdbt.com/blob/db94b9a207b42db8fe7181eb1082949805819187/website/dbt-versions.js#L34-L37
https://github.com/dbt-labs/docs.getdbt.com/blob/db94b9a207b42db8fe7181eb1082949805819187/website/dbt-versions.js#L42-L45
