### ISSUE TITLE
Nitpicks on CDC article

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#1729]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/blog/change-data-capture

## Explicitly call out antipatterns:
On my first read through, I only skimmed this article, so originally didn't see that most of the Scenario block is describing the antipattern implementation. Especially since it is so meticulously documented! 

If we're going to include the _what not to do_ version, it should be very very clearly called out at the top of the segment. ([See also my kvetching about this in a different context](https://twitter.com/joellabes/status/1489083160201596930))

## Potentially move the comparison chart up higher
I'm less attached to this opinion, but I also think it'd be useful to pull up the comparison chart at the bottom to before the two better alternatives, so that the reader is going in with a bit more context: 
![image](https://user-images.githubusercontent.com/7335046/179429673-af761036-9b9d-47ca-bcfb-2c451043edfc.png)

## Clarify dbt's relationship to versioning
Finally, "Because of this, the concepts of “version history” and “backups” aren’t intrinsic to dbt" is a bit unfair – version control isn't intrinsic to _any_ programming language, it sits on top of the text files. I'm worried that it'll get pulled out into a Google extract one day like 
![image](https://user-images.githubusercontent.com/7335046/179429619-59fbc925-6090-41aa-8b6d-14e4fbce54a1.png)
I don't really know what to write instead though sorry!

**Comment by joellabes** [comment]
@graciegoheen and @krevitt I _guess_ this is you? Not sure exactly who to @

**Comment by graciegoheen** [comment]
@johnblust Tagging you here as well

**Comment by johnblust** [comment]
@graciegoheen @joellabes If you two are on the same page about these changes, you can feel free to spin up a PR to make these changes!
