### ISSUE TITLE
Update Postgres profile configuration to reference retries parameter

### ISSUE THREAD

**Issue by tomasfarias** [fishtown-analytics/docs.getdbt.com#1733]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Postgres profile: https://docs.getdbt.com/reference/warehouse-profiles/postgres-profile
And Redshift profile (as the underlying adapter is the same): https://docs.getdbt.com/reference/warehouse-profiles/redshift-profile

### What part(s) of the page would you like to see updated?

dbt-core PR [#5432](https://github.com/dbt-labs/dbt-core/pull/5432) resolved dbt-core issue [#5022](https://github.com/dbt-labs/dbt-core/issues/5022) by adding retry functionality for dbt-postgres and dbt-redshift (as it inherits it from the former).

The docs should be changed so that users are aware of the existence of a new `retries` configuration in the `profiles.yml` of Postgres and Redshift, and that they can tweak it according to their needs.

The change should add `retries` to the sample `profiles.yml` for Postgres and Redshift, mention the default of 1, and explain how this parameter determines how many times will dbt attempt to connect a Postgres/Redshift database, which could help with transient network issues, like latency spikes.

### Additional information

The PR is still in development, but very close to finished, so the doc changes should line up with the dbt-core version that includes the change.

**Comment by runleonarun** [comment]
I see `retries` documented in both postgres and redshift profiles so I am closing this issue, but feel free to open if I've closed it in error!
