### ISSUE TITLE
KonMari your data: Fundamentals of Planning a Query Migration using the Marie Kondo Method

### ISSUE THREAD

**Issue by lbenezra-FA** [fishtown-analytics/docs.getdbt.com#1760]
### Contact Details

@lauren.benezra (slack)

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

We want to write a blog post that details how one might approach a massive migration project -- where do I start? Who should I bring in to help? What are reasonable expectations? 

### Link to an article.

https://dbtlabs.notion.site/KonMari-your-data-Fundamentals-of-Planning-a-Query-Migration-using-the-Marie-Kondo-Method-940ac363153d48339eaae75439c997d9

**Comment by krevitt** [comment]
One question for you @lbenezra-FA!  

Given we have the [refactoring guide](https://docs.getdbt.com/guides/getting-started/learning-more/refactoring-legacy-sql) + [course](https://courses.getdbt.com/courses/refactoring-sql-for-modularity) (which follow a relatively similar path to your outline), I wonder if there's a different angle we could take on this age-old problem?  One idea (not offended at all if you think this idea is trash)...

Something that's come up for me recently is how to actual select + plan your first big migration project - like how do you choose a first thing to work on, plan out how to get it done, decide who should be involved + what timelines you should expect, etc?  Kind of "how to plan" + "what to expect" in your first big pass at writing modular SQL.

**Comment by lbenezra-FA** [comment]
ohhhh i love that! @krevitt super great take on refactoring. I'll update!

**Comment by lbenezra-FA** [comment]
I've redesigned this concept to be applying the KonMari Method to data migration. See here for the WIP
https://dbtlabs.notion.site/KonMari-your-data-Fundamentals-of-Planning-a-Data-Migration-using-the-Marie-Kondo-Method-940ac363153d48339eaae75439c997d9

**Comment by lbenezra-FA** [comment]
@krevitt ready for review!

**Comment by krevitt** [comment]
Now live w/ https://github.com/dbt-labs/docs.getdbt.com/pull/1958: https://docs.getdbt.com/blog/marie-kondo-query-migration
