### ISSUE TITLE
On-page anchors don't seem to be working

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#1785]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

As far as I can see, all that contain anchors. I'm opening this after trying to go to https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook#call-a-macro-to-grant-privileges-on-a-model from a Slack link.

The page loads but I stay at the top of the page, instead of being taken down to that header. If I click `Call a macro to grant privileges on a model` in the right hand table of contents, I am jumped down to that header and the URL in the top bar doesn't change at all. 

I _suspect_ that this is something to do with versioning? the ToC sometimes spins when I first load/reload the page, presumably while it evaluates what headings even exist. 

### What changes are you suggesting?

In-page anchors should work

**Comment by runleonarun** [comment]
Joel, I think this happens when the title of the page has changed. I no longer see that section on this page, so I'm closing this issue. Please open a new issue if you still see this behavior!
