### ISSUE TITLE
Getting Started - Unneccessary step to replace default values

### ISSUE THREAD

**Issue by matthunt1984** [fishtown-analytics/docs.getdbt.com#1790]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/guides/getting-started/learning-more/getting-started-dbt-core

Step 6
![image](https://user-images.githubusercontent.com/16030708/180656211-aa7da62b-5f2e-4565-b17e-f4c063bd650f.png)

### What changes are you suggesting?

The step outlines changing default values, however these are already in place in my project file

![image](https://user-images.githubusercontent.com/16030708/180656254-39666d93-70b0-4fa8-a214-c70ae6a9e8dd.png)

![image](https://user-images.githubusercontent.com/16030708/180656268-c67d25d5-c572-48e3-9322-deb11038e411.png)

I assume Step 6 can be removed

### Additional information

This is my first time using dbt (hence the guide!) but seems to be outdated

**Comment by runleonarun** [comment]
Closing this issue as we've refreshed this guide! Please open a new issue if you see any other problems! 🙇🏻‍♀️
