### ISSUE TITLE
Getting Started With the dbt Semantic Layer: How To Metric

### ISSUE THREAD

**Issue by callum-mcdata** [fishtown-analytics/docs.getdbt.com#1796]
### Contact Details

@callummccann

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

This blog covers what the semantic layer is, what components it is built from, and how to use it today and in the future! It is the devhub companion blog post to a soon-to-be released product post from Drew on the Semantic Layer. 

### Link to an initial outline.

https://www.notion.so/dbtlabs/Getting-Started-With-The-dbt-Semantic-Layer-To-Metric-Or-Not-To-Metric-46e562ec6f1549b3b5e6af2a483d8439

**Comment by KiraFuruichi** [comment]
Hey @callum-mcdata can we close this out now :)

**Comment by callum-mcdata** [comment]
Let it close!
