### ISSUE TITLE
[Beta] Core 1.3 release (July, 2022)

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#1800]
### Overview 
For Core v 1.3 Beta, we aim to provide helpful content for the new Python models.  

### Link to source material

Source material includes any Core PRs that we should document. It may include internal content, but we will minimize that when possible and note when that happens.
* Link to internal doc project.
* Link to Core PR for Python models

### Subtasks
Tasks we need to accomplish to consider this project complete:
* link-to-issue#

### Documentation plan

The documentation plan should include the minimum viable docs (MVD) for this beta release. We want to provide content to help people successfully use the new feature while minimizing the amount of content we need to rewrite for GA.

**Comment by jtcohen6** [comment]
Closing as resolved - we did the thing!
