### ISSUE TITLE
Code formatting and links not working together

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#1832]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

These 3 pages have typos in formatting:

- https://docs.getdbt.com/reference/dbt-classes
- https://docs.getdbt.com/reference/dbt-jinja-functions/ref
- https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.0

### What part(s) of the page would you like to see updated?

Here are screenshots of each (with the erroneous section highlighted in blue):

https://docs.getdbt.com/reference/dbt-classes

![image](https://user-images.githubusercontent.com/44704949/182716604-088ce7d2-037c-4ecf-a44c-c12082cd96ff.png)

https://docs.getdbt.com/reference/dbt-jinja-functions/ref

![image](https://user-images.githubusercontent.com/44704949/182716625-42f0c3b7-3195-4e6e-9e89-047f19f62f74.png)

https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.0

![image](https://user-images.githubusercontent.com/44704949/182716668-6ad8495f-07bc-4b8b-9f33-f079a753305d.png)

### Additional information

I did not investigate further or try any fixes.

**Comment by runleonarun** [comment]
Looks like this has been fixed
