### ISSUE TITLE
Remove insert, update, merge, delete suggestions from CTE page

### ISSUE THREAD

**Issue by epapineau** [fishtown-analytics/docs.getdbt.com#1838]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/terms/cte#cte-syntax-how-it-works

### What part(s) of the page would you like to see updated?

The first sentence of the CTE Syntax: How it works reads like it's suggesting this is possible / appropriate:
```
with my_cte as (
    merge...
)
```

Even if it's interpreted as follows, that is not the correct way to build at least an insert, delete, or merge statements
```
with my_cte as (
 select my_col
 from foo
)
select/insert/merge/delete/update
```

**Comment by KiraFuruichi** [comment]
Hey @epapineau , great callout, I see how this is confusing. I'll add this in to my next PR for glossary updates and tag you in the PR!
