### ISSUE TITLE
I want to write about how the Model Timing tab helped identify a long running model that was fixed

### ISSUE THREAD

**Issue by bennieregenold7** [fishtown-analytics/docs.getdbt.com#1842]
### Discussed in https://github.com/dbt-labs/docs.getdbt.com/discussions/1802 for Developer Blog

<div type='discussions-op-text'>

<sup>Originally posted by **bennieregenold7** July 26, 2022</sup>
## Core Thesis
 - Using `Model Timing` to find a model bottleneck
 - Go through the steps required to troubleshoot, optimize, test, and deploy the code

## Specific Target Audience
Those that have long running jobs and may not know how to best approach getting the run times down

## Supporting Example Use Case
Us!! See the mock intro below for how we addressed `fct_dbt_invocations`

## Narrative Arc
- Start with how big our project is, and why that makes it hard to visualize run times
- Model Timing tab to the rescue!
- Explain how finding the long-running model is just step 1, next up you have to fix it
- Walk through identifying the possible performance gains using Snowflake profiler
- Show how we tested out theories and compared run times
- Touch on how we tested the change to make sure things were still looking good
- Mention the deployment process
- Save the fun for the end...the $$$ saved with this change (specifically how Cloud providers make it possible to assign a $ figure to improved run times)

## First Draft
Checkout the link here: https://www.notion.so/dbtlabs/Devhub-Blog-Model-Timing-f9a079563c7540e0a89ba30c42273d94
</div>

**Comment by KiraFuruichi** [comment]
So hyped about this Bennie! Will take a look/pass at it this week!

**Comment by KiraFuruichi** [comment]
@bennieregenold7 this is looking really great to me, I think we should be able to have published by end of next week! I left some new comments in the Notion draft, but other than that (and coming up with a title), it's looking good to me. I think all that's left is for @jasnonaz 's feedback and then we can whip up a PR!

**Comment by bennieregenold7** [comment]
Excellent! I went ahead and put the branch together for this. Once we get those final edits it should be quick to move to a PR.

https://github.com/dbt-labs/docs.getdbt.com/tree/model-timing-blog-post
