### ISSUE TITLE
Broken links to source code

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#1852]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/contributing/building-a-new-adapter#required-macros

### What part(s) of the page would you like to see updated?

None of these links work:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/44704949/183915506-768ceea5-f3c9-4b80-a3d8-99580048f5b1.png">

### Additional information

There's a few different ways to solve this so it creates less problems in the future:
1. Remove the links to the source code altogether
1. Permalink them to the current references in the main branch
1. Permalink them to the latest stable release of Core (like [this](https://github.com/dbt-labs/dbt-core/blob/v1.2.0/core/dbt/include/global_project/macros/adapters/columns.sql#L37))

I like the last one, especially if each version of the docs has its own version of these links.
The key part would be making sure it stays up to date every time we do a new release (which is not trivial!)

But at least the links wouldn't be _broken_ at that point -- they would just be stale.

**Comment by lostmygithubaccount** [comment]
can't we do some sort of autogeneration here (maybe not now, but eventually)? manually maintaining links to code in documentation has, in my limited experience, been a fruitless effort

**Comment by dbeatty10** [comment]
How were you thinking about autogenerating?

**Comment by lostmygithubaccount** [comment]
normally there's something like this with a "[source]" link that's auto-generated from the underlying code via sphinx or something: 

<img width="796" alt="image" src="https://user-images.githubusercontent.com/54814569/183942809-4e77edcf-0047-46c7-8be6-5c503a5266a3.png">

**Comment by dbeatty10** [comment]
I've used sphinx to auto-generate docs for a Python project before -- indeed basically just followed the example of how Pandas generates their documentation.

In this case, the language is Jinja rather than Python. I'm not aware of Sphinx-like system for generating docs for Jinja macros. If you find something though, you should add it to this conversation!

However, there _is_ a dbt way to [generate documentation for project-level macros](https://docs.getdbt.com/docs/building-a-dbt-project/jinja-macros#example:~:text=%C2%A0How%20do%20I%20document%20macros%3F) (`dbt docs generate`), but I'm not sure if it links to GitHub or not. Regardless, it creates a stand-alone website written in Angular that needs to be hosted somewhere -- far cry from the HTML docs created by Sphinx -- and I'm guessing not compatible with the software we use to host our docs.

**Comment by runleonarun** [comment]
This is fixed in the short-term and hopefully we will get some automation going in the future!
