### ISSUE TITLE
Metrics properties aren't in the properties section of the docs

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#1865]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

The table at https://docs.getdbt.com/docs/building-a-dbt-project/metrics#available-properties should instead live at https://docs.getdbt.com/reference/configs-and-properties

### What part(s) of the page would you like to see updated?

Right now the documentation isn't in the same place as for all other nodes.

**Comment by mirnawong1** [comment]
closing this as metrics are going to be deprecated - let me know if i got this wrong @joellabes !
