### ISSUE TITLE
Updates to incremental models > `unique_key`

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#1888]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#defining-a-uniqueness-constraint-optional

### What part(s) of the page would you like to see updated?

In cases with multiple `unique_key` (list), none of the column values should be null. If there's any risk of one or more columns being null, users should handle that within their model logic, either by:
- `coalesce`'ing each column or creating a single surrogate (hash) key
- using [`dbt_utils.surrogate_key`](https://github.com/dbt-labs/dbt-utils#surrogate_key-source)

Additionally, I think we should retitle this section to something other than "uniqueness **constraint**" because:
- this is not a real [database constraint](https://www.postgresql.org/docs/current/ddl-constraints.html)
- specifying this `unique_key` config does not prevent the _new data_, returned by model SQL, from containing dupes — it just defines the key(s) to use when upserting/merging

### Additional information

https://github.com/dbt-labs/dbt-core/issues/5691

**Comment by runleonarun** [comment]
This appears to have [been addressed](https://docs.getdbt.com/docs/build/incremental-models#defining-a-unique-key-optional)!  Please reopen if you think otherwise!
