### ISSUE TITLE
A Guide to Migrating from dbt Core to Cloud

### ISSUE THREAD

**Issue by anaisvaillant** [fishtown-analytics/docs.getdbt.com#1892]
### Contact Details

anais.vaillant@dbtlabs.com

### I have read the dbt Developer Blog contribution guidelines.

- [x] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [x] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

Brian Gillet, Amy Chen and I are noodling over a migration guide for customers interested in moving from dbt core to dbt cloud. When speaking to customers, we've noticed the word _migration_ feels intimidating and often leaves customers overthinking where/how to start. 

The hope with this guide, is to help create a framework of how to think about a migration and provide a list of considerations (similarly to the [how to configure your dbt repository (one or many)](https://discourse.getdbt.com/t/how-to-configure-your-dbt-repository-one-or-many/2121) post) so the customer has a better grasp of the amount of work and time needed. 

We are thinking about this in the lines of workflows and how these would change: 
- people
- dbt (cloud account, dbt cloud project and dbt project)
- other tools they may have (orchestration, docs, BI, etc)

Target Audience: a data engineering lead, architect, project leader

### Link to an initial outline.

https://www.notion.so/dbtlabs/Migrating-from-dbt-Core-to-Cloud-ebc29b299bdf43059cc83efad6bc2d12

**Comment by jasnonaz** [comment]
Hi @anaisvaillant - this looks like a really incredible post that fills a real niche. Looking forward to reading a draft. I think the key for this will be getting really detailed about how to prep for the migration and the hands-on things we've seen work well in the past.

The outline looks incredible to me. Only thing I'm wondering is whether it's a bit ambitious for a V1 - a huge amount of interesting topics in there that I imagine will each require a hefty amount of thought. Up to you, but wondering if it makes sense to do a v1 that covers less surface area, but is able to go appropriately deep - then immediately move into work on adding the rest of this.

**Comment by runleonarun** [comment]
Looks like this work has been complete in https://github.com/dbt-labs/docs.getdbt.com/issues/2592

Closing as fixed, but let me know if we need to reopen!

**Comment by runleonarun** [comment]
oops! This is still needed!

**Comment by amychen1776** [comment]
I don't think anyone would disagree with me that we should close this out for now. We have one blog post on why but let's not leave this open until we have capacity/more specifics
