### ISSUE TITLE
Demystifying event streams: Transforming events into tables with dbt

### ISSUE THREAD

**Issue by reallocf** [fishtown-analytics/docs.getdbt.com#1894]
### Contact Details

Charlie Summers in dbt slack or charlie@gomerits.com

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

This article discusses how to convert events from an event-driven microservice architecture into relational tables in a warehouse like Snowflake. In it, I’ll share:
- Why you may want to use an architecture like this.
- How to structure your event messages.
- How to use dbt macros to make it as easy as possible to onboard new domain models.
To learn more, check out my talk at Coalesce 2022!

Targeted at people working with event streams within dbt.

### Link to an initial outline.

First draft: https://docs.google.com/document/d/18TQ64LQNBVWqoKwhDNukLBA-fs4XkxbB4xb5ZfwMI8Q/edit

**Comment by jasnonaz** [comment]
Charlie this is a _killer_ post!! Thank you for putting it together. It clarifies a ton of concepts super well and really goes deep on how you solved the problem.

If there's one area I'd love to see a little bit more detail on it's how exactly the data contracts were decided on, encoded and enforced. This is a topic of huge personal interest atm and would love to hear just a bit more there. Once that is done, I think we're looking really great here and can start getting this ready to publish.

**Comment by reallocf** [comment]
@jasnonaz just finished making the requested edits! I also added a section called "Events as Contracts" - let me know if it has the info you're interested in. Happy to elaborate more if you think it's worth it! :)

**Comment by jasnonaz** [comment]
This looks fantastic! Ready from our end to get this published @reallocf. Just give me a 👍 and we can get it loaded up.

**Comment by johnblust** [comment]
@reallocf Hey Charlie, I'll be opening a PR for this content so we can get it published. I'll need access to the document to be able to do that. Let me know when you're ready to share this doc with me!

**Comment by reallocf** [comment]
Thanks @jasnonaz and @johnblust ! I'm getting final sign-off from my marketing team that it looks good on their end as well. Will get back with more info soon 👍

**Comment by johnblust** [comment]
Cool, I'll hold off on creating a PR for this until we get the 🟢

**Comment by reallocf** [comment]
@johnblust @jasnonaz I made some small tweaks on my end, feel free to review again as a final pass. But we're all clear from Marketing! They're prepping a copy of the post for our blog - @jasnonaz you mentioned we should link them together somehow, let me know what you need from me to help get that done.

Thanks so much for all y'all's help! Really excited to get this up and posted! 🎉
