### ISSUE TITLE
Specify that Python models are not currently supported for BigQuery in dbt Cloud

### ISSUE THREAD

**Issue by KiraFuruichi** [fishtown-analytics/docs.getdbt.com#1906]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/building-a-dbt-project/building-models/python-models#specific-data-warehouses

### What part(s) of the page would you like to see updated?

We hint at this in the beginning of the page with "dbt Cloud support will be limited at the start", but I'd like to be more explicit for practitioners that at the current moment, they cannot use Python models in dbt Cloud for BigQuery.

In specific, would love to see a little callout that we don't currently have the equivalence of the profile options needed for running Python models in BigQuery in dbt Cloud in the `Specific data warehouses` section. Folks using BigQuery should defer to using the CLI for Python model development (for now).

Also not sure if Python models work in dbt Cloud of Databricks either? @lostmygithubaccount suggested they might not be, so we should add to this new callout if that's also true!

Could also reframe it so that it's more like "Snowflake is the only data warehouse that is currently supported for Python model development in dbt Cloud during this beta phase"

### Additional information

[Community slack thread](https://getdbt.slack.com/archives/CBSQTAPLG/p1661349199843349) where this issue was originally brought up.

**Comment by runleonarun** [comment]
Thank you @KiraFuruichi This is a great idea! Adding it to the Hackathon bucket.

**Comment by runleonarun** [comment]
This has been addressed in [Specific data platforms section](https://docs.getdbt.com/docs/build/python-models#specific-data-platforms)
