### ISSUE TITLE
Why Analysts Make The Best Analytics Engineers

### ISSUE THREAD

**Issue by brittanykrauth** [fishtown-analytics/docs.getdbt.com#1911]
### Contact Details

@Brittany Krauth (Degreed)

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

Leading up to my 2022 Coalesce talk on _Upskilling from an Analyst to an Analytics Engineer_... I wanted to share my favorite reasons for _Why Analysts Make The Best Analytics Engineers_.  Instead of hiring your next Analytics Engineer, I'm hoping to convince you that you already have someone with a ton of potential on your team: your Analyst!  This blog post will focus on the "Why" and share my top reasons that your Analyst is the perfect candidate to be diving into dbt

### Link to an initial outline.

https://docs.google.com/document/d/1w0D6MjJ0wHQtv5h999hTrFzWtsUTaK-PSBwCVm0kkek/edit?usp=sharing

**Comment by KiraFuruichi** [comment]
Hey @brittanykrauth how are we looking for a first draft in the next few weeks? Is there anything you need from me to support you in this? :)

**Comment by KiraFuruichi** [comment]
Looking forward to your next draft Brittany! Please don't hesitate to reach out if you have any questions for me :)
