### ISSUE TITLE
Clarify variable scoping for macros

### ISSUE THREAD

**Issue by lostmygithubaccount** [fishtown-analytics/docs.getdbt.com#1928]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-variables#defining-variables-in-dbt_projectyml

See https://github.com/dbt-labs/dbt-core/issues/5587 for context

### What part(s) of the page would you like to see updated?

Add a note/warning that a macro's context is derived from its calling model's project, not the one it is defined

### Additional information

I can take a stab at making a PR for this

**Comment by isaacsantelli** [comment]
Looking at this !

**Comment by jtcohen6** [comment]
was just about to resolve this with https://github.com/dbt-labs/docs.getdbt.com/pull/3605 !
