### ISSUE TITLE
Foundry Blog - Round One Apprentice Retrospective

### ISSUE THREAD

**Issue by SamHarting** [fishtown-analytics/docs.getdbt.com#1946]
### Contact Details

Slack Sam Harting | Wasila

### I have read the dbt Developer Blog contribution guidelines.

- [ ] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

This is targeted towards people either interested in becoming an analytics engineer or those wanting to develop their own apprenticeship program for their company. 

This article explores Sam and Wasila's experiences in the Foundry Program. This will include what led us to the program, what learning to be analytics engineer was like, how it felt to work with clients, and where we are at now in our careers. This will serve both as a story, as well as hopefully provide some inspiration and important knowledge to our target audiences.

Initial outlining and brainstorming was done with @jasnonaz, @SamHarting and @wasilaq. The exact structure of the article is still not fully decided.

### Link to an initial outline.

[Initial Outline](https://docs.google.com/document/d/15zPoK30-YIKy5GBSAg89FST_GDjeqvepwIzVGGzP3O0/edit#)
_The outline changed significantly from the beginning to where we are at now at the time of opening this issue. Each version of the outline is clearly labeled within the document itself._

[Sam's Rough Draft](https://docs.google.com/document/d/1xOQbhdBAlsxysVcb-Pa5yz4p-lM-iOaLErOzxBhn1Vg/edit)

[Wasila's Rough Draft](https://docs.google.com/document/d/1S2_cr7pkozkObvAwbxDm0Rzpiw96cuXe-It-0HrPNF4/edit?usp=sharing)

**Comment by jasnonaz** [comment]
Just noting down the decision from last week's writing session that we're going to go ahead with these as two separate posts that are released together + link to each other

**Comment by wasilaq** [comment]
Posting the link for my [new draft](https://docs.google.com/document/d/1f7xg5fDITadeonNvrHCvB7Ibqutuh3HvTxOY6w7rqTI/edit?usp=sharing). I'll stop by office hours this week :)

**Comment by wasilaq** [comment]
@KiraFuruichi

**Comment by KiraFuruichi** [comment]
I'm going to get up a PR for Wasila's next week :) 🚀

**Comment by SamHarting** [comment]
Howdy, my article is ready for another review!

**Comment by SamHarting** [comment]
@KiraFuruichi

**Comment by KiraFuruichi** [comment]
Awesome Sam thanks for letting me know! I'm going to be OOO starting on Friday and all next week, so I won't be able to have time to review it before then.

If you have time, feel free to stop by DevHub Writing Sessions tomorrow at 12:30pm PST so the group can take a look :) 

Either when I'm back in a week and a half or David/Ganz can provide a deeper review of your draft next week if you're unable to make it to writing session tomorrow! NBD either way :)

**Comment by SamHarting** [comment]
@johnblust Hello! Kira and I went over edits to this article during office hours last week. I went over what she gave me and made the adjustments. I believe she is on vacation this week so she told me to talk to you once I have finished the edits. Should be ready for your final adjustments (adding links etc)!

**Comment by johnblust** [comment]
Hey @SamHarting! I've got this on my to-do list for this week. I'll message you here once I've taken a look :)

**Comment by johnblust** [comment]
@SamHarting I've left some small grammatical/word choice suggestions throughout the draft, and I also added a brief section at the end calling out Wasila's content piece. Let me know when you've resolved all suggestions or if you have any questions! Great job on this content piece!!!


@KiraFuruichi I left one question in there for when you get back regarding the intro. LMK what you think!

**Comment by SamHarting** [comment]
@johnblust I believe I just resolved all of the grammatical errors!
