### ISSUE TITLE
Enhancement: Centralize page for `hostname` definition

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#1953]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

The purpose of this issue is to have a separate page that explains what a `hostname` means for MT and ST instances in more detail, and can serve as the centralized page that lays out `hostname` and its meanings for different regions. This issue is indirectly related to PR #783  

### Resources
Affected pages:
- https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-sso-with-saml-2.0
- https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/connecting-your-database

### Proposal 
The `hostname` field can live [here](https://docs.getdbt.com/reference/dbt_project.yml) potentially and include the following information:

- instance/`hostname` IP address
- instance/`hostname` URL
- region where the instance is hosted, 
- dbt Cloud account number example (ST instances have a combination of numbers and letters)

### What changes are you suggesting?

Changes are being suggested to have a centralized location of the definition of hostname. This is important as dbt Cloud multi-tenant scales to other regions and will also allow users/docs team to link out to that definition page, where appropriate. This keeps content aligned and centralized, and if any changes need to be made, they are made in one page.

**Comment by runleonarun** [comment]
I think [this page](https://docs.getdbt.com/docs/cloud/about-cloud/regions-ip-addresses) resolves this issue, but feel free to open, Mirna, if I'm wrong.
