### ISSUE TITLE
Run dbt in the browser using Pyodide

### ISSUE THREAD

**Issue by arieldbt** [fishtown-analytics/docs.getdbt.com#1970]
I wanted to share a hack time project that will allow you to run dbt in your browser using Web Assembly via the Pyodide project:

https://pyodide.org/en/stable/

The tldr is that the Pyodide project has done all of the hard work of compiling the Python interpreter to WebAssembly. I made some small changes so that dbt could be run on Pyodide. Here is a demo of the jaffle shop example project using sqlite and dbt in the browser:

https://s3.amazonaws.com/com.getdbt.cloud.wasm/index.html

This work is very experimental and I expect there to be some rough edges. That being said, it would be great to hear how running dbt in your browser could help empower your work or the work of others in your organization.

**Comment by runleonarun** [comment]
Closing as it was closed in the core repo
