### ISSUE TITLE
Dead link on Building a new adapter

### ISSUE THREAD

**Issue by sdebruyn** [fishtown-analytics/docs.getdbt.com#1974]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/contributing/building-a-new-adapter

### What part(s) of the page would you like to see updated?

> The more you can answer Yes to the below questions, the easier your adapter development (and user-) experience will be. See the [New Adapter Information Sheet wiki](https://github.com/dbt-labs/dbt-core/wiki/New-Adapter-Information-Sheet) for even more specific questions.

The link _New Adapter Information Sheet wiki_ is dead and points to a wiki that doesn't exist (anymore).

**Comment by runleonarun** [comment]
Closing because I no longer see this link on  this page, which now lives here: https://docs.getdbt.com/guides/advanced/adapter-development/7-verifying-a-new-adapter

Please reopen if I missed something!
