### ISSUE TITLE
Capture SSO and Azure DevOps screen shots for new UI

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#1976]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

Below are the screenshots/gif that capture the new UI, for the following documents:

- https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-sso-with-saml-2.0
- https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/setup-azure

- _Note - [this page](https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-enterprise-sso-with-azure-active-directory) has a Azure ST configuration screenshot with numbers and the numbers don't seem to sync with the steps_

### A. SSO
- [Setting up SSO SAML](https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-sso-with-saml-2.0)
![setting_sso_saml_dbtcloud](https://user-images.githubusercontent.com/89008547/189630489-87de46f9-d486-40b7-a3bd-17bdcdd0925f.png)

- [Setting up SSO with Gsuite](https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-sso-with-google-gsuite)
![setting_sso_gsuite](https://user-images.githubusercontent.com/89008547/189630390-66d8fa89-7bdf-42cb-b868-b55022a5b535.png)

*Could not replicate the [Verify SSO Credentials](https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-sso-with-google-gsuite#supply-your-oauth-client-id-and-client-secret) step so I captured the existing example of what the user should receive, and removed the UI portion of the screenshot. 
![setting_sso_gsuite_verify](https://user-images.githubusercontent.com/89008547/189630419-a2e7cc54-c4d6-47bd-9f5c-65e8ce911504.png)

- [Setting up SSO with Azure](https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-enterprise-sso-with-azure-active-directory)
![setting_sso_azuread_st](https://user-images.githubusercontent.com/89008547/189630454-640fe754-8ae5-4fca-ad07-252cd74eefe9.png)

### B. Configure Azure Dev Ops
- [Set up Azure DevOps](https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/setup-azure#add-your-azure-ad-app-to-dbt-cloud) 
![connecting_azure_devops](https://user-images.githubusercontent.com/89008547/189628493-ba9553e7-0f52-48a2-b408-ebe9ff67469d.gif)
![connecting_azure_set_up](https://user-images.githubusercontent.com/89008547/189629855-ecaba22a-69ac-4a81-ba01-cb3376a47d1a.png)

- [Connecting a service user](https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/setup-azure#connecting-a-service-user)
![connecting_azure_set_up](https://user-images.githubusercontent.com/89008547/189629949-a85ad670-7f01-42ce-861a-cf98c396962c.png)

- [Authenticate with Azure DevOps](https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/authenticate-azure)
![connecting_azure_linked_azuredevops_acct](https://user-images.githubusercontent.com/89008547/189629319-f2ca6dd8-2e96-4ac0-8560-11220ad3c2c8.png)

### What changes are you suggesting?

Below are the screenshots/gif that capture the new UI, for the following documents:

- https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-sso-with-saml-2.0
- https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/setup-azure

- _Note - [this page](https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-enterprise-sso-with-azure-active-directory) has a Azure ST configuration screenshot with numbers and the numbers don't seem to sync with the steps_

**Comment by runleonarun** [comment]
Thanks so much for your help Mirna! This issue will close once I merge PR#1839

**Comment by runleonarun** [comment]
Should have close when we merged https://github.com/dbt-labs/docs.getdbt.com/pull/1839
