### ISSUE TITLE
add GH action to validate `sidebar.js`'s `sidebarSettings` variable

### ISSUE THREAD

**Issue by dataders** [fishtown-analytics/docs.getdbt.com#1997]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

all PRs in which pages are added or deleted.

### What changes are you suggesting?

 If there's an EOL comma in an array, docusaurus build action will fail with the message "failed to build". There should be something that lints/validates the `sidebar.js` before trying to do a docusaurus build.

thanks in advance,

late-night committers, everywhere

### Additional information

Maybe we could run [ESLint](https://eslint.org/docs/latest/user-guide/getting-started#installation-and-usage) on just `sidebar.js` as a starting point?

**Comment by dataders** [comment]
not sure if it's possible but linting a JSON object would be easier than linting a javascript dict within a javascript file. perhaps `sidebars.js` could load `sidebarSettings` from `.json`?
https://github.com/dbt-labs/docs.getdbt.com/blob/4497633c59d62abe4b9d1741b99dcbba99fbcefe/website/sidebars.js#L1-L10

**Comment by runleonarun** [comment]
@JKarlavige What are your thoughts on this? Should I create an Asana ticket?

**Comment by JKarlavige** [comment]
> @JKarlavige What are your thoughts on this? Should I create an Asana ticket?

Yes a ticket for us would be great! We have ESLint enabled, so we should just have to edit the ESLint config to ensure it is checking the sidebars file.

**Comment by mirnawong1** [comment]
Hey team, if an asana ticket has been created, I'll go ahead and close this issue. Thank you for opening us Anders!

If an asana ticket hasn't been opened, pls let me know and I'll do it!
