### ISSUE TITLE
Python improvements

### ISSUE THREAD

**Issue by lostmygithubaccount** [fishtown-analytics/docs.getdbt.com#2017]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

python models, I can find it 

### What part(s) of the page would you like to see updated?

we should add:

- section with huge warning lights on how to go from development => prod
- bleeds into best practices, but very much needed somewhere for now 
- GCP quota note
- other platform-specific learnings (to pandas)
- maybe a note on Pandas on that

**Comment by lostmygithubaccount** [comment]
- lowercase note
- the other issue assigned to me

**Comment by runleonarun** [comment]
Thanks for opening this, Cody! I am going to close this as it doesn't have enough context to act on. Feel free to reopen and provide a little more context (like links to pages and what's needed) and we're happy to triage alongside our new feature work ❤️
