### ISSUE TITLE
Add favor-state feature to defer documentation

### ISSUE THREAD

**Issue by josephberni** [fishtown-analytics/docs.getdbt.com#2021]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/node-selection/defer

### What part(s) of the page would you like to see updated?

Addition of documentation around the new favor-state feature which which enables --defer to favor using --state node even if node exists in current target.

This optionally removes the below second --defer criterion when using the --favor-state flag.

**Comment by jtcohen6** [comment]
More context for this in https://github.com/dbt-labs/dbt-core/issues/5016

**Comment by jtcohen6** [comment]
resolved by #2676
