### ISSUE TITLE
Add snowflake profile docs on how to authenticate with private_key instead of the private_key_path

### ISSUE THREAD

**Issue by ZeRego** [fishtown-analytics/docs.getdbt.com#2036]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/warehouse-profiles/snowflake-profile

### What part(s) of the page would you like to see updated?

Ability to authenticate by providing the decoded private_key instead of the private_key_path and private_key_passphrase.

Related to: https://github.com/dbt-labs/dbt-snowflake/pull/265

**Comment by runleonarun** [comment]
Hello and thank you for opening this issue! It looks like this has been added for 1.5 and higher: https://docs.getdbt.com/docs/core/connect-data-platform/snowflake-setup#key-pair-authentication Feel free to reopen if you believe it hasn't been addressed.
