### ISSUE TITLE
Convert docs page to an FAQ 

### ISSUE THREAD

**Issue by nghi-ly** [fishtown-analytics/docs.getdbt.com#2041]
[Link to internal project](https://www.notion.so/dbtlabs/Fast-follows-Docs-IA-refresh-cfe834d2530d43f2adfef242188b911d)

### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Currently this page https://docs.getdbt.com/docs/building-a-dbt-project/dont-nest-your-curlies lives in the Docs area which seems a bit out of place. 

### What part(s) of the page would you like to see updated?

Convert the page to an FAQ. Then, create a redirect and update links that point to the page.

**Comment by runleonarun** [comment]
We moved this and I think it's great where it is. Feel free to reopen if you think we should address this.
