### ISSUE TITLE
Ignore files via `.dbtignore`

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#2043]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Probably makes sense to create a new page for this.

Users can define a `.dbtignore` file that uses the exact same syntax as `.gitignore`:
- https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files
- https://git-scm.com/docs/gitignore

As the name suggests, dbt will ignore these files. They won't be treated as part of your dbt project.
```
models/
├─ include_these/
├─ but_not_this/
```
```
# .dbtignore
models/but_not_this/*
```

### What part(s) of the page would you like to see updated?

- Create a new page for this
- Reference it in https://docs.getdbt.com/reference/project-configs/model-paths (and similar pages)

### Additional information

https://github.com/dbt-labs/dbt-core/pull/5897

**Note: This will only be available in v1.3+**

**Comment by jmg-duarte** [comment]
Does `.dbtignore` support path "inclusion"?
```
models/
!models/special_ones # only includes this one
```

**Comment by lostmygithubaccount** [comment]
@jmg-duarte I think so? if it's supported in a `.gitignore`, it should be supported in `.dbtignore` -- if you find otherwise please open an issue in the `dbt-labs/dbt-core` repository: https://github.com/dbt-labs/dbt-core/issues/new/choose

closing this as completed by #2245
