### ISSUE TITLE
add `macros` to Jinja context

### ISSUE THREAD

**Issue by karunpoudel** [fishtown-analytics/docs.getdbt.com#2070]
Related to https://github.com/dbt-labs/dbt-core/pull/5915

### Contributions

- [ ] I am a PM or subject matter expert at dbt who is responsible for this feature.

### Where does this content belong?

In [dbt Jinja functions](https://docs.getdbt.com/reference/dbt-jinja-functions), add `macros` similar to graph and model

### Link to source material

macros

`macros` is the dict object that lists all macros in the dbt project with their details similar to how it appears in manifest.json.

**Comment by runleonarun** [comment]
Closing because related Core PR has been closed. https://github.com/dbt-labs/dbt-core/pull/5915 Feel free to reopen if we decide to move forward with the core PR
