### ISSUE TITLE
Edit dbt Cloud feature content and re-home artifacts and model-timing tab content

### ISSUE THREAD

**Issue by nghi-ly** [fishtown-analytics/docs.getdbt.com#2074]
[Link to internal project](https://www.notion.so/dbtlabs/Fast-follows-Docs-IA-refresh-cfe834d2530d43f2adfef242188b911d)

### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/get-started/dbt-cloud-features
https://docs.getdbt.com/docs/dbt-cloud/cloud-ide/the-dbt-ide

### What part(s) of the page would you like to see updated?

- [x]  Rename and rewrite "the dbt IDE" page to include the dbt Cloud features too, not just the IDE.
- [x]  Cull information from these pages: https://docs.getdbt.com/docs/running-a-dbt-project/using-the-dbt-ide and https://docs.getdbt.com/docs/dbt-cloud/cloud-ide/ide-beta#overview and https://docs.getdbt.com/docs/dbt-cloud/cloud-ide/ide-beta#dbt-cloud-ide-features and  
- [x] Edit [dbt Cloud features](https://docs.getdbt.com/docs/get-started/dbt-cloud-features) to include the dbt Cloud features too, not just the IDE

### Additional information

Update Dec 14th, 2022: We moved tasks from this issue for rehoming content to a new issue. #2573

**Comment by nghi-ly** [comment]
hi @runleonarun : with the current PR #2100 i'm working on, i've migrated "the dbt IDE" page over to the new dir, renamed it to "dbt Cloud features", and set up the redirect. marked it as done.

**Comment by mirnawong1** [comment]
closing issue as this was addressed in this pr: https://github.com/dbt-labs/docs.getdbt.com/pull/2771
