### ISSUE TITLE
How to move data from spreadsheets into your warehouse

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#2086]
### Contact Details

@joellabes

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

A common question is "if I'm not allowed to use seeds to load large files into the DWH, what should I use instead?" 

This doc answers that question - I went and found (pretty much) every way to turn a spreadsheet into a table, and provide the pros and cons for each approach. 

### Link to an initial outline.

https://docs.google.com/document/d/1EPR4WxnBwFwhfcwpAfxkYav4ID-bsEm2u3gkU-yLj9g/edit#

**Comment by KiraFuruichi** [comment]
Dope dope dope dope post idea @joellabes ! Assigning myself as your go-to person for editing, PR, and promotion support since this topic is near and dear to my heart. This seems like it's in a really good place already, so I'll go through and give it a thorough editing pass later this week!

**Comment by KiraFuruichi** [comment]
Ok I read it while it was fresh on the mind and left some feedback in the doc! I think it's in such fantastic state, my only overall thematic suggestion is to include some concrete examples for what type of data/files is appropriate for each tool.
