### ISSUE TITLE
accurate test summary

### ISSUE THREAD

**Issue by maciejskorski** [fishtown-analytics/docs.getdbt.com#2107]
### Discussed in https://github.com/dbt-labs/docs.getdbt.com/discussions/2095

<div type='discussions-op-text'>

<sup>Originally posted by **maciejskorski** September 28, 2022</sup>
I find the test summary bit imprecise on reporting sub-selected tests.
 
When I subselect ~ 70 tests to run, I see all of them counted in the summary. 
I would rather expect "found 4", or a two-line communicate "a) found 70, b) subselected 4".
Would it be beneficial to give it some thinking and improving the message?

```
azureuser@mskorski:~/projects/test_project/dataops-dic-dbt$ dbt test --select tag:source_data
15:17:40  Running with dbt=1.0.4
15:17:40  Found 9 models, 78 tests, 0 snapshots, 0 analyses, 390 macros, 2 operations, 0 seed files, 9 sources, 0 exposures, 0 metrics
15:17:40  
15:17:40  
15:17:40  Running 1 on-run-start hook
15:17:40  1 of 1 START hook: dataops_dic.on-run-start.0................................... [RUN]
15:17:40  1 of 1 OK hook: dataops_dic.on-run-start.0...................................... [CREATE SCHEMA in 0.00s]
15:17:40  
15:17:40  Concurrency: 6 threads (target='test')
15:17:40  
15:17:40  1 of 4 START test test_clinical_rowcount........................................ [RUN]
15:17:40  3 of 4 START test test_labs_results_numeric..................................... [RUN]
15:17:40  2 of 4 START test test_labs_namemapping......................................... [RUN]
15:17:40  4 of 4 START test test_labs_rowcount............................................ [RUN]
```</div>

**Comment by runleonarun** [comment]
@dbeatty10 should this be transferred over to Core?

**Comment by runleonarun** [comment]
@jtcohen6 What do you think?

**Comment by mirnawong1** [comment]
hey @dbeatty10 or @jtcohen6 wanted to follow up on this> otherwise, happy to close this issue if it's not related to the docs.

**Comment by mirnawong1** [comment]
hey @maciejskorski , apologies for the delay here! but if you're still encountering this issue or an issue similar to error messages, the best place to address this would be opening up a [dbt core issue](https://github.com/dbt-labs/dbt-core/issues/new/choose) to flag this. 

since this issue relates to dbt core it seems and not the docs.getdbt.com site, I'm going to go ahead and close this issue up. thank you again for opening it and let me know if you think this should be re-opened!
