### ISSUE TITLE
Update Setting up Airflow and dbt Cloud

### ISSUE THREAD

**Issue by kwcanuck** [fishtown-analytics/docs.getdbt.com#2110]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/guides/orchestration/airflow-and-dbt-cloud/2-setting-up-airflow-and-dbt-cloud

### What part(s) of the page would you like to see updated?

Some of the Astro CLI commands are outdated. For example,` brew install astronomer/cloud/astrocloud` is now `brew install astro` and `astrocloud dev start` is now `astro dev start`. An updated version of the Astro CLI Guide is available [here](https://deploy-preview-1275--gallant-neumann-56599d.netlify.app/astro/cli/overview).

### Additional information

Hi! We're writers at Astronomer and we noticed that some of the Astro CLI commands in the dbt Cloud docs use outdated syntax. You'll probably want to update the example Astro CLI syntax and replace `astrocloud` with `astro`.

**Comment by kwcanuck** [comment]
Hi, @runleonarun. Just checking in to see when this issue might be addressed. Thanks in advance for any updates you can share.

**Comment by runleonarun** [comment]
Addressed in https://github.com/dbt-labs/docs.getdbt.com/pull/2789
