### ISSUE TITLE
Link to Guides from Docs by opening new tab

### ISSUE THREAD

**Issue by nghi-ly** [fishtown-analytics/docs.getdbt.com#2122]
[Link to internal project](https://www.notion.so/dbtlabs/Fast-follows-Docs-IA-refresh-cfe834d2530d43f2adfef242188b911d)

### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Let's link to guides from the Docs sidebar when appropriate, but have them live in /guides.

For example, we could move [Getting started with dbt Cloud](https://docs.getdbt.com/docs/get-started/getting-started/set-up-dbt-cloud) over to /guides, but have it appear to be part of the docs by putting the link in the sidebar.js. Along with the box with arrow we see here: 

![Image](https://user-images.githubusercontent.com/3880403/205777823-0b60cd59-43ea-4527-9917-d119855404e2.png)

### What part(s) of the page would you like to see updated?

Should these links open in a new tab?

**Comment by runleonarun** [comment]
This issue is now addressed with the new quickstarts project. If we want to add the arrow box, we need to open an asana ticket for the front end eng team
