### ISSUE TITLE
Use a different colored favicon to differentiate between docs and dbt Cloud tabs

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/docs.getdbt.com#213]
When you have the docs and dbt Cloud open at the same time, it becomes confusing which is which.

We should consider using a different color favicon for the docs — grey? navy? Over to you @amy-byrum

**Comment by clrcrl** [comment]
Inspo: Snowflake docs versus console
<img width="602" alt="Screen Shot 2020-06-16 at 8 45 27 AM" src="https://user-images.githubusercontent.com/20294432/84776012-ca82e380-afad-11ea-92ab-e34909dbd47a.png">

**Comment by amy-byrum** [comment]
My suggestion would be to use the color that's currently serving as the header background on the docs site. [https://drive.google.com/file/d/1N68JXTQZhkCL5Mvi1P3d2P-p-hQwO2vt/view?usp=sharing](url)

**Comment by clrcrl** [comment]
I like that!

**Comment by amy-byrum** [comment]
Iterating on this for dark/light mode
