### ISSUE TITLE
Create survey for user feedback after Coalesce 

### ISSUE THREAD

**Issue by nghi-ly** [fishtown-analytics/docs.getdbt.com#2130]
[Internal project](https://www.notion.so/dbtlabs/Fast-follows-Docs-IA-refresh-cfe834d2530d43f2adfef242188b911d)

### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Survey readers to obtain feedback on the Docs site: https://docs.getdbt.com/docs/ 

### What part(s) of the page would you like to see updated?

Leona will reach out to Emily to create some docs surveys to capture user feedback post coalesce. Surveys can include user feedback on sidebar landing pages and other structured questions

**Comment by runleonarun** [comment]
Closing because we've launched a new user research program
