### ISSUE TITLE
Add a page for new available regions

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#2134]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Possibly add the new page here:
https://next.docs.getdbt.com/docs/deploy/regions

### [new page] Regions (under dbt Cloud Deployments)

This page would move the table that currently lives in [[IP Restrictions](https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/connecting-your-database#ip-restrictions)](https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/connecting-your-database#ip-restrictions) into its own page that lists available regions. 

Provides a central place to link to vs embedding regions into many pages: the Multi Tenant Page, Security Page, IP Restrictions page.

### Additional information

Internal link to [starter content](https://docs.google.com/document/d/1FfI_1uv9Hd0SRn_y8GrOPDbOKkk30oq2KIBTRtrALDs/edit?usp=sharing)

* Work with @azzam34 to collaborate on the content 
* Create the GitHub PR to add it to the next branch.

**Comment by mirnawong1** [comment]
@azzam34 @runleonarun - looks like this page be included in the [about deployments page?](https://deploy-preview-2152--docs-getdbt-com.netlify.app/docs/deploy/deployments) if yes, the page should then be renamed 'Deployments and regions or something like that?

**Comment by runleonarun** [comment]
closed by https://github.com/dbt-labs/docs.getdbt.com/pull/2174
