### ISSUE TITLE
Azure AD SSO client secret expiration

### ISSUE THREAD

**Issue by MitchellBarker** [fishtown-analytics/docs.getdbt.com#2145]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-enterprise-sso-with-azure-active-directory#creating-a-client-secret

### What part(s) of the page would you like to see updated?

Just noticed a small inaccuracy in our azure sso docs. Looks like azure AD [no longer supports](https://devblogs.microsoft.com/microsoft365dev/client-secret-expiration-now-limited-to-a-maximum-of-two-years/) setting client secrets to never expire, but our docs still instruct users[ to set up the client secret](https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-enterprise-sso-with-azure-active-directory#creating-a-client-secret) with that expiration value. The max that value can be set to now is 2 years.

I'd suggest a fix, but not sure exactly how we'd want to word it. Perhaps the copy under [Connecting Azure DevOps](https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/setup-azure#add-your-azure-ad-app-to-dbt-cloud) would work here as well:
> You are responsible for the Azure AD app secret expiration and rotation.

**Comment by kbrock91** [comment]
had a customer ask about this exact issue this week! any updates on getting this updated in our docs with information about secret rotation?

**Comment by ajaythomas** [comment]
Resolved by https://github.com/dbt-labs/docs.getdbt.com/pull/2728
