### ISSUE TITLE
FAQ: What does the number in the CLI output mean?

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/docs.getdbt.com#215]
Add an FAQ for this output:
```
15:22:14 | 1 of 1 OK hook: logging.on-run-end.0................................. [SUCCESS 1 in 1.80s]
```
(especially when there's two numbers for incremental models!)

We get this questions every so often, and I never remember the answer, so would be good to know it

**Comment by clrcrl** [comment]
@drewbanin — do you want to add this? Or just let me know the answer in the commend and I'll turn it into an FAQ?

**Comment by drewbanin** [comment]
Sure thing! This is actively changing in some places, so the docs are going to be a little difficult to pin down:
- https://github.com/fishtown-analytics/dbt/issues/2580
- https://github.com/fishtown-analytics/dbt/pull/2530

The exact output you see depends on:
1. the configured materialization
2. the target database

pg/redshift should show you:
 - **Table**: `SELECT <rows in table>`
 - **View**: `CREATE VIEW`
 - **Incremental**: `INSERT 0 <rows inserted>`

Here, the incremental case is the interesting one. The pg/redshift status for an insert statement contains two numbers. The first number is "*oid* row that was inserted" if a single row is inserted. The second number is the number of rows that were inserted if the more than 1 row was inserted.

An _oid_ is a unique identifier for a row. More info on this in [the docs](https://www.postgresql.org/docs/current/sql-insert.html) (cmd+f for "outputs").

For Snowflake/BigQuery, we render even more different outputs for different statement types. The work being done in #2530 is really compelling, and I'm really looking forward to #2580!

**Comment by clrcrl** [comment]
Ha, ok this issue is enough info for me! I might close this and then next time someone asks it, we at least have the issue available
