### ISSUE TITLE
How to integrate dbt with 3rd party Snowflake ML workflows 

### ISSUE THREAD

**Issue by segar3** [fishtown-analytics/docs.getdbt.com#2154]
### Contact Details

@ryan.segar

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

How to integrate dbt with 3rd party Snowflake ML workflows- as we launch our python capabilities on dbt cloud a lot of questions have emerged around what dbt python is designed for and more important what it is not designed for. ML and how ML tools can integrate with dbt workflows is an important distinction to make. This "how to" write up demonstrates how users can achieve mock ML calls using dbt functions with standard sql workflows, sagemaker and modelbit. The diversity of the examples is meant to show the flexibility of the dbt placement in these use cases as well as variance in which tools can be used to accomplish ML goals. 

I will need some help to round out the tech how to with the messaging that you all find appropriate to frame this. I recognize that I'm not the best writer :-) 

### Link to an initial outline.

https://docs.google.com/document/d/1ejkCBfvSz9ow4SRoXl-RG1nmYuZb0CxX4lvanUzL7vQ/edit#heading=h.lk5mcjogc4o3

**Comment by KiraFuruichi** [comment]
Hey @segar3, thanks for opening up this issue and sharing your draft!! We’re always super excited for ML content on the DevBlog and particularly for the Solutions Architects to get more involved.

After looking at your draft, you have a very strong technical piece that I think will speak well to the audience your are targeting. I really like how you go into multiple examples and scenarios throughout your post, so readers can customize what they learn here to their own work.

The biggest opportunity for expansion in this article is around the building a strong narrative within the piece to complement the technical aspects.  Some things we might consider:
- Why someone would want to be doing this (beyond saving costs and time); perhaps grounding the narrative and context of this piece entirely around the lead_scoring example you mention here.
- Aesthetic, editorial changes to fit Developer Blog style and add to readability (ex. adding explicit or numbered steps to your descriptions “First, a data scientist will typically need to deploy a model using something like AWS Sagemaker”), which the DevHub Team can help with in a line-by-line editing process (which we can do async or we can set up some sync time).
- Supplementing your post with a graphic or two to show the actual workflow, probably in the beginning of the post somewhere, to help users grok what you’ll be describing in words (we can send some template [Figma files/designs](https://www.notion.so/dbtlabs/Technical-Content-Design-Resources-a496a5abbbcc48e38127f8c32f9c352e) that you can build off of).
- Additional context to augment the technical sections. This could either be expansions on the why or the how - all in service of connecting to the narrative, practitioner focused thesis.

One thing that might be helpful for developing this post's narrative would be a co-writer, particular someone with a DS/ML background like Sung or Matt W.

I’ve assigned myself as the primary Team DevHub member for this post, so can help with any editing, feedback, PR creation, and promotion after Coalesce. For next steps, I can do a line-by-line first pass on where I think you can add more context or build a stronger narrative, but let me know if you’d prefer to iterate on it first before I do that.

Regarding timelines, we aim to have posts from Issue --> Publication in ~6 weeks, but we work on a schedule that works for you and we recognize that there's a lot going on at dbt Labs in the following month. We want contributing to the DevBlog to be a fun activity for folks, so please let me know what works for you for next steps and a general timeline that you think will work for you 😄

**Comment by KiraFuruichi** [comment]
Hey @segar3! Just wanted to check-in on this issue; is this article something you want to pursue next quarter, or potentially close out all together? Just lmk, I'm trying to create a slate of DevBlog issues to work on for the new year :)

**Comment by sungchun12** [comment]
@segar3 I added comments!
