### ISSUE TITLE
Python models has missing link and section

### ISSUE THREAD

**Issue by belasobral93** [fishtown-analytics/docs.getdbt.com#2176]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/docs/building-a-dbt-project/building-models/python-models#specific-data-platforms

![Screen Shot 2022-10-10 at 10 03 13 AM](https://user-images.githubusercontent.com/35778239/194918535-c673e8a7-5687-4d43-8fe7-ada894fc742e.png)

### What changes are you suggesting?

1. `Note that only [specific data platforms](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/python-models#specific-data-platforms) support dbt-py models.`
  -- link doesn't take us anywhere

2. `Below, you'll see sections entitled "❓ Our questions." We are excited to release a first narrow set of functionality in v1.3, which will solve real use cases.`
 -- there aren't any sections that have ❓ on the page

**Comment by runleonarun** [comment]
Thanks for opening this issue @belasobral93! 
1. The specific data platform link works for me. Can you let me know your browser and version so we can investigate?
2. I see the sections. They are "callouts." But we will make the language clearer so you can better understand how to navigate these!  cc @lostmygithubaccount @jtcohen6 and @matthewshaver

**Comment by belasobral93** [comment]
@runleonarun 
I think it does have to do with my chrome version ( 106.0.5249.103 ), the screenshot below is the only thing I see when I open the page (no other sections on the right hand side, and no callouts below) 

![Screen Shot 2022-10-10 at 11 27 04 AM](https://user-images.githubusercontent.com/35778239/194930652-4b80ea08-0064-4aba-b225-de1d9f7611b6.png)

**Comment by lostmygithubaccount** [comment]
I think we resolved this -- main issue being that 1.3 isn't selected at the top, so seeing some 1.2 placeholder docs. internal slack thread: https://dbt-labs.slack.com/archives/C03C17F0PC6/p1665430951974699?thread_ts=1665424345.376319&cid=C03C17F0PC6

**Comment by runleonarun** [comment]
I think we fixed this now! As @lostmygithubaccount mentioned, we have part of the page versioned for 1.3. We now link to that version 1.3 from the 1.2 or lower page so you can easily change to it. I'm going to close this, but please let me know if we should reopen!
