### ISSUE TITLE
Move "Learning more" guides to another location 

### ISSUE THREAD

**Issue by nghi-ly** [fishtown-analytics/docs.getdbt.com#2178]
[Link to internal project](https://www.notion.so/dbtlabs/Fast-follows-Docs-IA-refresh-cfe834d2530d43f2adfef242188b911d)

### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

* [Using jinja](https://docs.getdbt.com/docs/get-started/learning-more/using-jinja).
* [Refactoring Legacy SQL](https://docs.getdbt.com/docs/get-started/learning-more/refactoring-legacy-sql)

PR based off of `next` that moved these guides into the Docs area: https://github.com/dbt-labs/docs.getdbt.com/pull/2172 

### What part(s) of the page would you like to see updated?

Think about moving these guides to another location:

- Refactoring legacy SQL to dbt 
- Using Jinja

**Comment by mirnawong1** [comment]
hey @nghi-ly closing this issue as it seems this was resolved with the recent guide changes. let me know if you think this should stay open, however!
