### ISSUE TITLE
Clarify what is a project name 

### ISSUE THREAD

**Issue by nghi-ly** [fishtown-analytics/docs.getdbt.com#2194]
[Link to internal project](https://www.notion.so/dbtlabs/Fast-follows-Docs-IA-refresh-cfe834d2530d43f2adfef242188b911d)

### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Follow up after Coalesce: 

https://www.notion.so/draft-About-dbt-projects-500fc58648ba43a4be64aa5f95160b48?d=40d6a6db95f143aba663a1c9630a026d#0a6824157a95417a9918b9ecaadde0e4

### What part(s) of the page would you like to see updated?

Investigate the "project name" differences and document them to reduce confusion

**Comment by runleonarun** [comment]
Completed https://docs.getdbt.com/docs/build/projects
