### ISSUE TITLE
Document addition of `merge_exclude_columns`

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#2197]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#strategy-specific-configs

### What part(s) of the page would you like to see updated?

- Add `merge_exclude_columns` in parallel to `merge_include_columns`
- Mention and link from v1.3 migration guide

### Additional information

https://github.com/dbt-labs/dbt-core/pull/5457

**Comment by boxysean** [comment]
Wow, I just had a team ask for this feature. Apparently it was just released but the documentation is not yet visible 🤯 Anyways, I love moments like this, and hope you can share a little bit of joy @jtcohen6
