### ISSUE TITLE
Change Postgres configurations page

### ISSUE THREAD

**Issue by dennis8** [fishtown-analytics/docs.getdbt.com#2199]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

[https://docs.getdbt.com/reference/resource-configs/postgres-configs](https://docs.getdbt.com/reference/resource-configs/postgres-configs)

### What part(s) of the page would you like to see updated?

Add an additional configuration option:
`{{ config(materialized='table', columnar=True) }}`
With this you can define the table should be column-oriented.
This requires Citus Columnar extension to be activated in the PostgreSQL database.

### Additional information

I have tested it and it works for me.

**Comment by matthewshaver** [comment]
Looks like this was closed on the Core repos. See Jercos reasoning [here)https://github.com/dbt-labs/dbt-core/issues/6052#issuecomment-1334207940)
