### ISSUE TITLE
Link broken in docs?

### ISSUE THREAD

**Issue by max-sixty** [fishtown-analytics/docs.getdbt.com#222]
### Describe the bug

On this page: https://docs.getdbt.com/reference/resource-configs/schema/
<img width="858" alt="image" src="https://user-images.githubusercontent.com/5635139/85059257-31440080-b158-11ea-9621-4eeb5873ecac.png">

There's a link to this page under `Using Custom Schemas`: https://docs.getdbt.com/reference/resource-configs/schema/

...which gives me a `Page Not Found`

<img width="862" alt="image" src="https://user-images.githubusercontent.com/5635139/85059275-3c972c00-b158-11ea-90ec-ba1e88e2699b.png">

Thanks!

**Comment by drewbanin** [comment]
hey @max-sixty - thanks for the heads up. I transferred this issue to the docs.getdbt.com repo. Feel free to send through a PR for a fix if you can, otherwise we'll get this fixed up soon!

**Comment by VersusFacit** [comment]
This has been fixed. I just checked the broken link in question and it works. Closing this issue
