### ISSUE TITLE
Fix broken link

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#2252]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/artifacts/dbt-artifacts#notes

### What part(s) of the page would you like to see updated?

The third bullet has a broken link:
> * [visualizing source freshness](https://docs.getdbt.com/reference/artifacts/cloud-snapshotting-source-freshness)

**Comment by brad-meru** [comment]
Should this point [here](https://docs.getdbt.com/docs/deploy/source-freshness)? Looks like it originally pointed to a "Snapshotting Source Freshness" article. Or in that case, maybe [this](https://docs.getdbt.com/docs/build/sources#snapshotting-source-data-freshness) is the right link.

**Comment by runleonarun** [comment]
Close by https://github.com/dbt-labs/docs.getdbt.com/pull/2259
