### ISSUE TITLE
Fix/Remove broken links in the documentation

### ISSUE THREAD

**Issue by matthewshaver** [fishtown-analytics/docs.getdbt.com#2258]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

The following areas of the documentation contain links returning 404 errors.
docs.getdbt.com/guides/...
docs.getdbt.com/blog/...
docs.getdbt.com/reference/...

Need to validate that the links are bad, whether or not a replacement can be found, or if the link should be removed.
Use the following spreadsheet to view all "known bad" links:

https://docs.google.com/spreadsheets/d/1migO1gjKGGHKy6V9g0vTIGLfcpg8NZvsmkVxMxgpMsM/edit?usp=sharing

### What changes are you suggesting?

Change all docs.getdbt.com links returning 404 errors to reflect a working dbt link with the relevant info. 
If a replacement docs.getdbt.com link can not be found, notify the docs team via @dbt-labs/product-docs mention

For 3rd party links, if an updated, working link can not be found, remove it from the documentation.

**Comment by runleonarun** [comment]
These should all be fixed now!
