### ISSUE TITLE
Bug: Link broken in doc

### ISSUE THREAD

**Issue by southpolemonkey** [fishtown-analytics/docs.getdbt.com#226]
## Steps to reproduce:

Link to `Configuring Quoting` is broken in [Class Reference - Relation section](https://docs.getdbt.com/docs/writing-code-in-dbt/class-reference/#relation)

## Expected results:

Jump to the right page

## Actual results

Page Not Found

## Extra details

I think [this](https://docs.getdbt.com/reference/project-configs/quoting) should be the landing page.

**Comment by clrcrl** [comment]
You can also suggest an edit (especially for small fixes) by clicking the "Edit this page" button at the bottom of each page
