### ISSUE TITLE
Jinja functions space should have documentation for `metric()`, like `ref()`. 

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#2260]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Doesn't exist yet

### What part(s) of the page would you like to see updated?

There should be a single page which talks about what `metric()` does. The only documentation I can find is on how to query a metric using the metrics package, where it is used in the example e.g. in `metric_list` https://docs.getdbt.com/docs/build/metrics#supported-inputs

### Additional information

https://docs.getdbt.com/reference/dbt-jinja-functions/ref

**Comment by mirnawong1** [comment]
hey @joellabes , i think this issue is now not necessary given the updates to the SL and metricflow, right?

**Comment by joellabes** [comment]
Yep this is obsolete now!
