### ISSUE TITLE
Dead link on profile docs

### ISSUE THREAD

**Issue by sdebruyn** [fishtown-analytics/docs.getdbt.com#2265]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/reference/project-configs/profile

### What changes are you suggesting?

the link [Connecting to your warehouse](https://docs.getdbt.com/reference/project-configs/dbt-cli/configure-your-profile) on that page doesn't work anymore, needs to be updated

**Comment by compilerqueen** [comment]
https://docs.getdbt.com/docs/get-started/connection-profiles#connecting-to-your-warehouse-using-the-command-line

^ seems to be the most likely replacement, though it'll need the additional clarification that it's for command line only.
