### ISSUE TITLE
Dead link on Source Properties: https://docs.getdbt.com/reference/source-properties

### ISSUE THREAD

**Issue by LMandtler** [fishtown-analytics/docs.getdbt.com#2267]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/reference/source-properties

### What changes are you suggesting?

The link 'using sources' in the first paragraph is basically dead. Probably it should link to this page: https://docs.getdbt.com/docs/build/sources#using-sources

**Comment by runleonarun** [comment]
Thanks for opening this, @LMandtler and contributing to our open source repo! It appears that we have fixed this link.
