### ISSUE TITLE
Add documentation of ALLOW_UNUSED_CONFIG_PATHS flag

### ISSUE THREAD

**Issue by katieclaiborne** [fishtown-analytics/docs.getdbt.com#2272]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/reference/global-configs

### What changes are you suggesting?

dbt-labs/dbt-core#6091 introduces a new flag, which needs to be documented.

**Comment by katieclaiborne** [comment]
cc @felippecaso

**Comment by runleonarun** [comment]
Closing because https://github.com/dbt-labs/dbt-core/pull/6091 was closed. Let me know if you think this should remain open and be addressed.
