### ISSUE TITLE
Mention the scope required for the service account API token for the semantic layer integration

### ISSUE THREAD

**Issue by b-per** [fishtown-analytics/docs.getdbt.com#2280]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/use-dbt-semantic-layer/quickstart-semantic-layer
https://docs.getdbt.com/docs/use-dbt-semantic-layer/setup-dbt-semantic-layer#set-up-dbt-semantic-layer

### What part(s) of the page would you like to see updated?

The pages suggest creating a service account API token but they don't mention what access scope the token need to be provided.

**Comment by mirnawong1** [comment]
hey @b-per , thank you for opening this up! I've added some add'l clarifying language in PR #2288 based on this [slack thread](https://dbt-labs.slack.com/archives/C03KHQRQUBX/p1666179201277549?thread_ts=1666167820.879499&cid=C03KHQRQUBX) and also wanted to  ask if the language [here](https://docs.getdbt.com/docs/use-dbt-semantic-layer/setup-dbt-semantic-layer#set-up-dbt-semantic-layer) in step 11 needed more clarification on the permissions needed: 

> Set up the [Metadata API](https://docs.getdbt.com/docs/dbt-cloud-apis/metadata-api) (Team and Enterprise accounts only) in the integrated partner tool to import the metric definitions. The [integrated partner tool](https://www.getdbt.com/product/semantic-layer-integrations) will treat the dbt Server as another data source (like a data platform). This requires:
The account ID, environment ID, and job ID (visible in the job URL)
An [API service token](https://docs.getdbt.com/docs/dbt-cloud-apis/service-tokens) with job admin and metadata permissions
Add the items above to the relevant fields in your integration tool

**Comment by mirnawong1** [comment]
#2288
