### ISSUE TITLE
update BigQuery/Dataproc docs on permissions and other details

### ISSUE THREAD

**Issue by lostmygithubaccount** [fishtown-analytics/docs.getdbt.com#2308]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

python models

### What part(s) of the page would you like to see updated?

BigQuery setup

### Additional information

https://getdbt.slack.com/archives/C03QUA7DWCW/p1666735910433449

check through other threads too

**Comment by jtcohen6** [comment]
Related: https://github.com/dbt-labs/docs.getdbt.com/pull/2393
