### ISSUE TITLE
Link to Python models best practices does not exists

### ISSUE THREAD

**Issue by JCZuurmond** [fishtown-analytics/docs.getdbt.com#2328]
[The link to the Python models best practices does not exist.](https://github.com/dbt-labs/docs.getdbt.com/blob/d70b04337bbe59578ddf1fcca1c523f246bf6b6e/website/docs/docs/build/python-models.md?plain=1#L15).

Does anyone know which discussion it should link to?

**Comment by lostmygithubaccount** [comment]
it looks like discussions were disabled for this repo, breaking the link -- following up internally, thanks for reporting
