### ISSUE TITLE
Make content more accessible

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#2345]
Internal Docs project: https://www.notion.so/dbtlabs/Translations-I18N-Internationalization-0f94f6dec41f4e91a6750f8c3f7cc9d8 and https://www.notion.so/dbtlabs/Make-content-more-accessible-624529faae224e37bacfd09d6463a8d8
## Overview

We should make sure our docs are accessible to all audiences. Our docs contain complex sentences and language, which might prevent some people from being able to benefit from our docs. Headings tend to be less descriptive and often use one word.

- [ ] Provide a checklist to help writers (from dbt and the community) provide content with web accessibility and non-native English speakers in mind. It can include both [localization-specific](https://github.com/github/docs/blob/main/contributing/localization-checklist.md) and [web accessibility](https://www.w3.org/WAI/tips/writing/) guidelines.
 - [ ] Edit all existing pages using the check list.
- [ ] Help remind people to use the checklist for new content (maybe edit our GitHub Action to link to the checklist in the issue template?

### What part(s) of the page would you like to see updated?

all

**Comment by matthewshaver** [comment]
Ongoing but will revisit project in the future
