### ISSUE TITLE
Dark Mode Font Color Issue

### ISSUE THREAD

**Issue by ibozhu** [fishtown-analytics/docs.getdbt.com#2346]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/docs/build/snapshots

![](https://aws1.discourse-cdn.com/business7/uploads/getdbt/original/2X/b/b014ada63d40bb4050c4cb44055f5b28302c94bd.png)

### What changes are you suggesting?

Whenever there is a light background, use a dark colour for the font.

**Comment by mirnawong1** [comment]
hey @ibozhu ! thanks so much for flagging this and great callout! I will share this with our front engineering team so they can have a look at this. 

I'll message you back here when it's been fixed, appreciate your contribution!

**Comment by kopackiw** [comment]
Also, the same issue is spotted with "hoverable" elements ([source page](https://docs.getdbt.com/docs/build/sources#faqs), the `How do I run tests on just my sources?` section).

<img width="808" alt="Screenshot 2022-11-05 at 17 57 47" src="https://user-images.githubusercontent.com/26244440/200132041-41b662a4-1174-49ca-8133-5800c188b792.png">

**Comment by kopackiw** [comment]
... and tabs in tab groups as well 😅 

<img width="822" alt="Screenshot 2022-11-05 at 18 44 10" src="https://user-images.githubusercontent.com/26244440/200133826-52763987-5917-495d-b627-b0464a1e0f9b.png">

**Comment by JKarlavige** [comment]
Thanks for sharing the additional sections with issues @kopackiw. I added them to our task to get those fixed!

**Comment by runleonarun** [comment]
Was fixed in https://github.com/dbt-labs/docs.getdbt.com/pull/2481
