### ISSUE TITLE
clearly note resource name schemes (e.g. dots "." not really supported)

### ISSUE THREAD

**Issue by lostmygithubaccount** [fishtown-analytics/docs.getdbt.com#2347]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

not entirely sure -- feel free to close if this is clearly covered. opening this to track a review + required updates on resource naming conventions per https://github.com/dbt-labs/dbt-core/issues/5980

certain characters, like dots "." are not exactly supported

### What part(s) of the page would you like to see updated?

see above -- clearly enumerate rules for resource names

**Comment by runleonarun** [comment]
It looks like we do mention that special characters are not recommended in source names in [this page](https://docs.getdbt.com/reference/resource-properties/quoting#default) about quoting so I'm going to close this issue out. Feel free to reopen if I am wrong!
