### ISSUE TITLE
add dbtonic language to glossary

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#2350]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

## Overview
Clarify what dbtonic means and where it can live. Currently the only reference to dbtonic is in the [dbtonic Jinja](https://docs.getdbt.com/docs/build/jinja-macros#dbtonic-jinja) section which describes dbtonic as:

> Just like well-written python is pythonic, well-written dbt code is dbtonic.

Based on Docs team meeting, this issue serves the purpose to document the problem statement and proposed solution. Adding @KiraFuruichi to the issue as well per Leona for technical accuracy
   

## Problem statement
How can we clarify what dbtonic means (dbt way of writing dbt code) to users, and where can this live so it's easily discoverable by users? 

See [slack thread here](https://dbt-labs.slack.com/archives/C017GDLAF7D/p1666684449476619)

## Proposed solution
- dbtonic definition can live in the [glossary page](https://docs.getdbt.com/glossary) to clarify what it means
- If more code-related examples are needed, dbtonic definition and code examples can live in the https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md OR https://docs.getdbt.com/blog/essential-dbt-project-checklist

## Resources
Slack thread: https://dbt-labs.slack.com/archives/C017GDLAF7D/p1666690253793359?thread_ts=1666684449.476619&cid=C017GDLAF7D

### What part(s) of the page would you like to see updated?

add dbtonic entry to https://docs.getdbt.com/glossary page or other pages 
   
### Additional information
 - [ ] Discussed in docs meeting: https://www.notion.so/dbtlabs/Docs-team-meeting-80e77db95fee4366b877c9e17c6c8d47

**Comment by mirnawong1** [comment]
hey @sdurry ! did you still want to take this on and add 'dbtonic' to the glossary?

**Comment by sdurry** [comment]
> hey @sdurry ! did you still want to take this on and add 'dbtonic' to the glossary?

Thank you @mirnawong1 for the reminder. I have just not been able to put the content together and don't think I will anytime soon. Sorry 😢

**Comment by mirnawong1** [comment]
hey @sdurry no worries! also i'm happy to contribute to this or help get this over the finish line - i understand what dbtonic language is but may need help with examples. do you have any links you can point me to that have a good example? if you don't have any, no worries and i can close this issue out and we can reopen later on.

**Comment by mirnawong1** [comment]
Closing this issue and it's not planned in the near future but happy to reopen it again should we have more info!
