### ISSUE TITLE
Creating Type 2 Kimball Dimensions from Snapshots

### ISSUE THREAD

**Issue by brandon-segal** [fishtown-analytics/docs.getdbt.com#2363]
### Contact Details

bsegal@spotify.com

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

This post was inspired by the "Babies in the bathwater" talk from the 2022 Coalesce talk that discussed if Kimball is still relevant. A common pattern in data engineering is to take a daily snapshot ([recording the state of a table and saving it to a daily partition](https://www.youtube.com/watch?v=4Spo2QRTz1k) ) as a mechanism for change data capture. While very simple, this method does result in a bad experience through downstream consumers that makes it difficult to bring these dimensions into bi tools, effectively understand change events, and respond to upstream data quality issues. This post will go over taking these snapshots and translating them through clear steps and macros used by our team at Spotify to Kimball-style type two dimensions. 

### Link to an initial outline.

[Type 2 Dimensions after snapshotting all the things](https://docs.google.com/document/d/1IiNslXj63lurdLM1b4SBrS_HF2Klr4T0_cLk-eYVPL4/edit?usp=sharing)

**Comment by KiraFuruichi** [comment]
Hey @brandon-segal! As I commented in the other issue you opened up, we are very very hyped to get this post up on the Developer Blog!

I’ve assigned @krevitt, a member from the dbt Labs DevHub Team, as your primary editor and support for this article; David can help you with editing passes, getting the posts live on our site, and promoted on our social. We aim for a ~6 week turnaround time for posts from Issue to Publication, but also work on your timing (especially with the holidays coming up) :slightly_smiling_face: 

Next steps here will be David taking a look at your outline, helping determine where there should be expansion, and then you send a full-form draft in the following weeks. You'll work back and forth to get into its final form.

Let me or David know if you have any questions, but we're excited to work with you and get this up 😄

**Comment by krevitt** [comment]
Hey @brandon-segal I'll be your editor here!  Took a first pass through the draft and left a few comments, in general looks great to me.  

One question: under the [process section](https://docs.google.com/document/d/1IiNslXj63lurdLM1b4SBrS_HF2Klr4T0_cLk-eYVPL4/edit?pli=1#heading=h.iklgcwl49cwp), were you imagining providing a small example / demo dbt project that someone could pick up and use?

**Comment by brandon-segal** [comment]
Hey, @krevitt, that sounds like a great idea and might be able to be easily incorporated with something like a public BigQuery dataset. I would also intend to include code underneath each step to illustrate what is happening.

**Comment by krevitt** [comment]
> Hey, @krevitt, that sounds like a great idea and might be able to be easily incorporated with something like a public BigQuery dataset. I would also intend to include code underneath each step to illustrate what is happening.

Great!  Could also be seeds within the project if it's < a few hundred rows of < 5 tables.

**Comment by brandon-segal** [comment]
Just added some code samples to go with the process. Will add a sample dbt project to work in BigQuery so that users can play around with it as well.

**Comment by krevitt** [comment]
Oook thank you @brandon-segal, just gave this another read through.  Main thing before we do a last editing round before publishing is to align on context in which this work is happening - we may want to write the title / frame the post in a different way depending on that context:

If I'm reading this correctly, you have a large historical snapshotted table (being snapshotted outside by some ETL process, not dbt snapshots?).  The goal here is to go from that raw historical snapshot to `valid_from` + `valid_to` cols that you can then join on.   

Am I reading that correctly?  If so, and given [dbt snapshots](https://docs.getdbt.com/docs/build/snapshots) do this for you out of the box, we could frame this post as "how to hand-roll your own SCD type 2 w/ SQL, in the case you haven't been using dbt snapshots all along" orrr "how to get your historical data ready to leverage dbt snapshots" (a migration story).   Think the SQL work you're doing here is interesting + useful, regardless of whether dbt users can get this for free.  Thoughts?

**Comment by brandon-segal** [comment]
Hey @krevitt  your read on the context is absolutely right. dbt is a relatively new tool in our org and the historically snapshotted tables were the de facto standard in our data warehouse. This would be a situation where we could begin implementing dbt snapshots on the now up-to-date SCD type 2 tables.

**Comment by krevitt** [comment]
Great!  That's helpful framing.  Mind if I go through a Big Red Pen editing pass and suggest some edits with that context in mind?  Biggest thing will be proposing a couple context-setting paragraphs in the middle to anchor readers.

**Comment by krevitt** [comment]
@brandon-segal just checking in, happy new year!  curious if you're ready for me to go through an editing pass and suggest changes?

**Comment by runleonarun** [comment]
Hey @brandon-segal I am going to close this out, but please re-open if you want to pick this up again!
