### ISSUE TITLE
Build A Scrappy Stack With Me

### ISSUE THREAD

**Issue by lbenezra-FA** [fishtown-analytics/docs.getdbt.com#2368]
### Contact Details

@lauren.benezra (slack)

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

I volunteer for a cat rescue organization called Feral Change as their Foster & Behavior Coordinator. As you can imagine, our data is a rat's-nest of Google Sheets, and I've finally started designing the long-desired proper data stack that we can implement. We want to build a framework that other rescues and non profits can benefit from. 

I thought it would be super fun to document this process, thinking, and design, so other tiny start-ups or non profits can build their own modern data stacks on a budget. Obviously, this includes utilizing dbt.

### Link to an initial outline.

https://www.notion.so/dbtlabs/DevHub-Blog-Scrappy-Cat-Stack-4d1b40228f644fcd8857afb796b289d6

**Comment by KiraFuruichi** [comment]
Hey @lbenezra-FA , thanks for opening up this issue! So hyped for this post. Just assigned @krevitt as your primary editor/PM for this piece, so feel free to collab with him and chat through anything at devhub writing sessions :)

**Comment by krevitt** [comment]
❤️ this post idea @lbenezra-FA!  outline LGTM - my main question is [around framing in this comment](https://www.notion.so/DevHub-Blog-Scrappy-Cat-Stack-4d1b40228f644fcd8857afb796b289d6?d=cafee5cd018649e6a27c5db569fcaa8e#47fb555cba7d4b26a3da787607fd2832) (why would a nonprofit org do this, what's their typical use case / need for a warehouse look like)

**Comment by runleonarun** [comment]
@lbenezra-FA closing this issue out to clean up our open issues, but please re-open if you want to get this blog post going again!
