### ISSUE TITLE
A crash course on dbt yml files: Your one-stop guide to configuring models in dbt

### ISSUE THREAD

**Issue by mer-alder** [fishtown-analytics/docs.getdbt.com#2421]
### Contact Details

meredith@hightouch.io

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

Target Audience:  All dbt practitioners 

Summary:
The dbt documentation explains yml files and model configuration on several different pages. This article will consolidate the information with practical examples and hints to avoid problems. I've found that many dbt practitioners struggle with getting yml files right and often exhaust time and frustration on trial and error. Since yml files are crucial to unlocking the full potential of dbt, it's a topic worth understanding. 

### Link to an initial outline.

[Outline](https://docs.google.com/document/d/1NJp_w60B0pFhHhuyCjp2I2lqSq0ccEflej41z5JiZlI/edit?usp=sharing)

**Comment by KiraFuruichi** [comment]
Hey @mer-alder, thank you so much for opening up this issue! We're always excited to have contributions to the Developer Blog from external writers :) 

My name is Kira, and I'm a technical writer here at dbt Labs and one of the folks who helps manage the Developer Blog. After giving your outline a quick read, it looks like it's a great candidate for a blog post here :) 

I’ve assigned myself as your primary editor and support for this article; I can help you with editing passes, getting the posts live on our site, and promoted on our social. We aim for a ~6 week turnaround time for posts from Issue to Publication, but also work on your timing (especially with the holidays coming up) 🙂

Next steps here I will be taking a deeper look at your outline, helping determine where there should be expansion and comment on my thoughts, and then you send a full-form draft in the following weeks. We'll work back and forth here to get into its final form.

Let me know if you have any questions, but we're excited to work with you and get this up and I'll ping you once I've left some deeper thoughts/comments on the outline!

**Comment by KiraFuruichi** [comment]
Hey @mer-alder gave your outline a closer look and it all looks really strong to me!

My biggest question: Is your plan to have a through-line example of an actual yaml file (or build one up throughout the article)? I think having one solid example dbt model and its corresponding yaml file can help solidify some of the points you may hit on while carrying a practical example.

Let me know how you feel about this and you can get started on writing a full-formed draft!

**Comment by mer-alder** [comment]
Hi @KiraFuruichi, I'm excited to work with you to develop this post. I agree with including one solid example. I could describe each step to build it within the article and then in the conclusion provide code blocks with the actual files. I'm open to suggestions though. Thanks for your feedback!

**Comment by KiraFuruichi** [comment]
Hey @mer-alder yeah I was envisioning like a code snippet at each section and then presenting the fully-formed file(s) at the end to wrap everything else would make sense to me (if that works with what you're envisioning).

Let me know if you have any questions now or while you're creating a draft; happy to help think through anything!

**Comment by mer-alder** [comment]
Exactly @KiraFuruichi! I'll start the draft and get back to you soon.

**Comment by KiraFuruichi** [comment]
Hey @mer-alder just wanted to check-in here to see how the writing process is going! Lmk if you need any support or edits :)

**Comment by mer-alder** [comment]
Hi @KiraFuruichi - It is going well and I will have a draft here in the next couple of days. Thanks!

**Comment by KiraFuruichi** [comment]
@mer-alder just checking in, happy new year! curious if you're ready for me to go through an editing pass for your draft?

**Comment by KiraFuruichi** [comment]
Hey @mer-alder, just checking in on how this is coming along :)

**Comment by mer-alder** [comment]
Hi @KiraFuruichi - I changed the approach on the code samples and will have my draft submitted to you this week. Thanks for your patience. :-)

**Comment by KiraFuruichi** [comment]
Hey @mer-alder! Curious if you're ready for me to go through an editing pass for your draft? Just a heads up I'll have limited availability next week, so can take a look either this week or the week of 2/13!

**Comment by KiraFuruichi** [comment]
Hey @mer-alder any updates on this draft?

**Comment by runleonarun** [comment]
Hi @mer-alder I'm going to close this issue out, but please re-open when you are ready to have your draft reviewed!
