### ISSUE TITLE
Ability to bookmark docs pages with a signed profile

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#2438]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

improve the ability to bookmark or save pages in the  docs.getdbt.com site, to your cloud profile. 

Slack thread: https://dbt-labs.slack.com/archives/C02NCQ9483C/p1669049565699959

Not sure if this is possible with docusaurus but did tag Jason K for verification and created issue to capture this.

### What changes are you suggesting?

In GCP docs, you can bookmark pages with a signed in profile: https://cloud.google.com/bigquery/docs/table-snapshots-intro

**Comment by runleonarun** [comment]
@mirnawong1 I'm going to icebox this until we have a universal login for docs.
