### ISSUE TITLE
Add redirect for broken link to "Testing a New Adapter"

### ISSUE THREAD

**Issue by bbrewington** [fishtown-analytics/docs.getdbt.com#2452]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/guides/advanced/adapter-development/7-verifying-a-new-adapter

### What part(s) of the page would you like to see updated?

In github.com/dbt-labs/dbt-integration-tests, [README line 4](https://github.com/dbt-labs/dbt-integration-tests/blob/67108cf325383a92ab528709e549cc2223c8b845/README.md?plain=1#L4) links to an old version of the page above.  Probably need to set this up as a URL redirect (or fix the README)

**Comment by runleonarun** [comment]
That line looks like it redirects now so I'm closing this issue. Please let me know if I need to reopen it!
