### ISSUE TITLE
Autoscaling CI in dbt Cloud

### ISSUE THREAD

**Issue by dpguthrie** [fishtown-analytics/docs.getdbt.com#2457]
### Contact Details

doug.guthrie@dbtlabs.com

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

This post is targeted towards people using dbt Cloud.  If they're using slim CI, they've most likely encountered the issues that this solution attempts to solve.  The python package I created, dbtc, has a function, `trigger_autoscaling_ci_job`, that allows a customer to get around the following limitations of slim CI:

- Forced to wait for job to complete even when a new commit has been added
- Can't have a single CI job run concurrently across multiple pull requests

### Link to an initial outline.

https://docs.google.com/document/d/17TwAtPXUksCTo-jOylFRxc3WEKc57oLOyFXTvfjnDTU/edit

**Comment by KiraFuruichi** [comment]
Hey @dpguthrie thanks for opening up this issue and sorry for the delay on my end (I've been on vacay)!

I've assigned myself as the primary editor for your piece—I'll be responsible for helping with any editing, PR creation, and promotion. We generally aim for a ~6 week turnaround time from Issue --> Publication, but with the holidays going on, we'll work on a schedule that works best for you :) 

Your outline looks good; I think keeping it simple is best! Next steps would be for you to fill it out with some text and once you're done there (or want any assistance), ping me here or on slack and I'll do an editing pass. Lmk if you have any qs and feel free to come to DevHub Writing Session on Thursday if you want any group feedback :)

**Comment by KiraFuruichi** [comment]
hey @dpguthrie how are you looking for a draft in the next few weeks?

**Comment by dpguthrie** [comment]
Hey @KiraFuruichi - I should have a draft by the end of the week (hopefully sooner) and we can catch up then!

**Comment by KiraFuruichi** [comment]
Awesome, thanks for the update Doug, excited to give it a read 🚀
