### ISSUE TITLE
Buggy yml in resource-properties/columns page (seeds section)

### ISSUE THREAD

**Issue by bbrewington** [fishtown-analytics/docs.getdbt.com#2470]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-properties/columns

### What part(s) of the page would you like to see updated?

The hierarchy `columns --> name --> columns --> name` seems like a bug in the docs

https://github.com/dbt-labs/docs.getdbt.com/blob/569b3eae3c543a991f2f7f375833759d9ec7a74d/website/docs/reference/resource-properties/columns.md?plain=1#L80-L83

**Comment by bbrewington** [comment]
in case it's worth calling out, got a notification for this GH Action run failure: https://github.com/dbt-labs/docs.getdbt.com/actions/runs/3587700453

Here's error details:

<img width="883" alt="Screenshot 2022-12-04 at 10 32 26 AM" src="https://user-images.githubusercontent.com/10573749/205499699-910e1639-11e3-4e53-a0fb-b3382f49165e.png">

**Comment by runleonarun** [comment]
Thank you for opening this issue @bbrewington I've addressed the issue in [this PR](https://github.com/dbt-labs/docs.getdbt.com/pull/3498). 

Also our GH Actions should be working (for now) 😄
