### ISSUE TITLE
Find location for Cloud content 

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#2505]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

[link to IA fast-follow project](https://www.notion.so/dbtlabs/Fast-follows-Docs-IA-refresh-cfe834d2530d43f2adfef242188b911d)

These pages could be re-homed out of the quickstart guide:
* https://docs.getdbt.com/docs/get-started/dbt-cloud-features
* https://docs.getdbt.com/docs/get-started/connect-your-database
* https://docs.getdbt.com/docs/get-started/develop-in-the-cloud
* https://docs.getdbt.com/docs/get-started/dbt-cloud-tips
* https://docs.getdbt.com/docs/get-started/run-your-dbt-projects

### What part(s) of the page would you like to see updated?

Create a new place where this content and possibly content for setting up your Cloud account can all live. Soon we will need to home content like "Setting up your account" or "Adding or removing users" (Enterprise) "Moving to a team plan" etc. 

### Additional information

<img width="282" alt="Screenshot 2022-12-06 at 10 18 07 AM" src="https://user-images.githubusercontent.com/3880403/205991419-fe4e9763-f965-4d95-88f8-1b07de3270d4.png">

**Comment by runleonarun** [comment]
@matthewshaver and @nghi-ly This issue seems to affect things you're both working on. I wonder if this content can stay put once Ly fixes the Get started guides to be warehouse specific. I think the content will no longer get lost among so many folders.

**Comment by nghi-ly** [comment]
@runleonarun : per our discussion, here's my [latest IA proposal](https://docs.google.com/spreadsheets/d/1bso9xri9d-24_3B9jweLGy6lvcRKGY3WTdJXgAt07eE/edit?usp=sharing) which handles all the highlighted pages. 

@matthewshaver : lemme know if you have any questions about the IA proposal! would love to collab with you on your project if you like!

**Comment by runleonarun** [comment]
@nghi-ly Is this captured in your get started guide project?

**Comment by matthewshaver** [comment]
Closing down as we've since addressed these in subsequent pull requests
