### ISSUE TITLE
Improve layout and landing pages for guides

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#2506]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/guides/best-practices and other overview or landing pages under /guides.

### What part(s) of the page would you like to see updated?

-  [ ] There are now three sections with 1 or 2 guides in them (Ecosystem, Advanced and Orchestration). Do we think that this is desirable? Should we try and consolidate?

- [ ] ...wonder if we should swap the summary pages out to be the beautiful new cards we put together for the DevHub launch [in the guides directory].
image
![image](https://user-images.githubusercontent.com/3880403/205999917-ad13bff8-4538-410e-b0a2-822c22313ff3.png)

To do this, we'd look at how we [add these cards](https://raw.githubusercontent.com/dbt-labs/docs.getdbt.com/mwong-dbt-ecosystem/website/docs/docs/get-started/getting-started/overview.md) to  the [Getting Started landing/overview page](https://docs.getdbt.com/docs/get-started/getting-started/overview).

### Additional information

* Came up in this [PR comment](https://github.com/dbt-labs/docs.getdbt.com/pull/2489#issuecomment-1339649787)

**Comment by nghi-ly** [comment]
@runleonarun : thank you so much for capturing this! this looks like a great candidate for phase 2 of the Guides project.

**Comment by mirnawong1** [comment]
hey @runleonarun and @nghi-ly , looks like we can close this out based on the recent changes right? will close this issue but let me know if you think otherwise.
