### ISSUE TITLE
feat: add doc for full_refresh option to on_schema_change

### ISSUE THREAD

**Issue by pol-defont-reaulx** [fishtown-analytics/docs.getdbt.com#2546]
### Contributions

- [ ] I am a PM or subject matter expert at dbt who is responsible for this feature.

### Where does this content belong?

I created the PR #6412 on dbt-core to add the full_refresh option to on_schema_change config of incremental models. This will allow the user to define that, when a schema change occurs on an incremental model, dbt needs to do a full refresh of this model. If there is no change in the model, then the full_refresh will not be activated.

This option need to be added to the section "[What if the columns of my incremental model change?](https://docs.getdbt.com/docs/build/incremental-models#what-if-the-columns-of-my-incremental-model-change)" of the incremental model page.

### Link to source material

No source material

**Comment by mirnawong1** [comment]
hey @pol-defont-reaulx thanks for opening this docs issue! I'm going to add an icebox label as it seems the original core pr https://github.com/dbt-labs/dbt-core/pull/6412 was closed due to the decoupling. we can reopen this again once it goes through. really appreciate you opening this up!
