### ISSUE TITLE
Find location for building and config artifacts cloud page

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#2573]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/dbt-cloud/using-dbt-cloud/artifacts

### What part(s) of the page would you like to see updated?

At the bottom of page `/docs/deploy/source-freshness` - content links out to https://docs.getdbt.com/docs/dbt-cloud/using-dbt-cloud/artifacts, which doesn't have a permanent location and is part of the IA clean-up work.

Proposal for "Artifacts" page:
- move 'Building and configuring artifacts' to `docs/deploy/artifacts`  or 
- move to the new proposed location of the [Artifacts](https://docs.getdbt.com/reference/artifacts/dbt-artifacts) content, which is: `docs/collaborate/artifacts ` or
- add to [this page](https://docs.getdbt.com/docs/collaborate/build-and-view-your-docs#configure-project-documentation) which covers artifacts already

Tasks (moved from #2074):
- [ ] Cull info from these locations and move to new location in new IA 
   - [x] https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-using-a-managed-repository
   - [ ] https://docs.getdbt.com/docs/dbt-cloud/using-dbt-cloud/artifacts
   - [ ] https://docs.getdbt.com/docs/dbt-cloud/using-dbt-cloud/cloud-model-timing-tab 
- [ ] Delete these old ^ pages and the entire cloud-dbt directory after pulling relevant content
- [ ] Create redirects for deleted and moved content.
- [ ] Search for old links and update them.

related to #2505 and #2074

**Comment by runleonarun** [comment]
This appears to have been completed. Feel free to re-open if I'm missing something!
