### ISSUE TITLE
A large enterprise moving from Core to Cloud to enable more dbt developers

### ISSUE THREAD

**Issue by boxysean** [fishtown-analytics/docs.getdbt.com#2592]
### Contact Details

@boxysean

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

This post is a success story targeted towards dbt Core users at large enterprises who are looking to expand their dbt usage by adopting dbt Cloud. It will include key technical challenges and solutions used to solve them that others can follow.

### Link to an initial outline.

https://www.notion.so/dbtlabs/848888d520f541a78c11e9e147a31581

**Comment by jasnonaz** [comment]
Hey @boxysean - this is an awesome topic for a post. We have been wanting to do a [guide on moving for Core to Cloud](https://github.com/dbt-labs/docs.getdbt.com/issues/1892) for a while and I still think we should do that, but starting with a single example and going deep makes a ton of sense. Let's plan on you, me and @dave-connors-3 spending some time digging into this in early Jan.
