### ISSUE TITLE
How to set up your project with dbt and Databricks

### ISSUE THREAD

**Issue by asteichen** [fishtown-analytics/docs.getdbt.com#2598]
### Contact Details

Aaron Steichen

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

This is the first of 3 blogs we're doing in collaboration with Databricks SAs (Amy and Anders are leading this initiative).

Intended for Databricks users who are either just getting started with dbt or are migrating from the Spark adapter to dbt-databricks and want to know how to incorporate Unity Catalog with their dbt project.

### Link to an initial outline.

[Link to Google Doc Draft](https://docs.google.com/document/d/1ubKG_KEbAyCSW_kBQKHy6vfecyPWMOYZ4gBkjyg_InY/edit#)

Outline on page 1/2. Actual content starts at the end of page 2.

**Comment by jasnonaz** [comment]
Hi @asteichen - this looks like a really awesome contribution to the Developer Hub - we've been looking to get more helpful content for how folks can use dbt + databricks together.

This is a great candidate for a [guide](https://docs.getdbt.com/guides/dbt-ecosystem) in the Ecosystem section. While we try and make both both guides and blogs evergreen - guides have a longer and more permanent discoverability period so this should hopefully mean over time more folks get the benefit here.

I'm tagging in @joellabes to help out with review - he's on break and will be able to help out in the new year.

**Comment by amychen1776** [comment]
Closing this since the PR was merged in!
