### ISSUE TITLE
metrics talk about running dbt_metrics_calendar_model which is the var not the model to run

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#2603]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

[https://docs.getdbt.com/docs/build/metrics#querying-your-metric](https://docs.getdbt.com/docs/build/metrics#querying-your-metric:~:text=make%20sure%20to%20run%20the%20dbt_metrics_calendar_model%20model%20as%20this%20is%20required%20for%20macros%20used%20to%20query%20metrics)

### What part(s) of the page would you like to see updated?

it says to run dbt_metrics_calendar_model, but the default model is `dbt_metrics_default_calendar`. it should say something like "run the dbt_metrics_default_calendar model or your custom model defined in the dbt_metrics_calendar_model variable"

### Additional information

this thread with Lydia: https://getdbt.slack.com/archives/C02CCBBBR1D/p1671519974053899?thread_ts=1646319497.324559&cid=C02CCBBBR1D

**Comment by mirnawong1** [comment]
hey @joellabes , closing this issue since dbt metrics is getting deprecated. let me know if you'd still like to keep this open and I'll be happy to take a look!
