### ISSUE TITLE
Improve dbt Core and dbt Cloud set-up documentation 

### ISSUE THREAD

**Issue by kbrock91** [fishtown-analytics/docs.getdbt.com#2608]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/docs/collaborate/environments

### What changes are you suggesting?

Would be great if this also included how to manage environments in Cloud (via the Environments UI + Dev Credentials) vs. just in Core (with targets in profiles.yml). Would also be great to call out the development vs deployment environment types that exist in dbt Cloud

**Comment by runleonarun** [comment]
I think this issue has been addressed! Please reopen if I'm wrong. https://docs.getdbt.com/docs/collaborate/environments/dbt-cloud-environments
