### ISSUE TITLE
Refactor the Get started guides for dbt Cloud

### ISSUE THREAD

**Issue by nghi-ly** [fishtown-analytics/docs.getdbt.com#2612]
### Contributions

- [x] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/get-started/getting-started/set-up-dbt-cloud 

#### Content updates

As part of the Docs team's Guides project: 

Merge the Set up and connect, Build your first models, Test and document your project, and Schedule a job pages so it's one end-to-end guide, similar to the [Getting started with dbt Core](https://docs.getdbt.com/docs/get-started/getting-started-dbt-core) guide. 

New titles for these get-started guides will be:  

- Get started with Big Query
- Get started with Databricks
- Get started with Redshift
- Get started with Snowflake

Also, need to update the cards on the landing page appropriately https://docs.getdbt.com/docs/get-started/getting-started/overview 

#### Left sidebar updates

- dbt Cloud guides to live under the Get started with dbt > dbt Cloud section
- dbt Core guide to live under the Get started with dbt > dbt Core section
- Update links and redirects

**Comment by runleonarun** [comment]
This work has been completed!
