### ISSUE TITLE
Create "Get started with Git" guide 

### ISSUE THREAD

**Issue by nghi-ly** [fishtown-analytics/docs.getdbt.com#2613]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/get-started/getting-started/overview

#### Content updates
As part of the Docs team's Guides project:

- Create a brand new "Get started with Git" guide, covering Git basics.
- Add card for new guide to landing page: https://docs.getdbt.com/docs/get-started/getting-started/overview

#### Left sidebar updates

- Add guide to the "Get started with dbt" section

**Comment by mirnawong1** [comment]
closing this as we have a git/version control doc here; https://docs.getdbt.com/docs/collaborate/git/version-control-basics
