### ISSUE TITLE
Move the SL quickstart to the top of the sidebar

### ISSUE THREAD

**Issue by nghi-ly** [fishtown-analytics/docs.getdbt.com#2615]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/use-dbt-semantic-layer/quickstart-semantic-layer 

#### Content updates 

As part of the Docs team's Guides project:

- Rename "dbt Semantic Layer quickstart" to "Get started with Semantic Layer" 

#### Left sidebar updates 

- Move guide to the "Get started with dbt" section 
- Update links and redirects

**Comment by runleonarun** [comment]
This looks complete! Feel free to re-open if I am wrong.
