### ISSUE TITLE
Move guides out of "Learning more" section 

### ISSUE THREAD

**Issue by nghi-ly** [fishtown-analytics/docs.getdbt.com#2616]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/get-started/learning-more/using-jinja

https://docs.getdbt.com/docs/get-started/learning-more/refactoring-legacy-sql 

#### Content updates

As part of the Docs team's Guides project:

- Check to see if links to getting started guides need to be added 

#### Left sidebar updates

- Move the [Refactoring legacy SQL to dbt](https://docs.getdbt.com/docs/get-started/learning-more/refactoring-legacy-sql) guide to the /website/docs/guides/migration/tools folder
- Move the [Using Jinja](https://docs.getdbt.com/docs/get-started/learning-more/using-jinja) guide to the /website/docs/guides/migration/advanced folder
- Remove the "Learning more" section 
- Update links and redirects

**Comment by matthewshaver** [comment]
Moved as part of https://github.com/dbt-labs/docs.getdbt.com/pull/3016
