### ISSUE TITLE
Reorganize "Get started with dbt" in the left sidebar 

### ISSUE THREAD

**Issue by nghi-ly** [fishtown-analytics/docs.getdbt.com#2618]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Landing page for section: https://docs.getdbt.com/docs/get-started/getting-started/overview 

### What part(s) of the page would you like to see updated?
As part of the Docs team's Guides project:

Reorganize the "Get started with dbt" section in the Docs left sidebar so it becomes the home for get-started guides. This can include:

- Moving pages to other locations
- Deleting unnecessary files
- Renaming sections in the left sidebar
- Adding new sections to the left sidebar
- Adding new pages
- Update links and redirects

Refer to the Guides project plan for the latest IA (info architecture) proposal.

**Comment by matthewshaver** [comment]
Closing as complete since these were addressed during IA changes earlier this year
