### ISSUE TITLE
Include the meta field in the node_info property description

### ISSUE THREAD

**Issue by tmastny** [fishtown-analytics/docs.getdbt.com#2632]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/reference/events-logging

### What changes are you suggesting?

https://github.com/dbt-labs/dbt-core/pull/6493 adds the meta field to the `node_info` property of structured logs. 

This issue suggests that the meta should be added to the list of fields in `node_info`.

**Comment by jtcohen6** [comment]
Thanks for opening @tmastny, and nice work getting the contribution merged in time for inclusion in v1.4!

I'll include this update as part of the broader changes to events/logging (https://github.com/dbt-labs/docs.getdbt.com/issues/2639)
