### ISSUE TITLE
The missing guide to Jinja's `debug()` in dbt

### ISSUE THREAD

**Issue by b-per** [fishtown-analytics/docs.getdbt.com#2641]
### Contact Details

benoit.perigaud@dbtlabs.com

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

This post would be targeted at advanced dbt users or people developing adapters. It would expect an existing knowledge of Jinja and dbt macros (how to write them, how to run them). 

This post would be technical and focused on:
1. the different reasons why someone would want/need to use [the debug() command](https://docs.getdbt.com/reference/dbt-jinja-functions/debug-method) 
2. how to use the command and navigate the debugger interface

### Link to an initial outline.

None for now, but I am happy to work on an outline if this is a blog post that would interest people.

**Comment by KiraFuruichi** [comment]
Hey @b-per love this idea for a DevBlog post! Really into the idea of having specific audiences in mind when creating new content. 

Lmk once you have an outline together and I'll give it a look :)

**Comment by KiraFuruichi** [comment]
Hey @b-per any updates on an outline/draft for this?

**Comment by b-per** [comment]
Hi @KiraFuruichi , [here is a first draft](https://www.notion.so/dbtlabs/The-missing-guide-to-debug-in-dbt-c93e29f393554343abdb8a7f825df439?pvs=4) (internal, Notion) of what I was thinking of covering. Let me know what you think!

**Comment by KiraFuruichi** [comment]
Hey @b-per, thanks for sharing! Just did an initial first pass--overall I think your outline and what you're talking about is very relevant, but I think that the blog post is missing some overall context, which I commented in parts in the draft on where I think you can elaborate! Ping me here, Slack, or Notion if you have any qs on my comments!

**Comment by b-per** [comment]
Thanks a lot Kira! I will check your comments and update the doc accordingly

**Comment by KiraFuruichi** [comment]
Hey @b-per, how are you feeling about your draft!
