### ISSUE TITLE
Write post on using python dbt model to calculate business hours

### ISSUE THREAD

**Issue by nzewail** [fishtown-analytics/docs.getdbt.com#2655]
### Contact Details

nzewail@hey.com

### I have read the dbt Developer Blog contribution guidelines.

- [x] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

We recently needed to calculate number of business hours for some of our zendesk events and recently started making use of the dbt python models. This process was much better designed than writing in SQL with a very ugly cross-join. We were able to ship something useful with a lot less code and something that was far more testable using python to calculate the number of business hours that transpired between the events. 

### Link to an initial outline.

https://docs.google.com/document/d/1sUHW6SmTXmFJXdaaw8KUjzo5ZwdN6fXaxxJDjVVI7CM/edit?usp=sharing

**Comment by KiraFuruichi** [comment]
Hey @nzewail thank you for opening up this issue and sharing your idea with us! My name is Kira, and I'm a technical writer here at dbt Labs and one of the folks who helps manage the Developer Blog. After giving your outline a quick read, it looks like it's a great candidate for a blog post here :)

I’ve assigned @dave-connors-3 as your primary editor and support for this article; Dave actually wrote the original [Developer Blog post on calculating time on task in SQL](https://docs.getdbt.com/blog/measuring-business-hours-sql-time-on-task), so he'll be a great resource for you here. Dave can help you with editing passes, getting the posts live on our site, and promoted on our social. We aim for a ~6 week turnaround time for posts from Issue to Publication, but also work on your timing 🙂

Next steps here will be you taking your outline and transforming it into a real draft. You and Dave will work back and forth here to get into its final form.

Let me know if you have any questions, but we're excited to work with you and get this up 😄

**Comment by nzewail** [comment]
Sounds good! I will get started on it!

**Comment by dave-connors-3** [comment]
Hey @nzewail ! Just wanted to check in here -- have you made any progress on a draft? Anything I can do to be helpful to you here?

**Comment by nzewail** [comment]
I haven't made a lot of progress! Will get started soon

**Comment by dave-connors-3** [comment]
@nzewail no trouble at all! Just wanted to make sure to reach out and see if you needed anything! there's not any rush at all!

**Comment by dave-connors-3** [comment]
@nzewail -- just wanted to check in here and see if this was still on your roadmap!

**Comment by runleonarun** [comment]
Hey @nzewail I am going to close this issue, but please re-open once you've made some progress and we will be happy to take a look!

cc  @dave-connors-3
