### ISSUE TITLE
Add wildcard selector method to dbt docs

### ISSUE THREAD

**Issue by z3z1ma** [fishtown-analytics/docs.getdbt.com#2702]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/node-selection/methods

### What part(s) of the page would you like to see updated?

# The "wildcard" method

The wildcard method can be used to select a model using unix-style wildcard expressions evaluated against the fqn.
See fnmatch [reference](https://docs.python.org/3/library/fnmatch.html#module-fnmatch) for syntax.

```bash
# These are equivalent
dbt run --select 'wildcard:*_model_?'
dbt run --select some_model_a some_model_b some_model_1

# So are these
dbt run --select 'wildcard:*_feature_model_[1-3]'
dbt run --select test_feature_model_1 new_feature_model_2 ml_feature_model_3
```

### Additional information

I have a PR I am opening in dbt-core now. I will post its link for reference. 
This PR is not relevant until the attached PR is merged.

https://www.notion.so/dbtlabs/dbt-Core-v1-5-docs-a2ae11be77bf47629f85faf7a3f27991

**Comment by z3z1ma** [comment]
This becomes relevant after this is merged, tagging it for tracking purposes:

https://github.com/dbt-labs/dbt-core/pull/6599

**Comment by runleonarun** [comment]
Thanks so much for opening this issue, @z3z1ma! I labeled this for 1.5 but let us know if it's available sooner.

**Comment by z3z1ma** [comment]
@runleonarun the PR connected to this documentation change was merged 🎉 

Some small changes. The `wildcard:` is no longer needed as a prefix as the functionality is baked into the default selector. Furthermore all string based (ie. non status based) selectors have the functionality enabled. The list can be seen below. 

    FQN
    Tag
    Source
    Exposure
    Metric
    File
    Package
    TestName

Here is a markdown table to include describing the syntax. My recommendation is a note in all the above selectors that points to a specific section in the documentation containing this table. 

| Wildcard | Description                                               |
| -------- | --------------------------------------------------------- |
| \*       | matches any number of any characters (including none)     |
| ?        | matches any single character                              |
| [abc]    | matches one character given in the bracket                |
| [a-z]    | matches one character from the range given in the bracket |

cc @jtcohen6 @dbeatty10 for visibility/input (if nothing else) since they both grokked the issue through its lifecycle.

**Comment by runleonarun** [comment]
Thanks so much for lettign us know, we have this in the queue to be documented! cc @matthewshaver
