### ISSUE TITLE
Document setting up deferral in dbt Cloud outside of a Slim CI context

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#2703]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/deploy/about-state (or somewhere nearby - it might need to be a net-new document?)

### What part(s) of the page would you like to see updated?

After reading [this message on the community forum](https://discourse.getdbt.com/t/dbt-cloud-run-in-deployment-only-one-model-of-job/6066), I wanted to guide the original poster to set up an adhoc job which deferred to the daily production run. In this example, it would be `dbt build -s state:modified+` but it would run in the production context. 

However all of our deferral content in a dbt Cloud context talks about Slim CI. 

We should have guidance explaining how to set up a *production* job to defer to the main job, not just CI.

**Comment by mirnawong1** [comment]
hey @joellabes , do you think we still need this given the changes to orch? for example, we have this callout [here](https://docs-getdbt-com-git-mirnawong1-patch-27-dbt-labs.vercel.app/reference/project-configs/query-comment#default) about defer and[here](https://docs.getdbt.com/docs/deploy/jobs) too.

**Comment by joellabes** [comment]
should be ok!
