### ISSUE TITLE
Incremental predicates expects a list but docs suggest a string

### ISSUE THREAD

**Issue by rlh1994** [fishtown-analytics/docs.getdbt.com#2719]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/docs/build/incremental-models#about-incremental_predicates

### What changes are you suggesting?

Change the example of the incremental predicates to be a list, otherwise you get a `can only concatenate list (not "str") to list` error.

### Additional information

Tested on dbt=1.4.0-rc1

**Comment by mirnawong1** [comment]
hey @rlh1994 thanks so much for opening this up and @dave-connors-3 opened up pr #2720 to sort this out 🙌
