### ISSUE TITLE
Update Cloud docs to reflect new button name

### ISSUE THREAD

**Issue by matthewshaver** [fishtown-analytics/docs.getdbt.com#2745]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Internal request: update "Commit and push" button name to "Commit and sync"

### What part(s) of the page would you like to see updated?

Need to update docs to reflect renamed button per https://dbtlabs.atlassian.net/browse/XP-1717

Update "Commit and push" button name to "Commit and sync"

**Comment by mirnawong1** [comment]
i'm not sure if we have specific details on the docs re: git button names but i think this may be a good doc to update maybe: https://docs.getdbt.com/docs/collaborate/git/version-control-basics

**Comment by mirnawong1** [comment]
hey @matthewshaver also this screenshot will need updating too: https://docs.getdbt.com/docs/get-started/develop-in-the-cloud

**Comment by runleonarun** [comment]
I found two other places that could use updating: 
* https://docs.getdbt.com/guides/orchestration/custom-cicd-pipelines/2-lint-on-push#2-commit-and-push-your-changes-to-make-sure-everything-works

* https://docs.getdbt.com/docs/collaborate/git/merge-conflicts#identify-merge-conflicts

**Comment by matthewshaver** [comment]
Closed with[ PR 2763](https://github.com/dbt-labs/docs.getdbt.com/pull/2763)
