### ISSUE TITLE
version optional in dbt_project.yml

### ISSUE THREAD

**Issue by seub** [fishtown-analytics/docs.getdbt.com#2747]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/project-configs/version#dbt_projectyml-versions

### What part(s) of the page would you like to see updated?

> Although this is a required parameter, it is not currently meaningfully used by dbt"

[This PR](https://github.com/dbt-labs/dbt-core/pull/6718) in dbt-core makes `version` optional. Therefore, when the PR is merged, the doc should be updated to replace this sentence by something like:

> This is an optional parameter, not currently meaningfully used by dbt.

https://www.notion.so/dbtlabs/dbt-Core-v1-5-docs-a2ae11be77bf47629f85faf7a3f27991

**Comment by matthewshaver** [comment]
Closing issue as text in doc has been updated.
