### ISSUE TITLE
Automating the art of code review

### ISSUE THREAD

**Issue by kylemcnair** [fishtown-analytics/docs.getdbt.com#2767]
### Contact Details

@Kyle McNair 

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

**Topic**:
Code review is (yet another) software engineering practice that has been recently thrown at analytics engineers, with little guidance on how to navigate. Code review is critical to maintaining quality code, knowledge sharing, and documenting technical decisions. Despite the clear value, maintaining a robust code review culture is difficult, and often neglected. PRs sit open, superficial review is given, or even worse, reviewers give a mountain of nitpicky feedback. This post goes beyond a checklist, and gives specifics on how to _automate_ parts of code review, making life easier for the author, the reviewer, and benefitting the business.

**Audience**:
Anyone interested in improving code review culture. This applies to new analytics engineers, and growing teams trying to scale effectively.

### Link to an initial outline.

[Google doc outline](https://docs.google.com/document/d/1QnvVw76uLuAYv_kOnwgTw96o1Aq-Nw6GaO-H6l4Mv_8/edit)

**Comment by KiraFuruichi** [comment]
Hey @kylemcnair thank you for opening up this issue! My name is Kira and I'm one of the folks who helps shepherd the Developer Blog here at dbt Labs. I'll be assigned to your piece to help edit, triage, publish, and promote this piece as you work on it.

After reading your proposal and outline, this sounds like a really compelling piece! I think the biggest points to keep an eye out as you draft this is a) keeping the post from being sales-y (which you already mention in the outline) and b) ensuring there are differences between this post and the one you wrote for Datafold (definitely ok if there's overlap, but also want to ensure net-new learnings which from your outline, sounds like there are 😄).

Next steps is for you to work on a full-form draft and ping me once you have a draft you want to be reviewed for an editing pass. We aim to have posts from outline to published in ~6 weeks, but also work on a timeline that's best for you. Don't hesitate to reach out here or in the community slack if you have any questions or need any support.

Looking forward to reading this!

**Comment by KiraFuruichi** [comment]
Hey @kylemcnair, any updates on this!

**Comment by kylemcnair** [comment]
> Hey @kylemcnair, any updates on this!

Hey @KiraFuruichi, I'm hoping to have a draft done this week. I haven't been able to spend much time on this since I opened the issue but trying to carve out time this week.

**Comment by KiraFuruichi** [comment]
Hey @kylemcnair ! Any updates on the draft for this?

**Comment by kylemcnair** [comment]
> Hey @kylemcnair ! Any updates on the draft for this?

Can't believe how long this has been open...

This is the week I get a draft done!

**Comment by runleonarun** [comment]
Hey @kylemcnair I am going to close this issue out, but please re-open it once you've got a draft and we will be happy to take a look.
