### ISSUE TITLE
Securing dbt Cloud's access to BigQuery

### ISSUE THREAD

**Issue by ernestoongaro** [fishtown-analytics/docs.getdbt.com#2772]
### Contact Details

ernesto.ongaro@dbtlabs.com

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

Keeping your dbt Cloud environment secure when using BigQuery is crucial for the protection of sensitive data. Two of the ways to ensure security is through the proper management of service account files and the use of personal authentication.

### Link to an initial outline.

[Securing dbt Cloud's access to BigQuery](https://docs.google.com/document/d/1uGhDgEl30ytMKJkdN7RauFVVLu85ffcibzovRdw5iUA/edit#)

**Comment by jasnonaz** [comment]
Closing the loop here - this is a great fit for [show and tell](https://discourse.getdbt.com/c/show-and-tell/22) on discourse
