### ISSUE TITLE
Docs reference kebab_case while using snake_case

### ISSUE THREAD

**Issue by daguito81** [fishtown-analytics/docs.getdbt.com#279]

**Comment by daguito81** [comment]
The name reference https://docs.getdbt.com/reference/project-configs/name/  says only underscores can be used. Which would be snake_case. But instead it states to use kebab_case which would be using hyphens to separate words instead. 

https://en.wikipedia.org/wiki/Snake_case
https://en.wikipedia.org/wiki/Naming_convention_(programming)

**Comment by clrcrl** [comment]
Nice timing! I made a PR to fix this yesterday! #277

**Comment by daguito81** [comment]
Perfect. I guess we can close the issue or wait until the PR is merged. Whatever works for you.

**Comment by clrcrl** [comment]
Merged it just then 😄
