### ISSUE TITLE
Review headers in dbt Cloud CI job page

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#2794]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Erin [raised a question](https://dbt-labs.slack.com/archives/C02NCQ9483C/p1675261589931689) in the docs channel and flagged a potential mismatch of headers and content in the [dbt Cloud CI job](https://docs.getdbt.com/docs/deploy/cloud-ci-job#configuring-a-dbt-cloud-ci-job) page. 

Specifically, the `Understanding dbt Cloud Slim CI` seems to just talk about CI while the `Configuring a dbt Cloud CI job ` goes into more detail about slim CI

### What part(s) of the page would you like to see updated?

https://docs.getdbt.com/docs/deploy/cloud-ci-job#configuring-a-dbt-cloud-ci-job

**Comment by runleonarun** [comment]
I believe this was addressed in our latest rewrite of the dbt Cloud CI content! Closing it out, but please reopen if we need to.
