### ISSUE TITLE
Revise metadata API contact email

### ISSUE THREAD

**Issue by cafzal** [fishtown-analytics/docs.getdbt.com#2846]
Contributions
 I have read the contribution docs, and understand what's expected of me.
Link to the page on docs.getdbt.com requiring updates
https://docs.getdbt.com/docs/dbt-cloud-apis/metadata-api

What part(s) of the page would you like to see updated?
Change [metadata@dbtlabs.com](mailto:metadata@dbtlabs.com) to [cloudAPIs@dbtlabs.com](mailto:cloudAPIs@dbtlabs.com)

Additional information
No response

https://www.notion.so/Revise-metadata-API-contact-email-5b5d26336a424357a98fb8c9a886d29a

**Comment by mirnawong1** [comment]
thanks @cafzal - will look into this for you!
