### ISSUE TITLE
How to reach dbt support: unify instructions 

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#2851]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

When triaging bug reports in dbt-core and adapters like dbt-bigquery, etc, I sometimes need to redirect the bug report to the team that supports Cloud. Here's the relevant content:

> If you are a dbt Cloud user and need help with one of the following issues, please reach out to us by using the speech bubble (💬) in the dbt Cloud interface or at [support@getdbt.com](mailto:support@getdbt.com)

<img width="450" alt="image" src="https://user-images.githubusercontent.com/44704949/218176483-98b472da-3ac1-44b7-a6b9-f453184c0b51.png">

We have two primary pages that come up at the top of Google search results for "dbt cloud support":
1. https://docs.getdbt.com/docs/dbt-support
1. https://docs.getdbt.com/guides/legacy/getting-help#dbt-cloud-support

### What part(s) of the page would you like to see updated?

The awkward thing is that nearly every time, I'm wanting to refer to the 2nd one, which contains "legacy" in the URL path. This wording gives the connotation that the content is outdated or superseded.

I perceive multiple issues:
1. [This](https://docs.getdbt.com/docs/dbt-support) page doesn't _directly_ answer my question, but [this](https://docs.getdbt.com/guides/legacy/getting-help#dbt-cloud-support) one does
2. The [non-legacy](https://docs.getdbt.com/docs/dbt-support) page actually links to the [legacy](https://docs.getdbt.com/guides/legacy/getting-help#dbt-cloud-support) one `:spiderman_pointing:`
3. Whenever I share a link that contains the word "legacy" in the path, it gives me an uneasy feeling

Potential solution:
- Could we create a single common snippet and then include it on both pages?

Open to other ideas too!

**Comment by runleonarun** [comment]
> Could we create a single common snippet and then include it on both pages

I like this solution a lot!

**Comment by mirnawong1** [comment]
hey @dbeatty10 , we've made [changes](https://docs.getdbt.com/docs/dbt-support) to the dbt support page - does it solve this issue? i do think we can link to the dbt support page from the https://docs.getdbt.com/community/resources/getting-help#dbt-cloud-support page maybe?

**Comment by mirnawong1** [comment]
Closing issue as the page no longer includes or lives under legacy and points to the main support page.
