### ISSUE TITLE
Better organize list of adapters in sidebar (profile setup)

### ISSUE THREAD

**Issue by owenprough-sift** [fishtown-analytics/docs.getdbt.com#2853]
https://github.com/dbt-labs/docs.getdbt.com/blob/94f1e771c82771ae4da663fd02c7d5ea77014353/website/sidebars.js#L611

Currently the adapter-specific profile setups are listed in no discernible order.

Ideas of better ways to organize them:
- Alphabetical (keeping `profiles.yml` first)
- `profiles.yml` first followed by dbt Labs-maintained adapters (alphabetical) followed by other adapters (alphabetical)

**Comment by owenprough-sift** [comment]
# Exhibit A: the present lawless wasteland
![image](https://user-images.githubusercontent.com/74567580/218470481-5fd30431-7f42-46b9-a339-d6790815f90d.png)

**Comment by owenprough-sift** [comment]
@dataders it's not clear to me how #3341 addresses this issue. The adapters are still have no discernible order in the "deploy preview" linked from the PR, and there remains no particular order to them in `sidebars.js`.

**Comment by owenprough-sift** [comment]
@mirnawong1 I don't think this issue was actually addressed.

As of today, the adapters are still listed in an order which is all willy-nilly:
![image](https://github.com/dbt-labs/docs.getdbt.com/assets/74567580/9fa2c361-319d-41c8-94d8-9286a44d0513)

**Comment by mirnawong1** [comment]
hey @owenprough-sift , oh thanks for flagging this and i was under the impression this issue related to the adapters set up and not configs. I'll take a look to see if we can bring some structure here, thank you!

**Comment by mirnawong1** [comment]
going to review this this week
