### ISSUE TITLE
Broken link to versioning components within PR template

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#2861]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

The PR template includes this link:
- https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/versioningdocs.md

I'm guessing it should link here instead:
- https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#about-versioning

The section that has been relevant to me most often:
- https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content

### What changes are you suggesting?

Update the link to the desired URL

**Comment by nghi-ly** [comment]
log: looks like the first 2 bullets have been addressed. looking into the 3rd one
