### ISSUE TITLE
Snowflake incremental models: `tmp_relation_type`

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#2887]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/build/incremental-models
https://docs.getdbt.com/reference/resource-configs/snowflake-configs

### What part(s) of the page would you like to see updated?

New in v1.4, users can configure `tmp_relation_type` for incremental models on Snowflake

See inline code comment [here](https://github.com/dbt-labs/dbt-snowflake/blob/443e35687d29906f663272b1db8d91327e3e2a88/dbt/include/snowflake/macros/materializations/incremental.sql#L1-L57)

### Additional information

https://github.com/dbt-labs/dbt-snowflake/pull/403

Did we backport this to v1.3?

**Comment by matthewshaver** [comment]
Closed with https://github.com/dbt-labs/docs.getdbt.com/pull/3371
