### ISSUE TITLE
Improve dbt commands page and layout

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#2926]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

The dbt commands page needs restructuring to better clarify cloud vs cli commands, and perhaps automate automatically adding any new future commands that are for the CLI or Cloud (e.g. with a tag or whatever)

Currently, cloud commands are inferred because cli commands are the only ones called out with parenthesis. 

![Screenshot 2023-02-24 at 10 26 12](https://user-images.githubusercontent.com/89008547/221155624-db1c79d5-af02-4e15-88bc-45c11f5118d1.png)

### What part(s) of the page would you like to see updated?

https://docs.getdbt.com/reference/dbt-commands

**Comment by jtcohen6** [comment]
Potentially relevant — auto-generated docs for CLI commands:
- https://github.com/dbt-labs/docs.getdbt.com/issues/2674
- https://github.com/dbt-labs/docs.getdbt.com/issues/2693

(That doesn't solve for denoting command parity across Core <> Cloud)

**Comment by mirnawong1** [comment]
closing as pr #3151 fixes layout, however, automatically adding any new future commands that are for the CLI or Cloud is still something that's still outstanding. leaving jerco's issue for that.
