### ISSUE TITLE
Update multi-project docs for v1.5.0-b3 (March 2)

### ISSUE THREAD

**Issue by MichelleArk** [fishtown-analytics/docs.getdbt.com#2938]
### Contributions

- [x] I have read the contribution docs, and understand what's expected of me.

### Model Contracts
@jtcohen6

Existing Docs: 
- https://docs.getdbt.com/reference/resource-configs/contract

Changes: 
- constraints_enabled renamed to contract

### Groups & Access
@MichelleArk

- https://docs.getdbt.com/docs/collaborate/publish/model-access
  - rewrite & expand
- https://docs.getdbt.com/docs/build/exposures#available-properties
  - one of email or name is required on exposure owner
- https://docs.getdbt.com/docs/collaborate/publish/model-access
  - `group` also supported as config
- https://docs.getdbt.com/reference/model-configs#general-configurations
  - add `group` to general configurations + new page for `group`
    - document all groupable nodes
- https://docs.getdbt.com/reference/resource-properties/
  - add `access` to general properties
  - ref restriction
- https://docs.getdbt.com/docs/build/
  - add `groups` resource 
- https://docs.getdbt.com/reference/dbt-jinja-functions/graph
  - add `groups` to `graph`
- https://docs.getdbt.com/reference/artifacts/manifest-json#top-level-keys
  - add groups to top-level keys
- https://docs.getdbt.com/reference/node-selection/methods
  - `group:` selection 
-  https://docs.getdbt.com/docs/collaborate/publish/model-access  
   - ref restrictions
- https://docs.getdbt.com/reference/resource-properties/
  - add owners under 'general properties' 
  
## Related `dbt-core` issues

- https://github.com/dbt-labs/dbt-core/issues/7058
- https://github.com/dbt-labs/dbt-core/issues/6748
- https://github.com/dbt-labs/dbt-core/issues/6823
- https://github.com/dbt-labs/dbt-core/issues/6824
- https://github.com/dbt-labs/dbt-core/issues/6825
- https://github.com/dbt-labs/dbt-core/issues/6826

https://www.notion.so/dbtlabs/dbt-Core-v1-5-docs-a2ae11be77bf47629f85faf7a3f27991

**Comment by jtcohen6** [comment]
Resolved by https://github.com/dbt-labs/docs.getdbt.com/pull/2946
