### ISSUE TITLE
More granular "global configs" for logging

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#2939]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/global-configs

### What part(s) of the page would you like to see updated?

Document these additional "global configs" for logging:
```
  --log-format [text|debug|json|default]
                                  Specify the format of logging to the console
                                  and the log file. Use --log-format-file to
                                  configure the format for the log file
                                  differently than the console.
  --log-format-file [text|debug|json|default]
                                  Specify the format of logging to the log
                                  file by overriding the default value and the
                                  general --log-format setting.
  --log-level [debug|info|warn|error|none]
                                  Specify the minimum severity of events that
                                  are logged to the console and the log file.
                                  Use --log-level-file to configure the
                                  severity for the log file differently than
                                  the console.
  --log-level-file [debug|info|warn|error|none]
                                  Specify the minimum severity of events that
                                  are logged to the log file by overriding the
                                  default value and the general --log-level
                                  setting.
  --use-colors / --no-use-colors  Specify whether log output is colorized in
                                  the console and the log file. Use --use-
                                  colors-file/--no-use-colors-file to colorize
                                  the log file differently than the console.
  --use-colors-file / --no-use-colors-file
                                  Specify whether log file output is colorized
                                  by overriding the default value and the
                                  general --use-colors/--no-use-colors
                                  setting.
```

### Additional information

- https://github.com/dbt-labs/dbt-core/issues/6639
- https://github.com/dbt-labs/dbt-core/pull/6994
https://www.notion.so/dbtlabs/dbt-Core-v1-5-docs-a2ae11be77bf47629f85faf7a3f27991

**Comment by jtcohen6** [comment]
Starting in v1.5, these flags are now functionally equivalent:
- `--log-level debug`
- `--debug`, `-d` ([docs](https://docs.getdbt.com/reference/global-configs#debug-level-logging))

The first one is more explicit, and it's what we should recommend going forward. We'll keep the second one around for historical purposes / backwards compatibility.

**Comment by dbeatty10** [comment]
It would be helpful if all of these are grouped together on the same page. Or cross-link to each other if they get put on separate pages.

e.g., if they all stay on the same page, these sections should be near each other since they are all related to logging (and have similar explanations for new flags in v1.5):
- https://docs.getdbt.com/reference/global-configs#log-formatting
- https://docs.getdbt.com/reference/global-configs#debug-level-logging
- https://docs.getdbt.com/reference/global-configs#use-colors
