### ISSUE TITLE
Configurable MAXIMUM_SEED_SIZE for state hash comparison

### ISSUE THREAD

**Issue by noppaz** [fishtown-analytics/docs.getdbt.com#2958]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/node-selection/state-comparison-caveats#seeds

### What part(s) of the page would you like to see updated?

Changes to reflect the feature in https://github.com/dbt-labs/dbt-core/pull/7125.

If above PR is merged, the documented behaviour remains. However, we should add documentation about the potential to use `DBT_MAXIMUM_SEED_SIZE` to change the maximum file size of hashed seed files. The behaviour should explain that it's set in MiB increments and that you can use 0 to remove the limit completely.

https://www.notion.so/dbtlabs/dbt-Core-v1-5-docs-a2ae11be77bf47629f85faf7a3f27991

**Comment by mirnawong1** [comment]
hey @noppaz , thanks for opening this up and it looks like this is still blocked by dev. I'll go ahead and close this issue out until the [core PR](https://github.com/dbt-labs/dbt-core/pull/7125) is picked up. will keep an eye out!

**Comment by mirnawong1** [comment]
https://github.com/dbt-labs/dbt-core/pull/11177
