### ISSUE TITLE
Python 3.11 support for dbt-snowflake

### ISSUE THREAD

**Issue by mikealfare** [fishtown-analytics/docs.getdbt.com#2965]
### Contributions

- [ ] I am a PM or subject matter expert at dbt who is responsible for this feature.

### Where does this content belong?

`dbt-snowflake=>1.4.2` will support Python 3.11. This will already be listed in PyPI, but I imagine will be listed somewhere in our docs as well. There are no new features with this update, it simply allows users to use Python 3.11 if they choose to do so.

## Who will use this feature?
The intended audience is anyone running Python 3.11 for their projects. That is currently limited to `dbt-core` users as dbt Cloud is not yet on Python 3.11.

## Feature description how it will help people
You can now run `dbt-snowflake` on the current version of Python (3.11). There is no new functionality in the tool itself, but you can use it with other packages which may only support Python 3.11. It's like releasing a movie in a new language. The content of the movie is the same, but now it's more accessible.

## Customer feedback and research
N/A

## How can we test or use this feature?
You can test this in this way:

1. Install Python 3.11:
  download from python.org
    or
  `brew install python@3.11`
1. Create and activate a virtual environment:
  `python -m venv venv && . ./venv/bin/activate`
1. Install `dbt-snowflake`:
  `pip install "dbt-snowflake==1.4.2"`
1. `dbt-snowflake` should successfully install:
  `dbt --version`

## Source Material
The content is the same, so installing Python 3.11 is the only extra step, which many users will already have.

**Comment by mirnawong1** [comment]
closing this issue as have the python compatibility matrix and satisfies this: https://docs.getdbt.com/docs/core/pip-install#python-compatibility-matrix
