### ISSUE TITLE
Correct Slack Notification Note

### ISSUE THREAD

**Issue by epapineau** [fishtown-analytics/docs.getdbt.com#2967]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/faqs/accounts/slack

### What changes are you suggesting?

You don't need to be an admin of the Slack workspace (cc: @christineberger) to configure Slack notifications - at least for unpaid Slack.

**Comment by vishalsingh2972** [comment]
is this issue still open? @epapineau

**Comment by runleonarun** [comment]
Looks like this was addressed [here](https://github.com/dbt-labs/docs.getdbt.com/pull/3133)
