### ISSUE TITLE
Update AWS CodeCommit instructions because their default branch is `master` instead of `main`

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#2973]
### Contributions

- [x] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/collaborate/git/import-a-project-by-git-url#aws-codecommit

### What part(s) of the page would you like to see updated?

- [ ] In the [AWS CodeCommit](https://docs.getdbt.com/docs/collaborate/git/import-a-project-by-git-url#aws-codecommit) instructions, we should link to instructions/explain that people might need to use a custom branch (`master`) as their default branch in dbt Cloud. Here are some resources to help write these instructions:
* FAQ for [setting up a custom branch](https://docs.getdbt.com/faqs/environments/custom-branch-settings#development) in the dev environment.
* An FAQ that [troubleshoots a particular error](https://docs.getdbt.com/faqs/troubleshooting/git-revlist-error)
* [Internal Jira ](https://dbtlabs.atlassian.net/browse/XP-1842)ticket to fix in product.
* [Internal Slack convo](https://dbt-labs.slack.com/archives/C02NCQ9483C/p1678401493869059).

**Comment by will-sargent-dbtlabs** [comment]
Interestingly, my new CodeCommit project's branch was "main" by default in AWS... (As of yesterday Nov 19, 2024)  So I'm unclear if the OP's "master" was an account setting or if AWS changed their default..
