### ISSUE TITLE
5. Metadata API - Add additional API endpoints 

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#2993]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

[Docs project](https://www.notion.so/dbtlabs/Discovery-Metadata-API-Latest-DAG-state-endpoint-af442dcbfa0249028f25360d8d72e983?pvs=4)

1. Add use case content in the metadata api page
2. Turn main metadata api page into landing page
3. Add use case page with example query and response code
4. Simplify layout and page names 
5. Add additional API endpoints (April time)
6. Out-of-scope - move API docs into a more discoverable location
7. Nice-to-have - embed apollo explorer sandbox

### What part(s) of the page would you like to see updated?

https://docs.getdbt.com/docs/dbt-cloud-apis/metadata-api

**Comment by runleonarun** [comment]
Closing because it seems like this has been addressed! Feel free to re-open if you need to!
