### ISSUE TITLE
Document interactive compile

### ISSUE THREAD

**Issue by aranke** [fishtown-analytics/docs.getdbt.com#2994]
### Contributions

- [X] I am a PM or subject matter expert at dbt who is responsible for this feature.

### Where does this content belong?

Probably in the [compile](https://docs.getdbt.com/reference/commands/compile) docs?

## Who will use this feature?
* Users who want to check out what their compiled model looks like
* dbt Cloud under the hood

## How can we test or use this feature?
```
dbt compile --inline "select * from {{ ref('raw_orders') }}"
```
or
```
dbt compile --select stg_payments
```

**Comment by jtcohen6** [comment]
Also need to document the new flag `--no-introspect`, which can also be used for "standard" `dbt compile` (not interactive)
