### ISSUE TITLE
Streaming content for Core v1.6

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#3005]
### Contributions

- [ ] I am a PM or subject matter expert at dbt who is responsible for this feature.

### Where does this content belong?

@Fleid Can you help fill this out?

### Link to source material

Not yet available

**Comment by dbeatty10** [comment]
Bumping to 1.6 per @Fleid.

**Comment by matthewshaver** [comment]
Closed per discussion with engineering
