### ISSUE TITLE
Deprecated: setting `log-path` + `target-path` in `dbt_project.yml`

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#3014]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/project-configs/log-path
https://docs.getdbt.com/reference/project-configs/target-path

### What part(s) of the page would you like to see updated?

We are deprecating the ability to set these configs in `dbt_project.yml`, in favor of setting them as CLI flags or env vars. This is much more consistent with how other flags are set/passed during app initialization.

In v1.5, there will be backwards compatibility for continuing to set these configs in `dbt_project.yml`. We plan to remove this back compat in a future (as-of-yet-undetermined) version of `dbt-core`.

### Additional information

https://github.com/dbt-labs/dbt-core/pull/7185

**Comment by adamcunnington-mlg** [comment]
@jtcohen6 please can you confirm whether this decision was reversed at a later date? I've noticed the docs no longer say these 2 properties are deprecated but according to Google, they did as of February.

![Screenshot_20240326-070302](https://github.com/dbt-labs/docs.getdbt.com/assets/93528462/3c50bc5b-8dfe-49c0-a108-b38f70d982fc)

**Comment by jtcohen6** [comment]
@adamcunnington-mlg These two configs are still deprecated for setting in `dbt_project.yml`. They are supported to set via CLI flag (`--log-path`, `--target-path`) or environment variable.

We did recently reorganize this documentation:
- #4814 

From the updated page (https://docs.getdbt.com/reference/global-configs/about-global-configs):

<img width="826" alt="Screenshot 2024-03-28 at 15 05 09" src="https://github.com/dbt-labs/docs.getdbt.com/assets/13897643/45c8fe2c-def7-4a45-ae7f-b3a904047690">

And the table further down (with my scrappy edit to show both flags more concisely):

![Untitled](https://github.com/dbt-labs/docs.getdbt.com/assets/13897643/bc73be6e-8468-46ff-b292-aa41cdc7e26a)
