### ISSUE TITLE
Add documentation to configure "delimiter" for seed files

### ISSUE THREAD

**Issue by ramonvermeulen** [fishtown-analytics/docs.getdbt.com#3015]
### Contributions

- [ ] I am a PM or subject matter expert at dbt who is responsible for this feature.

### Where does this content belong?

https://docs.getdbt.com/reference/seed-configs
The configurable delimiter option should be added to the list of arguments for the seed configuration as soon as https://github.com/dbt-labs/dbt-core/pull/7186 gets merged.

Then there needs to be a new documentation link:

https://docs.getdbt.com/reference/resource-configs/delimiter

### Link to source material

I have no access to the template (asked for permission), but the example on the seeds-config page should be:

```
version: 2

seeds:
  - name: [<seed-name>]
    config:
      [quote_columns](https://docs.getdbt.com/reference/resource-configs/quote_columns): true | false
      [column_types](https://docs.getdbt.com/reference/resource-configs/column_types): {column_name: datatype}
      [delimiter](https://docs.getdbt.com/reference/resource-configs/delimiter): <string>
```

and for the (new) url: https://docs.getdbt.com/reference/resource-configs/delimiter

# Definition
An optional seed configuration, used to determine which delimiter should be used by the csv parser when a [table](https://docs.getdbt.com/terms/table) is created. Defaults to comma.

# Usage
## Globally use a pipe as delimiter for seed files
```
seeds:
  +delimiter: '|'
```

## Only use the pipe delimiter for seeds in the seeds/mappings directory.
For a project with:

* `name: jaffle_shop` in the `dbt_project.yml` file
* `seed-paths: ["seeds"]` in the `dbt_project.yml` file
```
version: 2

seeds:
  - name: mappings
    config:
      delimiter: '|'
```

# Recommended configuration
* Explicitly set this value when you want to use a different delimiter in a seed file than a comma
* When using a mix of different seed files with delimiters, configure this value on a per seed file basis

**Comment by ramonvermeulen** [comment]
PR got merged, heads up for the documentation on seed files to be changed as well.

**Comment by matthewshaver** [comment]
These updates have been made in another issue. Closing this one
