### ISSUE TITLE
Generating dynamic documentation for a whole domain

### ISSUE THREAD

**Issue by Mikael-Thorup** [fishtown-analytics/docs.getdbt.com#3036]
### Contact Details

@Mikael on dbt slack

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

When building models on top of event-driven architecture, the same columns (with the same documentation) will appear several times. In order to save time spent writing and maintaining documentation (and following the DRY principle), we can utilize some CLI, the codegen package, docs blocks, and some regex to create the dbt documentation for us without us having to fiddle around with docs blocks, yaml formatting, etc.

### Link to an initial outline.

I've already written up some of this stuff for internal use ([link](https://docs.google.com/document/d/1HiLs3s7sVEsEB1M_BHkl7ts_XDVgCKsM_9zg_9_yl1c/edit)). Let me know if this makes it harder for you to evaluate whether this is relevant for the dbt Developer blog, and I can edit it into a short outline :)

**Comment by KiraFuruichi** [comment]
Hey @Mikael-Thorup, thank you for opening up this issue! We're always excited to have contributions to the Developer Blog from the Community :)

My name is Kira, and I'm a technical writer here at dbt Labs and one of the folks who helps manage the Developer Blog. After giving your outline a quick read, it looks like it's a great candidate for a blog post here :)

I’ve assigned myself as your primary editor and support for this article; I can help you with editing passes, getting the posts live on our site, and promoted on our social. We aim for a ~6 week turnaround time for posts from Issue to Publication, but also work on your timing 🙂

Next steps here is you should take your internal documentation and create an outline of how you would want your blog post to read, and then I can take a deeper look and make any suggestions before you actually begin writing. We'll work back and forth here to get into its final form.

Let me know if you have any questions, but we're excited to work with you and get this up. Please let me know here when you have a final outline ready and I'll take a look!
