### ISSUE TITLE
Update Redshift Configs and Setups with Query Tagging Documentation

### ISSUE THREAD

**Issue by trouze** [fishtown-analytics/docs.getdbt.com#3045]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/warehouse-setups/redshift-setup

https://docs.getdbt.com/reference/resource-configs/redshift-configs

### What part(s) of the page would you like to see updated?

Opening this issue in relation to dbt-redshift adapter [issue dbt-labs/dbt-adapters#648](https://github.com/dbt-labs/dbt-adapters/issues/648) and [PR # 379](https://github.com/dbt-labs/dbt-redshift/pull/379).

Development has already begun on [this branch](https://github.com/trouze/docs.getdbt.com/tree/adap-381-redshift-query-tagging), I'll open a PR soon.

**Comment by trouze** [comment]
Opened PR #3046 for this

**Comment by matthewshaver** [comment]
Original PR closed as attached issues/PRs still not complete. Can reopen when addressed
