### ISSUE TITLE
`--project-dir` and `DBT_PROJECT_DIR`

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#3053]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

I don't think we document `--project-dir` anywhere!!

We document `--profiles-dir` in a few places — namely [this one](https://docs.getdbt.com/docs/core/connection-profiles#advanced-customizing-a-profile-directory) — but only in passing.
```
$ dbt build --help
Usage: dbt build [OPTIONS]

  Run all Seeds, Models, Snapshots, and tests in DAG order

Options:
...
  --profiles-dir PATH             Which directory to look in for the
                                  profiles.yml file. If not set, dbt will look
                                  in the current working directory first, then
                                  HOME/.dbt/
  --project-dir PATH              Which directory to look in for the
                                  dbt_project.yml file. Default is the current
                                  working directory and its parents.
...
```

### What part(s) of the page would you like to see updated?

dbt subcommands have accepted a `--project-dir` flag since forever.

99% of the time, it makes sense to just run dbt from the same working directory as the dbt project (= where `dbt_project.yml` lives). This is an advanced feature, often for use in orchestration, that allows dbt commands to be run from a working directory that's different from the one where the dbt project lives.

Starting in v1.5, dbt will now accept an env var `DBT_PROJECT_DIR` that's equivalent to passing the `--project-dir` flag. If both are set, the flag wins (takes precedence).

### Additional information

- https://github.com/dbt-labs/dbt-core/pull/6659

**Comment by matthewshaver** [comment]
@jtcohen6 I can build the missing docs for the flags if you can suggest the best spot for them both. I'll take care of the new env var at the same time.

**Comment by jtcohen6** [comment]
Let's just mention it on this page: https://docs.getdbt.com/reference/dbt_project.yml

Something to the effect of: "By default, dbt will look in your current working directory for `dbt_project.yml`, but you can set a different directory using <flag or env var>"
