### ISSUE TITLE
How to build a Kimball dimensional model with dbt 

### ISSUE THREAD

**Issue by jonathanneo** [fishtown-analytics/docs.getdbt.com#3060]
### Contact Details

jonathanneo@me.com

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

While the relevancy of Kimball’s dimensional modelling has been debated in the Analytics Engineering community, in practice it is still the most widely adopted data modelling technique. 

Despite its popularity, resources for performing dimensional modelling using dbt remain sparse. 

In this tutorial, I provide Analytics Engineers with practical steps on how to apply dimensional modelling on a sample dataset using dbt.

### Link to an initial outline.

https://flint-wisteria-555.notion.site/How-to-build-a-kimball-dimensional-model-with-dbt-outline-only-09e33d6ff8634b9aba23bdb28a30e38b

**Comment by KiraFuruichi** [comment]
Closed with #3210
