### ISSUE TITLE
The Last Mile between Clean Tables and Data Visualization

### ISSUE THREAD

**Issue by unnatipalan** [fishtown-analytics/docs.getdbt.com#3062]
### Contact Details

unnati.palan@gmail.com

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

In organizations with dedicated data teams, the business logic is often stored within BI tools, making it difficult for non-technical users to understand how the metric is calculated. By creating a "last mile" BI visualization layer in dbt, organizations can 

- standardize business terms,
- ensure accurate testing, and
- correct date/time discrepancies,

resulting in improved data accuracy and reduced broken charts.

### Link to an initial outline.

https://cut-mask-6a0.notion.site/The-Last-Mile-between-Clean-Tables-and-Data-Visualization-9281a516495347b783f00aa3bfd972d6

**Comment by nghi-ly** [comment]
Thank you so much for creating this issue, @unnatipalan! 

The docs team has reviewed this blog post request and, at present,  there are no plans for it. Adding the `icebox` label in case we can revisit this request later and closing issue.
