### ISSUE TITLE
Custom Materializations Doc Page Points to Ancient Dev Branch

### ISSUE THREAD

**Issue by robinreeves** [fishtown-analytics/docs.getdbt.com#3063]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/guides/advanced/creating-new-materializations

### What changes are you suggesting?

The link in the overview section that is intended to take you to the materialization code in dbt-core is pointing to a more than three year old dev branch. These examples include calls to deprecated methods, and are significantly different from the current version. This will lead developers to see old, and potentially poor, patterns when starting to develop custom materializations.

**Comment by runleonarun** [comment]
Thanks for opening this issue, @robinreeves! We'll get this fixed!
