### ISSUE TITLE
Link to union and intersection definitions in YAML selector docs

### ISSUE THREAD

**Issue by epapineau** [fishtown-analytics/docs.getdbt.com#3068]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/node-selection/yaml-selectors#definitions

### What part(s) of the page would you like to see updated?

In the Definitions section:
> Use union and intersection to organize multiple arguments.

However, `union` and `intersection` are not defined on this page. @runleonarun linked me to [these definitions on the operators page](https://docs.getdbt.com/reference/node-selection/set-operators#unions), but I would not have found them without her intervention (ty @runleonarun! ❤️)

**Comment by dbeatty10** [comment]
➕ I've run into this same thing multiple times.

**Comment by epapineau** [comment]
Resolved with #3093 :)
