### ISSUE TITLE
Review new guide content 

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#3070]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/guides/dbt-ecosystem/dbt-python-snowpark/1-overview-dbt-python-snowpark

### What part(s) of the page would you like to see updated?

@hope-wat wrote an awesome guide and @nghi-ly helped her get it onto the docs site. It would be nice to loop back and give the guide a thorough Docs review so we can provide a more predictable reading experience for our users, reducing their cognitive load. 

For example, we might combine the content in "What you need to know" and "What you'll use during the lab" into a Prerequisites section to align with other similar guides.

**Comment by mirnawong1** [comment]
hey @runleonarun is this still an open issue?

**Comment by runleonarun** [comment]
It is but I don't see us having time to do this any time soon. Adding icebox label and closing.
