### ISSUE TITLE
Unit Testing in dbt: A Quick and Easy Guide to Getting Started

### ISSUE THREAD

**Issue by LukasSandm** [fishtown-analytics/docs.getdbt.com#3076]
### Contact Details

lukas@sandmeir.info

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

Today, there is no out of the box unit testing framework available for dbt. While there are a few different blog posts with solutions available, none of these fulfilled all our requirements. They were either too complex, or missed relevant features, like sad path testing capabilities. In this blog post, I will share how we set up a testing framework that works with available dbt testing capabilities, providing an easy to use unit testing framework for dbt.

### Link to an initial outline.

https://docs.google.com/document/d/13PDiyqssiNx4XrmWAuZnye2mwF3nFY6Fzc_2dUOXJro/edit#heading=h.5x0d5h95i329

**Comment by runleonarun** [comment]
Hello @LukasSandm We appreciate you taking the time to submit this blog post idea. Unfortunately, we have selected the blog posts we're going to publish this quarter. 

Would you like us to consider this idea again next quarter (which is in the August to October timeframe)?
