### ISSUE TITLE
`dbt show`

### ISSUE THREAD

**Issue by aranke** [fishtown-analytics/docs.getdbt.com#3097]
### Contributions

- [X] I am a PM or subject matter expert at dbt who is responsible for this feature.

### Where does this content belong?

New command under https://docs.getdbt.com/reference/dbt-commands

### Link to source material

# Who will use this feature?

* Users who want to see a preview of their model
* dbt Cloud under the hood

# How can we test or use this feature?
```
dbt compile --inline "select * from {{ ref('raw_orders') }}"
```
or
```
dbt compile --select stg_payments
```

**Comment by matthewshaver** [comment]
Awaiting demo for documentation

**Comment by aranke** [comment]
@matthewshaver I merged the feature in yesterday, will record a demo today and link it here.
