### ISSUE TITLE
In v1.5, `dbt list` will have standard default log level (`info`)

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#3107]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.5#breaking-changes

### What part(s) of the page would you like to see updated?

`dbt list` will no longer suppress `INFO`-level logging by default.

Instead, if users want to pipe the results of `dbt list` to a file / `jq` / another process, and exclude unrelated log messages from the output, they can use either of the following flags:
- `dbt --log-level warn ls` — exactly equivalent to previous default behavior
- `dbt --quiet ls` — suppresses anything less than `ERROR` level, except for "printed" messages

### Additional information

Relevant issue comment:
- https://github.com/dbt-labs/dbt-core/issues/7206#issuecomment-1488823893

**Comment by matthewshaver** [comment]
Closed with https://github.com/dbt-labs/docs.getdbt.com/pull/3138
