### ISSUE TITLE
Test RBAC/SSO docs and update if you can enable SSO

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#3131]
> we say you need to get things enabled by support or your account manager. is that true?

## Pages affected
https://docs.getdbt.com/docs/cloud/manage-access/set-up-sso-okta#enable-okta-native-auth-beta

https://docs.getdbt.com/docs/cloud/manage-access/enterprise-permissions#how-to-set-up-rbac-groups-in-dbt-cloud

![image](https://user-images.githubusercontent.com/3880403/229656422-2a8ac92e-0190-458d-b087-29591cc44326.png)

![image](https://user-images.githubusercontent.com/3880403/229656472-466630a2-8d90-43db-879d-db6de2e5e8be.png)

Copied from an [internal discussion](https://dbt-labs.slack.com/archives/CH1AWA9ST/p1680266279383509)

**Comment by matthewshaver** [comment]
These pages have been updated to reflect current workflows. Closing the issue
