### ISSUE TITLE
Clarify -1 value for adapter_response

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#3145]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

[Per slack thread](https://dbt-labs.slack.com/archives/C017GDLAF7D/p1680682398935539), users have reached out confused about what the `-1` means when they see `'rows_affected': {'_message': 'CREATE VIEW', 'code': 'CREATE VIEW', 'rows_affected': -1}}` in their run results.json artifact. 

`-1` is the standard value for `rowcount` in cases where your query's rowcount can't be determined: https://peps.python.org/pep-0249/#rowcount

Exactly as Benoit said, creating a view is just saving a query for the future — it doesn't actually create/alter/return any rows until you actually select from it. 

### What part(s) of the page would you like to see updated?

any page where adapter_response is discussed (which could deserve its own page)

- https://docs.getdbt.com/reference/artifacts/run-results-json#top-level-keys
- https://docs.getdbt.com/reference/dbt-classes#result-objects

### Additional information

hey @dbeatty10 - if you have any bandwidth at all in the next few weeks, can i create a pr and as for your technical advice so i can explain this correctly and also make sure I'm adding content in the correct places?

**Comment by dbeatty10** [comment]
> hey @dbeatty10 - if you have any bandwidth at all in the next few weeks, can i create a pr and ask for your technical advice so i can explain this correctly and also make sure I'm adding content in the correct places?

Absolutely @mirnawong1 -- just tag me in when you create the PR.
