### ISSUE TITLE
How to work with dbt in a decentralized, mesh like, context

### ISSUE THREAD

**Issue by guillesd** [fishtown-analytics/docs.getdbt.com#3146]
### Contact Details

Slack --> Guillermo (GoDataDriven)

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

As a follow up on my talk at dbt Coalesce on "[dbt & Data Mesh: The perfect pair(?)](https://www.youtube.com/watch?v=P1erB7GfIUY)", I wanted to provide an insight into why a company my choose for a decentralized setup with dbt (being this data mesh or a hubspoke model). Then, I'd like to deepdive into how companies could make a multi-repo approach work, with the interoperability requirements that this comes with, and how a data contract (using dbt sources and exposures) can be the answer to make this work.

**Disclaimer: The title is not settled yet and may change**

### Link to an initial outline.

# Some title
Intro
## Context: Decentralized data teams
Explain why decentralized data teams are emerging.
Explain briefly what organizational model options have emerged to solve the “how to decentralize” problem
Data Mesh (emphasize what we see at clients) 
Hubspoke
## Why a (dbt) monorepo doesn’t cut it in decentralized scenarios
Explain why a dbt monorepo is not a good candidate in a decentralized setup (particularly in data mesh) (link to dbt content)
### What is a data contract?
Briefly explain what a data contract is and why is this is important in a data mesh/decentralized setup.
### Defining a data contract in a dbt multi-repo setup
Explain how a dbt exposure in project A can be paired with a dbt source in project B to conform a dbt cross-repo contract.
### Automating some of the work
Guide to a practical, minimalistic example of how to implement this, including code snippets and link to a repo containing the full solution (a minimalistic one).
#### Requesting a exposure on the source repo
Example of how to create a exposure in Project A, so that I can consume it from Project B
#### Syncing this exposure as a source on the target repo
Example of how the build of Project A (with your newly merged exposure) generates a PR for a new source in Project B (your target project where you wanted to consume the data). This includes permissions for the Project B team to read the Project A table/view object.
#### Enforcing the constraints of the data contract
Example of how to define two constraints in the contract:
One for source freshness
Another one for schema checks (source in Project B expects a certain schema from exposure in Project A)
## Conclusions
Some conclusions + also discuss what dbt is currently doing to move into this direction (https://docs.getdbt.com/reference/resource-properties/constraints, https://docs.getdbt.com/reference/resource-configs/contract, https://docs.getdbt.com/docs/collaborate/publish/model-versions) 
Multi project support in dbt Cloud (https://github.com/dbt-labs/dbt-core/discussions/6725)

**Comment by runleonarun** [comment]
Hi @guillesd Thanks for pitching this idea! Are you still interested in writing this?  I feel like this would be a great blog post, so let me get someone to review the outline before you start drafting content. 

Hey @dbeatty10 and @azzam34 Do you have feedback for @guillesd's outline?

**Comment by nghi-ly** [comment]
The docs team has reviewed this blog post request and, at present, there are no plans for it. It's a good idea so adding the `icebox` label in case we can revisit this request later. Closing. Thank you so much, @guillesd !
