### ISSUE TITLE
Redirection URL incorrect on DBT community adapter docs

### ISSUE THREAD

**Issue by gssakash** [fishtown-analytics/docs.getdbt.com#3161]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/guides/dbt-ecosystem/adapter-development/1-what-are-adapters

### What changes are you suggesting?

The DBT [docs website](https://docs.getdbt.com/guides/dbt-ecosystem/adapter-development/1-what-are-adapters) page under the Next button at the bottom is supposedly pointing to an incorrect URL. 
Instead of going to the next step of the adapter development steps which is  "Prerequisites for a new adapter", it redirects the user back to the current page. 

![image](https://user-images.githubusercontent.com/52027687/230777485-34ec2138-bdd0-4265-ba2f-a0cfa470c289.png)

**Comment by mirnawong1** [comment]
hey @gssakash , thanks for opening this up and apologies for the delay here! this issue is now fixed and the URL takes you to the right page https://docs.getdbt.com/guides/adapter-creation?step=2

thank you again for flagging this!
