### ISSUE TITLE
Split up the Global Configs page

### ISSUE THREAD

**Issue by matthewshaver** [fishtown-analytics/docs.getdbt.com#3184]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/reference/global-configs

### What changes are you suggesting?

This page is very long and difficult to parse. Splitting it up into individual reference pages similar to the `List of Commands` pages. The `Global Configs` doc would become a parent category with the individual articles broken up below it.

**Comment by matthewshaver** [comment]
Per Doug,
It would be helpful if all of these are grouped together on the same page. Or cross-link to each other if they get put on separate pages.

e.g., if they all stay on the same page, these sections should be near each other since they are all related to logging (and have similar explanations for new flags in v1.5):

https://docs.getdbt.com/reference/global-configs#log-formatting
https://docs.getdbt.com/reference/global-configs#debug-level-logging
https://docs.getdbt.com/reference/global-configs#use-colors

**Comment by mirnawong1** [comment]
Giving some feedback on this too!

- Def agree with your proposal, makes total sense.
- One thing I'm. not clear about is whether this is for both cloud and core? these are all on the profiles.yml so it makes me think it's all cli. 
- I think you can prob use the autogenerated index for a landing page, with a small paragraph. However bear in mind that the doccarousel is going to merge soon so you can use that in the future too.
