### ISSUE TITLE
Start an About References landing page

### ISSUE THREAD

**Issue by matthewshaver** [fishtown-analytics/docs.getdbt.com#3187]
### Contributions

- [ ] I am a PM or subject matter expert at dbt who is responsible for this feature.

### Where does this content belong?

docs.getdbt.com/references

### Link to source material

docs.getdbt.com/references

**Comment by mirnawong1** [comment]
This is awesome @matthewshaver - Leona asked me to provide any feedback. So far i have:

- Def agree on a landing page and I personally think this landing page should have cards with a quick sentence of what each card (or section) represents (similar to our dbt features or dbt deploy jobs pages) to give the users a simple overview of what this section is and use cards to have them link to the relevant sections. 
- I also think a 'related docs' section may be appropriate. Eg. guides, quickstarts, dbt cloud section, dbt core section.

**Comment by mirnawong1** [comment]
hey @matthewshaver , i've created a landing page for this already so I'll add myself as the assignee if that's cool! can i ask for your review on it though?

cc @runleonarun
