### ISSUE TITLE
Document `--project-dir`

### ISSUE THREAD

**Issue by owenprough-sift** [fishtown-analytics/docs.getdbt.com#3197]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Uncertain

### What part(s) of the page would you like to see updated?

I assert that all CLI options of dbt ought to be mentioned/documented in the online documentation. `--project-dir` is not. This makes it more difficult for folks to use dbt ([example](https://getdbt.slack.com/archives/CBSQTAPLG/p1681468213197619)). Especially with the upcoming `dbt==1.5.0` release which adds support for environment variable `DBT_PROJECT_DIR` ([PR](https://github.com/dbt-labs/dbt-core/pull/6659)), it would be good to have thorough documentation on ways to specify the location of `dbt_project.yml`.

**Comment by matthewshaver** [comment]
Closing as this appears to have since been added to [migration guide](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.5) and [dbt_project.yml](https://docs.getdbt.com/reference/dbt_project.yml) pages.
