### ISSUE TITLE
Refactor: Rationalize use of alerts and callouts

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/docs.getdbt.com#32]
These two components are very similar. Can we just choose to use one over the other?

**Comment by clrcrl** [comment]
@drewbanin — is there one we should be preferring?

Should we instead bump our docusaurus version and use [callouts](https://v2.docusaurus.io/docs/markdown-features/#calloutsadmonitions) instead?

**Comment by VersusFacit** [comment]
@clrcrl Still something you have an opinion on? :)

**Comment by clrcrl** [comment]
I think this it outdated, we ended up implementing the native-docusaurus callouts
