### ISSUE TITLE
Model contracts: examples with size or precision & scale

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#3200]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/collaborate/govern/model-contracts

### What part(s) of the page would you like to see updated?

Within the database, certain data types can have size specified (e.g., `varchar(80)`). Others can have precision and scale specified (e.g., `decimal(18, 2)`). Others will only have precision (e.g. `timestamp_tz(3)`). Others will have nothing extra (e.g., `bool`, `int`, etc).

We should make it clear through examples how model contracts will treat these types of columns.

e.g. What will happen if the model contract says `varchar(80)` but the actual database type is `varchar(256)`?

My belief is that the model contact will allow this to pass the pre-flight check and that this is the intended behavior. This could surprise some folks, so we'll want to be explicit in our docs.

### Additional information

Related:
https://docs.getdbt.com/reference/dbt-classes#static-methods

**Comment by jtcohen6** [comment]
Rather than a detailed example, I'm just going to opt for an explicit note in the reference documentation: https://docs.getdbt.com/reference/resource-configs/contract

Lemme know if you disagree!

**Comment by dbeatty10** [comment]
Yep, "explicit note in the reference documentation" in https://github.com/dbt-labs/docs.getdbt.com/pull/3249 will work great. Thanks for that update!
