### ISSUE TITLE
"Model governance" vs. "Publishing models"

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#3202]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

When searching for "model versions", why does this say "Publishing models" instead of "Model governance"? Can we change it?

<img width="400" alt="image" src="https://user-images.githubusercontent.com/44704949/232551750-c0b87259-a5ea-49b1-8421-fe8870419f73.png">

Possibly related (or not): the following redirect didn't work for me this weekend, but it does now 🤷 

According to the [_redirects](https://github.com/dbt-labs/docs.getdbt.com/blob/950b4437dcfedd81fc28f7b47128aae9e5d53e16/_redirects#L34) file, [this](https://docs.getdbt.com/docs/collaborate/publish/model-versions) page should redirect to [here](https://docs.getdbt.com/docs/collaborate/govern/model-versions).

It wasn't redirecting this weekend for me for some unknown reason.

### What changes are you suggesting?

It should say "Model governance" instead of "Publishing models".

**Comment by jtcohen6** [comment]
I think this is no longer an issue, because
- the redirects have had enough time to work their magic
- the new links have taken priority in Algolia's index
- some secret third thing

**Comment by dbeatty10** [comment]
Thank you for confirming @jtcohen6 👍
