### ISSUE TITLE
Add 1.5 to the latest releases table in core versions page

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#3208]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/dbt-versions/core

### What part(s) of the page would you like to see updated?

I noticed that v1.5 is not showing up in the latest releases table. It also shows up in the upcoming releases table.

**Comment by jtcohen6** [comment]
I believe this is done!
