### ISSUE TITLE
Enhancing Security and Collaboration with BigQuery OAuth Integration in dbt Cloud

### ISSUE THREAD

**Issue by ernestoongaro** [fishtown-analytics/docs.getdbt.com#3214]
### Contact Details

ernesto.ongaro@dbtlabs.com

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

BQ Oauth went GA in dbt Cloud, so I suggest we publish this under @GideonShils and @Fleid's names 

### Link to an initial outline.

We're excited to announce that dbt Cloud now supports developer OAuth integration with BigQuery! This new feature brings an additional layer of security for dbt enterprise users and streamlines the process of collaborating within the dbt Cloud IDE. In this blog post, we will discuss the benefits of using this new feature and provide an overview of how to set it up.

Benefits of Using BigQuery OAuth Integration

Improved Security: By enabling BigQuery OAuth for your dbt Cloud projects, you are adding an extra layer of security. Each developer is required to authenticate with BigQuery in order to use the dbt Cloud IDE, ensuring that only authorized users have access to your data.
Streamlined Collaboration: With BigQuery OAuth integration, developers no longer need to share or manage individual service account keys. Instead, they simply authenticate using their own BigQuery credentials, making it easier for teams to work together and manage access to resources.
Simplified User Management: BigQuery OAuth integration allows you to manage user access within the dbt Cloud interface. Administrators can easily grant or revoke access, and users can authenticate with their existing BigQuery accounts.
Setting Up BigQuery OAuth Integration

Getting started with BigQuery OAuth integration in dbt Cloud is a simple three-step process:

Create a BigQuery OAuth 2.0 client ID and secret: This involves setting up a new OAuth app in BigQuery and generating the client ID and secret needed for authentication. These credentials will be stored in dbt Cloud.
Configure the connection in dbt Cloud: Add the client ID and secret generated in the previous step to your dbt Cloud project's connection settings.
Authenticate to BigQuery for each developer: Finally, each dbt Cloud user must authenticate with BigQuery in their profile settings to access the dbt Cloud IDE.

Conclusion

The new BigQuery OAuth integration in dbt Cloud is a powerful feature that enhances security and collaboration within your data team. By implementing this integration, you can ensure that only authorized users have access to your data, streamline the collaboration process, and simplify user management. Get started today and experience the benefits of this exciting new feature!

**Comment by ernestoongaro** [comment]
Authors of blog should prob be: @schottj, @GideonShils, @Fleid

**Comment by runleonarun** [comment]
Hey @ernestoongaro I think this was probably meant for the [company blog](https://www.getdbt.com/category/product-news/). I'm going to close this out, but feel free to re-open if you still want this on the developer blog!
