### ISSUE TITLE
Add info and faqs on how to add custom fields to dbt generated docs

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#3219]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Users have [asked](https://getdbt.slack.com/archives/C0441GSRU04/p1681911452896649) if there is a way to expand dbt generated docs with custom fields. there is! but it's don't clearly documented. 

**Answer**
There’s a [meta config](https://docs.getdbt.com/reference/resource-configs/meta) that exists on models and columns that can be defined in yaml. Believe they’ll all be surfaced through the docs (certainly model level stuff is, but I’m less positive on column level)

### What part(s) of the page would you like to see updated?

Proposing adding this helpful piece:

- Docs FAQs
- build and view your docs page as faq_src
- link faq in meta config page as faq_src
- dbt docs reference page as faq_src

**Comment by runleonarun** [comment]
@mirnawong1 I'm going to close this because of efforts needing to be put into dbt Explorer instead. Please let me know or reopen if you disagree!
