### ISSUE TITLE
Data Vault 2.0 with dbt Cloud

### ISSUE THREAD

**Issue by IL-RASTI** [fishtown-analytics/docs.getdbt.com#3237]
### Contact Details

rastislav@infinitelambda.com

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

The aim of the post is to help dbt practitioners understand the benefits of Data Vault 2.0 modelling, particularly drawing attention to the implications around agility and scalability. Ultimately, readers should be able to tell if this methodology is suitable for their organisation and understand the benefits of building it using dbtCloud.

Target audience of the post are versed analytics engineers in data modelling. They understand the need of multi layer data warehouse for their organisation and are keen to learn how can they build it using dbtCloud and Data Vault 2.0 methodology.

### Link to an initial outline.

https://docs.google.com/document/d/1o1mhg2gwwO370ipbT1ynG4F6cA8AHJidB2OI2H7KP6A/edit#

**Comment by boxysean** [comment]
I'm excited to be working with @IL-RASTI on this post :-) (cc @sdurry)

**Comment by KiraFuruichi** [comment]
Whoo excited to see this! @boxysean, do you foresee needing any additional editorial support for this blog post (similar to what Dave did for dbt^2 post)?

**Comment by boxysean** [comment]
Yes @KiraFuruichi that would be great

**Comment by KiraFuruichi** [comment]
Ok can do! @boxysean I can provide some light editing support for this piece. Please lmk when it's in its more final draft-y stages and I'll be happy to take a look at it :)

**Comment by boxysean** [comment]
Will do! @IL-RASTI and I will check-in this week 👍
