### ISSUE TITLE
Improve snapshots docs examples and `dbt_updates_at` field description

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#3242]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Examples like this: https://docs.getdbt.com/docs/build/snapshots#hard-deletes-opt-in

dbt_updated_at description:
https://docs.getdbt.com/docs/build/snapshots#snapshot-meta-fields

## For the examples
Update examples to match filenames to match the name of the snapshot. In this [example](https://docs.getdbt.com/docs/build/snapshots#hard-deletes-opt-in), we need to change `hard_delete_example.sql` to `orders_snapshot_hard_delete` 
From @graciegoheen 
> It’s our best practice for the name of the files to match the name of the snapshot, but our examples have names that differ from the snapshot name (this confused a customer i’m working with who was trying to copy the examples to test out the functionality)

Update the `dbt_updated_at_timestamp` description to account for different strategies as described by Grace in the following quote. We might need to consult @dbt-labs/devex on these nuances. 

> the dbt_updated_at field is described as “The `updated_at timestamp` of the source record when this snapshot row was inserted.” But if you have a snapshot using the `check_cols` strategy, your source record won’t have an `updated_at` timestamp. Does this field depend on the [strategy](https://github.com/dbt-labs/dbt-core/blob/828d723512fced809c63e369a82c7eb570a74986/core/dbt/include/global_project/macros/materializations/snapshots/strategies.sql#L140) that you’re using? Looks like it’s the `current_timestamp` if you’re using `check_cols`.

**Comment by runleonarun** [comment]
@mirnawong1 I added this to the References project if we can address part or all of it in V1, if not we can move to the V2 of References.

**Comment by dbeatty10** [comment]
It feels like there's two different things here, both related to snapshots:
1. Filename vs. snapshot name
1. Documentation related to `dbt_updated_at`

I'd suggest splitting them into two different issues and two different PRs.

### Filename vs. snapshot name

This one seems really easy to address and can be knocked out with a quick PR.

Edit: I opened https://github.com/dbt-labs/docs.getdbt.com/pull/3251 to address this portion.

### Documentation related to `dbt_updated_at`

This one has way more complication and nuance and will take more intense focus to get all the details right. And it seems like it would be covered by one or more of these issues:

- https://github.com/dbt-labs/docs.getdbt.com/issues/2900
- https://github.com/dbt-labs/docs.getdbt.com/issues/3117
- https://github.com/dbt-labs/docs.getdbt.com/issues/1948

Maybe @graciegoheen's comments related to `updated_at` could be added to one of those other issues instead?
