### ISSUE TITLE
Add new functionalities to 'job scheduler' page

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#3257]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

[Docs project](https://www.notion.so/dbtlabs/Improve-dbt-Cloud-CI-content-8d40d9d29a9d436384c1402bbff67f55?pvs=4)

According to discussions, [this doc](https://www.notion.so/dbtlabs/Issue-3144-Job-queue-content-ac97f41f0633409ba920c709ccd764ef#21e940dd3cbc430983c68122a700b891), and [loom](https://www.loom.com/share/991e1ded344942a9bba30f2f85649753) - @nghi-ly is going to add new functionalities/behaviors to [this doc](https://github.com/dbt-labs/docs.getdbt.com/pull/3253/) (new job scheduler page, which isn't launched as of when this issue was created) as part of the CI improvement project. 

### What part(s) of the page would you like to see updated?

https://github.com/dbt-labs/docs.getdbt.com/pull/3253/

https://docs.getdbt.com/docs/deploy/dbt-cloud-job

**Comment by runleonarun** [comment]
I believe this has been addressed, but feel free to reopen if I'm wrong!
