### ISSUE TITLE
Add "edit this page" button to the developer blog

### ISSUE THREAD

**Issue by VersusFacit** [fishtown-analytics/docs.getdbt.com#3266]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

The sidebar of blog articles does not have the same edit button that an ordinary blog post does. 

<img width="258" alt="image" src="https://user-images.githubusercontent.com/67295367/234425244-e240c6fd-9dc7-4c3a-8f26-c68a50e4db58.png">
this blog post's sidebar: https://docs.getdbt.com/blog/kimball-dimensional-model

### What changes are you suggesting?

<img width="258" alt="image" src="https://user-images.githubusercontent.com/67295367/234425176-a571b065-c846-43e1-a247-a4bfa76011c4.png">
From docs front page

This feature lowers the bar to contributing, and encourages both employees and open-source contributors to correct typos or wording issues as they spot team.

### Additional information

Because a developer blog post is written by a contributor, we might name this button something like "edit copy" or similar – we can also have sign posts along the way then encourage people who want to change content to instead write their own post.

**Comment by runleonarun** [comment]
@JKarlavige Is this possible and is there a reason it's not on the dev blog? Thank you! LMK if I should open an asana ticket!

**Comment by JKarlavige** [comment]
> @JKarlavige Is this possible and is there a reason it's not on the dev blog? Thank you! LMK if I should open an asana ticket!

I'm not 100% sure why it is not active for the Blog, but we should be able to get this in there. Feel free to submit a task for this!

**Comment by mirnawong1** [comment]
Closing this as it should be an asana task!
