### ISSUE TITLE
Disambiguate versions

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#3290]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

- https://docs.getdbt.com/reference/project-configs/version
- https://docs.getdbt.com/reference/resource-properties/versions
- https://docs.getdbt.com/docs/collaborate/govern/model-versions

### What part(s) of the page would you like to see updated?

`version` is different from `versions`, so we should be clear to help people disambiguate and find the right page if their search engine sends them to the wrong place!

The later is for model versioning introduced in 1.5. The former is no longer required in 1.5 (for either `dbt_project.yml` or `_properties.yml` files).

**Comment by mirnawong1** [comment]
working on this this week
