### ISSUE TITLE
Blue/green Deployment Blog Post

### ISSUE THREAD

**Issue by wasilaq** [fishtown-analytics/docs.getdbt.com#3307]
### Contact Details

Wasila Quader

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

The post is a step-by-step guide on how to implement blue/green deployment if you're using Snowflake. It's an update to [Claire's original discourse post](https://discourse.getdbt.com/t/performing-a-blue-green-deploy-of-your-dbt-project-on-snowflake/1349) on how to do the same thing from a few years back.

Let me know if this works as a blog post or if there's a better medium to make this info publicly available! Right now it exists as an internal resource.

### Link to an initial outline.

https://www.notion.so/Blue-Green-Deployment-944c0ecd5e854882ac94c9556ff4733f

**Comment by mirnawong1** [comment]
closing issue as this has been stale for a while. will reopen if we revisit this though!
