### ISSUE TITLE
Update the redshift-setup page to include `region` as a field

### ISSUE THREAD

**Issue by nssalian** [fishtown-analytics/docs.getdbt.com#3308]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/reference/warehouse-setups/redshift-setup

### What changes are you suggesting?

Appending 
```
region: [optional, if not provided, will be determined from host (e.g. host.123.us-east-1.redshift-serverless.amazonaws.com)]
``` 
to line 71

Relevant to the changes made here: https://github.com/dbt-labs/dbt-redshift/pull/420

**Comment by dbeatty10** [comment]
Resolved by https://github.com/dbt-labs/docs.getdbt.com/pull/3309
