### ISSUE TITLE
Link checker resolves to first matching suffix, not first matching path

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/docs.getdbt.com#333]
## Steps to reproduce:
If I create a link like this:
```
[run](run)
```
I expect it to go to the page named run:
```
https://docs.getdbt.com/reference/commands/run/
```

Instead, it goes to the first path that ends in `run`:
```
https://docs.getdbt.com/faqs/failed-prod-run
```

## Live example
Source code:
https://github.com/fishtown-analytics/docs.getdbt.com/blame/current/website/docs/reference/dbt-commands.md#L18

[Relevant page](https://docs.getdbt.com/reference/dbt-commands/)

## Extra details
We _could_ update all the links to be fully qualified, but I also think that my assumption about where the page will go is a pretty reasonable one.

In general, I'm a little blurry on the best way to write these hyperlinks in general! A heuristic would be useful to avoid future issues like this

**Comment by drewbanin** [comment]
closed by https://github.com/fishtown-analytics/docs.getdbt.com/pull/334
