### ISSUE TITLE
1.5 - Missing new config for Snowflake for the `profiles.yml` set up

### ISSUE THREAD

**Issue by b-per** [fishtown-analytics/docs.getdbt.com#3330]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/warehouse-setups/snowflake-setup

### What part(s) of the page would you like to see updated?

For `Key Pair Authentication`, the doc only mentions `private_key_path` and `private_key_passphrase`. 

[This PR](https://github.com/dbt-labs/dbt-snowflake/pull/292) on the dbt-snowflake adapter side added the ability from 1.5 onwards to pick between `private_key_path` (the path to the private key), and `private_key` (the value of the private key). Only one of the 2 can be defined though.

**Comment by dbeatty10** [comment]
Resolved by https://github.com/dbt-labs/docs.getdbt.com/pull/3432
