### ISSUE TITLE
Add descriptive titles to references (part 2)

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#3334]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/

Any page that has a one-word title needs a `sidebar_label: "one-word_title"` and a new title that describes the content. 

### What part(s) of the page would you like to see updated?

In this [previous PR](https://github.com/dbt-labs/docs.getdbt.com/pull/3325), we fixed most reference titles that were causing errors because they were duplicates. But, that PR was getting long and I fixed the major issues causing code conflicts. However, there are more titles that could be re-titled to improve discoverability and make more sense in Google searches!

You can use [this PR](https://github.com/dbt-labs/docs.getdbt.com/pull/3325) to understand how we've been re-titling these pages.

**Comment by ThienBNguyen** [comment]
Hi runleonarun, I am interested in the issue. can I try to solve it? thanks

**Comment by runleonarun** [comment]
HI @ThienBNguyen we would love your contributions! Do you feel like there's enough guidance in this issue? Let me know if you have any questions!

**Comment by ThienBNguyen** [comment]
I will try to fork the project and run on my system. if I run into an issue, I will let you know

**Comment by ThienBNguyen** [comment]
I have few questions. I have seen the previous PR. there are titles that have more than 'one word' but do not have sidebar_label: . do I need to add sidebar_label to the md files for those titles have more than one word? or I only need to add it to the title that have only one word and fix the title name.  here is an example in website/blog/2019-05-01-how-we-structure-dbt-projects.md with title: "How We Structure our dbt Projects". if I find the title name with one word how do you want me to name the title?

**Comment by mirnawong1** [comment]
hey @runleonarun do we still need this issue open?

**Comment by runleonarun** [comment]
Let's close this. It's pretty low priority
