### ISSUE TITLE
Remove changelog notes for <1.0

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#3348]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

You'd need to search for <changelog> and look at it on a case-by-case basis. They are sometimes notes and sometimes just and general

### What part(s) of the page would you like to see updated?

For example, you might find a note like this, which is not necessary now that we've deprecated content for versions prior to 1.0.
https://github.com/dbt-labs/docs.getdbt.com/pull/3325/files#diff-7d17a41f55e0f78d286ccd9f533b1ff326535eb20005a4bcac8ae91a2c4fe040L7-L13

**Comment by mirnawong1** [comment]
hey @runleonarun or @matthewshaver do we still need this issue open? i thought this was addressed already but i may be making this up!

**Comment by runleonarun** [comment]
Yes this has been done!
