### ISSUE TITLE
Add reuse_connections to Postgres setup docs

### ISSUE THREAD

**Issue by ckdake** [fishtown-analytics/docs.getdbt.com#3356]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/warehouse-setups/postgres-setup

### What part(s) of the page would you like to see updated?

Once https://github.com/dbt-labs/dbt-core/pull/7587 is merged, the postgres documentation should be updated to include `reuse_connections` as a new optional configuration line for Postgres. Something along the lines of:

`reuse_connections: [optional, defaults to False. Set to True to reuse connections when possible instead of closing/opening multiple times]`

## reuse_connections
By default, in each thread dbt closes and opens connections to Postgres multiple times during a `dbt run`.  If you prefer dbt to maintain connections as long as possible (which should result in each thread connecting once when it starts, and maintaining that connection), set this to True.

**Comment by matthewshaver** [comment]
Closing for now as the attached PR is closed. Can revisit if the future if needed
