### ISSUE TITLE
Remove name from documentation

### ISSUE THREAD

**Issue by callum-mcdata** [fishtown-analytics/docs.getdbt.com#3406]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/reference/exposure-properties

Jerco added it back a few months ago and probably should be someone else now. 

### What changes are you suggesting?

```
    owner:
      name: Callum McData
      email: data@jaffleshop.com
```

to something else!

**Comment by joellabes** [comment]
![image](https://github.com/dbt-labs/docs.getdbt.com/assets/7335046/08e56d68-b2ec-4078-9ea8-0f0107bfd6e3)

**Comment by mirnawong1** [comment]
here here!
