### ISSUE TITLE
Provide more context in upgrade core version in dbt Cloud

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#3435]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/dbt-versions/upgrade-core-in-cloud#upgrading-to-the-latest-version-of-dbt-in-cloud

### What part(s) of the page would you like to see updated?

Let's add more context to this page to provide a complete picture for upgrading  dbt Core version in Cloud
*  Should we add more to "creating a new project?"
* Are there other places where you need to change the version?
* Should we add any screenshots to help guide people?
* What can we glean from  [this blog post](https://docs.getdbt.com/blog/upgrade-dbt-without-fear)? (once we verify the information is current or find updated info)

### Additional information

This was inspired by an internal conversation with @travismarceau where he was using [this blog post](https://docs.getdbt.com/blog/upgrade-dbt-without-fear) to help customers understand how to upgrade.

**Comment by mirnawong1** [comment]
hey @runleonarun , do you think we should still tackle this issue going forward? or is this straightforward?

**Comment by runleonarun** [comment]
Yea let's close it out!
