### ISSUE TITLE
Create missing global configs features

### ISSUE THREAD

**Issue by matthewshaver** [fishtown-analytics/docs.getdbt.com#3450]
_Originally posted by @dbeatty10 in https://github.com/dbt-labs/docs.getdbt.com/issues/3332#issuecomment-1544688769_:

> @matthewshaver Exciting that you are working on this!
> 
> The Netlify preview failed, so I could only look at the code and not the actual web pages.
> 
> There are a couple issues that would be awesome to address either in this PR or a follow-up:
> - https://github.com/dbt-labs/docs.getdbt.com/issues/3264
> - https://github.com/dbt-labs/docs.getdbt.com/issues/2894

**Comment by mirnawong1** [comment]
Closing this issue as addressed in the PR mentioned inside each issue
