### ISSUE TITLE
More with less: a simple and rich model naming convention

### ISSUE THREAD

**Issue by ArthurMro** [fishtown-analytics/docs.getdbt.com#3483]
### Contact Details

arthur@datablaze.ai

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

A very simple trick to increase readability and dependencies visibility of models:
Take 4 digits: the first digit represents the stage, the 3 following the dependencies. For the 1st digit, we use:
_0 for sources, 1 for stagings, 2 - 8 for intermediaries & 9 for finals/marts. For instance, buiding the number on logically dependcies, you will have "_1012_google_ads_per_country.sql". Visually and verbally it's easier to communicate about the "1012" than about the "stg_google_ads_per_country"

### Link to an initial outline.

https://docs.google.com/document/d/1SbxUDA3j58tjx52tHqp2vTBpajM-GzcNqXR_NXzNNks/edit?usp=sharing

**Comment by nghi-ly** [comment]
Thank you so much for creating this issue, @ArthurMro! 

The docs team has reviewed this blog post request and, at present,  there are no plans for it. Adding the `icebox` label in case we can revisit this request later (like your idea!) and closing issue.
