### ISSUE TITLE
Support for Snowflake Dynamic Tables

### ISSUE THREAD

**Issue by mikealfare** [fishtown-analytics/docs.getdbt.com#3494]
### Contact Details

@mikealfare

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

We're going to support dynamic tables for `dbt-snowflake` and dbt Cloud.

### Link to an initial outline.

https://github.com/dbt-labs/dbt-snowflake/issues/603

**Comment by runleonarun** [comment]
@pofl Do you and @mikealfare want this to be a developer blog post, or should this go on our [corporate blog](https://www.getdbt.com/blog/)?

cc @azzam34

**Comment by pofl** [comment]
I think I was tagged by mistake here. I'm not aware of the context here 😅

**Comment by mikealfare** [comment]
@Fleid, I believe you were the intended tag.

**Comment by Fleid** [comment]
Hey @runleonarun I think we can close this issue. I'll ping you on Slack.

**Comment by runleonarun** [comment]
Apologies for the wrong ping 😬 Thanks Florian!
