### ISSUE TITLE
Metrics-related items within migration guide for dbt v1.6

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#3503]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Migration guide for dbt v1.6:
https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.6

### What part(s) of the page would you like to see updated?

For projects that define metrics, give them any information that they need.

### Additional information

Internal Slack link with context: https://dbt-labs.slack.com/archives/C0131TY7EEA/p1686330380388209?thread_ts=1686328666.241689&cid=C0131TY7EEA

**Comment by jtcohen6** [comment]
@mirnawong1 @Jstein77 Does one/both of you want to take on this one?

I'm picturing a strongly worded note under the "Behavior changes" section of [the migration guide](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.6):

> **Action required if your project defines `metrics`:** The spec for metrics has changed...

**Comment by mirnawong1** [comment]
hey @jtcohen6, i've added something in PR #3386 but would love to have @Jstein77 also review it since he's creating the migration script.

**Comment by Jstein77** [comment]
This is very timely! I had time carved out separately this week to work on a migration guide. It's also going to include how to update your cloud environments to migrate to the new SL.

**Comment by Jstein77** [comment]
@jtcohen6 @dbeatty10 here's the draft of the metrics migration guide

**Comment by mirnawong1** [comment]
did you mean [this one](https://www.notion.so/dbtlabs/Migrating-to-New-SL-74e502ec6c0043548133af6dd84720a6?d=62b9a2a2618243d69eca6f8217499d90#3db81297a68c4d92881816c573191f70) @Jstein77 ? FYI team, I've moved the migration guide over to git in preparation for the SL public beta. check out the [pr here](https://github.com/dbt-labs/docs.getdbt.com/pull/3705/files#diff-22904e5207637b398cbeb113622637e8cd2283ad5417c238413a56d0089800cf)
