### ISSUE TITLE
Update the Owner and Member Groups in dbt Cloud Enterprise section of the self-service permissions page

### ISSUE THREAD

**Issue by matthewshaver** [fishtown-analytics/docs.getdbt.com#3520]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/cloud/manage-access/self-service-permissions

### What part(s) of the page would you like to see updated?

We've made a lot of changes to licenses and roles recently, the section regarding Owner and Member Groups in dbt Cloud Enterprise could use refreshing

**Comment by runleonarun** [comment]
Addressed with https://github.com/dbt-labs/docs.getdbt.com/pull/3462
