### ISSUE TITLE
Fix links that reference other quickstart steps

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#3524]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

In the quickstart guides, the links that reference other steps within the same quickstart don't work. Example:

https://docs.getdbt.com/quickstarts/databricks?step=5
![Screenshot 2023-06-14 at 12 27 45](https://github.com/dbt-labs/docs.getdbt.com/assets/89008547/5f4e90ca-1650-4e03-84a0-35b78608d113)

I noticed this for most of the quickstart pages so all pages should be checked.

### What part(s) of the page would you like to see updated?

https://docs.getdbt.com/quickstarts

example: https://docs.getdbt.com/quickstarts/databricks?step=5

**Comment by runleonarun** [comment]
Thank for opening this, Mirna.  I marked this medium priority.  The links aren't working so this could be confusing though not too hard to figure out.

**Comment by mirnawong1** [comment]
Fixed
