### ISSUE TITLE
Broken link in `website/docs/guides/best-practices/materializations/materializations-guide-7-conclusion.md`

### ISSUE THREAD

**Issue by owenprough-sift** [fishtown-analytics/docs.getdbt.com#3525]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/guides/best-practices/materializations/7-conclusion

### What part(s) of the page would you like to see updated?

The "custom materializations" link is broken.

It points to: https://docs.getdbt.com/guides/best-practices/materializations/guides/advanced/creating-new-materializations (non-existent page)

It _should_ point to here: https://docs.getdbt.com/guides/advanced/creating-new-materializations

The link syntax itself in `website/docs/guides/best-practices/materializations/materializations-guide-7-conclusion.md` seems reasonable, but when it renders it incorrectly includes `guides/best-practices/materializations/` as a prefix.

### Additional information

Issue reported on Slack by gilcrest: https://getdbt.slack.com/archives/CBSQTAPLG/p1686747677792289

**Comment by runleonarun** [comment]
Thanks for reporting this bad link, @owenprough-sift! I [opened a PR](https://github.com/dbt-labs/docs.getdbt.com/pull/3536) to fix it
