### ISSUE TITLE
dbt Cloud support

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#3542]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/dbt-support

### What part(s) of the page would you like to see updated?

Sometimes we're communicating with a user in GitHub, but we need to escalate them to dbt Cloud support.

The best content for reaching out to dbt Cloud Support is in a "legacy" page here:
https://docs.getdbt.com/guides/legacy/getting-help#dbt-cloud-support

Could we move/copy/import that same block of text to https://docs.getdbt.com/docs/dbt-support?

Also, could https://docs.getdbt.com/docs/dbt-support be reviewed for relevance and clarity? It's hard to pick out the TLDR for me.

### Additional information

Example: https://github.com/dbt-labs/dbt-redshift/issues/427#issuecomment-1592819008

**Comment by mirnawong1** [comment]
the [support page](https://docs.getdbt.com/docs/dbt-support) was recently tweaked for clarity and i've also linked the legacy page in pr #4559
