### ISSUE TITLE
Fixing broken link on: https://docs.getdbt.com/guides/best-practices/materializations/3-configuring-materializations

### ISSUE THREAD

**Issue by MaratAbdullaev** [fishtown-analytics/docs.getdbt.com#3562]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/guides/best-practices/materializations/3-configuring-materializations

### What part(s) of the page would you like to see updated?

[which adapter you’re using](https://docs.getdbt.com/guides/best-practices/materializations/docs/supported-data-platforms)

### Additional information

link is broken

**Comment by mirnawong1** [comment]
thanks again for this @MaratAbdullaev ! opened up a pr to get this fixed ✨
