### ISSUE TITLE
Broken link in https://docs.getdbt.com/guides/best-practices/materializations/4-incremental-models

### ISSUE THREAD

**Issue by MaratAbdullaev** [fishtown-analytics/docs.getdbt.com#3563]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/guides/best-practices/materializations/4-incremental-models

### What part(s) of the page would you like to see updated?

[does in fact exist in dbt](https://docs.getdbt.com/guides/best-practices/materializations/reference/dbt-jinja-functions/this)

### Additional information

broken link

**Comment by mirnawong1** [comment]
hey @MaratAbdullaev ! great catch and thank you for opening up this issue! I've spun up a pr to fix these links so we'll get this correct as soon as we can ✨.
