### ISSUE TITLE
Whither `website/Makefile`?

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#3578]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

I was a frequent user of `make run` and `make build` to preview/build the docs site while developing locally. It's possible (even trivial) to use `npm` commands instead, but that was my muscle memory!

Here's what that file used to look like, on an older branch: https://github.com/dbt-labs/docs.getdbt.com/blob/1.5-maintainer-upgrade-guide/website/Makefile

We also still recommend running `make build` within the repo's README:

> 7. Before pushing your changes to a branch, check that all links work by using the `make build` script.

### What changes are you suggesting?

Any reason we shouldn't bring it back?

**Comment by dbeatty10** [comment]
+1

**Comment by dbeatty10** [comment]
@JKarlavige it looks like you removed the Makefile in https://github.com/dbt-labs/docs.getdbt.com/pull/3284/commits/c069a02482845dcaeaa079720ddf8bafd75ebecd. Would you protest if we resurrect it? But minus the specific lines that you don't want and need anymore?

**Comment by JKarlavige** [comment]
Yeah I don't see an issue with that! Mind adding me as a reviewer in the PR where the Makefile is added back in to look it over?
