### ISSUE TITLE
improve grammar

### ISSUE THREAD

**Issue by MaratAbdullaev** [fishtown-analytics/docs.getdbt.com#3589]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/guides/best-practices/environment-setup/2-one-deployment-environment

### What part(s) of the page would you like to see updated?

multiple developers can easily contributing 

### Additional information

multiple developers can be easily contributing 
OR
multiple developers can easily contribute

**Comment by runleonarun** [comment]
Thanks for opening this @MaratAbdullaev! You are welcome to address this in a PR, otherwise, I've triaged it for the docs team.

**Comment by mirnawong1** [comment]
Hey @MaratAbdullaev thanks for flagging this! I've opened a pr to address and clarify 🙏
