### ISSUE TITLE
website: getting started tutorial LoomVideo not showing 

### ISSUE THREAD

**Issue by ecerulm** [fishtown-analytics/docs.getdbt.com#359]
## Steps to reproduce:
Go to https://docs.getdbt.com/tutorial/create-a-project-dbt-cli

## Expected results:
See the video 
## Actual results
![image](https://user-images.githubusercontent.com/58676/91334957-061d0380-e7d0-11ea-9143-a5e8e5118fcb.png)

## Extra details
None of the <LoomVideo> tags seems to work

**Comment by clrcrl** [comment]
Yikes! We just changed our Loom account, and I did not realize this was going to happen!

**Comment by clrcrl** [comment]
It seems that as part of the migration to a Team account, only my most recent 25 videos were migrated. The rest... disappeared? I have an active support case with Loom right now

**Comment by clrcrl** [comment]
These videos were archived as part of our migration. I've now un-archived them, so am closing the issue :)
