### ISSUE TITLE
Add current_db_only as a new config in dbt-redshift

### ISSUE THREAD

**Issue by jiezhen-chen** [fishtown-analytics/docs.getdbt.com#3601]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/core/connect-data-platform/redshift-setup

### What part(s) of the page would you like to see updated?

Configuring dbt-redshift

### Additional information

Tagging this [PR](https://github.com/dbt-labs/dbt-redshift/pull/428) which adds a new configurable parameter current_db_only in dbt-redshift. The docs should be update to reflect what this parameter does and how to set it

**Comment by runleonarun** [comment]
Thanks for opening this issue! I've triaged it and it's in our queue to address.

**Comment by dbeatty10** [comment]
Closing since `current_db_only` was removed from https://github.com/dbt-labs/dbt-redshift/pull/428 in https://github.com/dbt-labs/dbt-redshift/pull/428/commits/ced9cd100d0721b70a79d3ec80a018a3348011d4
