### ISSUE TITLE
Document `thread_id` context var

### ISSUE THREAD

**Issue by NiallRees** [fishtown-analytics/docs.getdbt.com#3614]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/reference/dbt-jinja-functions

### What changes are you suggesting?

Add page for new thread_id context var https://github.com/dbt-labs/dbt-core/pull/7942

**Comment by dbeatty10** [comment]
The new documentation page for `thread_id` would be similar to [`invocation_id`](https://docs.getdbt.com/reference/dbt-jinja-functions/invocation_id) or [`run_started_at`](https://docs.getdbt.com/reference/dbt-jinja-functions/run_started_at).
