### ISSUE TITLE
Deploy dbt: deployment creation instructions do not match dbt UI

### ISSUE THREAD

**Issue by mbarraco** [fishtown-analytics/docs.getdbt.com#3621]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/quickstarts/snowflake?step=15

### What changes are you suggesting?

The instructions
<img width="1429" alt="image" src="https://github.com/dbt-labs/docs.getdbt.com/assets/8098465/9dbae8da-26d3-4cc2-82fc-1b123202e953">
do not match
<img width="1660" alt="image" src="https://github.com/dbt-labs/docs.getdbt.com/assets/8098465/3fb3ddf0-52cf-4545-aac3-bbbf1d0b0656">

**Comment by mirnawong1** [comment]
great catch @mbarraco ! i've opened pr #3670 to fix this up, appreciate you flagging this!
