### ISSUE TITLE
Add results examples to `dbt retry` page

### ISSUE THREAD

**Issue by matthewshaver** [fishtown-analytics/docs.getdbt.com#3625]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/commands/retry

### What part(s) of the page would you like to see updated?

Add examples of both successful and failed runs for `dbt retry`

**Comment by graciegoheen** [comment]
Hi! While this page shows example logs of retry running, it doesn't actual show the command syntax to use. Could we add some examples of that as well?

cc: @dbeatty10 
relevant to [this](https://github.com/dbt-labs/dbt-core/issues/8948) core bug issue where there's some confusion between `--state` and `--target-path`

**Comment by graciegoheen** [comment]
Like looking at [this](https://docs.getdbt.com/reference/project-configs/target-path) page for `target-path`, I don't see anything for `dbt retry` - is that expected @ChenyuLInx ?

And [this](https://docs.getdbt.com/reference/node-selection/defer) seems to be the only docs for `--state` (the deferral docs) - should we have a separate page for the `--state` flag if it's used by retry and deferral?

**Comment by dbeatty10** [comment]
These are keen insights @graciegoheen 🧠 

Created these new issues as a result:
- https://github.com/dbt-labs/docs.getdbt.com/issues/4916
- https://github.com/dbt-labs/dbt-core/issues/9575
- https://github.com/dbt-labs/docs.getdbt.com/issues/4917

@graciegoheen Is there anything else that isn't covered? I'm going to close this issue in favor of the ones above.
