### ISSUE TITLE
#2691

### ISSUE THREAD

**Issue by moltar** [fishtown-analytics/docs.getdbt.com#3639]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/global-configs/warnings

[website/docs/reference/global-configs/warnings.md](https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/reference/global-configs/warnings.md?plain=1)

### What part(s) of the page would you like to see updated?

Page could use some cleanup:

## Seems like a typo

https://github.com/dbt-labs/docs.getdbt.com/blob/9dd5d184677b6b85b45b58d9c50027a64267a19e/website/docs/reference/global-configs/warnings.md?plain=1#L46

## Not a valid JSON array

https://github.com/dbt-labs/docs.getdbt.com/blob/9dd5d184677b6b85b45b58d9c50027a64267a19e/website/docs/reference/global-configs/warnings.md?plain=1#L35

Should be:

```
["NoNodesForSelectionCriteria"]
```

## Invalid config name

> Turning on the `WARN_ERROR` config

This capitalized string is neither a config nor a env var. All env vars begin with `DBT_`.

And config options are `snake_cased`.

### Additional information

Added in PR #2691

**Comment by runleonarun** [comment]
Thanks for opening this issue and providing so much context! We really appreciate it. I've triaged this issue and we will get to it when we can. You are always welcome to open a PR if you'd like to see these changes sooner. 🙇🏻‍♀️

**Comment by dbeatty10** [comment]
Opened this PR to address the points you raised @moltar -- wanna give it a look?
https://github.com/dbt-labs/docs.getdbt.com/pull/3648

The only thing I didn't take action was the following comment since that is just the way we refer to [global configs](https://docs.getdbt.com/reference/global-configs/about-global-configs) throughout our documentation.

> Turning on the `WARN_ERROR` config
