### ISSUE TITLE
dbt-duckdb ADLS profiles.yml examples

### ISSUE THREAD

**Issue by MarkrJames** [fishtown-analytics/docs.getdbt.com#3642]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/core/connect-data-platform/duckdb-setup

### What part(s) of the page would you like to see updated?

Would it please be possible to provide an example of a dbt-duckdb profile.yml used to connect to ADLS

The accompanying table would be useful:

Configuration option | Description | Type | Example
-- | -- | -- | --

**Comment by runleonarun** [comment]
Thank you for opening this issue! The Docs team would love to provide an example profile.yml for ADLS <> dbt-duckdb, but this is not high priority at this time. If we can't get to this in the next quarter, we will close it out. 

In the meantime, I will mark it with a `Hackathon` label in case someone in the community wants to provide this information!

**Comment by dbeatty10** [comment]
@MarkrJames like @runleonarun mentioned we'd love it if a community member (maybe you!) would be wiling to submit a pull request for this.

It looks like this thread (which I'm guessing you kicked off) is the best (only?) source on the topic currently:
https://getdbt.slack.com/archives/C039D1J1LA2/p1688030917860639

Here's the easiest way to open a PR, if you're interested:
1. Click [here](https://github.com/dbt-labs/docs.getdbt.com/edit/current/website/docs/docs/core/connect-data-platform/duckdb-setup.md) to go into editing mode
1. Make your additions
1. Click the "Commit changes" button

**Comment by runleonarun** [comment]
Closing this, but feel free to re-open if you have an example for duckdb & ADLS!
