### ISSUE TITLE
dbt with Microsoft Fabric: a love story

### ISSUE THREAD

**Issue by sdebruyn** [fishtown-analytics/docs.getdbt.com#3657]
### Contact Details

Sam Debruyn on Slack / sam@dataroots.io

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

This blog post would be about how dbt has entered the Microsoft SQL ecosystem with SQL Server, Azure SQL, Azure Synapse and Microsoft Fabric. As maintainer for all the dbt adapters for Microsoft SQL products, I'd like to write the story about how dbt can embrace and help Microsoft SQL users to bringing clarity into their solutions.

### Link to an initial outline.

I gave a talk about this at the [Data Platform Next Step](https://dataplatformnextstep.com/) conference. Description [here](https://sessionize.com/s/sam-debruyn/dbt-fabric-better-together/73316) and slides [here](https://docs.google.com/presentation/d/1qtxF7dnW4p0f4ANVtvdU1Pyf-WCFegmCWdp4E9hKLyk/edit?usp=sharing).

**Comment by sdebruyn** [comment]
Idea of an outline:

# dbt with Microsoft Fabric: a love story

## Breaking into new worlds with dbt-sqlserver

A few paragraphs about how having dbt instead of stored procedures just makes life a lot easier and how this is groundbreaking for the typically closed Microsoft ecosystem (vs. the open source world).
Talking about the history of the dbt-sqlserver adapter (Mikael's work).

## Building more adapters: dbt-synapse

A few paragraphs about how Microsoft's SQL ecosystem grew with Synapse and how Anders made dbt there available as well. Focus here is to talk about the system of adapter inheritance.

## The maintenance of a dbt adapter

A few paragraphs about what it entails to maintain a dbt adapter. Focus here is to talk about the things we did to make adapter maintenance easier with linting and CI etc. and what we have to do to keep the adapters up to date (dbt versions and automated testing).

## When it all comes together

A few paragraphs about how Microsoft stepped in and how we are now working together to make dbt a first-class citizen in the Microsoft data ecosystem. We can also talk about Fabric fully embraces OSS and why dbt fits well into that picture.

**Comment by runleonarun** [comment]
Hello @sdebruyn! Thanks for submitting this idea! I will consult with the team to see if you should move forward with this post. 

cc @jasnonaz

**Comment by nghi-ly** [comment]
Thank you so much for creating this issue, @sdebruyn ! 

The docs team has reviewed this blog post request and, at present,  there are no plans for it. Adding the `icebox` label in case we can revisit this request later and closing issue.
