### ISSUE TITLE
`dbt debug --connection`

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#3725]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/commands/debug

### What part(s) of the page would you like to see updated?

Use the `--connection` flag to test _just_ the connection

### Additional information

- https://github.com/dbt-labs/dbt-core/issues/7104
- https://github.com/dbt-labs/dbt-core/pull/7741

**Comment by mirnawong1** [comment]
@jtcohen6 i just want to make sure i understand this, do i have to replace `dbt debug` with `dbt debug --connection` to test just the connection? and is this for ALL versions or just for 1.6 and higher?

**Comment by jtcohen6** [comment]
@mirnawong1
- `dbt debug` (no flags) works the same as always, and it tests everything: your DWH connection, plus the validity of your project file and your installation of any requisite dependencies (namely `git` for running `dbt deps`)
- You can specify `dbt debug --connection` (with the added flag) to skip those other checks, and _just_ test the connection to the DWH given a profile
- This new capability (`--connection` flag) is for just v1.6+

**Comment by mirnawong1** [comment]
gotcha thanks! have updated my pr 🙏 https://github.com/dbt-labs/docs.getdbt.com/pull/3731
