### ISSUE TITLE
Incremental model unique key - not so unique

### ISSUE THREAD

**Issue by mike-6383** [fishtown-analytics/docs.getdbt.com#3747]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

[https://docs.getdbt.com/docs/build/incremental-models#defining-a-unique-key-optional](https://docs.getdbt.com/docs/build/incremental-models#defining-a-unique-key-optional)

### What part(s) of the page would you like to see updated?

Here's the original text (with added emphasis):

> Please note that if there's a unique_key with more than one row in either the existing target table or the new incremental rows, **the incremental model run will fail**. Your database and [incremental strategy](https://docs.getdbt.com/docs/build/incremental-models#about-incremental_strategy) will determine the specific error that you see, so if you're having issues running an incremental model, it's a good idea to double check that the unique key is truly unique in both your existing database table and your new incremental rows. You can [learn more about surrogate keys here](https://docs.getdbt.com/terms/surrogate-key).

This is confusing, if not wrong. Depending on the incremental strategy the run will not fail. For instance, a delete+insert strategy on Snowflake will run successfully when the unique_key on target and source is not unique. (In fact, it's useful in some scenarios).

Something like the below would be better:
> Please note that if there's a unique_key with more than one row in either the existing target table or the new incremental rows, the incremental model may fail depending on your database and [incremental strategy](https://docs.getdbt.com/docs/build/incremental-models#about-incremental_strategy). If you're having issues running an incremental model, it's a good idea to double check that the unique key is truly unique in both your existing database table and your new incremental rows. You can [learn more about surrogate keys here](https://docs.getdbt.com/terms/surrogate-key).

**Comment by matthewshaver** [comment]
Changes were made. Closing issue. Thank you!
