### ISSUE TITLE
Clarify selection via the `@` operator

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#3755]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/node-selection/graph-operators#the-at-operator

### What part(s) of the page would you like to see updated?

Per @jtcohen6 [here](https://github.com/dbt-labs/dbt-core/issues/7703#issuecomment-1632166085):
> there's an opportunity to freshen up our docs on `@`

### Problem

It's not clear how many levels ancestors (or descendants) get included by each of `@` and `+`. e.g., Is it only 1st-level parents? Or all ancestors? Or something in between?

#### More context

Question from @foundinblank in https://github.com/dbt-labs/dbt-core/issues/7703#issuecomment-1611126164:

> One thing I've never actually been sure about is the current implementation of `@changed_model` - ["the parents of the children"](https://docs.getdbt.com/reference/node-selection/graph-operators#the-at-operator) - does "the parents" mean only first-order parents or all (great)(grand)parents? This could be clarified with a small change to the documentation. 

Answer:

> The order of operations for resolving the `@` operator: _first_ we select the children, and _second_ we select their parents.

### Solution

We should clarify what we mean by parent/child. We might want to use terminology like [ancestor/descendant](https://en.wikipedia.org/wiki/Tree_(data_structure)#Terminology) instead. We'll want the documentation to be clear how many layers of ancestors (or descendants) get included.

I think the answer is:
- If placed at the front of the model selector, `+` will select all ~parents~ upstream ancestors of the selected model (depth=∞).
- If placed at the end of the string, `+` will select all ~children~ downstream descendants of the selected model (depth=∞).
- However, the depth of both ancestors and descendants can be specified explicitly via the ["n-plus" operator](https://docs.getdbt.com/reference/node-selection/graph-operators#the-n-plus-operator) (depth=n)
- For the `@` operator (which can only be placed at the front of the model selector), will select all the ~parents~ upstream ancestors of the ~children~ downstream descendants of the selected model (depth=∞).
- There is no way to control the depth for the `@` operator (but https://github.com/dbt-labs/dbt-core/issues/7703 would change that).

**Comment by foundinblank** [comment]
I think that's a great start, @dbeatty10! 

I was going to point out that dbt docs uses parent/child so using ancestor/descendant would be a terminology shift for them and that we might need signoff from dbt Labs' technical writers (if they have any?). _Then_ I saw the [Set Operators doc](https://docs.getdbt.com/reference/node-selection/set-operators#intersections) and it uses ancestor/descendant too so probably no issue here. 

Building on the modified description for the @ operator, how's this? 

- For the `@` operator (which can only be placed at the front of the model selector), it will select all downstream descendants of the selected model (depth=∞), and also select all ancestors of those descendant models (depth=∞).

**Comment by martanthony** [comment]
Came here to +1 the ancestor/descendant terminology – the 'all parents/all children' semantics are definitely misleading. If I have two children, and one of those children goes on to have two children of their own, I don't now have four children (I have two children and two grandchildren) but I do have four descendants.

**Comment by dbeatty10** [comment]
Thanks for the nudge @martanthony !

Based on feedback from you and @foundinblank, raised this PR to update the language: https://github.com/dbt-labs/docs.getdbt.com/pull/5313
