### ISSUE TITLE
Add docs for the GitLab integration

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/docs.getdbt.com#378]
The landing page for these docs should live at:

https://docs.getdbt.com/docs/dbt-cloud/configuration/connecting-gitlab

Let's use this as an opportunity to fix up the existing URL scheme (and add redirects). The current scheme would have this page living at https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-installing-the-github-application

**Comment by runleonarun** [comment]
✅ We have these now: https://docs.getdbt.com/docs/collaborate/git/connect-gitlab
