### ISSUE TITLE
Adding PEM key option for Snowflake auth

### ISSUE THREAD

**Issue by jschenz-chwy** [fishtown-analytics/docs.getdbt.com#3787]
### Contributions

- [ ] I am a PM or subject matter expert at dbt who is responsible for this feature.

### Where does this content belong?

The new content belongs in this section: https://docs.getdbt.com/docs/core/connect-data-platform/snowflake-setup#key-pair-authentication

This change is connected to [this pr](https://github.com/dbt-labs/dbt-snowflake/pull/671).

The PR adds the option of using a plain-text private key in PEM format.  The change for the documentation should reflect that option.

### Link to source material

I have an open PR to address this change: https://github.com/dbt-labs/docs.getdbt.com/pull/3786

**Comment by matthewshaver** [comment]
Closing as this has since been added to the docs. Thank you!
