### ISSUE TITLE
Run an automated, routine maintenance task to find bad links

### ISSUE THREAD

**Issue by alison985** [fishtown-analytics/docs.getdbt.com#3792]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

#3791 demonstrates that `databases.md` had a link that was a)not referring to the correct directory and b) not updated when, presumably, `models` changed to `sql-models` to support `python-models`.

### What changes are you suggesting?

There are a number of ways to handle bad links within a website. One is updating all links to a page when you change the page name. One is aliasing pages so multiple names resolve to one page. One is .htaccess redirects. The benefit of 302 redirects in a `.htaccess` file, or similar, is that links outside your control will still resolve to where they were intended instead of giving a page not found error.

### Additional information

Bad links have been discussed previously in https://github.com/dbt-labs/docs.getdbt.com/issues/379, https://github.com/dbt-labs/docs.getdbt.com/issues/2258, and https://github.com/dbt-labs/docs.getdbt.com/issues/1287. I'm saying pick a way to automate it and do the automation.

Bonus for looking in your logs for what pages aren't found by a visitor that are _not_ linked to within the site itself. Then redirect them as well.

**Comment by matthewshaver** [comment]
Thank you @alison985 We do run periodic link checks over existing docs (and have PR link checks), but will look into something more automated
