### ISSUE TITLE
model access groups - unfinished sentence

### ISSUE THREAD

**Issue by ben-marengo-msmg** [fishtown-analytics/docs.getdbt.com#3793]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/docs/collaborate/govern/model-access.md?plain=1#L32

### What changes are you suggesting?

> Models can be grouped under a common designation with a shared owner. For example, you could group together all models owned by a particular team, related to modeling a specific data source (github), or

the sentence is unfinished

**Comment by mirnawong1** [comment]
thanks for opening this issue up @ben-marengo-msmg and [this pr](https://github.com/dbt-labs/docs.getdbt.com/pull/3918)  fixed this issue so i'll go ahead and close this. ✨
