### ISSUE TITLE
Add IAM Authentication to dbt-postgres

### ISSUE THREAD

**Issue by christopherscholz** [fishtown-analytics/docs.getdbt.com#3798]
### Contributions

- [ ] I am a PM or subject matter expert at dbt who is responsible for this feature.

### Where does this content belong?

The new content belongs in this section: https://docs.getdbt.com/docs/core/connect-data-platform/postgres-setup#profile-configuration

This change is connected to https://github.com/dbt-labs/dbt-core/pull/8187.

The PR adds the option of using IAM Authentication for dbt. The change for the documentation should reflect that option.

### Link to source material

I have an open PR to address this change: #3799

**Comment by runleonarun** [comment]
Hello @christopherscholz and thanks for opening the PR associated with this!

**Comment by runleonarun** [comment]
_This issue is not prioritized so adding to 1.8 for us to investigate later. Currently not prioritized in Core repo_

**Comment by mirnawong1** [comment]
The attached issue in the Core repo was closed on April 10th (due to the decoupling of adapters). There was not a new one attached so closing this issue and adding an icebox label if we need to revisit/reopen this.
