### ISSUE TITLE
Common question: schema names 

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/docs.getdbt.com#380]
We get questions about schema names _all the time_ in dbt Slack, along the lines of "I used the schema config but I didn't get the schema name I expected"

Evidently our docs aren't doing a great job here (or dbt isn't doing a great job here 😅 )

Not sure on the exact solution here, but probably time to revisit the current docs

Another idea would be to add a new article "Debugging schema names" which has steps like:
1. Do you have a macro named `generate_schema_name`?
2. What's the name of your target and your target schema?
3. Does the generated schema name now make sense?

**Comment by runleonarun** [comment]
Fixed with this article https://docs.getdbt.com/guides/legacy/debugging-schema-names
