### ISSUE TITLE
Updating the builtin `ref`/`source` functions is most likely different in dbt 1.5+

### ISSUE THREAD

**Issue by b-per** [fishtown-analytics/docs.getdbt.com#3802]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/dbt-jinja-functions/builtins

### What part(s) of the page would you like to see updated?

The page provide examples on how to update the `ref` command but it doesn't support:
- cross project ref (coming in 1.6)
- model versions (from 1.5)

I have not tried it but I think that those 2 features would not work if someone copy pasted the code example in their project.

We should have separate code snippets for `<=1.4`, `1.5` and `>=1.6`

**Comment by mirnawong1** [comment]
asked in core support slack for confirmation and more info
