### ISSUE TITLE
Remove references to materialized views in dbt-bigquery

### ISSUE THREAD

**Issue by mikealfare** [fishtown-analytics/docs.getdbt.com#3812]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-configs/bigquery-configs#materialized-view

### What part(s) of the page would you like to see updated?

dbt-bigquery will not support materialized views in v1.6. We will release this functionality early in the v1.7 lifecycle, likely in v1.7.0b1. We need to remove references to materialized view support for dbt-bigquery in the docs.

**Comment by dataders** [comment]
resolved by: #3779
