### ISSUE TITLE
Materialized Views Touch Ups

### ISSUE THREAD

**Issue by mikealfare** [fishtown-analytics/docs.getdbt.com#3818]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-configs/postgres-configs#materialized-view
https://docs.getdbt.com/reference/resource-configs/redshift-configs#materialized-view
https://docs.getdbt.com/reference/resource-configs/snowflake-configs

### What part(s) of the page would you like to see updated?

# dbt-postgres

- `on_configuration_change` no longer has a value of `skip`, it was renamed to `continue` since `skip` already means something else in a very similar context
  - the `skip` bullet should be updated to `continue` and we should avoid the use of the word skipped
  - the key differentiation is that downstream models will still execute despite this model not running
- `indexes` is an adapter-specific supported configuration; they work just like `indexes` on tables

# dbt-redshift

- similar to `dbt-postgres`, `skip` should be updated to `on_configuration_change`
- `auto_refresh` is a new configuration specific to materialized views in `dbt-redshift`
  - it should be called out as a new configuration just like `on_configuration_change`; it's a boolean with default of `False` and corresponds to `autorefresh` on a Redshift materialized view
  - should it be included in the example code snippet?
- `backup`, `sort`, `sort_type`, and `dist` are supported configurations; they work just like their counterparts on tables

# dbt-snowflake

- similar to `dbt-postgres`, `skip` should be updated to `on_configuration_change`
- `downstream` is not currently supported for `target_lag`
- `warehouse` should be `snowflake_warehouse`, which is an existing configuration that was reused for dynamic tables

**Comment by amychen1776** [comment]
I agree with `auto_refresh` being part of the code snippet for dbt-redshift. It's more user friendly this way.

In terms of Snowflake - we are following up with the patch pretty early on so I think it's okay to include on the docs with an *. Let's make sure to have a code snippet that includes in the on_configuration_change values that work.

**Comment by mikealfare** [comment]
> we are following up with the patch pretty early on

The patch is ready for [review](https://github.com/dbt-labs/dbt-snowflake/pull/708). I anticipate getting it into the release without a patch.

> Let's make sure to have a code snippet that includes in the on_configuration_change values that work.

The values of `on_configuration_change` are all the same. The attributes that can make use of this are `target_lag` and `snowflake_warehouse`.

**Comment by dataders** [comment]
@mikealfare can you edit the above issue to reflect what isn't addressed in #3779?

**Comment by mikealfare** [comment]
@dataders I updated the description to reflect the work from #3779. I also submitted a review of that PR that overlaps a bit with the information above. The biggest change is the update to `dbt-snowflake`. Now this is basically down to `on_configuration_change=='continue'` and mentioning supported adapter-specific parameters.

**Comment by mikealfare** [comment]
The docs that appear [here](https://docs.getdbt.com/reference/resource-configs/redshift-configs) don't have any of the changes in the write-up above. We're getting [bug reports](https://github.com/dbt-labs/dbt-redshift/issues/565) from users that dbt is not working according to the docs.

**Comment by mikealfare** [comment]
This is no longer necessary to be re-opened. I've submitted a separate PR to correct the docs.
