### ISSUE TITLE
Provide more context to Snowflake Permissions page

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#3824]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Per [slack thread](https://dbt-labs.slack.com/archives/C02NCQ9483C/p1690468010848079), the [Snowflake permissions page](https://docs.getdbt.com/reference/snowflake-permissions) has no context or info around it.  

[Discourse page](https://discourse.getdbt.com/t/setting-up-snowflake-the-exact-grant-statements-we-run/439) has more info around this than the docs, which seems reverse. 

We should add contextual info, as a minimum, on this page. 

### What part(s) of the page would you like to see updated?

https://docs.getdbt.com/reference/snowflake-permissions

**Comment by runleonarun** [comment]
Here's the [original PR](https://github.com/dbt-labs/docs.getdbt.com/pull/1992) that added the permission page.
