### ISSUE TITLE
Broken link "Defining metrics" on docs page for "Metrics"

### ISSUE THREAD

**Issue by bbrewington** [fishtown-analytics/docs.getdbt.com#3826]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/docs/build/metrics

### What changes are you suggesting?

Fix broken link to: https://docs.getdbt.com/docs/build/build-semantic-layer-intro

### Additional information

Here's permalink to LOC creating that link - https://github.com/dbt-labs/docs.getdbt.com/blob/188d3d55309f5850603776691a9eff0e9c10ce58/website/docs/docs/build/metrics.md?plain=1#L22

**Comment by runleonarun** [comment]
Hello Brent! Thanks so much for letting us know. We are releasing [a PR](https://github.com/dbt-labs/docs.getdbt.com/pull/3705) that will fix this next week!
