### ISSUE TITLE
Remove custom Snippets for built-in Docusaurus Partials

### ISSUE THREAD

**Issue by JKarlavige** [fishtown-analytics/docs.getdbt.com#3832]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

Any pages where the `<Snippet>` component is used.

### What changes are you suggesting?

Convert existing snippets in the `website/snippets` directory to built-in partials. The docs team has already begun using partials (files in `website/snippets` which begin with an underscore) to take advantage of built-in functionality Docusaurus offers.

This should be completed to prevent confusion on if snippets or partials should be used. Once the custom snippets are converted, we can remove the custom Snippet component as well.

The expected functionality is nothing should change on the site. The existing snippets should be converted to partials by adding the underscore before the filename, then updating where the snippet component is used to use a partial component instead.

Docusaurus documentation on partials: https://docusaurus.io/docs/markdown-features/react#importing-markdown

**Comment by mirnawong1** [comment]
hey @JKarlavige , just checking if this issue is still needed?

**Comment by JKarlavige** [comment]
Hey @mirnawong1, no I'll close this one out! I'm good with leaving this up to your team whether to use custom snippets vs. built-in partials. Down the road if we notice we're not using custom snippets anymore we can remove the component at that time, but there's no issue with leaving it in place.
