### ISSUE TITLE
Add a link to best practice integration guide on the jdbc page and vice versa (Under Related Docs)

### ISSUE THREAD

**Issue by rpourzand** [fishtown-analytics/docs.getdbt.com#3862]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

At the bottom of the page for additional resources, I would add this: https://docs.getdbt.com/guides/dbt-ecosystem/sl-partner-integration-guide to our jdbc page https://docs.getdbt.com/docs/dbt-cloud-apis/sl-jdbc, and vice versa. 

I would probably recommend adding the integration best practice guide to all of our eventual API pages!

### What part(s) of the page would you like to see updated?

The bottom of the page with "Related Docs"

**Comment by nghi-ly** [comment]
thanks for filing this, @rpourzand ! 

took a look at those pages. 

- totally agree with you about the JDBC API page. 
- the guide already includes multiple links to the JDBC page. to prevent link overload, we try not to link out to the same page many times

![Screenshot 2023-08-04 at 3 59 22 PM](https://github.com/dbt-labs/docs.getdbt.com/assets/107218380/518df549-09f6-4f07-902d-de221e109bc7)

**Comment by nghi-ly** [comment]
updated API in PR #3863

**Comment by nghi-ly** [comment]
Fixed.
