### ISSUE TITLE
Add more warehouses to Database Permissions section within references

### ISSUE THREAD

**Issue by agnes-kiss** [fishtown-analytics/docs.getdbt.com#3901]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/snowflake-permissions
https://docs.getdbt.com/faqs/warehouse/database-privileges

### What part(s) of the page would you like to see updated?

It would be great to list more warehouses by adding more pages under `Database permissions`, currently only Snowflake is listed. It would enable dbt users to quickly get access to the list of most useful / necessary grants needed. 

There is also a [FAQ](https://docs.getdbt.com/faqs/warehouse/database-privileges) on database privileges where once this is done we can just link those pages so the user can easily navigate there depending the warehouse they are using.

I am happy to contribute to this, if needed.

**Comment by runleonarun** [comment]
Hello @agnessnowplow We'd love it if you can contribute to this work!

Here's a similar issue about the snowflake permissions page that's requesting we provide more context in that page.. https://github.com/dbt-labs/docs.getdbt.com/issues/3824
