### ISSUE TITLE
Staging Models and Limiting View Runs Guidance

### ISSUE THREAD

**Issue by brian-gillet** [fishtown-analytics/docs.getdbt.com#3929]
### Contact Details

brian.gillet@dbtlabs.com

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [ ] I am a dbt Community member or partner contributing to the Developer Blog
- [X] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

This post is targeted at dbt Cloud users who are questioning the usefulness of dbt Labs' staging models best practices and who want to understand what their options are for excluding views from runs to not be counted as part of their successfully built models count. 

### Link to an initial outline.

https://docs.google.com/document/d/1VBbvY9QgJjbukZOwPw3Z9QXCMzdT9j-IHuLjJgeWgTg/edit#heading=h.bv96nr9vvw6m

**Comment by runleonarun** [comment]
This is such a great idea @brian-gillet! Let me know how the product docs team can support you.

**Comment by nghi-ly** [comment]
Closing issue. Looks like the blog is published: 

https://www.getdbt.com/blog/staging-models-best-practices-and-limiting-view-runs
