### ISSUE TITLE
Add Explanation of Quoting Rules for Jinja

### ISSUE THREAD

**Issue by VersusFacit** [fishtown-analytics/docs.getdbt.com#393]
Not a day goes by, I feel like I don't see or hear of someone struggling with the arcane rules of quotation marks in writing macros. I strongly advocate, for this reason and speaking from personal experience, that adding a short guide would be a helpful addition.

In particular, I'd like to see quotation mark rules, including those with backslash escaping, added.

**Comment by runleonarun** [comment]
Hi @VersusFacit I was wondering if you can list the jinja quoting rules that you'd like to see in the docs so we can add them? Or you can provide us a resource we can link to from the docs (this would be ideal!)

**Comment by runleonarun** [comment]
Closing this and adding to icebox. We will defrost when we have time to address.
