### ISSUE TITLE
Improve Docs around Statements

### ISSUE THREAD

**Issue by VersusFacit** [fishtown-analytics/docs.getdbt.com#394]
The docs around running statements are currently under populated, I feel like. I was trying to answer a question of someone earlier in the Slack and realized we didn't clear document how statements are called. I'd like to 'beef those up' some.

I feel like a dig into the source code would be beneficial but it would require a bit more time on this issue than a simple add a few sentences. I'd like to have a similar level of documentation as for 'run query'

**Comment by runleonarun** [comment]
Hey Mila! I'm closing this issue as outdated. If you feel this is pretty important, then let me know and we'll get a new issue opened with more context.
