### ISSUE TITLE
Metachar Dictionary

### ISSUE THREAD

**Issue by VersusFacit** [fishtown-analytics/docs.getdbt.com#395]
Little syntax markers like `+` are a frequent source of headaches for people. I want to fix that if possible by providing a central page with links to elsewhere in the documentation for each notable metachars within dbt projects. Without it, I feel it's much too hard to search for the docs around these symbols.

Incidentally, when I asked if people in slack would want something like that, I got a very engaged response in the form of heart eye emoji.

**Comment by clrcrl** [comment]
Check out issue #381 and PR #390 which is a first attempt. I think I had meant to tag you on it, but somehow missed it 😅

**Comment by runleonarun** [comment]
Closing as addressed. If we want to add more, we can open a new Docs projects for this in our internal Notion page.
