### ISSUE TITLE
Remove how to install with Homebrew instructions

### ISSUE THREAD

**Issue by martynydbt** [fishtown-analytics/docs.getdbt.com#3951]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/docs/core/installation-overview.md

### What part(s) of the page would you like to see updated?

Should we remove the Homebrew instructions?

**Comment by runleonarun** [comment]
We removed the recommendation for Homebrew instructions in this PR: https://github.com/dbt-labs/docs.getdbt.com/pull/3484 so I'm going to close this issue. 

Teresa, let me know or re-open if you disagree!
