### ISSUE TITLE
Explain dbt's development and production designations more explicitly

### ISSUE THREAD

**Issue by VersusFacit** [fishtown-analytics/docs.getdbt.com#396]
Maybe this is my problem coming from a software engineering background, but I'd like to make clearer what we mean by 'dev' and 'prod' with regards to dbt. It's unclear and I think because of the influence of those terms in tech, there are assumptions people can sometimes make that we should voice aren't necessarily true. A little explanation here should be all that's necessary.

**Comment by runleonarun** [comment]
We attempt to explain the envs here: https://next.docs.getdbt.com/docs/collaborate/environments/dbt-cloud-environments#types-of-environments

Closing this old issue, but feel free to reopen or open a new one if you feel like it's still missing something.
