### ISSUE TITLE
Missing docs for resource types + general configs

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#3964]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

See below.

### What part(s) of the page would you like to see updated?

There is a many-to-many relationship between resource types and general configs. Each resource type has its own docs page as does each general config. These pages should refer to each other both(!) directions when a general config is applicable to a particular resource type.

The ✅ below is when a link exists in at least one direction, and the ☑️ are when something is linked one direction, but not the other.

⚠️ The tables below **only** point out where there is internal inconsistency; it does **not** highlight any potential instances where existing links are incorrect or utterly incomplete.

### Look at it one direction

The ☑️ below indicate that a general config page (like [`enabled`](https://docs.getdbt.com/reference/resource-configs/enabled) contains an example for a resource type (like `metrics`), but the config page for the resource type is missing a similar example.

|              | [models](https://docs.getdbt.com/reference/model-configs#general-configurations) | [seeds](https://docs.getdbt.com/reference/seed-configs#general-configurations) | [snapshots](https://docs.getdbt.com/reference/snapshot-configs#general-configurations) | [tests](https://docs.getdbt.com/reference/test-configs#general-configurations) | [sources](https://docs.getdbt.com/reference/source-configs#general-configurations) | [analyses](https://docs.getdbt.com/reference/analysis-properties) | [exposures](https://docs.getdbt.com/reference/exposure-properties) | [macros](https://docs.getdbt.com/reference/macro-properties) | metrics |
|--------------|--------|-------|-----------|-------|---------|----------|-----------|--------|---------|
| [enabled](https://docs.getdbt.com/reference/resource-configs/enabled)      |    ✅   |   ✅   |     ✅     |   ✅   |    ✅    |          |     ✅     |        |    ☑️    |
| [tags](https://docs.getdbt.com/reference/resource-configs/tags)         |    ✅   |   ✅   |     ✅     |   ✅   |         |     ✅    |           |        |         |
| [pre-hook](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook)     |    ✅   |   ✅   |     ✅     |       |         |          |           |        |         |
| [pre-hook](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook)    |    ✅   |   ✅   |     ✅     |       |         |          |           |        |         |
| [database](https://docs.getdbt.com/reference/resource-configs/database)     |    ✅   |   ✅   |           |   ✅   |         |          |           |        |         |
| [schema](https://docs.getdbt.com/reference/resource-properties/schema)       |    ✅   |   ✅   |           |   ✅   |    ☑️    |          |           |        |         |
| [alias](https://docs.getdbt.com/reference/resource-configs/alias)        |    ✅   |   ✅   |     ✅     |   ✅   |         |          |           |        |         |
| [persist_docs](https://docs.getdbt.com/reference/resource-configs/persist_docs) |    ✅   |   ✅   |     ✅     |       |    ☑️    |          |           |        |         |
| [full_refresh](https://docs.getdbt.com/reference/resource-configs/full_refresh) |    ✅   |   ✅   |           |       |         |          |           |        |         |
| [meta](https://docs.getdbt.com/reference/resource-configs/meta)         |    ✅   |   ✅   |     ☑️     |   ✅   |    ☑️    |     ☑️    |           |    ☑️   |         |
| [grants](https://docs.getdbt.com/reference/resource-configs/grants)       |    ✅   |   ✅   |     ✅     |       |         |          |           |        |         |
| [contract](https://docs.getdbt.com/reference/resource-configs/contract)     |    ✅   |       |           |       |         |          |           |        |         |

### Look at it the other direction

The ☑️ below indicate that a resource type page (like [`analyses`](https://docs.getdbt.com/reference/analysis-properties)) contains an example for a general config (like [`tags`](https://docs.getdbt.com/reference/resource-configs/tags), but the page for the general config is missing a similar example.

|              | [models](https://docs.getdbt.com/reference/model-configs#general-configurations) | [seeds](https://docs.getdbt.com/reference/seed-configs#general-configurations) | [snapshots](https://docs.getdbt.com/reference/snapshot-configs#general-configurations) | [tests](https://docs.getdbt.com/reference/test-configs#general-configurations) | [sources](https://docs.getdbt.com/reference/source-configs#general-configurations) | [analyses](https://docs.getdbt.com/reference/analysis-properties) | [exposures](https://docs.getdbt.com/reference/exposure-properties) | [macros](https://docs.getdbt.com/reference/macro-properties) | metrics |
|--------------|--------|-------|-----------|-------|---------|----------|-----------|--------|---------|
| [enabled](https://docs.getdbt.com/reference/resource-configs/enabled)      |    ✅   |   ✅   |     ✅     |   ✅   |    ✅    |          |     ✅     |        |    ✅    |
| [tags](https://docs.getdbt.com/reference/resource-configs/tags)         |    ✅   |   ✅   |     ✅     |   ☑️   |         |     ☑️    |           |        |         |
| [pre-hook](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook)     |    ✅   |   ✅   |     ✅     |       |         |          |           |        |         |
| [pre-hook](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook)    |    ✅   |   ✅   |     ✅     |       |         |          |           |        |         |
| [database](https://docs.getdbt.com/reference/resource-configs/database)     |    ☑️   |   ✅   |           |   ☑️   |         |          |           |        |         |
| [schema](https://docs.getdbt.com/reference/resource-properties/schema)       |    ☑️   |   ☑️   |           |   ☑️   |    ✅    |          |           |        |         |
| [alias](https://docs.getdbt.com/reference/resource-configs/alias)        |    ☑️   |   ✅   |     ☑️     |   ☑️   |         |          |           |        |         |
| [persist_docs](https://docs.getdbt.com/reference/resource-configs/persist_docs) |    ✅   |   ✅   |     ✅     |       |    ✅    |          |           |        |         |
| [full_refresh](https://docs.getdbt.com/reference/resource-configs/full_refresh) |    ✅   |   ✅   |           |       |         |          |           |        |         |
| [meta](https://docs.getdbt.com/reference/resource-configs/meta)         |    ✅   |   ✅   |     ✅     |   ✅   |    ✅    |     ✅    |           |    ✅   |         |
| [grants](https://docs.getdbt.com/reference/resource-configs/grants)       |    ✅   |   ✅   |     ✅     |       |         |          |           |        |         |
| [contract](https://docs.getdbt.com/reference/resource-configs/contract)     |    ✅   |       |           |       |         |          |           |        |         |

**Comment by runleonarun** [comment]
This is such a helpful way of looking at it Doug!

**Comment by mirnawong1** [comment]
Mirna to hardcode table

**Comment by dbeatty10** [comment]
Note: these tables are just showing the docs pages that currently exist (or not) -- they are **not** necessarily fully showing the which configs are available for each resource type. But creating such a table could be helpful too!

**Comment by mirnawong1** [comment]
hey @dbeatty10 , i've dug into this a little bit and if I'm not mistaken, it looks like the following docs need adding so they link to each other. however, there are some resources where it's either not supported or under the 'properties' page:

#### action needed
- schema -> source = need to add link to [source properties](https://docs.getdbt.com/reference/source-properties) example)
-  meta - macros  = need to add link to meta on [this page](https://docs.getdbt.com/reference/macro-properties)
- meta -> snapshots = add link to [snapshot properties](https://docs.getdbt.com/reference/snapshot-properties) in meta page for meta value
- meta -> sources = add link to [sources properties](https://docs.getdbt.com/reference/source-properties) in meta page for meta value.

#### no action needed
- persist docs - source = [not supported](https://docs.getdbt.com/reference/resource-configs/persist_docs) so seems like no linking is needed
- meta - analyses = The meta config is [not currently supported](https://docs.getdbt.com/reference/resource-configs/meta) for analyses. so seems like no linking is needed

**Comment by mirnawong1** [comment]
hey @dbeatty10 just wanted to follow up on this as a quick nudge 🙏
