### ISSUE TITLE
Add more info for "What version of Python can I use?" for adapters & core

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#3978]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/faqs/core/install-python-compatibility

### What part(s) of the page would you like to see updated?

While this answers "What version of Python can I use?" for the latest version of `dbt-core`, it doesn't provide much guidance for previous versions or for adapters. 

That information should be available on the pypi page for each release - [example for dbt-bigquery 1.5.4](https://pypi.org/project/dbt-bigquery/1.5.4/). 

![Screenshot 2023-08-25 at 18 33 52](https://github.com/dbt-labs/docs.getdbt.com/assets/53586774/9c18a638-3117-48a0-8d93-13e2a510bf1d)

Let's connect these two in some way - maybe as simple as adding something like "to see which versions of python are compatible with your specific version of dbt-core and dbt adapters, check out the relevant pypi page"

**Comment by runleonarun** [comment]
@graciegoheen I feel like this has been addressed in this page:
https://docs.getdbt.com/faqs/core/install-python-compatibility

Feel free to re-open if you think it could use more info.
