### ISSUE TITLE
window - can't be used with window

### ISSUE THREAD

**Issue by wanalytics8** [fishtown-analytics/docs.getdbt.com#3981]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/docs/build/metrics-overview

### What changes are you suggesting?

"The accumulation window, such as 1 month, 7 days, 1 year. This can't be used with window."

I think this is not correct, window can't be used with window? Or please explain, thanks!

**Comment by runleonarun** [comment]
Thanks for catching this typo @wanalytics8 ! Fix proposed in https://github.com/dbt-labs/docs.getdbt.com/pull/3982
