### ISSUE TITLE
docs website does not load due to potentially malicious js

### ISSUE THREAD

**Issue by sinia** [fishtown-analytics/docs.getdbt.com#3983]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

All docs pages are affected.

https://docs.getdbt.com/ or any other urls under this domain do not load properly on our enterprise network as, according to our security team, "it is blocked by the firewall as it contains malicious URLs: d33wubrfki0l68.cloudfront.net".

I have looked into this on my end, it seems the the following two .js files fail to be loaded which results in a very malformed website:
https://d33wubrfki0l68.cloudfront.net/bundles/d791b6693c16c1841df84779b9b34e5f51a8490a.js
https://d33wubrfki0l68.cloudfront.net/bundles/c260198a05b2bd9b7de3d9ec5ff2478a6c9f44c2.js

When I run one of the files through https://www.virustotal.com/ it is flagged as Malware by "Xcitium Verdict Cloud"
https://www.virustotal.com/gui/url/bf7b7978c35c0752409b2254a0313274615b7d32d219c51fe63d519362a8f661?nocache=1

Even if it is a false positive, would it be possible to do something so that it is not flagged as such?

### What changes are you suggesting?

Change js assets, how they are served etc so that those are not flagged as malicious.

**Comment by mirnawong1** [comment]
hey @sinia , thanks for raising this issue and I'll share this with our team internally. can you share a screenshot of what happens when you try to access the https://docs.getdbt.com/?

**Comment by sinia** [comment]
A browser screenshot demonstrating the issue (with web console open showing failed js loads):
![image](https://github.com/dbt-labs/docs.getdbt.com/assets/4824267/d9008650-34bb-4d2a-ba00-ee52440d4921)

**Comment by mirnawong1** [comment]
Hey @sinia , thanks for sharing that. I've shared this with our front end team and they will look into this on their end. Just to confirm, you're only experiencing this on the docs.getdbt.com site right? not on any dbt-related site?

I'll revert back when I have more info for you. appreciate you flagging this to us!

**Comment by sinia** [comment]
> Hey @sinia , thanks for sharing that. I've shared this with our front end team and they will look into this on their end. Just to confirm, you're only experiencing this on the docs.getdbt.com site right? not on any dbt-related site?
> 
> I'll revert back when I have more info for you. appreciate you flagging this to us!

Yes, only on docs.getdbt.com site.

**Comment by mirnawong1** [comment]
Hi @sinia , apologies for the delay here. The frontend team has asked me to check the following with you:

- It's pretty typical for webhosts to store assets like this on CDNs like Cloudfront. Could you check with your IT department and see what they suggest for cases like this?
- Is JS turned off entirely? This could be in your browser, or at the network level, by IT. 
- Are you using any sort of adblocker? (AdBlock Plus, uBlock Origin, etc)

cc @lfracalossiFA

**Comment by mirnawong1** [comment]
hey @sinia ! are you still having issues? If not, I'll go ahead and close this out for you but please let us know if you're still seeing odd behavior. I'm more than happy to re-open this issue up for you, thank you!

**Comment by sinia** [comment]
The issue was resolved, thanks.
