### ISSUE TITLE
Update recommended syntax for `--select` with unions + intersections on CLI

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#4040]
<p><a href="https://www.notion.so/dbtlabs/Prod-Docs-Beta-Cloud-CLI-Oct-9th-a389341b7c1f45e2b7c162e4de591d90?d=2b3208f1ff8c49698fde7b3946b86e91">Docs project</a></p>

### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/node-selection/set-operators
https://docs.getdbt.com/reference/commands/list

(I'm sure there are _many_ more pages)

### What part(s) of the page would you like to see updated?

To conform to [POSIX standards](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html), and for better readability, we should strongly encourage CLI users to quote unions/intersections passed to "multi-option" params. Unquoted may not work consistently across all operating systems, terminals, and product experiences.

This is mainly relevant for `--select` and `--exclude`.

So instead of:
```
$ dbt run --select +snowplow_sessions +fct_orders
$ dbt run --select +snowplow_sessions,+fct_orders
$ dbt run --select stg_invoices+,stg_accounts+
```

It should be:
```
$ dbt run --select "+snowplow_sessions +fct_orders"
$ dbt run --select "+snowplow_sessions,+fct_orders"
$ dbt run --select "stg_invoices+,stg_accounts+"
```

It is also relevant for the `--output-keys` param to `dbt list`. So instead of
```
$ dbt ls --select snowplow.* --output json --output-keys name resource_type description
```
It should be:
```
$ dbt ls --select snowplow.* --output json --output-keys "name resource_type description"
```

### Additional information

[internal notion doc](https://www.notion.so/dbtlabs/Utility-Syntax-Conventions-29dcd5659888467c83c8c257886064a1)

**Comment by mirnawong1** [comment]
hey @jtcohen6 , would `dbt run --select state:modified` need to have "state:modified" quoted? (and exposures too?)

**Comment by jtcohen6** [comment]
@mirnawong1 This is only required when there are **multiple** space-delimited or comma-delimited arguments being passed to `--select` or `--exclude`

So it's not strictly necessary for `--select state:modified` (only one argument). But `--select "state:modified"` works too — so we could just say "always quote" :)

**Comment by mirnawong1** [comment]
sounds like a good, consistent plan. thanks for clarifying @jtcohen6 !
