### ISSUE TITLE
All CLI flags should be passed after subcommand

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#4041]
[Docs project](https://www.notion.so/dbtlabs/Prod-Docs-Beta-Cloud-CLI-Oct-9th-a389341b7c1f45e2b7c162e4de591d90?d=2b3208f1ff8c49698fde7b3946b86e91)

### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/global-configs/command-line-flags

### What part(s) of the page would you like to see updated?

For better consistency, all flags should be passed after the subcommand.
```
dbt run --no-populate-cache
```

This includes "global" flags (supported for all commands) that have historically been passed before the subcommand:
```
dbt --no-populate-cache run
```

We could continue supporting the latter for backward compatibility, but make clear that it is legacy/deprecated functionality and liable to be removed in the future. It is not supported to pass the same flag before "before" and "after."

This should be much easier for everyone, as it doesn't require remembering which flags are "global" or "not global," and which ones are supported in _both_ places for legacy reasons.

### Additional information

Blocked by:
- https://github.com/dbt-labs/dbt-core/issues/6497

**Comment by mirnawong1** [comment]
@jtcohen6 , confirming this is no longer blocked by dev, right?

**Comment by jtcohen6** [comment]
@mirnawong1 Correct! Thanks for being on top of it :)

Most of this has been updated in `main` / for dbt Core v1.7. The only outstanding things here are:
- Three flags that we still need to figure out how to support: https://github.com/dbt-labs/dbt-core/issues/8715
- Backporting this to dbt Core v1.5 + v1.6:
    - https://github.com/dbt-labs/dbt-core/pull/8734
    - https://github.com/dbt-labs/dbt-core/pull/8732

**Comment by mirnawong1** [comment]
still monitoring this @jtcohen6 and @aranke - are the flags`p.warn_error`, `p.warn_error_options`, and `p.log_format` still pending support?

so far this is how i've shaped the doc for this page:
![Screenshot 2023-10-06 at 13 56 31](https://github.com/dbt-labs/docs.getdbt.com/assets/89008547/dd02a957-e680-458e-bb56-10a7f06b075b)

**Comment by mirnawong1** [comment]
Hey @jtcohen6 @aranke ! Looks like the 3 flags are still being worked on so I'm going to leave them out until the docs team is informed otherwise 🙏
