### ISSUE TITLE
Request to Update Twitter Icon to X 

### ISSUE THREAD

**Issue by lalitkumawat1m** [fishtown-analytics/docs.getdbt.com#4055]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

Footer Section

### Screenshot

<img width="960" alt="Screenshot 2023-09-10 082344" src="https://github.com/dbt-labs/docs.getdbt.com/assets/91591901/d7fc5384-d8d7-46ed-b4e8-57ca2a7430ac">

### What changes are you suggesting?

Twitter logo should be changed to X

### Additional information

@mirnawong1 @KiraFuruichi 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by mirnawong1** [comment]
hey @lalitkumawat1m , that sounds awesome and thanks so much for tackling this on 💪! I've assigned it to you and let me know if you have any questions on this!

**Comment by lalitkumawat1m** [comment]
Hey @mirnawong1, I'm facing an issue while setting up locally 

How to resolve it ?
<img width="960" alt="Screenshot 2023-09-12 061903" src="https://github.com/dbt-labs/docs.getdbt.com/assets/91591901/97113369-9d65-4500-8282-82aa56081f8a">

**Comment by mirnawong1** [comment]
hey @lalitkumawat1m sorry to hear you're having this issue! what step are you unable to complete in terms of setting up locally?
