### ISSUE TITLE
Update pages related to adapters for new adapters

### ISSUE THREAD

**Issue by alison985** [fishtown-analytics/docs.getdbt.com#4060]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/community-adapters

### What part(s) of the page would you like to see updated?

One example is that the new Microsoft adapters aren't listed. There may be others.

**Comment by mirnawong1** [comment]
thanks for opening this up @alison985 ! I'm going to loop in @dataders for some insight here. Anders, please let me now if we can help with this!

**Comment by mirnawong1** [comment]
we've reworked the adapters pages and have two categories of adapters: 'trusted' and 'community'. the  Microsoft adapters are listed under 'trusted adapters': https://docs.getdbt.com/docs/trusted-adapters.

closing this issue as it's been addressed, however let me know if you feel it hasn't and we'll re-open it up. thank you, Alison!
