### ISSUE TITLE
Simplify core versions table

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#4063]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Per discussion [here](https://github.com/dbt-labs/docs.getdbt.com/pull/4047) with @dbeatty10 , we should simplify the core versions table (and possibly automate it) in the future to have less manual maintenance. 

## first proposal (Mirna's)

combining both upcoming releases and latest release table. there's still some manual updates but at least it's updating once. 
one thing i was trying to do was see if i can add a dynamic badge that displays the release date but i can't seem to do it other than it being static. but it would be cool to have a badge that can automatically reflect the release date (and maybe even release status) [Microsoft does this similarly](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule)

![Screenshot 2023-09-08 at 13 01 21](https://github.com/dbt-labs/docs.getdbt.com/assets/89008547/a5a90722-eddb-4aac-b1eb-d8dddf7d9d96)

the reason i sugg the unified table approach is because in the future, we'd have to update all 3 tables when a version changes. another reason is - what makes an 'unsupported version' unsupported? 1.0-1.2 are still available in dbt cloud and i think it's confusing to say they're 'unsupported' when they're still available in cloud. [see slack thread](https://dbt-labs.slack.com/archives/C0131TY7EEA/p1683054263740429) for context on orgs upgrading.

## second proposal (Doug's)

From the perspective of a human trying to visually read the information, I'm also most attracted to three separate tables.

From the perspective of trying to ingest this data into a database table (or trying to keep thing in sync when updating 😉), then I'd prefer one unified table.

So my preference is something like this:

### Planned future releases

_Future release dates are tentative and subject to change._

| dbt Core                                                   | Initial Release | Support Level | Critical Support Until  | 
|------------------------------------------------------------|-----------------|----------------|-------------------------|
|  **v1.9**                                               | _Apr 2024_ |       | _Apr 2025_            | 
|  **v1.8**                                               | _Jan 2024_ |       | _Jan 2025_            | 
|  **v1.7**                                               | _Oct 2023_ |       | _Oct 2024_            | 

### Supported Versions

| dbt Core                                                   | Initial Release | Support Level | Critical Support Until  | 
|------------------------------------------------------------|-----------------|----------------|-------------------------|
| [**v1.6**](/guides/migration/versions/upgrading-to-v1.6)   | Jul 31, 2023    | Active         | Jul 30, 2024            |
| [**v1.5**](/guides/migration/versions/upgrading-to-v1.5)   | Apr 27, 2023    | Critical       | Apr 27, 2024            | 
| [**v1.4**](/guides/migration/versions/upgrading-to-v1.4)   | Jan 25, 2023    | Critical       | Jan 25, 2024            | 
| [**v1.3**](/guides/migration/versions/upgrading-to-v1.3)   | Oct 12, 2022    | Critical       | Oct 12, 2023            | 

### Unsupported Versions

| dbt Core                                                   | Initial Release | Support Level | Critical Support Until  | 
|------------------------------------------------------------|-----------------|----------------|-------------------------|
| [**v1.2**](/guides/migration/versions/upgrading-to-v1.2)   | Jul 26, 2022    | End of Life* | Jul 26, 2023            |
| [**v1.1**](/guides/migration/versions/upgrading-to-v1.1) | Apr 28, 2022    | End of Life* | Apr 28, 2023            | 
| [**v1.0**](/guides/migration/versions/upgrading-to-v1.0) | Dec 3, 2021     | End of Life* | Dec 3, 2022           | 
|  **v0.X**                                               | (Various dates) | Deprecated  | Deprecated            | 

_*All versions of dbt Core since v1.0 are available in dbt Cloud until further notice. Versions that are EOL do not receive any fixes. For the best support, we recommend upgrading to a version released within the past 12 months._

## Summary

I don't have strong feeling on the table placement, row ordering, or table format of the "planned future releases". But my eye and brain does prefer it to be visually separated from the "supported" and "unsupported" releases.

The emojis were a little intense for me (and they shouldn't be necessary with separate tables), so I dropped them above so we can see how it looks and feels.

### What part(s) of the page would you like to see updated?

https://docs.getdbt.com/docs/dbt-versions/core

**Comment by matthewshaver** [comment]
Assigned to myself. Have an upcoming meeting with Grace on the product team to revamp this and potentially remove the future versions based on proprietary core

**Comment by matthewshaver** [comment]
Assigned to myself. Have an upcoming meeting with Grace on the product team to revamp this and potentially remove the future versions
