### ISSUE TITLE
Add more info about the host value on the "Starburst/Trino setup" oage

### ISSUE THREAD

**Issue by b-per** [fishtown-analytics/docs.getdbt.com#4079]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/core/connect-data-platform/trino-setup

### What part(s) of the page would you like to see updated?

Under "Host parameters", `host` contains the info

host | mycluster.mydomain.com | The hostname of your cluster.Don't include the http:// or https:// prefix.
-- | -- | --

I personally struggled a bit to connect dbt to Starburst Galaxy because the URL of Starburst Galaxy is *not* the host. The host contains information about the cluster as well and not only the URL used to access Starburst Galaxy.

I managed to get the correct host by checking "partner connect" in Starburst Galaxy but I couldn't have guessed it otherwise

![image](https://github.com/dbt-labs/docs.getdbt.com/assets/8754100/74326c52-164b-4d28-b31f-8822e1f18c6b)

**Comment by mirnawong1** [comment]
hey @damian3031 @findinpath - wanted to ask if you had any insight on this so we can clarify further? thank you in advance!

**Comment by damian3031** [comment]
I agree that it would be useful to include an example with a host specific to Starburst Galaxy. I have added one in the PR https://github.com/dbt-labs/docs.getdbt.com/pull/6571
