### ISSUE TITLE
Databricks configurations - table broken

### ISSUE THREAD

**Issue by leo-schick** [fishtown-analytics/docs.getdbt.com#4099]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

Site: https://docs.getdbt.com/reference/resource-configs/databricks-configs

![image](https://github.com/dbt-labs/docs.getdbt.com/assets/67712864/2aa2a393-7605-4b4b-98ee-980246659b3d)

### What changes are you suggesting?

fix the table. Issue exists since 1.6+

**Comment by mirnawong1** [comment]
Hey @leo-schick thanks for flagging this, we really appreciate it! I opened up this pr here https://github.com/dbt-labs/docs.getdbt.com/pull/4098 which addresses this issue so the page/table should be rendering correctly now.

I'll go ahead and close this issue but give us a shout if there are any issues. Appreciate your contribution ✨
