### ISSUE TITLE
Example snippets should work when copy pasted into zsh

### ISSUE THREAD

**Issue by RoiTabach** [fishtown-analytics/docs.getdbt.com#4100]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Web page:
https://docs.getdbt.com/reference/node-selection/test-selection-examples?indirect-selection-mode=buildable#syntax-examples

GitHub link:
https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/reference/node-selection/test-selection-examples.md#L273

### What part(s) of the page would you like to see updated?

When copy pasting a command with an asterix, like dbt test --exclude source:*,  the behavior of zshell would be to expand the asterix. 

If the snippet would have included quotes around the source:* part, `dbt test --exclude 'source:*'` this would have worked right away when people reading the docs page copy paste it.

That's clearly not the only place in the docs with the same issue, I'd be happy to search for more if this is approved

I think it's different than issue #4040 

### Additional information

Raised in slack at least once here

https://getdbt.slack.com/archives/C2JRRQDTL/p1695064369322449?thread_ts=1695064369.322449&cid=C2JRRQDTL

**Comment by mirnawong1** [comment]
hey @RoiTabach thanks so much for opening this up and it looks like a great issue. i worked on #4040 and it sounds like it might have addressed what you raised -- are there any other pages where you find a similar issue?

**Comment by mirnawong1** [comment]
hey @RoiTabach , happy to look into this further for you. before I do though, i wanted to double check if you're still seeing or experiencing this issue?

**Comment by mirnawong1** [comment]
Closing this as we addressed it here that quotes are needed: https://docs.getdbt.com/reference/node-selection/syntax#specifying-resources

however, please do reopen this up if we think it needs addressing!
