### ISSUE TITLE
Help more people find the running CI jobs using bitbucket topic

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#4105]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/guides/orchestration/custom-cicd-pipelines/4-dbt-cloud-job-on-pr

### What part(s) of the page would you like to see updated?

* Request: update the Algolia weight about running CI jobs when using bitbucket?

The current issue is that searching for “bitbucket pr” or “bitbucket ci” returns many links from a Dev Blog article about dbt-core (screenshot 1), which is not relevant for dbt Cloud users, and we have to scroll all the way down to get the info for dbt Cloud (screenshot 2)

Here's the conversation about [weighting search terms](https://dbt-labs.slack.com/archives/C02NCQ9483C/p1692979653610069).

## Open questions
* We need to be careful about "weighting" topics because it could lead to a tangled mess
* Should we add bitbucket to the title?
* Do we need the one tab for Bitbucket? Is the tab not beign searched because it's not a "real" heading?

**Comment by mirnawong1** [comment]
resolved https://github.com/dbt-labs/docs.getdbt.com/pull/5994
