### ISSUE TITLE
Update the 1.7 migration guide

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#4123]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.7

### What part(s) of the page would you like to see updated?

We need to update this for what's going to be released in 1.7

### Additional information

@graciegoheen -> to add what content needs to go onto this page

**Comment by dataders** [comment]
Hi Grace, when you do this, do you mind linking to https://github.com/dbt-labs/dbt-core/discussions/8307? as we have done in previous upgrade guides? Something like the below?


> ### For maintainers of adapter plugins
> 
> For more detailed information and to ask questions, please read and comment on the GH discussion: [dbt-labs/dbt-core#8307](https://github.com/dbt-labs/dbt-core/discussions/8307).

**Comment by graciegoheen** [comment]
## For consumers of dbt artifacts (metadata)

The [manifest](https://docs.getdbt.com/reference/artifacts/manifest-json) schema version has been updated to v11. Specific changes:
- ???

@dbeatty10 do you know what the manifest schema changes were? The [PR that bumped the version](https://github.com/dbt-labs/dbt-core/pull/8335) didn't seem to make any other changes.

The [run_results](https://docs.getdbt.com/reference/artifacts/run-results-json) schema version has been updated to v5. Specific changes:
- Add node attributes related to compilation (`compiled`, `compiled_code`, `relation_name`)

The nodes dictionary in the `catalog.json` can now be "partial" if `dbt docs generate` is run with a selector.

**Comment by graciegoheen** [comment]
## New and changed documentation

### dbt docs generate now supports `--select` to generate documentation for a subset of your project
- currently snowflake and postgres only, but other adapters on their way

### source freshness can now be generated from warehouse metadata tables
- currently snowflake only, but other adapters that have metadata tables on their way
-  if you configure source freshness without a `loaded_at_field`, dbt will try to determine freshness from warehouse metadata tables
- expands the amount of sources folks can configure freshness for; previously, limited to sources that had a `loaded_at_field`

### MetricFlow enhancements
- automatically create metrics on measures, `create_metric: true`
- optional `label` in semantic_models, measures, dimensions and
  entities
- new configurations for semantic models - enable/disable, group, meta
- support `fill_nulls_with` and `join_to_timespine` for metric nodes
- `saved_queries` extend governance beyond the semantic objects to their consumption

### Quick hits

- configure a `delimiter` for a seed file
- allow setting `access` as a config
- support packages with same git repo and unique subdirectory
- move `date_spine` macro from dbt-utils to dbt-core

**Comment by graciegoheen** [comment]
Outstanding: 
- What are the known "Behavior changes"? 
- Anything else to highlight for "Multi-project collaboration" initiative? @jtcohen6 
- What are manifest changes to highlight?

**Comment by graciegoheen** [comment]
Behavior change:

Full information here -> https://github.com/dbt-labs/dbt-core/issues/8704#issuecomment-1753905285

[Previously](https://docs.getdbt.com/docs/build/sources#snapshotting-source-data-freshness:~:text=Additionally%2C%20the%20loaded_at_field%20is%20required%20to%20calculate%20freshness%20for%20a%20table.%20If%20a%20loaded_at_field%20is%20not%20provided%2C%20then%20dbt%20will%20not%20calculate%20freshness%20for%20the%20table.) -> "the loaded_at_field is required to calculate freshness for a table. If a loaded_at_field is not provided, then dbt will not calculate freshness for the table."

In 1.7 -> when you add a freshness: config to a source (and no loaded_at_field is provided), we will calculate freshness for that source via warehouse metadata tables when the warehouse supports it

**Comment by dataders** [comment]
@graciegoheen here's a [1.7 adapter upgrade guide snippet about dbt show](https://gist.github.com/dataders/0977e4948220d56ecc1fea941e5d6fab). My brain feels as though it's something worth calling out in the end user 1.7 guide, but perhaps not because this change just happened for all users of 1.5 and 1.6 as well? Do we this new behavior called out? Ok for the answer to be no, provided that we only ever rever to the new behavior. That said, I don't see any reference in the [doc for dbt show](https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/reference/commands/show.md) that mentions this new behavior

**Comment by dbeatty10** [comment]
> That said, I don't see any reference in the [doc for dbt show](https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/reference/commands/show.md) that mentions this new behavior

@dataders  I just opened an issue for this here: https://github.com/dbt-labs/docs.getdbt.com/issues/4256

I don't know the way you want to update the docs for [`show`](https://docs.getdbt.com/reference/commands/show), so I'm relying on you to update this docs issue as-needed.
