### ISSUE TITLE
Move Core migration guides to dbt-versions directory

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#4171]
### Contributions

- [x] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

These guides can be moved to a directory under `https://docs.getdbt.com/docs/dbt-versions/*`

https://docs.getdbt.com/guides/migration/versions/Older%20versions/upgrading-to-0-11-0
https://docs.getdbt.com/guides/migration/versions/Older%20versions/upgrading-to-0-12-0
https://docs.getdbt.com/guides/migration/versions/Older%20versions/upgrading-to-0-13-0
https://docs.getdbt.com/guides/migration/versions/Older%20versions/upgrading-to-0-14-0
https://docs.getdbt.com/guides/migration/versions/Older%20versions/upgrading-to-0-14-1
https://docs.getdbt.com/guides/migration/versions/Older%20versions/upgrading-to-0-15-0
https://docs.getdbt.com/guides/migration/versions/Older%20versions/upgrading-to-0-16-0
https://docs.getdbt.com/guides/migration/versions/Older%20versions/upgrading-to-0-17-0
https://docs.getdbt.com/guides/migration/versions/Older%20versions/upgrading-to-0-18-0
https://docs.getdbt.com/guides/migration/versions/Older%20versions/upgrading-to-0-19-0
https://docs.getdbt.com/guides/migration/versions/upgrading-to-dbt-utils-v1.0
https://docs.getdbt.com/guides/migration/versions/upgrading-to-v0.20
https://docs.getdbt.com/guides/migration/versions/upgrading-to-v0.21
https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.0
https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.1
https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.2
https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.3
https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.4
https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.5
https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.6

### What part(s) of the page would you like to see updated?

- [ ] Move all upgrade guides
- [ ] Possibly create an archive directory to put older ones

**Comment by matthewshaver** [comment]
This was completed in: https://github.com/dbt-labs/docs.getdbt.com/pull/4372
