### ISSUE TITLE
Broken Link? Open a discussion on the Developer Hub

### ISSUE THREAD

**Issue by aiwithwhitehat** [fishtown-analytics/docs.getdbt.com#4178]
### Contributions

- [x] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

[The affected page](https://docs.getdbt.com/community/resources/oss-expectations)

When I click on the link [Open a discussion on the Developer Hub](https://github.com/dbt-labs/docs.getdbt.com/discussions/new), I am directed to the below page:

<img width="1322" alt="Screenshot 2023-10-03 at 7 06 39 PM" src="https://github.com/dbt-labs/docs.getdbt.com/assets/6273915/5c3b7d2e-83a3-4747-8d1b-1cc1f06c9b5f">

It seems like broken.

### What changes are you suggesting?

There are 2 ways to fix this that I can think of:
1. Either put the correct link which takes one to the page to open the discussion
2. If this issue is arising because of some permission issue, then that can be mentioned somewhere on the doc.

**Comment by aiwithwhitehat** [comment]
Change might be required on these 2 lines:
1. https://github.com/dbt-labs/docs.getdbt.com/blob/144f5996045e28f69b77effcbe05b48e8a6121ac/website/docs/community/resources/oss-expectations.md?plain=1#L7
2. https://github.com/dbt-labs/docs.getdbt.com/blob/144f5996045e28f69b77effcbe05b48e8a6121ac/website/docs/community/resources/oss-expectations.md?plain=1#L54

**Comment by mirnawong1** [comment]
hey @anksu2024 , thanks so much for flagging this! I believe [discourse](https://discourse.getdbt.com/) is the right place to open up a discussion, however, i'm double checking this before i make any changes to the page. much appreciated! ✨

**Comment by aiwithwhitehat** [comment]
@mirnawong1 
Are you trying to convey that the [Open a discussion on the Developer Hub](https://github.com/dbt-labs/docs.getdbt.com/discussions/new) is actually expected to redirect to the [Discourse](https://github.com/dbt-labs/docs.getdbt.com/discussions/new) page?

If yes, I can make that change happen marking my first materialized open source Contribution.

**Comment by mirnawong1** [comment]
hey @anksu2024 ! i'm so glad to hear you'd like to make your first contribution ✨! So [this page](https://docs.getdbt.com/community/resources/oss-expectations) (inc the paragraph below and [this section on the page](https://docs.getdbt.com/community/resources/oss-expectations#best-practices-for-issues)) should link to [discourse](https://discourse.getdbt.com/c/discussions/21) to start a discussion. 

you can absolutely [open up a pr](https://github.com/dbt-labs/docs.getdbt.com/edit/current/website/docs/community/resources/oss-expectations.md) and make those changes -- we would really appreciate it!

So it should read something like this: 

>Have you seen things in other OSS projects that you quite like, and think we could learn from? [Open a discussion on the Developer Hub](https://discourse.getdbt.com/c/discussions/21), or start a conversation in the dbt Community Slack (for example: #community-strategy, #dbt-core-development, #package-ecosystem, #adapter-ecosystem). We always appreciate hearing from you!

**Comment by mirnawong1** [comment]
let me know if you need any help at all!

**Comment by aiwithwhitehat** [comment]
Created new PR https://github.com/dbt-labs/docs.getdbt.com/pull/4216

**Comment by aiwithwhitehat** [comment]
Resolved closing the issue
