### ISSUE TITLE
New Tool: Automate Redirect Updates

### ISSUE THREAD

**Issue by VersusFacit** [fishtown-analytics/docs.getdbt.com#421]
We want a make recipe like:
```
# make update_redirects from_path to_path
$ make update_redirects /dbt-cli/installation-guides/windows /dbt-cli/installation
```
Which would:
```
    search the _redirects file for any entries that have the from_path as the target, and replaces it with the to_path
    add a new entry to the _redirects file for the new mapping
```

**Comment by runleonarun** [comment]
The front end eng team is working on optimizing our redirects file. @JKarlavige @wendyvasq Curious if a tool like this would be useful or should I close this issue out?

**Comment by JKarlavige** [comment]
We are planning on removing the Makefile altogether for this repo, as it looks like we no longer need the functionality within it. I'm not 100% sure if that affects this, but i'm assuming a `make recipe` references that.

However, I feel like using a find/replace would be efficient enough for updating old redirects when requested, so I don't feel like this would be needed.

**Comment by runleonarun** [comment]
Thanks Jason! Closing this issue!
