### ISSUE TITLE
Improve seo for terraform dbt cloud repo

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#4210]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

@b-per raised that when googling 'Terraform dbt Cloud', the old community-maintained repo appears in the search as the first result, instead of the active dbt labs-maintained one. 

We should add a link to info on the docs to improve SEO. We should make sure to add wording around the support level offered. 

- [This is](https://github.com/dbt-labs/terraform-provider-dbtcloud) the repo that we own
  - [This is the dbt Labs one](https://registry.terraform.io/providers/dbt-labs/dbtcloud/latest) that's coming up 2nd in the results
- This is [the old community one](https://registry.terraform.io/providers/GtheSheep/dbt-cloud/latest) that's coming up first in google search results

### What part(s) of the page would you like to see updated?

[this page](https://docs.getdbt.com/docs/cloud/about-cloud/tenancy) could be a good place to add it to. @b-per  in case  you have more insight on where it could also live

**Comment by mirnawong1** [comment]
closing this issue as the dbt cloud registry is coming up first now, which means the SEO improved. I've also linked to the terraform doc here: https://github.com/dbt-labs/docs.getdbt.com/pull/5741/files

will go ahead and close this issue, however please let me know if you think otherwise!

**Comment by b-per** [comment]
This one can be closed, yes, but [this one](https://github.com/dbt-labs/docs.getdbt.com/pull/5728) is still relevant to point people to Terraform from our docs.

**Comment by mirnawong1** [comment]
no worries, we've flagged this to the docs team @b-per and i believe @matthewshaver is going to take a look and review your pr! 🙏
