### ISSUE TITLE
[Minor] Correct the order in which the bullet points are displayed in Quickstart Documentation

### ISSUE THREAD

**Issue by aiwithwhitehat** [fishtown-analytics/docs.getdbt.com#4236]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/quickstarts/bigquery?step=15

### Link to the Code: 
https://github.com/dbt-labs/docs.getdbt.com/blob/073804ef92b97087430b15a943e238a7dd6117f4/website/snippets/quickstarts/schedule-a-job.md?plain=1#L29

### In the Quickstart documentation, the bullet points are shown as follows:

<img width="1034" alt="Screenshot 2023-10-09 at 22 14 58" src="https://github.com/dbt-labs/docs.getdbt.com/assets/6273915/e72df70c-6afd-4621-bef4-aab92e71553c">

### Whereas in the dbt Cloud, this is how it is shown:
<img width="1291" alt="Screenshot 2023-10-09 at 22 06 38" src="https://github.com/dbt-labs/docs.getdbt.com/assets/6273915/a9ad55a4-f6f9-466e-a041-1bf14a38579f">

### Additional information

This is a minor change to make the Quickstart instructions easier to follow.

**Comment by mirnawong1** [comment]
closing as addressed here https://github.com/dbt-labs/docs.getdbt.com/pull/4237
