### ISSUE TITLE
column quoting

### ISSUE THREAD

**Issue by alison985** [fishtown-analytics/docs.getdbt.com#4238]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-configs/quote_columns
https://docs.getdbt.com/reference/project-configs/quoting

### What part(s) of the page would you like to see updated?

These two pages need to be linked/reconciled/merged or something.

**Comment by alison985** [comment]
Spoke too soon, there's also this: https://docs.getdbt.com/reference/resource-properties/tests#accepted_values

The problem that made me find all of these is trying to figure out why the dbt-core `accepted_values:` test fails because it's not quoting columns even though I have all the quote settings turned on. I have a hard time believing no one would have caught this before, so I'm trying to find something in the docs before filing a dbt-core bug report.

**Comment by alison985** [comment]
And this one https://docs.getdbt.com/reference/resource-properties/quote

**Comment by dbeatty10** [comment]
See also: https://github.com/dbt-labs/docs.getdbt.com/issues/3518

**Comment by dbeatty10** [comment]
@alison985  Great point that we should link/reconcile/merge/something all these related pages 💡 

I just added the key thing you pointed out about `quote` for `accepted_values` to #3518. If I missed anything, please comment within that issue 🙏

I think we have everything covered in #3518 now, so I'm going to close this one as a duplicate.
