### ISSUE TITLE
Borken img

### ISSUE THREAD

**Issue by ernestoongaro** [fishtown-analytics/docs.getdbt.com#4239]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/guides/orchestration/airflow-and-dbt-cloud/3-running-airflow-and-dbt-cloud

### What changes are you suggesting?

there's a few broken images

![image](https://github.com/dbt-labs/docs.getdbt.com/assets/47784/e3377431-a1ec-4682-ad0a-3caae3b48c66)

**Comment by mirnawong1** [comment]
This is fixed now!
