### ISSUE TITLE
add `docs generate` to the syntax overview page now that we are accepting `--select` for `docs generate`

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#4242]
> @matthewshaver I also think we may want to add docs generate to this [syntax overview page](https://docs.getdbt.com/reference/node-selection/syntax), now that we are accepting `--select` for `docs generate`

![Screenshot 2023-10-10 at 9 47 40 AM](https://github.com/dbt-labs/docs.getdbt.com/assets/53586774/159a7387-0327-4549-839c-532372f264c9)
^do we want to add docs generate as a command in this table?

_Originally posted by @graciegoheen in https://github.com/dbt-labs/docs.getdbt.com/issues/4217#issuecomment-1755725974_

**Comment by graciegoheen** [comment]
Hey @matthewshaver - I think theres a few other selection methods to add for `dbt docs generate`! I know it works with `--exclude`, would need to check for `--selector`. 

Running `dbt docs generate --help` should tell us which selection methods are supported!

**Comment by matthewshaver** [comment]
@graciegoheen Got it! I see `--defer` in there too. I'll add them all
