### ISSUE TITLE
Double-check config syntax for semantic models and metrics

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#4281]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

See below.

### What part(s) of the page would you like to see updated?

Within the description for https://github.com/dbt-labs/docs.getdbt.com/issues/4180, I added some examples of what I _guessed_ the syntax would be, but I didn't specify that these were completely unverified guesses 😬.

So we'll want to double-check if they all work or not and fix them as-needed.

**Comment by dbeatty10** [comment]
@matthewshaver and @graciegoheen This issue can be closed as resolved if these PRs are merged:
- https://github.com/dbt-labs/docs.getdbt.com/pull/4219
- https://github.com/dbt-labs/docs.getdbt.com/pull/4218
- https://github.com/dbt-labs/docs.getdbt.com/pull/4220

**Comment by matthewshaver** [comment]
Merged attached PRs. Thank you Doug!
