### ISSUE TITLE
[Doc Improvement] Updating the latest options that are visible in the BigQuery `Create credentials` setup

### ISSUE THREAD

**Issue by aiwithwhitehat** [fishtown-analytics/docs.getdbt.com#4299]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Git Code Permalink
https://github.com/dbt-labs/docs.getdbt.com/blob/5c40a44b3f5b414be23f813bd108d97dfb38242c/website/docs/quickstarts/bigquery-qs.md?plain=1#L76

Remove the extra line in the Documentation for DBT BigQuery Quickstart

### DBT BigQuery Quickstart Docs
Link: https://docs.getdbt.com/quickstarts/bigquery?step=4#generate-bigquery-credentials

There is no option referring to `No, I’m not using them and click Next` in latest Google BigQuery

<img width="1041" alt="Screenshot 2023-10-17 at 18 42 02" src="https://github.com/dbt-labs/docs.getdbt.com/assets/6273915/ee315a36-1662-484f-a4e7-26a8f6d30ce1">

### BigQuery
<img width="600" alt="Screenshot 2023-10-17 at 18 39 11" src="https://github.com/dbt-labs/docs.getdbt.com/assets/6273915/c87994d1-55fe-4628-908f-f8db620cbecd">

**Comment by aiwithwhitehat** [comment]
Resolution is to just remove the line from the DBT Bigquery Quickstart documentation

**Comment by ankitsarraf-hippo** [comment]
Marking this as closed as the PR was Approved and Deployed.

**Comment by aiwithwhitehat** [comment]
Marking this as closed as it is approved and Deployed.
