### ISSUE TITLE
The `resource-path` configuration applies to many (all?) resource types

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#4313]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-configs/resource-path

### What part(s) of the page would you like to see updated?

The [`resource-path`](https://docs.getdbt.com/reference/resource-configs/resource-path) page only explains how it applies to:
- models
- seeds
- snapshots

But it applies to other [resource types](https://docs.getdbt.com/docs/dbt-cloud-apis/project-state#affected-states-by-node-type) as well:
- tests
- sources
- potentially others

### The problem

https://github.com/dbt-labs/dbt-core/issues/8876 specifically mentioned that they were expecting this section to apply to `tests` also:

> The `<resource-path>` nomenclature is used in this documentation when documenting how to configure a model, seed, or snapshot, from your `dbt_project.yml` file. It represents the nested dictionary keys that provide the path to either a directory of models, or a single model.

The "info" section is also relevant:

> This example is for models, but the same concepts apply for seeds and snapshots.

But these sections only explain three node types and don't cover the other ones.

### Potential solution

The key insight is that it should be something like this instead:

> It represents the nested dictionary keys that provide the path to a directory of that resource type, or a single instance of that resource type by name.

e.g.

```yaml
<resource type>:
  <project name>:
    <directory name>:
      <subdirectory name>:
        <instance of resource type (by name)>:
          ...
```

### Related issues
- https://github.com/dbt-labs/dbt-core/issues/8876
- https://github.com/dbt-labs/dbt-core/issues/8960

**Comment by mirnawong1** [comment]
hey @dbeatty10 ! thank you for this, I've created a [PR here ](https://github.com/dbt-labs/docs.getdbt.com/pull/4394/files#diff-4caaf3187919c98f42856c140e32964b0829fc19165f3c989a6cd4ea088a7164) which addresses the above and also other items such as this [this core issue](https://github.com/dbt-labs/dbt-core/issues/8960)
