### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by alison985** [fishtown-analytics/docs.getdbt.com#4330]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/faqs/Snapshots/snapshot-schema-changes

### What part(s) of the page would you like to see updated?

https://docs.getdbt.com/faqs/Snapshots/snapshot-schema-changes is just a copy of information on https://docs.getdbt.com/docs/build/snapshots.

[https://docs.getdbt.com/docs/build/snapshots dp](https://docs.getdbt.com/faqs/Snapshots/snapshot-schema-changes) doesn't event link back to any other Snapshot page. I would think you'd want to permanently redirect this page to the longer snapshot page to avoid the duplication.

**Comment by matthewshaver** [comment]
Thanks, @alison985. One is an FAQ page. These sometimes have the same information as the articles, but we're enhancing and moving them soon, so this will no longer be an issue. We appreciate it!
