### ISSUE TITLE
update planned future releases

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#4333]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/dbt-versions/core#planned-future-releases

<img width="675" alt="Screenshot 2023-10-25 at 1 24 20 PM" src="https://github.com/dbt-labs/docs.getdbt.com/assets/53586774/fc4f3ba1-d806-4609-abb6-6e356cc2a860">

<img width="751" alt="Screenshot 2023-10-25 at 1 25 04 PM" src="https://github.com/dbt-labs/docs.getdbt.com/assets/53586774/de1963fe-b3ac-4809-b52f-6864bfd328b4">

### What part(s) of the page would you like to see updated?

Since 1.7 has now been released (or an initial release), we can remove it from the "planned future releases" table

We're also moving the 1.7 final release by a week (to November 2nd) - so we should update that date as well in the "latest releases" table

**Comment by matthewshaver** [comment]
Addressed as part of https://github.com/dbt-labs/docs.getdbt.com/pull/4373
