### ISSUE TITLE
Table of global configs (user configs, env var, and cli flag)

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#4366]
### Proposed solution

It would be awesome if there were dense table of all the [global configs](https://docs.getdbt.com/reference/global-configs/about-global-configs) and their associated [user configs](https://docs.getdbt.com/reference/global-configs/yaml-configurations), [environment variables](https://docs.getdbt.com/reference/global-configs/environment-variable-configs), and [CLI flags](https://docs.getdbt.com/reference/global-configs/command-line-flags).

Maybe like this (the content of which I have **only partially** verified):

| YAML User Config                                                                                               | Full Environment Variable                                                                                                                | Command Line Flag                                                                                                                      |
|----------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| [send_anonymous_usage_stats](https://docs.getdbt.com/reference/global-configs/usage-stats)                     | [DBT_SEND_ANONYMOUS_USAGE_STATS](https://docs.getdbt.com/reference/global-configs/usage-stats)                                           | [--send-anonymous-usage-stats](https://docs.getdbt.com/reference/global-configs/usage-stats)                                           |
| [use_colors](https://docs.getdbt.com/reference/global-configs/print-output#print-color)                        | [DBT_USE_COLORS](https://docs.getdbt.com/reference/global-configs/print-output#print-color)                                              | [--use-colors](https://docs.getdbt.com/reference/global-configs/print-output#print-color)                                              |
| [use_colors_file](https://docs.getdbt.com/reference/global-configs/logs#color)                                 | [DBT_USE_COLORS_FILE](https://docs.getdbt.com/reference/global-configs/logs#color)                                                       | [--use-colors-file](https://docs.getdbt.com/reference/global-configs/logs#color)                                                       |
| [partial_parse](https://docs.getdbt.com/reference/global-configs/parsing#partial-parsing)                      | [DBT_PARTIAL_PARSE](https://docs.getdbt.com/reference/global-configs/parsing#partial-parsing)                                            | [--partial-parse](https://docs.getdbt.com/reference/global-configs/parsing#partial-parsing)                                            |
| [write_json](https://docs.getdbt.com/reference/global-configs/json-artifacts)                                  | [DBT_WRITE_JSON](https://docs.getdbt.com/reference/global-configs/json-artifacts)                                                        | [--write-json](https://docs.getdbt.com/reference/global-configs/json-artifacts)                                                        |
| [warn_error](https://docs.getdbt.com/reference/global-configs/warnings)                                        | [DBT_WARN_ERROR](https://docs.getdbt.com/reference/global-configs/warnings)                                                              | [--warn-error](https://docs.getdbt.com/reference/global-configs/warnings)                                                              |
| [debug](https://docs.getdbt.com/reference/global-configs/logs#debug-level-logging)                             | [DBT_DEBUG](https://docs.getdbt.com/reference/global-configs/logs#debug-level-logging)                                                   | [--debug](https://docs.getdbt.com/reference/global-configs/logs#debug-level-logging)                                                   |
| [version_check](https://docs.getdbt.com/reference/global-configs/version-compatibility)                        | [DBT_VERSION_CHECK](https://docs.getdbt.com/reference/global-configs/version-compatibility)                                              | [--version-check](https://docs.getdbt.com/reference/global-configs/version-compatibility)                                              |
| [fail_fast](https://docs.getdbt.com/reference/global-configs/failing-fast)                                     | [DBT_FAIL_FAST](https://docs.getdbt.com/reference/global-configs/failing-fast)                                                           | [--fail-fast](https://docs.getdbt.com/reference/global-configs/failing-fast)                                                           |
| [use_experimental_parser](https://docs.getdbt.com/reference/global-configs/parsing#experimental-parser)        | [DBT_USE_EXPERIMENTAL_PARSER](https://docs.getdbt.com/reference/global-configs/parsing#experimental-parser)                              | [--use-experimental-parser](https://docs.getdbt.com/reference/global-configs/parsing#experimental-parser)                              |
| [static_parser](https://docs.getdbt.com/reference/global-configs/parsing#static-parser)                        | [DBT_STATIC_PARSER](https://docs.getdbt.com/reference/global-configs/parsing#static-parser)                                              | [--static-parser](https://docs.getdbt.com/reference/global-configs/parsing#static-parser)                                              |
| [printer_width](https://docs.getdbt.com/reference/global-configs/print-output#printer-width)                   | [DBT_PRINTER_WIDTH](https://docs.getdbt.com/reference/global-configs/print-output#printer-width)                                         | [--printer-width](https://docs.getdbt.com/reference/global-configs/print-output#printer-width)                                         |
| [log_format](https://docs.getdbt.com/reference/global-configs/logs#log-formatting)                             | [DBT_LOG_FORMAT](https://docs.getdbt.com/reference/global-configs/logs#log-formatting)                                                   | [--log-format](https://docs.getdbt.com/reference/global-configs/logs#log-formatting)                                                   |
| [log_format_file](https://docs.getdbt.com/reference/global-configs/logs#log-formatting)                        | [DBT_LOG_FORMAT_FILE](https://docs.getdbt.com/reference/global-configs/logs#log-formatting)                                              | [--log-format-file](https://docs.getdbt.com/reference/global-configs/logs#log-formatting)                                              |
| [log_level](https://docs.getdbt.com/reference/global-configs/logs#log-level)                                   | [DBT_LOG_LEVEL](https://docs.getdbt.com/reference/global-configs/logs#log-level)                                                         | [--log-level](https://docs.getdbt.com/reference/global-configs/logs#log-level)                                                         |
| [log_level_file](https://docs.getdbt.com/reference/global-configs/logs#log-level)                              | [DBT_LOG_LEVEL_FILE](https://docs.getdbt.com/reference/global-configs/logs#log-level)                                                    | [--log-level-file](https://docs.getdbt.com/reference/global-configs/logs#log-level)                                                    |
| [log_cache_events](https://docs.getdbt.com/reference/global-configs/logs#logging-relational-cache-events)                                                                                               | [DBT_LOG_CACHE_EVENTS](https://docs.getdbt.com/reference/global-configs/logs#logging-relational-cache-events)          | [--log-cache-events](https://docs.getdbt.com/reference/global-configs/logs#logging-relational-cache-events)                    |
| [indirect_selection](https://docs.getdbt.com/reference/node-selection/test-selection-examples#syntax-examples) | [DBT_INDIRECT_SELECTION](https://docs.getdbt.com/reference/node-selection/test-selection-examples#syntax-examples)                       | [--indirect-selection](https://docs.getdbt.com/reference/node-selection/test-selection-examples#syntax-examples)                       |
| [quiet](https://docs.getdbt.com/reference/global-configs/logs#suppress-non-error-logs-in-output)               | [DBT_QUIET](https://docs.getdbt.com/reference/global-configs/logs#suppress-non-error-logs-in-output)                                     | [--quiet](https://docs.getdbt.com/reference/global-configs/logs#suppress-non-error-logs-in-output)                                     |
| [print](https://docs.getdbt.com/reference/global-configs/print-output#suppress-print-messages-in-stdout)       | [DBT_PRINT](https://docs.getdbt.com/reference/global-configs/print-output#suppress-print-messages-in-stdout)                             | [--print](https://docs.getdbt.com/reference/global-configs/print-output#suppress-print-messages-in-stdout)                             |
| [cache_selected_only](https://docs.getdbt.com/reference/global-configs/cache)                                  | [DBT_CACHE_SELECTED_ONLY](https://docs.getdbt.com/reference/global-configs/cache)                                                        | [--cache-selected-only](https://docs.getdbt.com/reference/global-configs/cache)                                                        |
| [populate_cache](https://docs.getdbt.com/reference/global-configs/cache)                                       | [DBT_POPULATE_CACHE](https://docs.getdbt.com/reference/global-configs/cache)                                                             | [--populate-cache](https://docs.getdbt.com/reference/global-configs/cache)                                                             |
| [full_refresh](https://docs.getdbt.com/reference/resource-configs/full_refresh)                                | [DBT_FULL_REFRESH](https://docs.getdbt.com/reference/resource-configs/full_refresh)                                                      | [--full-refresh](https://docs.getdbt.com/reference/resource-configs/full_refresh)                                                      |
| [introspect](https://docs.getdbt.com/reference/commands/compile#introspective-queries)                         | [DBT_INTROSPECT](https://docs.getdbt.com/reference/commands/compile#introspective-queries)                                               | [--introspect](https://docs.getdbt.com/reference/commands/compile#introspective-queries)                                               |
| [store_failures](https://docs.getdbt.com/reference/resource-configs/store_failures)                            | [DBT_STORE_FAILURES](https://docs.getdbt.com/reference/resource-configs/store_failures)                                                  | [--store-failures](https://docs.getdbt.com/reference/resource-configs/store_failures)                                                  |
| [target](https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles#about-profiles)           | DBT_TARGET                                                                                                                               | [--target](https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles#about-profiles)                                 |
| profile                                                                                                        | DBT_PROFILE                                                                                                                              | [--profile](https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml)                                                      |

### Not within `dbt_project.yml`

| YAML User Config                                                                                               | Full Environment Variable                                                                                                                | Command Line Flag                                                                                                                      |
|----------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| N/A                                                                                                            | [DBT_PROJECT_DIR](https://docs.getdbt.com/reference/dbt_project.yml)                                                                     | [--project-dir](https://docs.getdbt.com/reference/dbt_project.yml)                                                                     |
| N/A                                                                                                            | [DBT_PROFILES_DIR](https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles#advanced-customizing-a-profile-directory) | [--profiles-dir](https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles#advanced-customizing-a-profile-directory) |

### Within `dbt_project.yml` as top-level configs instead of under `flags:`

| YAML User Config                                                                                               | Full Environment Variable                                                                                                                | Command Line Flag                                                                                                                      |
|----------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| [target-path](https://docs.getdbt.com/reference/global-configs/logs#log-and-target-paths)                      | [DBT_TARGET_PATH](https://docs.getdbt.com/reference/global-configs/logs#log-and-target-paths)                                            | [--target-path](https://docs.getdbt.com/reference/global-configs/logs#log-and-target-paths)                                            |
| [log-path](https://docs.getdbt.com/reference/global-configs/logs#log-and-target-paths)                         | [DBT_LOG_PATH](https://docs.getdbt.com/reference/global-configs/logs#log-and-target-paths)                                               | [--log-path](https://docs.getdbt.com/reference/global-configs/logs#log-and-target-paths)                                               |

#### Further verification needed

As noted in https://github.com/dbt-labs/docs.getdbt.com/issues/3264, some of the configs listed in the "YAML User Config" column may only work as environment variables and/or CLI flags and might not work within YAML config (like `profiles.yml`).

#### Missing docs

The row for `log_cache_events` above does not have hyperlinks because I didn't see any relevant documentation for this config.

Opened #4664 as a result.

### Problem

The big idea is that there are a lot of [global flags](https://github.com/dbt-labs/dbt-core/blob/a2a7b7d795eb40f743063601375e44a5b72f1b9a/core/dbt/cli/main.py#L123-L152) and/or global configs that can be specified in three different ways (lower takes priority):

1. [user config](https://docs.getdbt.com/reference/global-configs/yaml-configurations)
1. [environment variable](https://docs.getdbt.com/reference/global-configs/environment-variable-configs)
1. [CLI flag](https://docs.getdbt.com/reference/global-configs/command-line-flags)

i.e., if all three are provided, then the CLI flag takes precedence.

But it's not always easy to see what the different options are. In particular, the relevant environment variable is often a guessing game, and the user config name is not always clear either. The CLI flag is the thing that is most consistently included in the documentation and examples, but even that is [not always searchable](https://github.com/dbt-labs/docs.getdbt.com/issues/4365).

### Link to the page on docs.getdbt.com requiring updates

Either this page or some other page:
- https://docs.getdbt.com/reference/global-configs/about-global-configs

### What part(s) of the page would you like to see updated?

See proposed solution above.

### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

**Comment by graciegoheen** [comment]
bump on this! @matthewshaver

**Comment by mirnawong1** [comment]
hey @dbeatty10 , this issue isn't similar to [this one](https://github.com/dbt-labs/docs.getdbt.com/issues/4206), right? i _think_ they are slightly different and if so, I'll keep the other open. if they are the same -- what do you think about consolidating it and i can add my write up in yours as yours is more comprehensive?

**Comment by dbeatty10** [comment]
Yeah similar, but slightly different!

So agreed to keep them both open.

Both of these could easily get stale and out-of-date when changes are made to dbt-core.

[Here](https://github.com/dbt-labs/dbt-core/issues/6840#issuecomment-1646076536) is a script that uses `click` to determine which CLI flags (and environment variables) are relevant to each sub-command.

We could use a script like this to auto-generate the relationship between CLI flags and sub-commands.

I don't think it would cover the relationship between the user config name (for `profiles.yml`) and the CLI flag though.
