### ISSUE TITLE
Semantic manifest artifact

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#4369]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/dbt-cloud-apis/sl-manifest

### What part(s) of the page would you like to see updated?

The docs should have same or similar format as the rest of these artifacts:
- https://docs.getdbt.com/reference/artifacts/manifest-json
- https://docs.getdbt.com/reference/artifacts/run-results-json
- https://docs.getdbt.com/reference/artifacts/catalog-json
- https://docs.getdbt.com/reference/artifacts/sources-json

e.g., it should:
- show up in the "dbt Artifacts" menu [here](https://docs.getdbt.com/reference/artifacts/dbt-artifacts)
- Have a URL like https://docs.getdbt.com/reference/artifacts/semantic-manifest-json
- Have a "**Current schema**:" line
- Have a "**Produced by**:" line
- Heading "Top-level keys" instead of "Top level keys" (in order to match the style of the other artifact pages)

**Comment by mirnawong1** [comment]
hey @Jstein77 and @rpourzand  -- wanted to loop you in on this issue. i'm happy to move the semantic manifest to https://docs.getdbt.com/reference/artifacts/run-results-json for consistency but also wanted to get your insight.

**Comment by mirnawong1** [comment]
hey @Jstein77 and @rpourzand - friendly nudge on this when you have a sec.

**Comment by mirnawong1** [comment]
going to address this this quater

**Comment by MiConnell** [comment]
@mirnawong1 any updates on this? The schema should be added to https://schemas.getdbt.com/ as well

**Comment by mirnawong1** [comment]
hey @MiConnell , thanks for the ping! I'm going to meet with the PMs and will address this after!

**Comment by mirnawong1** [comment]
confirmed and addressing issue

**Comment by mirnawong1** [comment]
hey @joellabes @dave-connors-3 - do you know how we can add the semantic manifest schema to here: https://schemas.getdbt.com/

happy to do it myself but just don't know how to.
