### ISSUE TITLE
Document `model` jinja variable

### ISSUE THREAD

**Issue by drewmcdonald** [fishtown-analytics/docs.getdbt.com#437]
Hello! It would be nice to have a deeper list of variables available in the jinja context. Specifically, I found that the `model` variable is extremely useful but is only mentioned in passing in the docs for the `schema` variable.

Thanks!

**Comment by clrcrl** [comment]
Completely agree here! @VersusFacit — this would be a good one to do in any down time, it's just completely undocumented right now!

**Comment by runleonarun** [comment]
This was added! https://github.com/dbt-labs/docs.getdbt.com/commits/current/website/docs/reference/dbt-jinja-functions/model.md
