### ISSUE TITLE
broken link on https://docs.getdbt.com/reference/project-configs/version

### ISSUE THREAD

**Issue by alison985** [fishtown-analytics/docs.getdbt.com#4376]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/project-configs/version

### What part(s) of the page would you like to see updated?

Link to "documentation" at the bottom goes to "Page Not Found".
![Screenshot 2023-10-31 at 1 19 55 PM](https://github.com/dbt-labs/docs.getdbt.com/assets/1840865/7db8bfbf-7f00-43b3-b56d-c30360125981)

**Comment by alison985** [comment]
Edit: Nevermind, different use of versions. Though it's probably worth adding model versions to the list of version types dbt supports.
-Also missing 1.6 version warning when in 1.4 view. You can see this warning on https://docs.getdbt.com/docs/collaborate/govern/model-versions-

**Comment by mirnawong1** [comment]
hey @alison985 , thanks for opening this up and we've address this 🙌 ! the link was missing the forward slash and I've also consolidated the content to remove the versions so users know that its required for v1.4 or lower, but optional for those on v1.5 and higher. let me know if you have any feedback or questions but this was a great issue!
