### ISSUE TITLE
There is currently no documentation/example on how to run just 1 version of a model with multiple versions

### ISSUE THREAD

**Issue by b-per** [fishtown-analytics/docs.getdbt.com#4382]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/collaborate/govern/model-versions

### What part(s) of the page would you like to see updated?

I have searched across the docs and couldn't find the info I am after. It might be there somewhere, but if it is, it should be added to https://docs.getdbt.com/docs/collaborate/govern/model-versions as well.

If a model has multiple versions, I am quite sure that we can run:

- all versions, with `dbt run -s my_model`
- but also specific versions, with `dbt run -s my_model.v2` for example

This syntax with `.v2` doesn't seem to be anywhere in the docs.

**Comment by mirnawong1** [comment]
confirming syntax in [slack](https://dbt-labs.slack.com/archives/C04MEJT5VPY/p1700153757373539)
