### ISSUE TITLE
Update `group` config for analyses

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#4416]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-configs/group

### What part(s) of the page would you like to see updated?

Do analyses really have a `group` config?! (I wouldn't guess so because [analyses are not ref'able](https://github.com/dbt-labs/dbt-core/issues/7127).)

Depending on the answer, either:
- Remove example for analyses and replace with a message saying it isn't a valid config, or
- Add a <Version> block for analyses to indicate the first version that the `group` was possible

**Comment by mirnawong1** [comment]
have doubled check this [here](https://dbt-labs.slack.com/archives/C017GDLAF7D/p1709221574000329)

**Comment by mirnawong1** [comment]
asked again: https://dbt-labs.slack.com/archives/C017GDLAF7D/p1719827718815479

**Comment by dbeatty10** [comment]
Looks like analyses **do indeed** support the `group` config!

Example `analyses/_properties.yml`:

```yml
groups:
  - name: galois
    owner:
      name: Évariste Galois
      email: galois@jaffle.shop

analyses:
  - name: my_analysis
    group: galois
```

Here's a screenshot from `manifest.json`:

<img width="422" alt="image" src="https://github.com/user-attachments/assets/65632294-322b-4753-9464-2f164bbf75a0">

And here is the result of listing analyses that match this group:

```shell
$ dbt list --select "group:galois" --resource-types analysis -q

my_project.analysis.my_analysis
```

It works back to v1.5:

```shell
$ dbt list --select "group:galois" --resource-types analysis   

22:18:29  Running with dbt=1.5.9
22:18:30  Registered adapter: duckdb=1.5.2
22:18:30  Found 1 model, 0 tests, 0 snapshots, 1 analysis, 323 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 2 groups

my_project.analysis.my_analysis
```
