### ISSUE TITLE
Add semantic-models: config to dbt_project.yml page

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#4436]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/dbt_project.yml

### What part(s) of the page would you like to see updated?

Add the `semantic-models:` config

### Additional information

Until https://github.com/dbt-labs/docs.getdbt.com/issues/3957 is resolved, then there won't be a `[<semantic-model-configs>](https://docs.getdbt.com/reference/semantic-model-configs)` page to link to. It doesn't need to be a prerequisite though -- the hyperlink can be added afterwards.

See also:
- https://github.com/dbt-labs/docs.getdbt.com/issues/4441

**Comment by matthewshaver** [comment]
Thread with context for this issue https://dbt-labs.slack.com/archives/C05LRDBSCNL/p1699645088331809
