### ISSUE TITLE
Write documentation about how to use the dbt and Fishtown Analytics logos

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/docs.getdbt.com#448]
This content should go on this page: https://docs.getdbt.com/docs/about/license/

As community members create open source tooling that integrates with dbt, we should be explicit about how (and when) to use the dbt logo. We should also include information about the fact that the dbt logo is _not_ Apache 2.0 licensed. This document would help clarify acceptable uses for the dbt logo, and could also link out to some SVGs and PNGs :)

**Comment by runleonarun** [comment]
Looks like this is captured in our [Brand guidelines](https://www.getdbt.com/brand-guidelines/)!
