### ISSUE TITLE
Add `--clean-project-files-only` / `--no-clean-project-files-only` to 1.7 upgrade guide

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#4482]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.7

### What part(s) of the page would you like to see updated?

See https://github.com/dbt-labs/dbt-core/issues/9089#issuecomment-1813329844 for context.

>   --clean-project-files-only / --no-clean-project-files-only
>                                   If disabled, dbt clean will delete all paths
>                                   specified in clean-paths, even if they're
>                                   outside the dbt project.

Issue: https://github.com/dbt-labs/dbt-core/issues/8318
PR: https://github.com/dbt-labs/dbt-core/pull/8469

**Comment by jtcohen6** [comment]
This just came up in another `dbt-core` issue:
- https://github.com/dbt-labs/dbt-core/issues/9138
