### ISSUE TITLE
cloud API POST /accounts/{accountId}/jobs requires all fields in the body (not just the ones that are marked as required in the docs)

### ISSUE THREAD

**Issue by marselasulku** [fishtown-analytics/docs.getdbt.com#451]
### Describe the bug
In order to successfully create a job via the API, I have to specify all of the fields (including the ones that are not marked as 'required' by the docs). In some cases this means supplying unnecessary information. For example, if I'm create a job that I only intend to trigger via the API, I still have to specify a `schedule` even though it won't be used. 

### Steps To Reproduce
Make a `POST /accounts/{accountId}/jobs` request with the following body: 
```
{
	"account_id": 1,
	"project_id": 100,
	"environment_id": 10,
	"name": "some job",
	"execute_steps": [
		"dbt run"
	],
}
```
these fields are the ones that are marked as 'required' by [the docs ](https://docs.getdbt.com/dbt-cloud/api/#operation/createJob)

### Expected behavior
Should create a job and respond with 200. Instead, it responds with: 
```
{
  "status": {
    "code": 400,
    "is_success": false,
    "user_message": "The request was invalid. Please double check the provided data and try again.",
    "developer_message": ""
  },
  "data": {
    "_model": "HumanReadableJobDefinition",
    "state": "required key not provided",
    "id": "required key not provided",
    "triggers": "required key not provided",
    "schedule": "required key not provided",
    "settings": "required key not provided",
    "dbt_version": "required key not provided"
  }
}
```

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by marselasulku** [comment]
@jtcohen6 I think this might be an issue with the API. I think the documentation is correct. 

For example, `schedule` is marked as an optional field in the documentation but the API requires it. In the event that I set `triggers.schedule` to `false` (like when I dont want the job to run on a schedule), I _still_ have to specify a `schedule` which is unnecessary / data that is not used

**Comment by zxy-zxy** [comment]
Hello, any updates on this?

**Comment by Nazaniiin** [comment]
This issue is still happening. Besides the points mentioned, another thing that is quite strange for me in the list of required fields is the `id`. I expect the POST request to give the job I want to create an id and not ask me to do that since I really don't know what id to provide. I'd appreciate it if someone can clarify the correct behavior of DBT Cloud API.

**Comment by Nazaniiin** [comment]
Found the problem. There is a small bug in the documentation. You need to remove the last `/` from the URL, then everything works! So in your POST URL instead of `https://cloud.getdbt.com/api/v2/accounts/{accountId}/jobs/`, enter `https://cloud.getdbt.com/api/v2/accounts/{accountId}/jobs`

**Comment by dgreen161** [comment]
@jtcohen6 Has this been fixed? It appears that either the documentation is wrong or the API is broken.

I wonder if the endpoint is repointing to the [update job by id](https://docs.getdbt.com/dbt-cloud/api-v2#operation/updateJobById) endpoint since the `id` field is required. This id won't exist yet since we are creating a new job. Based on this, I don't think it's the documentation that is wrong but instead the API is broken.

**Comment by 5x-arpit** [comment]
Hello, I got the solution of this and would like to share here. Here's the problem with the create job API is, its taking the "id" field as an input in body which is required field. We need to give value of job id in "id" field but we would not be able to get it in create API so we need to pass null as a value in "id" field for create API. 

NOTE: This required field i.e. "id" is not mentioned anywhere in dbt documentation in create job API. For reference -https://docs.getdbt.com/dbt-cloud/api/#operation/createJob

Hope this helps !

@shelgeram07 
@arpit-1696

**Comment by runleonarun** [comment]
Closing this issue as it looks fixed in [the API docs](https://docs.getdbt.com/dbt-cloud/api-v2#tag/Jobs/operation/listJobsForAccount). Thank you for opening it and raising the issue!
