### ISSUE TITLE
Document the enabled config for sources

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/docs.getdbt.com#455]
I went [here](https://docs.getdbt.com/reference/resource-configs/enabled) and expected to see sources documented, but it was not so

**Comment by clrcrl** [comment]
@jtcohen6 — I know you said yesterday that this _was_ documented — whereabouts were you looking?

**Comment by jtcohen6** [comment]
@clrcrl https://docs.getdbt.com/reference/source-configs/

**Comment by runleonarun** [comment]
Looks like this is documented so I am closing this issue but we can open if we need anything.
