### ISSUE TITLE
Provide information on the Payments table in the tutorial

### ISSUE THREAD

**Issue by msteadly** [fishtown-analytics/docs.getdbt.com#459]
## Steps to reproduce:

In the 'Deploy Your Model' Step, It challenges the user (and the very end) to utilize the payments table and add it into the model. I cannot find the table or any documentation referring to it. Can you add it (or if it exists, make it easier to find documentation on it). 

Otherwise, I do not know if I can do this step.

**Comment by runleonarun** [comment]
We've revised the quickstarts and hopefully have addressed this issue! If we can improve anything else, then please open another issue and let us know!
