### ISSUE TITLE
`loaded_at_field` not required for source freshness checks as-of 1.7

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#4615]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-properties/freshness

### What part(s) of the page would you like to see updated?

Two things:
1. Update the page based off the information listed in the [v1.7 migration guide](https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.7#behavior-changes).
2. Explain (on one or more pages) which adapters require `loaded_at_field` in order to calculate freshness and which can be calculated from metadata.

### Platforms that support freshness from metadata

Currently, only Snowflake can calculate from metadata, but consult the following list of issues to track if other adapters add support:
- https://github.com/dbt-labs/dbt-snowflake/issues/785
- https://github.com/dbt-labs/dbt-redshift/issues/615
- https://github.com/dbt-labs/dbt-bigquery/issues/938
- https://github.com/dbt-labs/dbt-spark/issues/890

###  Achieving a mix of null and non-null for `loaded_at_field`

https://github.com/dbt-labs/dbt-core/issues/9320#issuecomment-1874327491

### Additional information

Additional information can be found in the following places:
- https://github.com/dbt-labs/dbt-core/issues/7012
- https://github.com/dbt-labs/docs.getdbt.com/issues/4123
- https://github.com/dbt-labs/dbt-core/issues/8704#issuecomment-1753905285

### Instigating issue

This came up during discussion of this regression: https://github.com/dbt-labs/dbt-bigquery/issues/1044

We have information related to `loaded_at_field` vs. database metadata in the upgrade guide, but we don't yet have it within the docs for [`freshness`](https://docs.getdbt.com/reference/resource-properties/freshness).

**Comment by runleonarun** [comment]
Note there's also info in this [duplicate issue](https://github.com/dbt-labs/docs.getdbt.com/issues/4718)
