### ISSUE TITLE
Guide on commands to run dbt in production

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/docs.getdbt.com#464]
We have a bit of this info [here](https://discourse.getdbt.com/t/what-are-the-dbt-commands-you-run-in-your-production-deployment-of-dbt/366), but I think it's time we pull it into the docs.

I imagine the content would be something along the lines of:

Job 1: Prod run
```
0. dbt deps
1. dbt seed
2. dbt run
3. dbt test
4. dbt source snapshot-freshness # though I do this after deps
```
Schedule this on a regular cadence

Job 2: Full refresh run
(as above but with --full-refresh)
Schedule this weekly at a non-busy time

Job 3: CI run
(all the instructions for doing state modified runs)
+ info on considerations if not using dbt-Cloud — schema naming / tearing down the schema

Other things seen in the wild:
- testing sources before running models
- using operations to perform a blue-green deploy as part of your prod run
- breaking up the DAG into subdags

**Comment by runleonarun** [comment]
Closing because we have these listed here: https://next.docs.getdbt.com/reference/dbt-commands
