### ISSUE TITLE
serverless dlt + dbt project

### ISSUE THREAD

**Issue by adrianbr** [fishtown-analytics/docs.getdbt.com#4657]
### Contact Details

adrian brudaru on slack

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

Showcasing how dlt and dbt can work together, in this case in a place where ingestion + dbt do not often run: google cloud functions. This setup is serverless and costs only a few cents to run which is great for a personal project or small stack.

This project was already done by a dlt user as a personal use project and he wrote up a description in the format of the  blog.

### Link to an initial outline.

https://github.com/euanjohnston-dev/docs.getdbt.com/blob/current/website/blog/2023-12-15-serverless-free-tier-data-stack-with-dlt-and-dbt-core.md

**Comment by nghi-ly** [comment]
PR #4658 is merged. Closing issue as part of cleanup.
