### ISSUE TITLE
Old logo in the docs docs

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#4737]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

I found an old logo! https://docs.getdbt.com/reference/resource-properties/description#include-an-image-from-your-repo-in-your-descriptions

### What part(s) of the page would you like to see updated?

The example image should use the new logo

**Comment by mirnawong1** [comment]
hey @joellabes thanks for opening this up! going to remove the image for now so the old logo doesn't show up
