### ISSUE TITLE
Persistent cookie policy pop-up in Vercel preview

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#4757]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

To the best I can tell, this affects all page(s) within the Vercel preview.

Example:

https://docs-getdbt-com-git-mwong-cross-db-macros-dbt-labs.vercel.app/reference/dbt-jinja-functions/cross-database-macros

Screenshot:

<img width="400" alt="image" src="https://github.com/dbt-labs/docs.getdbt.com/assets/44704949/981e0bf0-1e0c-4f50-ac95-0039fa7cfb06">

### What changes are you suggesting?

It doesn't matter if I click "Reject All" or "Accept Cookies" -- I get the same pop-up the next time the page loads. And the rest of the page is greyed out and I can't navigate to other pages by clicking the links in the left-hand menu.

### Additional information

I'm working around this by:
1. First, searching for the page I want within the public web documentation on getdbt.com (rather than the Vercel preview in a PR).
2. Second, going to the Vercel preview
3. Copy the ending portion of the URL from step 1 and pasting it into the preview URL from step 2.

Update: @nghi-ly gave me the pro-tip of adding `?otreset=true&otpreview=true&otgeo=us,va` to the end of the URL which helps.

It still continues to pop-up the cookie policy bit no matter what I choose, but adding that little bit actually lets me navigate the page 💪

**Comment by nghi-ly** [comment]
there's [an asana ticket filed](https://app.asana.com/0/1200099998847559/1204797100637466/f) for this bug. John Rock, back in June, investigated this a bit and found that OneTrust is adding an event on the body of the page after accepting the cookies.

closing bc we have an asana ticket tracking this bug. feel free to reopen if we wanna track it here as well
