### ISSUE TITLE
[CT-3568] `print` / `no_print` in `profiles.yml` has no effect

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#4776]
Here's the relevant documentation about the `print` global config:
- https://docs.getdbt.com/reference/dbt-jinja-functions/print
- https://docs.getdbt.com/reference/global-configs/print-output

I tried specifying `print: False` within `profiles.yml` as described in the docs, but it didn't have any effect.

So maybe it was fully deprecated sometime between dbt v1.5 and v1.7 but we didn't yet update the docs? Or maybe it was accidentally stopped working during the `click` migration (in https://github.com/dbt-labs/dbt-core/pull/7086)?

_Originally posted by @dbeatty10 in https://github.com/dbt-labs/docs.getdbt.com/pull/4740#discussion_r1454071332_

### To do

Try out the following within each of v1.5, v1.6, and v1.7. Figure out if it was fully deprecated or not and update the docs accordingly.

1. Create this simple model file:

`models/my_model.sql`

```sql
{{ print("") }}
{{ print("*** Parsing, compiling, or running: " ~ this) }}
{{ print("") }}

select 1 as id
```

2. Add the following config to `profiles.yml`:

```yaml
config:
  print: False
```

3. See if `*** Parsing ...` shows up in the logs or not:

```
dbt parse
```

**Comment by runleonarun** [comment]
Hey @dbeatty10, I came across a possibly related [Slack convo](https://dbt-labs.slack.com/archives/C051TUB7S9W/p1701687924769879). It maybe needs to be wrapped in a macro until it's fixed in Core?

**Comment by dbeatty10** [comment]
> Hey @dbeatty10, I came across a possibly related [Slack convo](https://dbt-labs.slack.com/archives/C051TUB7S9W/p1701687924769879). It maybe needs to be wrapped in a macro until it's fixed in Core?

Oooh, good call about that Slack convo 🧠

Digging into that convo deeper, it seems it is mainly related to other issues like these:
- https://github.com/dbt-labs/dbt-core/issues/8756
- https://github.com/dbt-labs/dbt-core/issues/9174

Looking at this more closely, I think this might be a bug in dbt-core, so I'm going to transfer this issue to that repo.

**Comment by dbeatty10** [comment]
See also: https://github.com/dbt-labs/dbt-core/issues/7036 (which also mentions `print` and would presumably resolve this issue).

**Comment by dbeatty10** [comment]
After further research, I think we just need an update to the docs.

Opened https://github.com/dbt-labs/docs.getdbt.com/pull/4775 to address this.
