### ISSUE TITLE
Add a procedure for "connecting dbt Cloud to Azure Snowflake using PrivateLink"

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#4832]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

under https://docs.getdbt.com/docs/cloud/secure/secure-your-tenant

### What part(s) of the page would you like to see updated?

Add a new page:
1. Enable Private Link on the Snowflake prod account https://docs.snowflake.com/en/user-guide/privatelink-azure
2. From the prod Snowflake instance, run `SYSTEM$GET_PRIVATELINK_CONFIG ` and send the output to your dbt account rep.  More here: https://docs.snowflake.com/en/sql-reference/functions/system_get_privatelink_config
3. dbt will use the resource ID to create a privateLink endpoint
4. dbt sends you Resource ID of the new endpoint
5. Grant the endpoint access to your Snowflake PrivateLink by creating a Snowflake Support Case with the Snowflake Account URL and the Private Endpoint resource ID/name. (https://community.snowflake.com/s/article/HowtosetupPrivatelinktoSnowflakefromCloudServiceVendors)
6. Create and verify Snowflake connection in dbt Cloud. More here: https://docs.getdbt.com/docs/cloud/connect-data-platform/connect-snowflake

consult with @T-Dunlap and @dhaworth 

### Additional information

Original internal chat [here](https://dbt-labs.slack.com/archives/C02NCQ9483C/p1706645182401839).

**Comment by matthewshaver** [comment]
Closing based on the conversation here https://dbt-labs.slack.com/archives/CSSHB76QL/p1708619375247639
