### ISSUE TITLE
[Feature] - User Defined Macros & Filters

### ISSUE THREAD

**Issue by afranzi** [fishtown-analytics/docs.getdbt.com#4872]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Not sure if this would be part of the https://docs.getdbt.com/reference/project-configs/macro-paths
Or in https://docs.getdbt.com/reference/dbt-jinja-functions

### What part(s) of the page would you like to see updated?

The main idea would be adding documentation about the new incoming feature allowing DBT developers to inject their own python JINJA macros and filters in addition to the native ones, so developers can move complex jinja templating code to python and level up their dbt projects with more possibilities.

Some examples:
- Expand DBT credentials fetching them from a secret store (i.e. AWS Secrets Manager).
- Enable models based on an external config (i.e. HTTP Requests to an external API which defines if the model can be enabled).
by 

We can enable this behavior by defining the following ENV vars with the `path:instance` format.
-   `DBT_USER_DEFINED_MACROS`: Jinja Macros
-  `DBT_USER_DEFINED_FILTERS`: Jinja Filters

### Additional information

This documentation would be based on this PR https://github.com/dbt-labs/dbt-common/pull/72.

See following example about how I've used it locally:

![Screenshot 2024-02-08 at 11 12 05](https://github.com/dbt-labs/docs.getdbt.com/assets/3647015/26c93ec6-0d7e-4aa6-abe6-b78a6ce0ba02)
![Screenshot 2024-02-08 at 11 11 36](https://github.com/dbt-labs/docs.getdbt.com/assets/3647015/a341a4c7-e998-40a6-a277-0fa24c2a177b)
![Screenshot 2024-02-08 at 11 11 14](https://github.com/dbt-labs/docs.getdbt.com/assets/3647015/63b33712-4cdb-4b57-a1c1-45c4b9cec677)

**Comment by afranzi** [comment]
Adding some examples about the credentials:
![Screenshot 2024-02-08 at 11 51 31](https://github.com/dbt-labs/docs.getdbt.com/assets/3647015/1f463058-29df-4412-b490-5dbb7e19affd)
![Screenshot 2024-02-08 at 11 51 38](https://github.com/dbt-labs/docs.getdbt.com/assets/3647015/205893fa-189a-412d-90a0-09bac794152d)
![Screenshot 2024-02-08 at 11 52 08](https://github.com/dbt-labs/docs.getdbt.com/assets/3647015/dcf90e40-4af1-4e9d-96c1-fa72799c92c1)

**Comment by ismailsimsek** [comment]
created related discussion here https://github.com/dbt-labs/dbt-adapters/discussions/259

IMO  Adapter factory should allow user provided customized adapter class. this will open door to customization

**Comment by ismailsimsek** [comment]
PR https://github.com/dbt-labs/dbt-adapters/pull/261
implemented in this package https://github.com/memiiso/opendbt
example https://github.com/memiiso/opendbt/blob/main/docs/EXAMPLES.md#execute-python-model-locally

using @available decorator makes the function available to jinja

**Comment by matthewshaver** [comment]
Attached PRs were closed, so closing this issue as well.

**Comment by afranzi** [comment]
It's quite sad seeing DBT Labs taking this approach and closing it.
