### ISSUE TITLE
A guide to migrating from dbt Core to dbt Cloud

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#4880]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/guides

### What part(s) of the page would you like to see updated?

Requested recently by @T-Dunlap  and @Stevedow99, and Inspired in part by @anaisvaillant 's [idea here](https://github.com/dbt-labs/docs.getdbt.com/issues/1892). 

Migration guide for customers interested in moving from dbt core to dbt cloud. 

Create a framework of how to think about a migration and provide a list of considerations (similar to the [how to configure your dbt repository (one or many)](https://discourse.getdbt.com/t/how-to-configure-your-dbt-repository-one-or-many/2121) post) so the customer has a better grasp of the amount of work and time needed.

It might help to think of workflow and how these would change:
* people
* dbt (cloud account, dbt cloud project and dbt project)
* other tools they may have (orchestration, docs, BI, etc)
* Target Audience: a data engineering lead, architect, project leader
 

### Additional information

We can use this [internal doc](https://docs.google.com/document/d/1iwTPg2cW0STA7b7oDr2kTXZPrMutAZ103DfXmVf0mJU/edit#heading=h.nnj6efytk5cz) as a resource. It's an initial outline of helpful questions compiled by @azzam34  and others.

**Comment by mirnawong1** [comment]
completed in april: https://docs.getdbt.com/guides/core-cloud-2?step=1
