### ISSUE TITLE
Fast follows for Unit Testing

### ISSUE THREAD

**Issue by matthewshaver** [fishtown-analytics/docs.getdbt.com#4889]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

 https://docs.getdbt.com/reference/node-selection/methods#the-test_type-method

### What part(s) of the page would you like to see updated?

can we update this page too with the new test_types

**Comment by matthewshaver** [comment]
Add format types

Add best practices for when to `run` unit tests

**Comment by matthewshaver** [comment]
Add `format` section to explain `dict` and `csv` data formats

**Comment by matthewshaver** [comment]
One more section here on "When to run your unit tests"

Like the general best practice on "run your unit tests in dev / ci" but not in prod - and maybe some thoughts/best practices around warehouse sizing?

**Comment by graciegoheen** [comment]
> Oooh can we update this page too with the new test_types -> https://docs.getdbt.com/reference/node-selection/methods#the-test_type-method

**Comment by graciegoheen** [comment]
> `dbt build` ([how unit tests fit into the dbt build command](https://github.com/dbt-labs/dbt-core/issues/8979))

docs for `dbt build` with unit tests

**Comment by graciegoheen** [comment]
Likely out of scope of this PR, but do we have an open issue already for documenting `data_tests:`?

For for backward compatibility tests: will be an alias for data_tests: in yml configuration files, but we will eventually deprecate tests:
```
models:
  - name: orders
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
```
```
# dbt_project.yml

data_tests: # legacy tests:
```

**Comment by graciegoheen** [comment]
Link to docs for `--empty` flag

**Comment by matthewshaver** [comment]
We need to update the dbt build command page as well

**Comment by graciegoheen** [comment]
> Really love how you nested data tests and unit tests under a "tests" section - I wonder if it would be valuable to have an "About dbt tests" page (similar to the "About dbt models") to talk more broadly about what "tests" are and how they're used. Could reduce some of the duplication of docs between data / unit (like the `dbt test` command). 
>
> We could also put some of the "this is how data tests and unit tests relate to each other" type of info on that page.
>
> Maybe out-of-scope for this initial pass, but just a thought!

**Comment by graciegoheen** [comment]
> I like how for the data tests ref section we have mini pages for the configs you can use for your data tests:
![Screenshot 2024-02-12 at 11 21 51 AM](https://github.com/dbt-labs/docs.getdbt.com/assets/53586774/b3689934-047e-40f1-a8d4-73ee095ace5b)
>
> Could we do the same for unit tests? I think we could break up the "about writing unit tests" section into separate pages on format, expect, given, overrides, etc.

**Comment by graciegoheen** [comment]
Nit-pick:
the actual logs have some specific formatting (color + bolding) to make this error message clearer to read - would it be possible to include that formatting here?

<img width="940" alt="Screenshot 2024-02-14 at 10 30 45 AM" src="https://github.com/dbt-labs/docs.getdbt.com/assets/53586774/3c66f028-0faf-4b5b-a4e1-feae7745394c">

- "Fail 1" is red
- "Complete with 1 error and 0 warnings:" is red
- "Failure in unit_test test_is_valid_email_address (models/marts/unit_tests.yml)" is red
- "actual" is green
- "expected" is red
- "True" is red and bold
- "False" is green and bold

**Comment by graciegoheen** [comment]
Same nit-pick as above:
<img width="947" alt="Screenshot 2024-02-14 at 10 31 48 AM" src="https://github.com/dbt-labs/docs.getdbt.com/assets/53586774/de1d63cd-8ff7-4c34-8bda-b92d88137ff4">

- "PASS" is green
- "Completed successfully" is green

**Comment by graciegoheen** [comment]
![Screenshot 2024-02-20 at 4 25 48 PM](https://github.com/dbt-labs/docs.getdbt.com/assets/53586774/9a4ce9de-a599-4488-b180-be16c0bb19c6)

add overrides examples for vars, macros, and env_vars https://github.com/dbt-labs/dbt-core/blob/7df747ae04a8c99dbd745085f42cd4647ec71d80/tests/functional/unit_testing/fixtures.py#L82

**Comment by graciegoheen** [comment]
IMPORTANT -> We should make it clear that unit tests must be defined in a YML file in your `models/` directory in the unit testing docs

**Comment by matthewshaver** [comment]
> Likely out of scope of this PR, but do we have an open issue already for documenting `data_tests:`?
> 
> For for backward compatibility tests: will be an alias for data_tests: in yml configuration files, but we will eventually deprecate tests:
> 
> ```
> models:
>   - name: orders
>     columns:
>       - name: order_id
>         data_tests:
>           - unique
>           - not_null
> ```
> 
> ```
> # dbt_project.yml
> 
> data_tests: # legacy tests:
> ```

Created [this issue](https://github.com/dbt-labs/docs.getdbt.com/issues/4989) and will follow up!
