### ISSUE TITLE
Docs for unit testing incremental models

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#4929]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

New section on this page 
https://docs.getdbt.com/docs/build/unit-tests

### What part(s) of the page would you like to see updated?

New section on unit testing incremental models

**Comment by runleonarun** [comment]
@graciegoheen (sorry for repeating this question, just want to get a sense of completion times.) Do you need Docs support on this? I think we should aim to have all issues addressed by Friday 2/23 to give reviewers and authors enough time.

**Comment by graciegoheen** [comment]
@MichelleArk and I can pair on this and tag y'all for a review if that works?
