### ISSUE TITLE
Docs for unit testing, data types

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#4930]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-properties/unit-tests

### What part(s) of the page would you like to see updated?

New section for data types 

Similar to https://docs.getdbt.com/reference/resource-properties/constraints#platform-specific-support

**Comment by runleonarun** [comment]
@graciegoheen Do you need Docs support on this? I think we should aim to have all issues addressed by Friday 2/23 to give reviewers and authors enough time.

**Comment by graciegoheen** [comment]
Lemme check in with Michelle, we can probably pair on this and I can tag you for a review!

**Comment by graciegoheen** [comment]
Known exceptions:
- can't unit test for precision / correct data type (since dbt converts your mock data into the correct data type to execute the unit test)

**Comment by graciegoheen** [comment]
Re-opening - this is different than the docs for the `format` config. Michelle and I will work on this, but this it not blocking for the beta

**Comment by matthewshaver** [comment]
@graciegoheen Sorry about that. Is there a current doc to reference? I can get started

**Comment by graciegoheen** [comment]
@matthewshaver [Here you go](https://www.notion.so/dbtlabs/Unit-Testing-Documentation-Changes-0d00d8077b044607878faecdd39831d3?pvs=4#7561e4e6ffff491cbd30bf138cd12942)!
