### ISSUE TITLE
Follow up for Semantic Layer FAQs

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#4947]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/use-dbt-semantic-layer/sl-faqs

### What part(s) of the page would you like to see updated?

There were two comments I didn't address:
* Add this [commented out FAQ](https://github.com/dbt-labs/docs.getdbt.com/pull/4942/files#r1492900688) about CLI limit=100
>It looks like this limit is not only for the Cloud CLI, right? Or is it that you can only override the metric in the CLI?

> Either way, I wonder if we should create a reusable and add it to both [Query section of Metricflow Commands](https://docs.getdbt.com/docs/build/metricflow-commands#query) and [Querying the API](https://docs.getdbt.com/docs/dbt-cloud-apis/sl-jdbc#querying-the-api-for-metric-values), which is where I'd expect to see this info.

> If overriding the limit is only possible in CLI, then I still think it's worth adding to those two places.
* Expanding on [What are the latency considerations of using the dbt Semantic Layer?](https://github.com/dbt-labs/docs.getdbt.com/pull/4942/files#r1492661224

**Comment by mirnawong1** [comment]
likewise i think maybe the dbt mesh faqs should have similar aesthetics in terms of toggles?

**Comment by mirnawong1** [comment]
asked about cloud cli limit in linear: https://linear.app/dbt-labs/issue/SL-1373/%F0%9F%9F%A1-the-cloud-cli-appears-to-have-a-limit-of-1024-rows-so-limit#comment-b328da5f

**Comment by mirnawong1** [comment]
Closing this as this was addressed
