### ISSUE TITLE
Programmatic invocations: advise against concurrent invocations in same process

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#4952]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/programmatic-invocations

### What part(s) of the page would you like to see updated?

Explicitly advise against multiple concurrent invocations because:
- may interact with database state in surprising ways (e.g. `run` and `build` for same models)
- each `dbt-core` invocation requires interacting with global Python variables, so need to be run in separate process (via spawn or celery or ...)

**Why this page?** My hunch is that users are more likely to try running multiple dbt operations in parallel if they are using the programmatic (Python) entry-point rather than the CLI entry-point.

### Additional information

Recent examples:
- https://getdbt.slack.com/archives/C50NEBJGG/p1707741946003719
- https://github.com/dbt-labs/dbt-core/issues/9603

**Comment by mirnawong1** [comment]
hey @jtcohen6  - woah this sounds similar to this pr here https://github.com/dbt-labs/docs.getdbt.com/pull/4909 that I'm working on (which started from Dichen's cloud cli ship and has grown to more info). does this pr (particularly [this section](https://github.com/dbt-labs/docs.getdbt.com/pull/4909/files)) address this issue?

**Comment by hash-data** [comment]
Hi @jtcohen6  instead of making global vars to be local why we just changing the docs.

**Comment by jtcohen6** [comment]
@hash-data This limitation has existed in `dbt-core` for some time, and in practice it only causes issues for a small subset of use cases.

We've opened issues in the past to address this, but we haven't been able to prioritize the work fully:
- https://github.com/dbt-labs/dbt-core/issues/5919
- https://github.com/dbt-labs/dbt-core/issues/6399

We could continue this conversation further in a new `dbt-core` feature request. To be honest, at this point, I'm not sure it's within the scope of `dbt-core` to support this kind of concurrency. Don't get me wrong — if I could wave a magic wand, and have it for free, I would; we may take steps there in the course of other refactoring, if it makes it easier to test & maintain `dbt-core` — but it hasn't proven necessary in the workflows & user experiences that `dbt-core` is designed to support. We need to prioritize improvements to existing functionality & more-common use cases.
