### ISSUE TITLE
Document the existence of DBT_PACKAGE_HUB_URL

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#4991]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Maybe the packages page? Maybe a page on secret env vars? I'm opening an issue instead of a PR because I don't really know where it should go

### What part(s) of the page would you like to see updated?

It's possible to use a custom package hub by specifying the [`DBT_PACKAGE_HUB_URL`](https://github.com/dbt-labs/dbt-core/blob/7329143ffb1b3558e805191c10679cfacf65bf0f/core/dbt/clients/registry.py#L22) environment variable. 

As far as I can see, there's no documentation for this, so I had to [ask chatgpt](https://chat.openai.com/share/e/3246a4b5-9c29-40b1-9238-6d630c4df732) to remember the name of the variable 😅

**Comment by mirnawong1** [comment]
closing issue as addressed in https://github.com/dbt-labs/docs.getdbt.com/pull/5122/files
