### ISSUE TITLE
Update Python versions page

### ISSUE THREAD

**Issue by aranke** [fishtown-analytics/docs.getdbt.com#5006]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/faqs/Core/install-python-compatibility

### What part(s) of the page would you like to see updated?

Compatibility matrix:

| dbt-core → <br/> Python ↓ | 1.0 | 1.1 | 1.2 | 1.3 | 1.4 | 1.5 | 1.6 | 1.7 | 1.8 |
|---------------------------:|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| **3.8**                   | ✓   | ✓   | ✓   | ✓   | ✓   | ✓   | ✓   | ✓   | ✓   |
| **3.9**                   | ✓   | ✓   | ✓   | ✓   | ✓   | ✓   | ✓   | ✓   | ✓   |
| **3.10**                  | ✓   | ✓   | ✓   | ✓   | ✓   | ✓   | ✓   | ✓   | ✓   |
| **3.11**                  | ✖️   | ✖️   | ✖️   | ✖️   | ✓   | ✓   | ✓   | ✓   | ✓   |
| **3.12**                  | ✖️   | ✖️   | ✖️   | ✖️   | ✖️   | ✖️   | ✖️   | ✓   | ✓   |

**Comment by aranke** [comment]
I'm happy to create the PR for this, would that be easier?

cc @runleonarun @matthewshaver

**Comment by runleonarun** [comment]
~~@aranke This table is so helpful! If you can open a PR would be great. If not, I can get to it tomorrow!~~
Standing up a PR now!
