### ISSUE TITLE
`DBT_INCLUDE_SAVED_QUERY` -> `DBT_EXPORT_SAVED_QUERIES`

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#5018]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/use-dbt-semantic-layer/exports#define-exports
https://docs.getdbt.com/docs/dbt-versions/release-notes/Feb-2024/exports-rn

### What part(s) of the page would you like to see updated?

- Rename `DBT_INCLUDE_SAVED_QUERY` to `DBT_EXPORT_SAVED_QUERIES`. The old name still works, because we added backwards-compatibility, but the old name is confusing and the new name is more precise about what's happening.
    - This is ONLY relevant starting with "Keep on latest version" in dbt Cloud. Anyone still on v1.7 should keep using the previous name, `DBT_INCLUDE_SAVED_QUERY`.
- Let's switch out "materialize" for "write." IMO the word "materialize" is confusing because it implies that saved query exports are being materialized using the same logic as dbt models materailizations, and they're not. @Jstein77 does that make sense to you?

### Additional information

- https://github.com/dbt-labs/dbt-core/pull/9605
- https://github.com/dbt-labs/dbt-core/issues/9629

**Comment by mirnawong1** [comment]
hey @matthewshaver , i'm happy take this one as it relates to SL? cc @nghi-ly and @runleonarun

**Comment by mirnawong1** [comment]
hey @jtcohen6 , does keep on latest version mean 'v1.7 and higher'? or 'v1.8 or higher'?
