### ISSUE TITLE
Clarify metadata permissions on enterprise permissions page

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#5059]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Support raised that we should clarify that the Metadata permission set is only for Service tokens for the Discovery API. This was due to a ticket where a customer attempted to add the Metadata permission set in a Group.

Wondering if we should include an asterisk disclaimer specifying it applies to disco api.

[Slack thread](https://dbt-labs.slack.com/archives/C02NCQ9483C/p1710165051535419)

### What part(s) of the page would you like to see updated?

https://docs.getdbt.com/docs/cloud/manage-access/enterprise-permissions

**Comment by matthewshaver** [comment]
Fixed in https://github.com/dbt-labs/docs.getdbt.com/pull/5066
