### ISSUE TITLE
Extend support for source freshness based on metadata to Redshift & Bigquery

### ISSUE THREAD

**Issue by MichelleArk** [fishtown-analytics/docs.getdbt.com#5061]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-properties/freshness#definition

### What part(s) of the page would you like to see updated?

![Screenshot 2024-03-11 at 2 13 52 PM](https://github.com/dbt-labs/docs.getdbt.com/assets/9407260/e3d279e7-eb43-48e1-a4f9-7fbba3f06ef9)

### Additional information

Redshift: https://github.com/dbt-labs/dbt-redshift/issues/615
BigQuery: https://github.com/dbt-labs/dbt-bigquery/issues/938

**Comment by mirnawong1** [comment]
hey @MichelleArk thanks so much for opening this up! we've added a pr here https://github.com/dbt-labs/docs.getdbt.com/pull/5080 to add redshift and BQ to the list of supported adapters.

**Comment by mirnawong1** [comment]
![Screenshot 2024-03-14 at 16 37 45](https://github.com/dbt-labs/docs.getdbt.com/assets/89008547/68c7966f-3d5b-4a38-8ffd-106c13bc8ec2)

[preview](https://docs-getdbt-com-git-mirnawong1-patch-26-dbt-labs.vercel.app/reference/resource-properties/freshness)
