### ISSUE TITLE
add docs for DBT_EXCLUDE_RESOURCE_TYPES and DBT_RESOURCE_TYPES

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#5074]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://github.com/dbt-labs/dbt-core/issues/9237

### What part(s) of the page would you like to see updated?

Add docs on new environment variable, relevant for unit testing

**Comment by runleonarun** [comment]
@graciegoheen can you let me know which date this needs to align with?

**Comment by graciegoheen** [comment]
This is for the 1.8 release!

**Comment by graciegoheen** [comment]
Closing as duplicate of https://github.com/dbt-labs/docs.getdbt.com/issues/5073
