### ISSUE TITLE
[Core] Instructions for dbt-core-bundles to replace brew install

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#5082]
We [stopped maintaining Homebrew](https://docs.getdbt.com/docs/core/homebrew-install) as a supported installation method for dbt-core and adapters starting with starting in version 1.6.0. More info here:
- [Installing dbt Core: saying goodbye to brew and hello to "bundles"](https://github.com/dbt-labs/dbt-core/discussions/8277)

So we want to update our docs so that users know what to do instead.

### Link to the page(s) on docs.getdbt.com requiring updates

Either remove the link to Homebrew installation here, or add "(deprecated)" or "no longer supported" as of v1.6:
https://docs.getdbt.com/docs/core/installation-overview#install-dbt-core

Create a new installation method for dbt-core-bundles and add [these](https://github.com/dbt-labs/dbt-core-bundles?tab=readme-ov-file#how-to-use) instructions.

Revisit these docs and make updates as-needed:
https://docs.getdbt.com/docs/core/homebrew-install

### Tell us more about this update

See more info here: https://github.com/dbt-labs/dbt-core/discussions/8277

### Reviewers/Stakeholders/SMEs

Colin and Jerco

### Related GitHub issues

https://github.com/dbt-labs/homebrew-dbt/issues/382

**Comment by runleonarun** [comment]
Closing this as addressed in https://github.com/dbt-labs/docs.getdbt.com/pull/5446 and captured previously in this issue: https://github.com/dbt-labs/docs.getdbt.com/issues/5432 

Still investigating whether CLI can still use Homebrew but will open another issue if we need to remove it there.
