### ISSUE TITLE
[Core] `dbt show` is only for SQL models (not Python)

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#5083]
### Link to the page(s) on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/commands/show

### Tell us more about this update

The docs do specify dbt-SQL in a couple places, but it would be nice to explicitly call out that [dbt-py](https://docs.getdbt.com/docs/build/python-models) (Python) models are not supported by `dbt show`.

### Reviewers/Stakeholders/SMEs

Kshitij

**Comment by mirnawong1** [comment]
hey @dbeatty10 and @aranke i've opened this pr #5135 to address this issue
