### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ghost** [fishtown-analytics/docs.getdbt.com#509]
## Steps to reproduce:

- Go to https://docs.getdbt.com/dbt-cli/installation#pip
- Click on [cryptography.io](https://cryptography.io/en/latest/faq/#compiling-cryptography-on-os-x-produces-a-fatal-error-openssl-aes-h-file-not-found-error)

## Expected results:

The linked page loads.

## Actual results

The link is broken.

## Extra details

I noticed that the correct link to the cryptography.io FAQ is:
https://cryptography.io/en/latest/faq.html

However, I also noticed that it no longer includes the section you're referencing.

**Comment by clrcrl** [comment]
@VersusFacit  — I think you added this part of the docs ([here](https://github.com/fishtown-analytics/docs.getdbt.com/blame/current/website/docs/dbt-cli/installation.md#L75))

**Comment by VersusFacit** [comment]
Dug into this. So super annoyingly, https://cryptography.io/en/latest/faq/#compiling-cryptography-on-os-x-produces-a-fatal-error-openssl-aes-h-file-not-found-error is linked the link on the actual faq header, but if you try to access it, as David points out, it is broken. I'll clean up the clean in a future PR.

**Comment by daviewales** [comment]
I think this might be fixed now.

**Comment by runleonarun** [comment]
Closing because this is no longer an issue! Thanks everyone!
