### ISSUE TITLE
Webhooks docs doesn't have all the necessary parameters documented

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#5098]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

The following suggestion was raised by @joellabes in [slack thread](https://dbt-labs.slack.com/archives/C02NCQ9483C/p1710724881181749):

The [Create webhooks wubscription](https://docs.getdbt.com/docs/deploy/webhooks#create-a-webhook-subscription) call doesn't have all the necessary parameters documented ([Slack thread](https://getdbt.slack.com/archives/C069A7N46UU/p1709555928504049)) - it only names `account_id` as required, but then complains that `active`, `event_types`, `client_url` and `name` are all missing.

### What part(s) of the page would you like to see updated?

https://docs.getdbt.com/docs/deploy/webhooks#create-a-webhook-subscription

**Comment by joellabes** [comment]
Had a crack at adding this here but I don't think I'm doing it right :( https://github.com/dbt-labs/dbt-cloud/pull/10636 will probably need some help from the cloud config gang

**Comment by runleonarun** [comment]
I requested help from Gideon or Mitchell.

**Comment by joellabes** [comment]
Resolved over on https://github.com/dbt-labs/dbt-cloud/pull/10636
