### ISSUE TITLE
[May 2] Update Adapter Creation Guide for v1.8 interface changes

### ISSUE THREAD

**Issue by nghi-ly** [fishtown-analytics/docs.getdbt.com#5104]
The guide https://docs.getdbt.com/guides/adapter-creation?step=1 needs to be reviewed and updated based on the changes to the adapters interface (ie dbt-common + dbt-adapters).
- https://github.com/dbt-labs/dbt-core/discussions/9171

### When is this due?
This is needed for v1.8 (Core) + "Keep on latest version" (Cloud) and can be worked on at any time, but is due May 2nd for 1.8 final GA

related: https://github.com/dbt-labs/dbt-adapters/issues/136

### Changes

- [x] update https://docs.getdbt.com/guides/adapter-creation?step=2#keeping-the-code-compatible-with-dbt-core
- [x] update https://docs.getdbt.com/guides/adapter-creation?step=2#versioning-and-releasing-your-adapter 
- [x] update https://docs.getdbt.com/docs/dbt-versions/core#how-we-version-adapter-plugins
- [x] update https://docs.getdbt.com/guides/adapter-creation?step=4#about-the-testing-framework
- [x] update https://docs.getdbt.com/guides/adapter-creation?step=4#testing-this-adapter 
- [x] update https://docs.getdbt.com/guides/adapter-creation?step=7#verify-a-new-adapter
- [x] Check w Amy: https://docs.getdbt.com/guides/adapter-creation?step=7#verified-by-dbt-labs
- [x] update https://docs.getdbt.com/guides/adapter-creation?step=8#release-cadence 
- [x] update diagram https://docs.getdbt.com/guides/adapter-creation?step=1#adapter-architecture 

### notes
For more context, see [slack thread](https://dbt-labs.slack.com/archives/C0131TY7EEA/p1710433062852709?thread_ts=1710193700.237319&cid=C0131TY7EEA).

**Comment by jtcohen6** [comment]
Related - we also need to update this documentation now that `dbt-core` and adapter versions will no longer be in lockstep:
- https://docs.getdbt.com/docs/dbt-versions/core#how-we-version-adapter-plugins

**Comment by nghi-ly** [comment]
notion page for collaboration: https://www.notion.so/dbtlabs/Adapters-Creation-Guide-71cb64fab2b2404692ccc53d21ababde?pvs=4 

contains the contents and links of where the docs updates should be made
