### ISSUE TITLE
[Core] Fix content in table for available flags (global configs)

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#5111]
### Link to the page(s) on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/global-configs/about-global-configs#available-flags

### Tell us more about this update

Here's what it is currently:

|    Flag name   |  Type  |               Default               | Supported in project? | Environment variable | Command line option | Supported in Cloud CLI? |
|:--------------:|:------:|:-----------------------------------:|:---------------------:|:--------------------:|:-------------------:|:-----------------------:|
| `target_path`  | path   | none                                | ❌                     | `DBT_TARGET_PATH`    | `--target-path`     | ❌                       |
| `profiles_dir` | path   | None (current dir, then `HOME` dir) | ❌                     | `DBT_PROFILES_DIR`   | `--profiles-dir`    | ❌                       |
| `target`       | path   | None (uses `target/`)               | ❌                     | `DBT_TARGET`         | `--target`          | ❌                       |
| `profile`      | string | None                                | ✅ (as top-level key)  | `DBT_PROFILE`        | `--profile`         | ❌                       |

Five things are not accurate:
1. Default for `target_path`
1. Default for `target`
1. Type for `target`
1. `DBT_TARGET` won't be available until https://github.com/dbt-labs/dbt-core/pull/9081 is merged+released
1. `DBT_PROFILE` won't be available until https://github.com/dbt-labs/dbt-core/pull/9081 is merged+released

Here's what it should be instead (until https://github.com/dbt-labs/dbt-core/pull/9081 is merged+released):

|    Flag name   |  Type  |               Default               | Supported in project? | Environment variable | Command line option | Supported in Cloud CLI? |
|:--------------:|:------:|:-----------------------------------:|:---------------------:|:--------------------:|:-------------------:|:-----------------------:|
| `target_path`  | path   | None (uses `target/`)               | ❌                     | `DBT_TARGET_PATH`    | `--target-path`     | ❌                       |
| `profiles_dir` | path   | None (current dir, then `HOME` dir) | ❌                     | `DBT_PROFILES_DIR`   | `--profiles-dir`    | ❌                       |
| `target`       | path   | None                                | ❌                     |                      | `--target`          | ❌                       |
| `profile`      | string | None                                | ✅ (as top-level key)  |                      | `--profile`         | ❌                       |

### Reviewers/Stakeholders/SMEs

Doug E. Fresh 😎

### Related GitHub issues

https://github.com/dbt-labs/dbt-core/pull/9081#issuecomment-2006229247

**Comment by jaklan** [comment]
`target` also should be `string`, not `path` 😉

**Comment by dbeatty10** [comment]
Good catch @jaklan!

Added the fix to this draft PR: https://github.com/dbt-labs/docs.getdbt.com/pull/5112/commits/f1730c3501b3445fe3648d66fc95b68d8d38d563

**Comment by runleonarun** [comment]
>  Doug E. Fresh 😎

😆 You need to use this all the time now.

**Comment by dbeatty10** [comment]
Thanks again @jaklan 🏆 

The updates are live [here](https://docs.getdbt.com/reference/global-configs/about-global-configs#available-flags) now.
