### ISSUE TITLE
Node selection mental model

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#514]
It feels like there's endless appetite to provide explanation and example for when resource selection feels counterintuitive. I think we have a lot to gain from laying out exactly the way that node selection _does_ work:

1. dbt selects any resource that is matched by one or more of the `--models`/`--select` criteria, in the order of selection methods (e.g. `tag:`), then graph operators (e.g. `+`), then set operators (`,`). The selected resources may be models, sources, seeds, snapshots, tests. _IFF the command is `dbt test`, dbt also selects any test that directly depends on a selected resource._
2. dbt de-selects any resource that is matched by one or more of the `--exclude` criteria. _IFF the command is `dbt test`, dbt also de-selects any test that directly depends on an excluded resource._
3. dbt now has a list of still-selected resources of varying types. As a final step, it tosses away any resource that does not match the resource type of the current invocation. (Only seeds are kept for `dbt seed`, only models for `dbt run`, only tests for `dbt test`, and so on.)

Things like test selection and the `source:` selection method feel tricky because they intersect with this process is ways that can feel quite different from `dbt run -m my_model`. Rather than write more about each edge case, I think we need to build the mental model, so that they seem less like "exceptions" to rote-memorize and more like tricky cases that are still consistent with the overall schematic.

(Note that step 2 works a bit different for YAML selectors because the `exclude:` key subtly differs from `--exclude`, in order to power more complex set logic. That's briefly documented [here](https://docs.getdbt.com/reference/node-selection/yaml-selectors/#exclude).)

**Comment by clrcrl** [comment]
Or.... we could make the feature simpler :)

**Comment by runleonarun** [comment]
@joellabes and @jtcohen6 is this request still valid?

**Comment by joellabes** [comment]
Yes please! Happy to help work with someone as a technical resource

**Comment by mirnawong1** [comment]
closing issue adn linked pr as content exists here: https://docs.getdbt.com/reference/node-selection/syntax#how-does-selection-work
