### ISSUE TITLE
[Core] Stand-alone page for upgrade guides for older versions

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#5222]
### Link to the page(s) on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/dbt-versions/core-upgrade

### Tell us more about this update

If you click on the tile for "🗃️ Older versions - 12 items", it will take you directly to the page for [0.11.0](https://docs.getdbt.com/docs/dbt-versions/core-upgrade/Older%20versions/upgrading-to-0-11-0) rather than a page enumerating all the older version guides.

The older versions _are_ available on the left hand side, but it was outside of my view and I needed to scroll down to see them:
<img width="694" alt="image" src="https://github.com/dbt-labs/docs.getdbt.com/assets/44704949/dde23df2-0236-4f77-8d43-4974cdfb987c">

### Reviewers/Stakeholders/SMEs

.

**Comment by runleonarun** [comment]
I think this is an easy fix messing with the sidebar.js.

**Comment by mirnawong1** [comment]
hey @dbeatty10 , thanks for opening this up! I've [checked with the web team](https://dbt-labs.slack.com/archives/C05L8R8UC3H/p1730737919361949) and it seems like creating a landing page is a bit more complicated than we thought. given the low number of visitors and the fact that docusaurus has a open git issue that would fix this, I'm going to go ahead and close this issue out.
