### ISSUE TITLE
Incremental models in-depth -- Broken link.

### ISSUE THREAD

**Issue by ialdg** [fishtown-analytics/docs.getdbt.com#5240]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/best-practices/materializations/4-incremental-models

### What part(s) of the page would you like to see updated?

Hi.
The following link is broken:
https://docs.getdbt.com/best-practices/materializations/reference/resource-configs/full_refresh
My proposal is to replace it for this:
https://docs.getdbt.com/reference/resource-configs/full_refresh
Regards.
IL.

**Comment by mirnawong1** [comment]
thanks for catching this and opening up the issue @ialdg ! I've opened a pr to fix this up: https://github.com/dbt-labs/docs.getdbt.com/pull/5253
