### ISSUE TITLE
dbt Python Models new config: external_access_integrations

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#5270]
See this issue 
https://github.com/dbt-labs/dbt-snowflake/pull/955#issuecomment-2050647754

**Comment by ernestoongaro** [comment]
Hi @runleonarun I have PR for this: https://github.com/dbt-labs/docs.getdbt.com/pull/5262

**Comment by runleonarun** [comment]
Closed by https://github.com/dbt-labs/docs.getdbt.com/pull/5262
