### ISSUE TITLE
Add link to the bottom of every page on the docs that links to the page in the repo

### ISSUE THREAD

**Issue by emilieschario** [fishtown-analytics/docs.getdbt.com#53]
## Expected results:

When I see a problem on the docs page, I want to be able to scroll all the way to the bottom to take me to the page in the repo for me to create a PR to fix it. 

## Actual results
I have to go digging through the repo

## Extra details
Example implementation (I am totally spoiled): https://about.gitlab.com/handbook/ceo/chief-of-staff-team/
<img width="506" alt="Screen Shot 2020-03-23 at 10 54 46" src="https://user-images.githubusercontent.com/14057155/77329704-bbfd9680-6cf4-11ea-8a5e-8c2bfd379786.png">

**Comment by drewbanin** [comment]
Hey @emilieschario - we have a link at the bottom of each page that says "Edit this page" currently! Were you thinking of something different?

<img width="1450" alt="Screen Shot 2020-03-23 at 11 02 54 AM" src="https://user-images.githubusercontent.com/1541139/77330574-ec920000-6cf5-11ea-9a7c-4be696218a8a.png">

**Comment by emilieschario** [comment]
@drewbanin I was just looking for it in the footer and my eyes glazed over that. Sorry for the extra issue! Will close
