### ISSUE TITLE
Snowflake Partner Connect has moved

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#5338]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/guides/sl-snowflake-qs?step=5

### What part(s) of the page would you like to see updated?

![image](https://github.com/dbt-labs/docs.getdbt.com/assets/7335046/8e40ff00-2b07-4f47-81fa-fc2dec649def)
![image](https://github.com/dbt-labs/docs.getdbt.com/assets/7335046/36a1d02d-8379-4fa8-b5e3-52241c8c6ddd)

Our guide says to go to Admin > Partner Connect, but it is now in Data Products > Data Connect https://docs.snowflake.com/en/user-guide/ecosystem-partner-connect#connecting-with-a-snowflake-partner

This is presumably a problem in multiple places but I noticed it on the SL guide.

**Comment by mirnawong1** [comment]
also closing as the pr above addressed this!
