### ISSUE TITLE
SL quickstart guide gives confusing advice for IDE users

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#5341]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

I'm preparing for the Semantic Layer training session next week by doing the quickstart. I'm on the [Test and query metrics](https://docs.getdbt.com/guides/sl-snowflake-qs?step=12) step

### What part(s) of the page would you like to see updated?

It says 
>dbt Cloud IDE users — Currently, running MetricFlow commands directly in the dbt Cloud IDE isn't supported, but is coming soon. 

So far so good. But then that same paragraph says 
>You can still validate metrics using the Preview or Compile options

What does this mean? I can't run SL commands by Previewing/Compiling a scratchpad can I? 

Also there's a section where it says 
>Validate your metrics using the Lineage tab in the IDE.

and I wouldn't use the word "validate" there either - sure it'll show them in context, but it doesn't mean that they work :thinking_face: I guess they will show an error if you have invalid code, but if that's what we're going for then I think it should be rephrased. 

### Additional information

Maybe it should say "the dbt Cloud IDE will show an error icon in the bottom right of the page if there is an error. You can click it to see the specific issue and resolve it."

**Comment by mirnawong1** [comment]
closing this as it was addressed in the PR above!
