### ISSUE TITLE
Release note improvements 

### ISSUE THREAD

**Issue by matthewshaver** [fishtown-analytics/docs.getdbt.com#5377]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/dbt-versions/2024-release-notes

### What part(s) of the page would you like to see updated?

hey @matthewshaver , great job and thanks so much for consolidating this! I've got some feedback on the layout:

- structure &mdash; maybe we can have a more consistent, clean layout that makes it easy to distinguish between different types of updates (new features, enhancements, fixes). i think if we use headers and subheaders, it might allow us to bulk related topics inside the header (e.g. all the 'new' goes under the `## new` header, etc. i also wonder if we can consider adding icons or colo to visually separate different sections?
- expandable &mdash;  maybe we can indent the expandable so its in line with the bullets. currently it's looking all weird. i also wonder if we can have the expendables grouped grouped together so it doesn't interrupt the bullet bullet bullet,etc flow?  
- right toc &mdash; might be good to have a right toc so users can quickly navigate?
- intro &mdash; nice-to-have a more fleshed-out intro sentence?

# example

### What’s new:
- Merge jobs [Beta] - Trigger dbt job runs via Git pull requests....
- Semantic Layer enhancements - Additional support for Privatelink and SSO....

### Enhancements:
- Select entities for group by, filter by, and order by in Semantic Layer...,

### Fixes:

- Resolved dbt parse error when using list filters.
- Improved join_to_timespine application in metrics.

**Comment by matthewshaver** [comment]
@mirnawong1 Great feedback and good ideas worth considering. We currently have an Asana task open to fix the formatting errors for the lifecycle pills so we can use those in front of the items. 

As for the grouping, we need to take into consideration that these will be grouped by week once we go live (based on customer requests for release notes). We've taken the historical data and grouped it by Month but when we go live it will look more like this:

## MONTH
### WEEK 1
- **New:** Feature
- **Fix:** Feature
- **Enhancement:** Feature

### WEEK 2
- **New:** Feature
- **Fix:** Feature
- **Enhancement:** Feature

and so on

Let's bring it to the group when I get back and figure out what we think is the best way to group in that context.

Right TOC - will be adding that, but the automation removes it from that section, so we have to figure out a way to put it back. If you have ideas, I'm open to them. 

Intro - it's a pretty straightforward section, so I kept it simple, but I'm open to any additional language you think would be good. 

**Expandables have been addressed in a separate PR**

**Comment by runleonarun** [comment]
@matthewshaver and @mirnawong1 I agree it's a little challenging to glance at. Looking forward to this discussion in a couple of weeks.

I wonder if there's an in between that might work:

## MONTH

### WEEK 1
New
* Feature 1
* Feature 2

Fix
* Feature 1 
* Feature 2

Enhancement
* Feature 1

**Comment by matthewshaver** [comment]
We're all on the same page with this but closing the issue as the only thing holding us back is the timeliness with which we get release notes. Once we have that figured out we can implement, but clearing up our backlog of issues here
