### ISSUE TITLE
Correct flag indirect selection.

### ISSUE THREAD

**Issue by ialdg** [fishtown-analytics/docs.getdbt.com#5394]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/global-configs/indirect-selection

### What part(s) of the page would you like to see updated?

Hi. At the beginning of the docs, this text is displayed:
"Use the **--indirect_selection** flag to dbt test or dbt build to configure which tests to run for the nodes you specify. You can set this as a CLI flag or an environment variable. In dbt Core, you can also configure user configurations in [YAML selectors](https://docs.getdbt.com/reference/node-selection/yaml-selectors) or in the flags: block of dbt_project.yml, which sets project-level flags."
It should be replaced by this:
"Use the **--indirect-selection** flag to dbt test or dbt build to configure which tests to run for the nodes you specify. You can set this as a CLI flag or an environment variable. In dbt Core, you can also configure user configurations in [YAML selectors](https://docs.getdbt.com/reference/node-selection/yaml-selectors) or in the flags: block of dbt_project.yml, which sets project-level flags."
Also it would be a good idea to add the "edit" option to the website.
Regards.
IL.

**Comment by matthewshaver** [comment]
Thanks, @ialdg Fixing it. 

> Also it would be a good idea to add the "edit" option to the website.

All of our page do have an "edit this page" option at the bottom. It's a little difficult to find, we're working on ways to make it better
