### ISSUE TITLE
Update SL Dimensions SCD section to comply with the validation rules

### ISSUE THREAD

**Issue by SOVALINUX** [fishtown-analytics/docs.getdbt.com#5395]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/build/dimensions

### What part(s) of the page would you like to see updated?

Current'y it's not very clear how to properly use SCD dimensions:  
1. In the top table in `type` field we say "There are three types", but in YML there are only 2 options possible, which is fine, but quite confusing
2. In all dimension examples it's shown `metric_time` as a dimension, however it's a reserved word and such dimension is not allowed
3. `Note: The SCD dimensions table must have valid_to and valid_from columns.` -- it's not clear if these columns are really physically should exist or just configured via `validity_params : is_start / is_end`

**Comment by mirnawong1** [comment]
update - we've merged a PR https://github.com/dbt-labs/docs.getdbt.com/pull/5409 which addressed this feedback - i really appreciate it!

**Comment by SOVALINUX** [comment]
Thanks for the quick improvement @mirnawong1 !  
However let me reopen the issue with some feedback:  
1. I see the change of `metric_time` in one place in the doc, however simple page search gives 17 more occurences - I'm sure many of them should be adjusted as well  
2. Overall it would be fantastic to put there some working examples, not some direction of the yml from previous versions. It's still not clear what is required and with what name based on your examples. Let me be specific here:   
a) `entity_key (required): An entity_key (or some sort of identifier) must be present.` -- how I should interpret it? To have any `entity` of any `type` or having dimension with the name `entity_key`?  
b) `valid_from` and `valid_to` that are required: should I have 2 dimensions named exactly like these or should I mark them via `validity_params: is_start/is_end`?  

Really sorry for bothering you with it. A bit on the background: I'm running multiple projects with DBT for 2+ years, maintaining a dbt fork and consider myself quite an experienced used, and I still can't deal with these SCD2 dimensions without looking into the metricflow code, that's why I decided to help community and open this doc improvement request.  
I know that this is not a error debug channel, but here is the error I have (maybe it will give you a hint where it's needed to update the docs, so users do know how to deal with it :) ):
`ERROR: Cannot process join to data set with alias subq_9 because it has a validity window set: ValidityWindowJoinDescription(window_start_dimension=TimeDimensionSpec(element_name='valid_from', entity_links=(), time_granularity=TimeGranularity.DAY, date_part=None, aggregation_state=None), window_end_dimension=TimeDimensionSpec(element_name='valid_to', entity_links=(), time_granularity=TimeGranularity.DAY, date_part=None, aggregation_state=None)), but source data set with alias subq_7 does not have a metric time dimension we can use for the window join!`

**Comment by mirnawong1** [comment]
hey @SOVALINUX thanks so much for the detailed write up - no worries at all and i appreciate you providing more context and looking out for the community ✨ - I'm going to look into this next week and see how can make this clearer for you. will revert back and thank you again! 

with regards to your error, I'm going to flag this to the team internally to see what they say!

**Comment by mirnawong1** [comment]
also wanted to mention that we're merging this pr today which may be a little related: https://github.com/dbt-labs/docs.getdbt.com/pull/5350/files#diff-fc3ac6b16bd26fe485beef2324ef300d38959f05522372a9e5eb9e2ea66677c1R230

**Comment by mirnawong1** [comment]
hey @SOVALINUX , thanks for your patience and I've checked with the internal team on this. if you're getting this error, it could be due to the following possibilities:

- You need to group by metric_time. If this solves the problem, please let me know so i can pass the info to the team to see if we can improve the error message. 
- Have you run a group-by-only query? If so, we might need to see how we're handling the SCD join scenario. A possible workaround for now is including metric time and filtering to a single metric time value.

Let me know if that helps solve the error you're seeing!

**Comment by mirnawong1** [comment]
hey @SOVALINUX ! sorry for the delay here and I'm working to confirm and clarify this next week!

**Comment by mirnawong1** [comment]
hey @SOVALINUX , i've opened up a pr to clarify the validity_params confusion - i hope it clarifies how `valid_to/valid_from` aren't  part of the config and its relation to `validity_params`. thank you again and let me know if you have any feedback on this!
