### ISSUE TITLE
Improve SL metrics examples

### ISSUE THREAD

**Issue by SOVALINUX** [fishtown-analytics/docs.getdbt.com#5396]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/build/metrics-overview

### What part(s) of the page would you like to see updated?

There is an inconsistency with `filter` field indentation. 
In the top schema definition it's on the 1st level, but in some examples below `filter` is put into `type_params` at 2nd or 3rd level, what looks incorrect and fails at validation stage.  
Also it would be useful to emphasize that only multi-line YML format is supported by filter field and single-line won't work

**Comment by mirnawong1** [comment]
tested and confirmed
![Screenshot 2024-04-30 at 12 37 36](https://github.com/dbt-labs/docs.getdbt.com/assets/89008547/df24867d-eb00-4847-8c0f-3b7055f027d0)

**Comment by mirnawong1** [comment]
hey @SOVALINUX  thanks for opening this up! you're absolutely right and I'm working on a pr to get this updated. can you provide more info on what you mean with "multi-line YML format is supported by filter field and single-line won't work"?

**Comment by SOVALINUX** [comment]
Re "multi-line YML format is supported by filter field and single-line won't work":
Looks like I was not right with this statement  
1. `filter: {{ Dimension('some_model__some_dimension') }} = true` - one-line no quotes doesn't work, but probably it's according to YML spec.
2. `filter: "{{ Dimension('some_model__some_dimension') }} = true"` - one-line double quoted works well (and I had a feeling that this also didn't work for me initially)
3. multi-line filter as in doc examples works as expected

So, thanks for checking - please disregard this part

**Comment by mirnawong1** [comment]
that's great, thanks for confirming and coming back to update the issue @SOVALINUX ! we've merged a PR https://github.com/dbt-labs/docs.getdbt.com/pull/5409 which addressed your feedback - i really appreciate it!
