### ISSUE TITLE
Fix inconsistency in SL measures

### ISSUE THREAD

**Issue by SOVALINUX** [fishtown-analytics/docs.getdbt.com#5398]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/build/measures

### What part(s) of the page would you like to see updated?

Update description for the `agg` in the top table by adding `percentile` option there:  
Currently it's "dbt supports the following aggregations: sum, max, min, avg, median, count_distinct, and sum_boolean.", however in the page below it has the `percentile` option as well

**Comment by mirnawong1** [comment]
hey @SOVALINUX, thanks for opening this up! really appreciate it and I've flagged this internally and we'll work to clarify! ✨
