### ISSUE TITLE
Add flag to flags menu.

### ISSUE THREAD

**Issue by ialdg** [fishtown-analytics/docs.getdbt.com#5402]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/global-configs/indirect-selection

### What part(s) of the page would you like to see updated?

Hi. If you reach the previous link, you can see that that particular flag doesn't appear in the flags menu. See the attached screenshot.
It would be a good idea to add it.
Regards.
IL.
![indirect_selection](https://github.com/dbt-labs/docs.getdbt.com/assets/39755524/16cce190-3a60-4a1b-a831-4040f3bc3a48)

**Comment by matthewshaver** [comment]
Closing as this has since been added to the menu
