### ISSUE TITLE
Ration metrics page: Remove extra property

### ISSUE THREAD

**Issue by SOVALINUX** [fishtown-analytics/docs.getdbt.com#5442]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/build/ratio

### What part(s) of the page would you like to see updated?

In the `add filter` section there is an extra property `owners` that is not supported and results in the validation error.  
`owners: - support@getdbt.com`

**Comment by mirnawong1** [comment]
thanks @SOVALINUX , i'm getting this as well! confirming with the team internally to address this.
