### ISSUE TITLE
Rename class methods to implement in adapter plugins

### ISSUE THREAD

**Issue by gansanay** [fishtown-analytics/docs.getdbt.com#546]
The documentation (https://docs.getdbt.com/docs/contributing/building-a-new-adapter) mentions 4 methods to implement in a new adapter plugin:
- `open`
- `get_status`
- `cancel`
- `exception_handler`

Actually, the inline documentation in https://github.com/fishtown-analytics/dbt/blob/dev/margaret-mead/core/dbt/adapters/sql/connections.py lists the 4 following methods, existing as abstract in `SQLConnectionManager`:
- `exception_handler`
- `cancel`
- `get_response`
- `open`

From the code, it looks like `get_status` has just been renamed as `get_response` and the fix is mainly consisting in a s/status/response in the docs.

I can provide a PR linked to this issue if you agree with this conclusion.

**Comment by jtcohen6** [comment]
You're right on @gansanay! We just renamed `get_status` to `get_response` in the last version of dbt (v0.19.0, released last week). I missed this during the associated docs updates, I'd welcome a PR to update it now :)
