### ISSUE TITLE
Add manifest v12 for dbt Core v1.8 / dbt Cloud KoLV

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#5525]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/artifacts/manifest-json

### What part(s) of the page would you like to see updated?

dbt Core v1.8 is using manifest v12

### Additional information

https://schemas.getdbt.com/dbt/manifest/v12/index.html

**Comment by dbeatty10** [comment]
Draft PR here: https://github.com/dbt-labs/docs.getdbt.com/pull/5526

Here's what the table looks like currently:

| dbt Core version | Manifest version |
|:----------------:|:----------------:|
| v1.7             | v11              |
| v1.6             | v10              |
| v1.5             | v9               |

Here's what it will look like after adding one new row:

| dbt Core version | Manifest version |
|:----------------:|:----------------:|
| v1.8             | v12              |
| v1.7             | v11              |
| v1.6             | v10              |
| v1.5             | v9               |

Do we also want to add a new column to indicate which manifest schema version is associated with dbt Cloud KoLV (Keep on Latest Version)?

| dbt Core version | dbt Cloud KoLV | Manifest version |
|:----------------:|:----------------:|:----------------:|
| v1.8             |        ✅       | v12              |
| v1.7             |                | v11              |
| v1.6             |                | v10              |
| v1.5             |                | v9               |

**Comment by mirnawong1** [comment]
@dbeatty10 i love the table idea! i'm going to loop in the docs leads here (@matthewshaver and @nghi-ly). if I'm understanding this correctly, i wonder if it's easier to just have a sentence in there somewhere so it's clear that kolv = latest manifest version.  that way we don't have to maintain the column for every new version?

'e.g. if you select 'Keep on latest version,' you'll always use the newest dbt Core version and its corresponding manifest schema. for example, if the latest dbt Core version is v1.8 with a manifest schema of v12, then 'Keep on latest version' will use manifest schema v12.'
