### ISSUE TITLE
add is_incremental as additional example of when you will need to force dependencies 

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#5547]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/dbt-jinja-functions/ref#forcing-dependencies

### What part(s) of the page would you like to see updated?

We already have an example for when you need to force dependencies - a model that only has a macro.

Let's also add an example for when references are wrapped in the `is_incremental()` macro - see [slack thread](https://dbt-labs.slack.com/archives/C05FWBP9X1U/p1716406069131559?thread_ts=1716344292.510149&cid=C05FWBP9X1U). 

Dependencies nested in the `is_incremental` macro will not show up in lineage, so will need to force dependencies in that case.

### Example

If you have an incremental model that includes a snippet like below, then you will not be able to see the `source('raw', 'orders')` upstream dependency in the lineage.

```sql
{% if is_incremental() %}
select * from {{ source('raw', 'orders') }}
{% endif %}
```

This is because the `is_incremental` macro will always return false at parse time, so anything buried inside that will not be available to parsing, so will not be added to `depends_on`.

So in this case, you'd need to do [force a dependency](https://docs.getdbt.com/reference/dbt-jinja-functions/ref#forcing-dependencies) _outside_ of the `is_incremental()` conditional like this instead:

```sql
 -- depends_on: {{ source('raw', 'orders') }}

{% if is_incremental() %}
select * from {{ source('raw', 'orders') }}
{% endif %}
```

**Comment by runleonarun** [comment]
Thanks @graciegoheen! Anything you think we should add to the [is_incremental](https://docs.getdbt.com/docs/build/incremental-models#understand-the-is_incremental-macro) macro docs?

**Comment by graciegoheen** [comment]
No I think this is enough!
