### ISSUE TITLE
[Bug] Enhance Log Formatting Documentation

### ISSUE THREAD

**Issue by iamtodor** [fishtown-analytics/docs.getdbt.com#5577]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Per documentation from https://docs.getdbt.com/reference/global-configs/logs#log-formatting

> If the value of this config is json, dbt will output fully structured logs in [JSON](https://docs.getdbt.com/terms/json) format; otherwise, it will output text-formatted logs that are sparser for the CLI and more detailed in logs/dbt.log.

I propose to add all allowed values as well as specifying the default one.

Similar to https://docs.getdbt.com/reference/global-configs/logs#log-level 

> This is a more flexible alternative to the --debug flag. The available options for the log levels are debug, info, warn, error, or none.

### Expected Behavior

Unambiguous and clear documentation

### Steps To Reproduce

Not applicable

### Relevant log output

```shell
Not applicable
```

### Environment

```markdown
Not applicable
```

### Additional Context

Documentation only

**Comment by iamtodor** [comment]
On the new issue template page https://github.com/dbt-labs/dbt-core/issues/new/choose, there is no documentation category, so I did my best to select the most appropriate one

<img width="1187" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/12586108/8ad26347-0ab5-44b2-9fa0-551fcd6462dd">

**Comment by iamtodor** [comment]
Also, from my perspective, it would be nice to add the possibility of adding a documentation issue, similar to Airflow templates https://github.com/apache/airflow/issues/new/choose

<img width="1186" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/12586108/e47e12a5-3c45-4b35-9f46-0263bc75b8c8">

**Comment by dbeatty10** [comment]
Thanks for reaching out @iamtodor !

https://github.com/dbt-labs/docs.getdbt.com is our repository for our documentation website, so I've transferred this issue accordingly.

We haven't had much other feedback about adding an "Open" button that links to our [documentation issue templates](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), but that would be easy to do without much downside.

It would be just adding a snippet like the following in [`github/ISSUE_TEMPLATE/config.yml`](https://github.com/dbt-labs/dbt-core/blob/main/.github/ISSUE_TEMPLATE/config.yml):
```yaml
  - name: Documentation
    url: https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose
    about: Problems and issues with dbt documentation
```

I opened https://github.com/dbt-labs/dbt-core/pull/10239 within the dbt-core repo to add this to the issue types.
