### ISSUE TITLE
[Core] Add `time_granularity` to metric spec

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#5790]
At a minimum, update body to include a link to the page on docs.getdbt.com requiring updates and what part(s) of the page you would like to see updated.

Issue: https://github.com/dbt-labs/dbt-core/issues/10376

PR: https://github.com/dbt-labs/dbt-core/pull/10378

**Comment by nghi-ly** [comment]
@nataliefiann : per our meeting with DX, this might already be done. please double-check. if done, we can close.

**Comment by nataliefiann** [comment]
Hiya @courtneyholcomb 

Happy Monday - I hope you're well.

I just wanted to ask if this still needs a docs update?

Kind Regards
Natalie

**Comment by courtneyholcomb** [comment]
> Hiya [@courtneyholcomb](https://github.com/courtneyholcomb)
> 
> Happy Monday - I hope you're well.
> 
> I just wanted to ask if this still needs a docs update?
> 
> Kind Regards Natalie

@nataliefiann Nope, this is in the docs already!
