### ISSUE TITLE
[dbt-core issue #10301] snapshots now can optionally respect generate schema/database/alias macros

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#5805]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

We need to update our snapshot documentation. Here's some initial pages I've identified as needing updates:
- https://docs.getdbt.com/docs/build/snapshots
- https://docs.getdbt.com/faqs/Snapshots/snapshot-target-schema
- https://docs.getdbt.com/reference/snapshot-configs
- https://docs.getdbt.com/reference/snapshot-properties
- https://docs.getdbt.com/reference/resource-configs/target_database (delete or add warning that this is an old config?)
- https://docs.getdbt.com/reference/resource-configs/target_schema (delete or add warning that this is an old config?)
- https://docs.getdbt.com/reference/resource-configs/database (add snapshot example)
- https://docs.getdbt.com/reference/resource-configs/schema (add snapshot example)

I think we likely want to remove `target_schema` and `target_database` configs from all of our snapshot examples - perhaps replace those with `schema` and `database`.

I think our best practice is still building your snapshots in a separate `schema` to avoid accidentally dropping them. They are not like models where if you drop them you can just rebuild them; dropping snapshots leads to losing all of your historical data.

### What part(s) of the page would you like to see updated?

Historically, snapshots require you set set an explicit `target_schema` (you can also set an explicit `target_database`) - meaning by default, regardless of what environment you're in (dev, ci, prod, etc.), when you run `dbt snapshot` it will build to the same table.

This can be problematic when trying to test out changes to existing snapshot or develop a new snapshot. Now that we have deferral and `dbt clone`, it no longer makes sense that snapshots wouldn't respect `generate_schema_name` / `generate_database_name`/ `generate_alias_name` like other resources (models, seeds, etc.).

Changes:
- `target_schema` is **now optional** for snapshots
- if you do not set `target_schema`, your snapshot will respect `generate_schema_name` macro
- if you do not set `target_database`, your snapshot will respect `generate_schema_name` macro
- old behavior continues to work for backwards compatibility: so you _can still_ set `target_schema` and/or `target_database` and that will be where your snapshot is built, but these are "old" configs
- new configs for `snapshots`: you can now set `database`, `schema`, `alias` for your snapshots to be used by the `generate_x_name` macros

### Additional information

From dbt-core issue https://github.com/dbt-labs/dbt-core/issues/10301

**Comment by noel** [comment]
Is this a typo?
`if you do not set target_database, your snapshot will respect generate_schema_name macro`

Would it be?
`if you do not set target_database, your snapshot will respect generate_database_name macro`
