### ISSUE TITLE
Does DBT Cloud Connect Apache Spark support SSH tunnel? 

### ISSUE THREAD

**Issue by alberttwong** [fishtown-analytics/docs.getdbt.com#5813]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/cloud/connect-data-platform/connect-apache-spark

### What part(s) of the page would you like to see updated?

Does DBT Cloud Connect Apache Spark support SSH tunnel? The redshift docs at https://docs.getdbt.com/docs/cloud/connect-data-platform/connect-redshift-postgresql-alloydb shows an example with ssh tunnel.

**Comment by matthewshaver** [comment]
Hi @alberttwong I asked internally and we don't at this time but we will document it on the linked page if it becomes available.
