### ISSUE TITLE
Review `dbt sl validate-configs` example command

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#5907]
### Contributions

- [x] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/build/validation#validations-command

### What part(s) of the page would you like to see updated?

This command didn't work for me when using the dbt Cloud CLI:

```shell
dbt sl validate-configs
```

<img width="773" alt="image" src="https://github.com/user-attachments/assets/1843f9d0-40e7-4e02-ac53-54e671890ac0">

```
$ dbt --version
dbt Cloud CLI - 0.38.7 (4f04e422469d123457c0dc15d08498399ef625cd 2024-07-30T18:36:03Z)
```

### Additional information

This looks like relevant info:
https://docs.getdbt.com/docs/build/metricflow-commands#validate-configs

**Comment by mirnawong1** [comment]
hey @dbeatty10 ! do you mean that we should clarify `dbt sl validate-configs` isn't supporte in the cloud cli? we have this info here but maybe it's not clear:

> Note, in dbt Cloud you don't need to validate the Semantic Layer config separately. Running a dbt command (such as dbt parse, dbt build, dbt compile, or dbt run) automatically checks it.

[internal slack thread](https://dbt-labs.slack.com/archives/C03KHQRQUBX/p1722534816137609?thread_ts=1722215844.627059&cid=C03KHQRQUBX) for reference

**Comment by dbeatty10** [comment]
Resolved by https://github.com/dbt-labs/docs.getdbt.com/pull/5887 💪
