### ISSUE TITLE
Screenshot for versionless/keep on latest is out of date

### ISSUE THREAD

**Issue by emmyoop** [fishtown-analytics/docs.getdbt.com#5951]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/dbt-versions/upgrade-dbt-version-in-cloud#environments

### What part(s) of the page would you like to see updated?

The screen shot drop down for dbt version under the Environments header uses "Keep on Latest" but in cloud its now "Versionless"

### Additional information

We link directly to this section from Cloud in the "Show me how to update to Versionless" link

**Comment by mirnawong1** [comment]
fix here: https://docs-getdbt-pn31flcwx-dbt-labs.vercel.app/docs/dbt-versions/upgrade-dbt-version-in-cloud
