### ISSUE TITLE
Broken links to 2023 Coalesce resources

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#6013]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://www.getdbt.com/blog/coalesce-2023-deliver-value-for-your-data-team

### What part(s) of the page would you like to see updated?

All the links lead to a 404 -- Is there a way for us to wander _back_ to the fun?!

<img width="658" alt="image" src="https://github.com/user-attachments/assets/6b810604-34cb-4242-bbbb-652f7cfd4418">

**Comment by mirnawong1** [comment]
great flag! i'm going to raise this with the frontend team since this relates to the getdbt.com blog site and not our devhub blog site. thank you for raising this @dbeatty10 - super important we get this sorted! will close this out

**Comment by mirnawong1** [comment]
Asana task raised here for frontend team: https://app.asana.com/0/0/1208235363557256/f
