### ISSUE TITLE
Update end user docs structure for Behavior Flags

### ISSUE THREAD

**Issue by mikealfare** [fishtown-analytics/docs.getdbt.com#6048]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/global-configs/behavior-changes
and/or platform-specific configs, e.g.
https://docs.getdbt.com/reference/resource-configs/redshift-configs

### What part(s) of the page would you like to see updated?

Until recently, behavior flags only existed at the `dbt-core` level.
However, we now have adapter behavior flags and platform-specific flags.
The general adapter behavior flags can probably go with the `dbt-core` behavior flags.
However, the platform-specific flags need a home.
They don't feel quite right in the general [page](https://docs.getdbt.com/reference/global-configs/behavior-changes) since platform-specific config is usually in it's own page.
But we still want to be able to reference one from the other so that users can get the whole picture.
We also need to be aware of the fact that third party adapters may be creating their own
behavior flags as the new framework allows that.
So we need to make sure that they have direction on where to put that documentation,
and maybe even a suggestion of what that documentation should look like.

**Comment by amychen1776** [comment]
@matthewshaver and I figured this out so closing this out!
