### ISSUE TITLE
Enterprise permissions - grant users elevated access

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#6060]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

In this [internal slack thread](https://dbt-labs.slack.com/archives/C02N953LRDF/p1726233905620939?thread_ts=1726218302.268479&cid=C02N953LRDF), you can grant users elevated write perms on jobs/runs for specific environment categories (dev, prod, staging, etc) within target projects using our new [environment level permissions feature](https://docs.getdbt.com/docs/cloud/manage-access/environment-permissions).

I wonder if we should mention that somewhere on the permissions page either via a callout or something?

### What part(s) of the page would you like to see updated?

https://docs.getdbt.com/docs/cloud/manage-access/enterprise-permissions#project-permissions-for-project-roles

**Comment by matthewshaver** [comment]
Addressed this when we updated the [access page](https://docs.getdbt.com/docs/cloud/manage-access/about-user-access#permissions)
