### ISSUE TITLE
[Core] Microbatch: event_time ref + source filtering

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#6063]
At a minimum, update body to include a link to the page on docs.getdbt.com requiring updates and what part(s) of the page you would like to see updated.

PR: https://github.com/dbt-labs/dbt-core/pull/10594
Issues: lots of them (see list within PR)

Applies to these dbt subcommands:
- `dbt run`
- `dbt build`

**Comment by nataliefiann** [comment]
Hiya @MichelleArk 

I hope you're well.

Just so I have an understanding here, can you let me know what you'd like updating on this please? 

Kind Regards
Natalie

**Comment by MichelleArk** [comment]
We don't need a standalone docs update here! It will be part of the broader microbatch documentation.
