### ISSUE TITLE
Create an "older versions" page and link to it

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#6130]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/dbt-versions/core-upgrade

### What part(s) of the page would you like to see updated?

Clicking on the "Older versions" tile should go to a stand-alone page that has a listing of the older versions:

<img width="514" alt="image" src="https://github.com/user-attachments/assets/4396d51f-b0ed-42b1-90a9-e3152a973ee0">

As it currently stands, it links to [this page](https://docs.getdbt.com/docs/dbt-versions/core-upgrade/Older%20versions/upgrading-to-v1.4) instead, which was unexpected.

The only way to get to a specific older version is to use the navigation menu on the left:

<img width="157" alt="image" src="https://github.com/user-attachments/assets/47b93e97-21bc-4a03-a8c2-3f67489f4944">

**Comment by mirnawong1** [comment]
hey @dbeatty10 , thanks for raising this! I've spent a couple of days looking at this and it looks like if we add an autogenerated index config, docusaurus duplicates the 'older versions' subfolder. They have an [open git issue](https://github.com/facebook/docusaurus/issues/5689) but we're not sure how to exclude a specific file/directory from being included when using the auto-generated sidebar. also, in terms of viewership - in the past 6 months we've seen ~ 2,009 distinct users view the older versions guides.

i think based on the workload needed and numbers, the best course of action is to close this issue out and come back to it if we get more people viewing them or a solution pops up. does that work @dbeatty10 ?

**Comment by mirnawong1** [comment]
![Screenshot 2024-11-05 at 14 35 43](https://github.com/user-attachments/assets/164ce7f1-b532-4475-9d23-b4f8175cdbe1)
