### ISSUE TITLE
[Core] Add content to v1.9 upgrade guide for beta

### ISSUE THREAD

**Issue by mirnawong1** [fishtown-analytics/docs.getdbt.com#6159]
### Link to the page(s) on docs.getdbt.com requiring updates

Add any relevant content to v1.9 upgrade guide for upcoming beta

### Tell us more about this update

Please use the following template as guidance (@matthewshaver will have more info): https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.8

### Reviewers/Stakeholders/SMEs

@graciegoheen 
@jtcohen6

**Comment by graciegoheen** [comment]
Now that adapters are decoupled from core.. should the `1.9` guide only focus on new "core" features (microbatch, snapshot improvements, etc.) or should it include "adapter" features still also (iceberg table format, etc.)? 

cc: @jtcohen6

**Comment by graciegoheen** [comment]
My very rough thoughts on what should go in this! (cc: @dbeatty10 @jtcohen6)

Big features to highlight:
- new microbatch `incremental_strategy`
    - new supporting configs (`event_time`, `begin`, `lookback`, `batch_size`
- improvements to snapshots
    - new snapshot spec (define in yml)
    - new `snapshot_meta_column_names` config for customizing name of meta fields
    - `target_schema` is now optional for snapshots - omit for environment-aware snapshots
    - add standard `schema`/`database` configs for snapshots
    - warning when `updated_at` is not proper data type / timestamp
    - [maybe] new way to track deletes (config etc.)
- [maybe] less false positives in `state:modified`
    - `state_modified_compare_more_unrendered_values`
    - `state_modified_compare_vars`

Small wins:
- can now add descriptions to singular data tests
- can use `ref` and `source` in foreign key constraints
- can use `--exclude-resource-type` + associated environment variable (and "include" opposites `--resource-type`) in `dbt test` command (for excluding unit tests in production)
- new `--inline-direct` parameter for 'dbt show'
- [adapters] data_test accepts arbitrary config options (allows you to set `snowflake_warehouse` for tests, as an example)
- [adapters] behavior flags

Other callouts:
- a reminder for Cloud folks to use versionless to get access to these new features
- a reminder that adapters have been decoupled with core (implications for installation)
- behavior change flag callouts!
- check with semantic layer team if there's anything to add! (time spines?) @Jstein77 
- check with adapters team if there's anything to add! @amychen1776
