### ISSUE TITLE
Mention sources "external:" property in the documentation

### ISSUE THREAD

**Issue by ecerulm** [fishtown-analytics/docs.getdbt.com#616]
## Steps to reproduce:
The [fishtown-analytics/dbt-external-tables/README.md](https://github.com/fishtown-analytics/dbt-external-tables/blob/master/README.md) says: 

> dbt v0.15.0 added support for an external property within sources that can include information about location, partitions, and other database-specific properties.

There is no mention of this property `external:` in the dbt documentation, I would expect a mention to it in one of this places:

* https://docs.getdbt.com/reference/source-configs
* https://docs.getdbt.com/reference/source-properties
* https://docs.getdbt.com/reference/dbt-jinja-functions/source

## Expected results:

I would expect to see at least 1 reference to the source's  `external` property in the documentation, at least mention it an point to https://github.com/fishtown-analytics/dbt-external-tables/blob/master/README.md,

**Comment by jtcohen6** [comment]
Added by #766!
