### ISSUE TITLE
Confusing use of the term "subdirectory" in the file `seed-paths`

### ISSUE THREAD

**Issue by davidculley** [fishtown-analytics/docs.getdbt.com#6163]
**I find the use of the word "subdirectory" (in line 22) confusing. I would say "directory" instead.**

https://github.com/dbt-labs/docs.getdbt.com/blob/711fc27acf7b5237be1e20d358cfbdaf5fb2a786/website/docs/reference/project-configs/seed-paths.md?plain=1#L22

Everywhere else, you actually refer to the `seeds/` directory as "directory" rather than "subdirectory", just not on line 22.

Evidence A:

https://github.com/dbt-labs/docs.getdbt.com/blob/711fc27acf7b5237be1e20d358cfbdaf5fb2a786/website/docs/reference/project-configs/seed-paths.md?plain=1#L15

Evidence B:

https://github.com/dbt-labs/docs.getdbt.com/blob/711fc27acf7b5237be1e20d358cfbdaf5fb2a786/website/docs/reference/project-configs/seed-paths.md?plain=1#L19

The use of the term "subdirectory" in line 22 gets even more confusing when you introduce actual subdirectories (for example, `seeds/one` and `seeds/two`) to avoid having to make changes to `seed-paths` and then refer to the directory `seeds/` on the root level of the project also as subdirectory (is it really a subdirectory when it's a directory at the root level?):

https://github.com/dbt-labs/docs.getdbt.com/blob/711fc27acf7b5237be1e20d358cfbdaf5fb2a786/website/docs/reference/project-configs/seed-paths.md?plain=1#L45

**Comment by matthewshaver** [comment]
Good call out! Thanks @davidculley
