### ISSUE TITLE
[Core] `state_modified_compare_more_unrendered_values` behavior change flag

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#6185]
### Link to the page(s) on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/global-configs/behavior-changes#behavior-change-flags

### Tell us more about this update

Epic: https://github.com/dbt-labs/dbt-core/issues/9562

Add new docs for this behavior change flag:
- `state_modified_compare_more_unrendered_values`

Issues: https://github.com/dbt-labs/dbt-core/issues/9564 and https://github.com/dbt-labs/dbt-core/issues/9573
PRs: https://github.com/dbt-labs/dbt-core/pull/10487 and https://github.com/dbt-labs/dbt-core/pull/10675

(The `state_modified_compare_vars` flag is covered by https://github.com/dbt-labs/docs.getdbt.com/issues/6202.)

### Reviewers/Stakeholders/SMEs

Grace, Michelle, Doug

**Comment by runleonarun** [comment]
that’s https://github.com/dbt-labs/dbt-core/issues/7387 (and https://github.com/dbt-labs/docs.getdbt.com/issues/6172 accompanying docs issue)

**Comment by dbeatty10** [comment]
The `state_modified_compare_vars` behavior change flag is covered by https://github.com/dbt-labs/docs.getdbt.com/issues/6202.
