### ISSUE TITLE
Documentation - Variables in Command Line - Example does not work on Windows 10

### ISSUE THREAD

**Issue by extrospective** [fishtown-analytics/docs.getdbt.com#620]
Ran sample code found in: https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-variables:

```
$ dbt run --vars 'key: value'
```

This generated an error.  "dbt: error: unrecognized arguments: value'"

What does work instead:
```
$ dbt run --vars "key: value"
```

I also had difficulty with some of the other sample commands in Windows command prompt, presumably due to quoting issues as well.

**Comment by runleonarun** [comment]
Closing and adding to the icebox for consideration at a later time.
