### ISSUE TITLE
[Core] Update docs on dbt-databricks constraints

### ISSUE THREAD

**Issue by togobingi** [fishtown-analytics/docs.getdbt.com#6250]
### Link to the page(s) on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-properties/constraints#platform-specific-support

### Tell us more about this update

The docs says: "As Databricks does not support transactions nor allows using `create or replace table` with a column schema, the table is first created without a schema, and `alter` statements are then executed to add the different constraints."

However, you can create and replace tables with a column schema as shown in the Databricks docs: https://docs.databricks.com/en/tables/constraints.html#set-a-not-null-constraint-in-databricks 

Implementing this approach would allow dbt to enforce constraints in Databricks by ensuring 'bad' data never gets inserted into the tables in the first place, which isn't exactly possible now.

### Reviewers/Stakeholders/SMEs

@mirnawong1

**Comment by mirnawong1** [comment]
thanks for opening this up @togobingi and appreciate the detailed description! I'm verifying internally and will get back to you here!

**Comment by mirnawong1** [comment]
hey @togobingi , thanks so much for opening this issue up! can you say more about how you came to this conclusion? I've just checked internally with the team and it looks like `dbt-databricks` doesn't currently support create/replace table with constraints, but it's on the backlog as a high priority. 

if you can clarify, i can work with the team to understand this more. many thanks!

**Comment by matthewshaver** [comment]
It's been a couple of months with no response. Closing for now but can reopen if necessary.
