### ISSUE TITLE
Instructions for setting up Slack notifications seems to refer to the old dbt Cloud UX

### ISSUE THREAD

**Issue by chrisweis** [fishtown-analytics/docs.getdbt.com#6322]
### Contributions

- [x] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/deploy/job-notifications#configure-slack-notifications

### What part(s) of the page would you like to see updated?

"From the gear menu, choose Notification settings."

What gear icon?

### Additional information

Instead it should probably be:
1. From **Account Settings**, under under **Notification Settings**, choose **Slack notifications**

**Comment by mirnawong1** [comment]
hey @chrisweis , great suggestion! i've opened a pr to update this and thank you for opening this issue up and bringing this to our attention!
