### ISSUE TITLE
[Core] what are "pure marts"?

### ISSUE THREAD

**Issue by AlexVialaBellander** [fishtown-analytics/docs.getdbt.com#6329]
### Link to the page(s) on docs.getdbt.com requiring updates

https://docs.getdbt.com/best-practices/how-we-structure/4-marts

### Tell us more about this update

What do you mean with "pure marts" here? A colleague asked me and I cant explain it well enough. Could it be expanded? 

### Reviewers/Stakeholders/SMEs

Not sure who that would be, but probably the authors of the dbt docs. it's your opinionated guide so yea?

**Comment by runleonarun** [comment]
Thank you for opening this issue! @dbeatty10 can you expand on pure marts or recommend another SME?

**Comment by dbeatty10** [comment]
### Current docs

<img width="650" alt="image" src="https://github.com/user-attachments/assets/921b86b6-b2b4-48db-9968-41b4d037908a">

### Explanation

This is more simple than it looks! In this context, "pure marts" just means marts that do **not** include any time-based rollups like `orders_per_day` or `orders_per_week`, but instead use the [semantic layer](https://docs.getdbt.com/best-practices/how-we-build-our-metrics/semantic-layer-1-intro) for dynamic and flexible downstream aggregations.

### Suggestion

To avoid confusion, we could update our docs to be something like this:

✅ **Focus on entity naming.** Use plain English to name the file based on the concept that forms the grain of the mart `customers`, `orders`. It's usually best to avoid including rollups on time dimensions in this layer (such as `orders_per_day`). Instead, consider [refactoring such rollups](https://docs.getdbt.com/best-practices/how-we-build-our-metrics/semantic-layer-8-refactor-a-rollup) into the [semantic layer](https://docs.getdbt.com/best-practices/how-we-build-our-metrics/semantic-layer-1-intro), enhancing flexibility and scalability.
