### ISSUE TITLE
UI issues with the docs home page in Microsoft Edge and Chrome

### ISSUE THREAD

**Issue by sophiad96** [fishtown-analytics/docs.getdbt.com#637]
## Steps to reproduce:
A customer reached out to support, pointing out that the UI for the docs.getdbt.com homepage wasn't behaving as expected and was preventing them from accessing certain links. They specifically sent this screenshot:

![image-1](https://user-images.githubusercontent.com/68790165/115055590-de81c500-9e9e-11eb-8b3e-ec808ad6e732.png)

Upon further investigation, @heysweet discovered another issue when viewing this page in Chrome and resizing the window:

![image-2](https://user-images.githubusercontent.com/68790165/115055655-f6594900-9e9e-11eb-868b-3ec67821abb0.png)

https://app.intercom.com/a/apps/c15gqki8/inbox/inbox/4347151/conversations/66439600084399

## Expected results:
I expected to see exactly what the customer saw.

## Actual results
I downloaded Edge and tried to recreate this on both my laptop (smaller) monitor, as well as my larger monitor. I wasn't able to do so. However, they are on Windows so that might be why.

I was able to recreate the issue that Andrew pointed out in Chrome by resizing my window while on the docs homepage to the minimum vertical on my laptop screen.

**Comment by runleonarun** [comment]
I'm closing this as old. Please let front-end engineering know if this is still a problem!
