### ISSUE TITLE
[Core] - Recommend using new snapshot configurations for net-new snapshots only

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#6374]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/snapshot-configs

### What part(s) of the page would you like to see updated?

Snapshots and incremental models are meant to be long-lived tables. In particular, snapshots capture history of data that might not be available anymore (or is expensive / difficult to replay). So they are more sensitive to either user bugs in modeling logic or bugs in the underlying dbt software -- in the worst case, there can be unrecoverable data loss.

So to reduce the blast radius of potential bugs in the dbt implementation, in we are recommending using the new v1.9 snapshot configurations with net new snapshots rather than pre-existing ones. This is in the same spirit as https://github.com/dbt-labs/dbt-core/issues/10923 (which might not be possible or reasonable to implement).

**Comment by graciegoheen** [comment]
For new-new snapshots _or_ migrate your old snapshot before running

**Comment by hope-wat** [comment]
> or migrate your old snapshot before running

Would we essentially recommend running `alter` statements manually?

**Comment by dbeatty10** [comment]
> Would we essentially recommend running `alter` statements manually?

Yes. To perform the applicable migration, we'd be recommending first making a backup copy (or clone) and then applying the applicable `alter` statements either manually or with a script.
