### ISSUE TITLE
Suggested improvements for "Building a new adapter"

### ISSUE THREAD

**Issue by moshir** [fishtown-analytics/docs.getdbt.com#640]
### Describe the feature
**Improve "building an adapter" documentation.**
The current available docs (https://docs.getdbt.com/docs/contributing/building-a-new-adapter) does not cover some of the the common patterns I found in existing adapters (catalog.py, relation.py). Some of the macro mechanisms are not obvious (what are some parameters passed to macros ? e.g. : what is information_schema, what are macros/method signatures). 
Following additions would be nice
1.  the method signatures in the [**Editing the adapter implementation**  section](https://docs.getdbt.com/docs/contributing/building-a-new-adapter#editing-the-adapter-implementation)
2. explaining the relation between [macros](https://docs.getdbt.com/docs/contributing/building-a-new-adapter#required-macros) and [SQL logic](https://docs.getdbt.com/docs/contributing/building-a-new-adapter#editing-the-adapter-implementation)  (before digging in the [dispatch](https://docs.getdbt.com/docs/contributing/building-a-new-adapter#adapter-dispatch) mecanisms)
3. documenting base [macros](https://docs.getdbt.com/docs/contributing/building-a-new-adapter#required-macros)  signatures in the required macros section (what is information_schema_name, why does it take database, where does it come from) 

As there are so many contributed adapters out there, I feel i'm certainly missing something :) 

### Describe alternatives you've considered
Looking at the code in repositories for spark, presto adapters, as well as code from core adapters
### Additional context
No
### Who will this benefit?
Any adapter contributor for databases not covered and that could be a dood fit for dbt (e.g. : firefolt, trino )

### Are you interested in contributing this feature?
Sure

**Comment by runleonarun** [comment]
@dataders or @moshir either of you willing to open a PR to address this, or should I close it to be addressed when the docs team has capacity?

**Comment by mirnawong1** [comment]
hey @dataders, wanted to flag this again to see if we can open up a pr to address this! 🙏

**Comment by mirnawong1** [comment]
hey @dataders and @moshir , great suggestion! I'm going to close this issue up but please feel free to re-open it to address this.
