### ISSUE TITLE
invalidate_hard_deletes missing from snapshot configurations

### ISSUE THREAD

**Issue by alison985** [fishtown-analytics/docs.getdbt.com#6405]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/snapshot-configs

### What part(s) of the page would you like to see updated?

The specification does not include `invalidate_hard_deletes` as an option. It seems like it was not integrated in. As a reference page it should show all the options.

### Additional information

This topic is covered here: https://docs.getdbt.com/reference/resource-configs/invalidate_hard_deletes

**Comment by mirnawong1** [comment]
hey @alison985, thanks for opening this issue and flagging this to us! we've gone ahead and updated the doc to add this back in - really appreciate your contribution!
