### ISSUE TITLE
Dagster dbt link broken link in docs

### ISSUE THREAD

**Issue by sarahkb125** [fishtown-analytics/docs.getdbt.com#643]
## Steps to reproduce:

In the dbt docs for Dagster [here](https://docs.getdbt.com/docs/running-a-dbt-project/running-dbt-in-production), the link for dagster_dbt goes to a broken page 

## Expected results:

I think it should be dagster-dbt instead:
https://docs.dagster.io/_apidocs/libraries/dagster-dbt

## Actual results

Instead, it goes to [here](https://docs.dagster.io/_apidocs/libraries/dagster_dbt) and has an error:
![image](https://user-images.githubusercontent.com/46351382/115711926-26db3000-a342-11eb-8006-9cb5e1189935.png)

**Comment by clrcrl** [comment]
Thanks Sarah! Just updated the link :) 

For broken links / quick fixes, feel free to use the "Edit this page" button at the bottom of each docs page
