### ISSUE TITLE
Redshift IAM Authentication docs mistake

### ISSUE THREAD

**Issue by korasino** [fishtown-analytics/docs.getdbt.com#644]
### Describe the bug
There is a mistake in Redshift profiles.yml configuration docs. In ﻿﻿[IAM Authentication#](https://docs.getdbt.com/reference/warehouse-profiles/redshift-profile#iam-authentication) section "cluster_id" configuration key should NOT be wrapped in "[]" array notation.

**Comment by korasino** [comment]
Hi @jtcohen6, I see the problem now, yeah, it's definitely confusing. But from what I can see other places in docs use square braces as well (for example https://docs.getdbt.com/reference/warehouse-profiles/postgres-profile).

So, I suppose that it would be the best to either to change all placeholders (in all docs subpages) to `<>`, either to just remove those prefilled made-up values and put `[]` there.

Second option is cool, but db_groups is actual array, which would be still a little bit  confusing

**Comment by runleonarun** [comment]
This has been updated in [the docs](https://docs.getdbt.com/reference/warehouse-setups/redshift-setup#iam-authentication). Let us know if you see any other problems by opening a new issue!
