### ISSUE TITLE
Add list_relation configuration flags for `dbt-snowflake`

### ISSUE THREAD

**Issue by mikealfare** [fishtown-analytics/docs.getdbt.com#6441]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-configs/snowflake-configs

### What part(s) of the page would you like to see updated?

We added two new project flags for configuring the pagination of `list_relations_without_caching`. I think this might be a new section; it doesn't appear to fit in any of the existing sections.

This will not be used very often, so putting it at the end is fine. The idea is that the default configuration allows for a maximum of 100K objects per schema in Snowflake. This is done as 10 pages of 10K objects. The user can configure either of these numbers, but will likely only configure the number of pages. I don't think Snowflake supports more than 10K per page, so this setting can only go down.

### Additional information

Context: https://github.com/dbt-labs/dbt-snowflake/pull/1235

**Comment by matthewshaver** [comment]
Closed with https://github.com/dbt-labs/docs.getdbt.com/pull/6445
