### ISSUE TITLE
[Core] microbatch, running batches in parallel

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#6550]
### Link to the page(s) on docs.getdbt.com requiring updates

- https://docs.getdbt.com/docs/build/incremental-microbatch

### Tell us more about this update

- we need docs for microbatch batches running in parallel
    - when you would want to run batches in parallel and when you would not
    - new config for running batches in parallel - `concurrent_batches` (default based on usage of {{ this }} and whether or not adapter supports)
    - which adapters support it

Core PR here - https://github.com/dbt-labs/dbt-core/pull/10958
Adapter PRs to come

### Reviewers/Stakeholders/SMEs

Grace, Doug, Quigley, Michelle

**Comment by mirnawong1** [comment]
once documented, link to new section in line 35. see: https://github.com/dbt-labs/docs.getdbt.com/pull/6544#discussion_r1859293601. specifically, this line here where 'concurrently' needs to link out to the new section:

This is a powerful abstraction that makes it possible for dbt to run batches [separately](#backfills), concurrently, and [retry](#retry) them independently.

**Comment by nataliefiann** [comment]
Hiya @mirnawong1 

I've assigned this one to myself. I'll pick this up.

Kind Regards
Natalie

**Comment by nataliefiann** [comment]
Hiya @graciegoheen 

I'm picking this up for @mirnawong1 
I've created a draft [notion](https://www.notion.so/dbtlabs/Microbatch-running-batches-in-parallel-14dbb38ebda7804aa80ef5f55c6f14ce) for this but I just wanted to ask with the part on adapters that support the microbatches running in parallel - are those the adapters mentioned [here](https://docs.getdbt.com/docs/build/incremental-strategy#supported-incremental-strategies-by-adapter) under the microbatch section?

Kind Regards
Natalie

**Comment by runleonarun** [comment]
Hey @nataliefiann, you should work with @mirnawong1 and @QMalcolm on this! Grace is OOO

**Comment by nataliefiann** [comment]
Thanks @runleonarun 
@mirnawong1 has scheduled a meeting with me on this today so I should be able to get this PR'd and I'll @ Malcolm for the tech review

Kind Regards
Natalie

**Comment by nataliefiann** [comment]
Hiya @QMalcolm 

I'm going to start drafting my PR on this but whilst I do so, I have a few questions if you wouldn't mind shedding some light please:

- How does parallel execution work with backfills and retries? Specifically - can people retry failed batches at the same time?

- Do we need a separate page for the `concurrent batches` config (like https://docs.getdbt.com/reference/resource-configs/event-time)?

Is this (running in parallel) only supported for models? And within models, is it only supported in project.yml file, properties.yml and sql file (concurrent batches) config?

Is there a limit to how many models can be run in parallel, does it depend on factors such a batch size, event time etc?

Also, with regards to the adapters that support the microbatches running in parallel feature - are those the adapters mentioned [here](https://docs.getdbt.com/docs/build/incremental-strategy#supported-incremental-strategies-by-adapter) under the microbatch section?

Kind Regards
Natalie

**Comment by mirnawong1** [comment]
also does `concurrent_batches` need its own page? i think yes imho since the other configs are going to get their pages too.

**Comment by runleonarun** [comment]
closed by https://github.com/dbt-labs/docs.getdbt.com/pull/6589
