### ISSUE TITLE
1.9+ snapshots docs should probably keep the legacy syntax as well

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#6561]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/build/snapshots

### What part(s) of the page would you like to see updated?

When viewing docs for v1.9 or Versionless, the "Configure snapshots in versions 1.8 and earlier" section says 

> The latest versions use an updated snapshot configuration syntax that optimizes performance.

This isn't accurate - the code that it generates + runs against the warehouse is going to be the same, but _configuring_ the snapshot in YAML can be more pleasant because there's less fiddly bits. _Edit: I've just seen that the 1.8 docs explain that it's because multiple nodes in a single file is trickier to parse. I guess that is true, but in the grand scheme of things it's not a huge deal._

Separate to that, my preference would be to have _both_ styles of configuration provided for new versions of dbt. New versions of dbt have not removed the classic snapshot syntax and people may still need to see how to configure them. Right now, I think that the classic syntax would just get deleted from the docs site once v1.8 goes EOL, which isn't right.

**Comment by mirnawong1** [comment]
hey @joellabes , this is a great callout and sorry for not being clear about it. 

- so during beta, we wanted to version block the legacy configs so users building net new snapshots would see the more performant and preferred way to configure them. 
- i [met with @dbeatty10 ](https://www.notion.so/dbtlabs/Mirna-x-Doug-13ebb38ebda780f7a95fc5022e636254?pvs=4) to learn about why the config is helpful.
- there is a [docs plan](https://www.notion.so/dbtlabs/Create-legacy-snapshot-page-14cbb38ebda780aebb7ad32131f669fd) to have a [separate legacy snapshot page](https://www.notion.so/dbtlabs/legacy-jinja-snapshot-doc-119bb38ebda780d1b435de9638d5139b?pvs=4) that contains all the legacy configs (incl the .sql file one) so users can find them and we don't lose these specifications. I plan to then rejig that page and link to the legacy page so it's available for all versions if they choose. 
- for the legacy page, i'm currently working on it and plan to have it hopefully live by the end of the year. 

For the 1.9 bit, i can modify that sentence so it says the following instead:

> The latest versions use an updated snapshot configuration syntax that significantly slow down parsing and compilation.

would love to hear your thoughts on this!

**Comment by joellabes** [comment]
> For the 1.9 bit, i can modify that sentence so it says the following instead:
> 
> > The latest versions use an updated snapshot configuration syntax that significantly slow down parsing and compilation.

How about 

> The latest versions use a more ergonomic snapshot configuration syntax that also speeds up parsing and compilation.

?
