### ISSUE TITLE
[Minor] Correct the Documentation for Upgrade to 1.7 (clean-paths)

### ISSUE THREAD

**Issue by aiwithwhitehat** [fishtown-analytics/docs.getdbt.com#6712]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://github.com/dbt-labs/docs.getdbt.com/blob/6a1e40d949a04215a1a9a9eee927dc1967de5a38/website/docs/docs/dbt-versions/core-upgrade/08-upgrading-to-v1.7.md?plain=1#L69C41-L69C136

### What part(s) of the page would you like to see updated?

The content under the subsection for `dbt clean` refers to the `clean-paths` in `dbt-project.yml`.
This requires correction because it is actually `clean-targets` and not `clean-paths`
The correction would involve changing `clean-paths` to `clean-targets`

### Additional information

Assigning to self

**Comment by mirnawong1** [comment]
Closed as addressed in pr #6713
