### ISSUE TITLE
Typo in command for finding profiles.yml

### ISSUE THREAD

**Issue by rsanjabi** [fishtown-analytics/docs.getdbt.com#679]
## Steps to reproduce:

* Go to [Debugging Errors](https://docs.getdbt.com/docs/guides/debugging-errors).
* Click on the "Debugging" under _Failed to Connect_

## Expected to see:

> Open your profiles.yml file (if you're unsure where this is, run `dbt debug --config-dir`)

## Actually see:
* Instead  `dbt debug --config dir` is listed with a missing hyphen

**Comment by clrcrl** [comment]
Thanks so much! I just fixed this on the default branch :), it should be updated in a few minutes.

Feel free to also open PRs for small fixes like this — every page has an "edit this page" button at the bottom of it, which should put you into the GitHub UI on the right page to make the change
