### ISSUE TITLE
happier path for new dbt users in Azure/MSFT stack

### ISSUE THREAD

**Issue by dataders** [fishtown-analytics/docs.getdbt.com#691]
## Issue

Folks looking to use SQL Server, Azure SQL, and Azure Synapse have a hard time understanding which adapters to use

see:
- https://github.com/embold-health/dbt-azuresynapse/issues/15
- https://github.com/embold-health/dbt-azuresynapse/issues/16

## Background

The [available adapters](https://docs.getdbt.com/docs/available-adapters) lists two adapters for each of SQL Server and Azure Synapse, but only one of them is up-to-date for each product.

![image](https://user-images.githubusercontent.com/8158673/121808692-c1ac0880-cc27-11eb-97ad-12663584acbf.png)

### Current status
| Adapter                                                               | dbt version | Last Commit  | Notes                  |
|-----------------------------------------------------------------------|-------------|--------------|------------------------|
| [dbt-mssql](https://github.com/jacobm001/dbt-mssql)                   | 0.14.4      | 9 months ago | Archived two weeks ago |
| [dbt-azuresynapse](https://github.com/embold-health/dbt-azuresynapse) | 0.17.1      | 7 months ago |                        |

## Potential Solutions

1. Remove `dbt-mssql` and `dbt-azuresynapse` from the list of community-supported adapters (as they are no longer supported by the community?)
2. Add a new column, "Actively Maintained?" to clearly indicate if it it likely the adapter works with the current version of dbt
3. Move the unsupported adapters to the bottom of the list (or hang their jerseys from the rafters? 😆 )

## To be consulted

@jacob001 & @mattberns, any strong opinions here? I defer to whatever y'all think is best for users.

**Comment by annafil** [comment]
@swanderz thanks for thinking about this! 👍 to  removing the archived adapter. Given we have an actively maintained alternative, agree that listing both would be confusing. 

@jacobm001 mentioning you in here with the right handle to make sure you see this. Thank you for being a good citizen and letting folks know when something is no longer being maintained, and pointing folks to an alternative 🙏 I'm assuming you're OK with the above given your archive note, but if not, holler in Slack and we can sort it out :) 

@mattberns Would love your input on `dbt-azuresynapse` :) Hit me up in a DM on the Community Slack if I can be helpful here, or you wanna chat in more detail.

**Comment by jacobm001** [comment]
@annafil Yes, this is fine with me. I probably should have reached out about this before, but I didn't think about it. 😅

Happy to help unify the groups. 🙂

**Comment by mattberns** [comment]
When we launched dbt-azuresynapse, @swanderz I believe was just starting out - and now that repo has really come so much further along. I definitely approve this change. Its on our roadmap to upgrade to 19 and use this. Definitely approve.

**Comment by dataders** [comment]
@jacobm001 @mattberns thanks for getting back so quickly.

I have two PRs open currently:

-:heart: #698 removes your adapters from the page
-:rocket: #693 marks them as no longer maintained and moves them to the bottom of the list

which would you prefer (vote w/ emoji)?

**Comment by annafil** [comment]
👏  thank you all for jamming on this together, and so quickly! This discussion makes me so happy ❤️

**Comment by annafil** [comment]
![](https://media.giphy.com/media/bKnEnd65zqxfq/giphy.gif)
