### ISSUE TITLE
Confusing / bad pattern suggestion for 'Using variables' section

### ISSUE THREAD

**Issue by ghost** [fishtown-analytics/docs.getdbt.com#701]
The suggestion of using variables to `avoid hardcoding table names` feels like a confusing use case for a beginner. I've now seen a couple people new dbt do this unnecessarily on top of or instead of sources, and the link it sends you out to is a defunct Quickbooks repo with 5 year old code. Seems like it's time for an update? See it in [docs here](https://docs.getdbt.com/docs/build/project-variables#defining-variables-in-dbt_projectyml)

<img width="805" alt="Screen Shot 2021-06-18 at 8 43 02 AM" src="https://user-images.githubusercontent.com/78385474/122571113-006c0500-d012-11eb-9109-750f05c38d87.png">

I would suggest linking to a pattern for optionally flipping a `limit in dev` macro on or off with a variable, this is a very useful pattern for most users. Happy to write up a Gist or discourse post to link to if that's agreed on.

**Comment by annafil** [comment]
Agreed. What do you think about adding an example to [the reference](https://docs.getdbt.com/reference/dbt-jinja-functions/var) that we can link to in the Using variables section? Feels like a solid example can really help make "a-ha" moments for folks when they look up the reference.

**Comment by runleonarun** [comment]
Closing as stale. We can fix if there are support cases.
