### ISSUE TITLE
Revamp select documentation

### ISSUE THREAD

**Issue by VersusFacit** [fishtown-analytics/docs.getdbt.com#706]
`--select` and `--models` flags need significantly improved documentation both for dbt Labs folks and community folks.

The particular case that spawned this issue (although it's come up plenty of times in the past):

<img width="595" alt="image" src="https://user-images.githubusercontent.com/67295367/123155947-90002200-d41d-11eb-89b6-85382fb987f7.png">

It's unclear when to use one or or the other and with which commands. We should have a page that summarizes the grammar and functionality of different command/option combinations.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/67295367/123155870-78c13480-d41d-11eb-95ac-2ecc831fa3d6.png">

Case and point:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/67295367/123158134-3ea56200-d420-11eb-8f8e-628575609b3a.png">

**Comment by jtcohen6** [comment]
Right on!

There is a table here of which flags go with which command: https://docs.getdbt.com/reference/node-selection/syntax

Ian is also totally right, we want to make this `--select` across the board (`--models` will still work, it just shouldn't be documented): https://github.com/fishtown-analytics/dbt/issues/3210

**Comment by jtcohen6** [comment]
Going to consider this resolved by v0.21 and https://github.com/dbt-labs/docs.getdbt.com/pull/802 / https://github.com/dbt-labs/docs.getdbt.com/pull/802/commits/58b8ed23d7bd197513d76192dec31ae6da8d4678
