### ISSUE TITLE
Setting up page has incorrect IAM roles for BigQuery

### ISSUE THREAD

**Issue by cdlethem** [fishtown-analytics/docs.getdbt.com#707]
## Steps to reproduce:

* Go [here](https://docs.getdbt.com/tutorial/setting-up#generate-bigquery-credentials)
* Look at step 2, sub-point "Role" where it says: `Role: BigQuery Job User & BigQuery User`

## Expected results:
It should also include BigQuery Editor

## Actual results
It does not include BigQuery Editor

## Extra details
IAM with BigQuery works differently than table/schema grant-based permissions. A service account with BigQuery User and BigQuery Job User roles alone can create datasets, but not tables within the new dataset. It can run queries and jobs, but not create tables or even view data in any existing tables.

**Comment by runleonarun** [comment]
@cdlethem Thank you for raising this issue! We are going to redo the Getting Started tutorial and will address this issue when we do.
