### ISSUE TITLE
Add property file tags reference to page in docs

### ISSUE THREAD

**Issue by VersusFacit** [fishtown-analytics/docs.getdbt.com#717]
This page https://docs.getdbt.com/reference/resource-configs/tags should have a small note on the ability to label tags on individual models in properties.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/67295367/124047184-6e2c0f80-d9c8-11eb-98a4-fb23b0e33036.png">

See [this page](https://docs.getdbt.com/reference/resource-properties/tags), which probably needs a bit of beefing up itself.

**Comment by jtcohen6** [comment]
> Note that you need to use the tag _configuration_ to apply tags to models, seeds, and snapshots. (Yes, we know this is confusing, and hope to resolve it in a future release!)

We might be working on this very soon :)

**Comment by jtcohen6** [comment]
I think this was resolved via #766, where we consolidated `resource-configs/tags` and `resource-properties/tags` into a single page, just called `tags`
