### ISSUE TITLE
Link to dbt_utils information under tests section of dbt docs is broken

### ISSUE THREAD

**Issue by kdw2126** [fishtown-analytics/docs.getdbt.com#719]
## Steps to reproduce:
* Go to [this page](https://docs.getdbt.com/docs/building-a-dbt-project/tests).
* Click on the "dbt-utils" link under "info" in the sentence "We've open sourced some useful schema tests in dbt-utils — skip ahead to the docs on packages to learn more!"

## Expected results:
*  I expect to go to the dbt_utils page under hub.get-dbt.com to see more information about this package. 

## Actual results
* Instead I get a 404 error.

## Extra details
It seems like someone on your team changed all references of "Fishtown Analytics" to "dbt labs" in the documentation website, but the website still references [Fishtown Analytics](https://hub.getdbt.com/fishtown-analytics/dbt_utils/latest/) in the URL.

**Comment by jtcohen6** [comment]
Thanks for opening @kdw2126.

> It seems like someone on your team changed all references of "Fishtown Analytics" to "dbt labs" in the documentation website

It was I!

Within the next week, we're going to migrate packages on the Hub site so that they appear under `dbt-labs`, and we're assessing a few options to avoid (or minimize) breaking changes.

**Comment by kdw2126** [comment]
Ha ha, sorry if that came across as a bit passive-aggressive.  Thanks for the quick response -- appreciate all you do at dbt labs!

**Comment by jtcohen6** [comment]
You're good!! Didn't mean to imply that in any way. It's a transitional period, there are going to be some things dropped along the way, genuinely appreciate you chipping in :)

**Comment by kdw2126** [comment]
This is working now so I'm closing this issue.  Thanks for the help!
