### ISSUE TITLE
Improve documentation around intersection of partitions + materializations + incremental strategies on BigQuery

### ISSUE THREAD

**Issue by tmshn** [fishtown-analytics/docs.getdbt.com#776]
Replacing partition(s) is a good strategy to partialy update time-growing BigQuery table idempotently.

While it is supported in dbt, its behavior is hard to understand, and actually there seem to be some bugs.

| Partitioning type           | dbt configuration                                                  |
| :-------------------------- | :----------------------------------------------------------------- |
| Ingestion time partitioning | `materialization='table'` and specifies `partitions`               |
| Column based partitioning   | `materialization='incremental', incremental_strategy='insert_overwrite'` |

## Problems

1. Partial update (i.e.: non full replace) of ingestion-time partitioned table is achieved using `materialization='table'` unlike column partitioned table
2. Cannot specify time granularity for ingestion-time partitioned table
3. With `incremental_strategy='insert_overwrite'`, specifying both `partition_by` and `partitions` has two bugs: 1. it raises type error, 2: it trys to insert data out of specified partition
4. With some combination of options, specified value is ignored, but undocumented
    - `materialization='table'` and specify `partitions` → `partition_by` is ignored
    - `incremental_strategy='insert_overwrite'` → `unique_key` is ignored
    - `incremental_strategy='merge'` → `partitions` is ignored

## Suggested solutions

1. Allow `partition_by = {'field': '_PARTITIONTIME'}` to make ingestion time partitioned table
2. Make `partitions` option to work only with `'insert_overwrite'`-ing ingestion time partitioned table
    - This change makes `materialization='table'` behave only full replace, so it going to be a breaking change
3. Enhance document so that user can understand the behavior based on the combination of options

Note:

- `partition_by` option should be supported on `materialization='table'` (full replace) or `incremental_strategy='merge'` too

**Comment by tmshn** [comment]
> In the meantime, I'm going to transfer this issue to the docs.getdbt.com repo, since that will be the place to contribute improvements to documentation.

Oh I was lost in woods of dbt-labs/dbt like "where's my issue gone?" haha!

---

> we'd actually like to rip it out in its entirety ([dbt-labs/dbt#2332](https://github.com/dbt-labs/dbt/issues/2332))

> In lieu of ingestion-time partitioning, we believe everyone should be using **column-based partitioning**.

> 1. I'm not sure I understand the implications of a user specifying `partition_by = {'field': '_PARTITIONTIME'}`, if it's not actually an ingestion-partitioned table.

I understand it's good idea to encourage users to use column-based partitioning instead of "ingestion-time" partitioning so that they can have better/explicit controlling over how a table is partitioned.

However, it's sill quite popular to use ingestion-time partitioning in my organization wide, and they are _actually_  ingestion-time partitioned. The reason we explicitly specify partitions are

- It's a good way to make jobs idempotent. Running query with `writeDisposition: WRITE_TRUNCATE, destiantionTable: foo.bar.baz$20210823` replaces the partition (here, the date is the actual date it runs), unlike running with `writeDisposition: WRITE_APPEND, destiantionTable: foo.bar.baz`.
- It's necessary to run on delayed recovery for incidents like a job failure. In this case, the date specified will be the date the job is planned to run, not the actual date it runs, so the exception for "ingestion time".

Of course any use case of ingestion-time partitioning can be covered by column-based partitioning, but migration won't happen unless there's strong motivation. So I'd be little happier if ingestion-time partitioning will be stayed as a first-class citizen in dbt (note that we've just started using dbt in a experimental project, so it won't bother us even if the change happens).

**Comment by tmshn** [comment]
> * There may be a few buggy edge cases with `incremental_strategy: insert_overwrite` + specific values of `partitions` + `partition_by`. If you could open those bug reports as new issues, I'd really appreciate it!

Here: https://github.com/dbt-labs/dbt/issues/3788

**Comment by runleonarun** [comment]
@tmshn It appears this issue has been addressed so I am going t close it out. Feel free to reopen if I am wrong!
