### ISSUE TITLE
Error threshold documentation has bad SEO

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#787]
## Steps to reproduce:
Search Google for `error threshold dbt test`

## Expected results:
- Be linked to https://docs.getdbt.com/reference/resource-configs/severity

## Actual results
An entire screen of different posts from Discourse, docs, next.docs, and GitHub that all claim such functionality is impossible
![image](https://user-images.githubusercontent.com/7335046/130951413-08c74d56-a9c8-4f8b-b232-214a3548f476.png)

## Extra details
The [FAQ](https://docs.getdbt.com/faqs/custom-test-thresholds) and [Discourse](https://discourse.getdbt.com/t/creating-an-error-threshold-for-schema-tests/966) in particular should be updated to reflect our wonderful new world of customisable test severity thresholds

**Comment by runleonarun** [comment]
Fix: add a description to the header [in this page](https://docs.getdbt.com/reference/resource-configs/severity). For example:
```
---
title: "Configuring test `severity`"
id: "from-source"
description: "You can use error thresholds in dbt to configure the severity of test results, or how many failed tests will produce an error or warning."
resource_types: [tests]
datatype: string

---

```

**Comment by matthewshaver** [comment]
Added fix based on @runleonarun to PR https://github.com/dbt-labs/docs.getdbt.com/pull/1922
