### ISSUE TITLE
Full changelog link broken for v.0.21.0

### ISSUE THREAD

**Issue by bthomson22** [fishtown-analytics/docs.getdbt.com#841]
## Steps to reproduce:

- head to https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-21-0
- click on "Full Changelog"
- Observe broken link

## Expected results:

I believe this should navigate to https://github.com/dbt-labs/dbt/blob/0.21.latest/CHANGELOG.md instead of https://github.com/dbt-labs/dbt/blob/0.21.0/CHANGELOG.md

## Actual results

404 error

## Extra details

Seems like a straightforward change but wanted to make sure it was on the radar!

**Comment by jtcohen6** [comment]
@bthomson22 You're spot on
