### ISSUE TITLE
Document that `alias` is available for tests now

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#890]
https://github.com/dbt-labs/dbt-core/issues/4097 will help people learn how to alias their tests, probably by directing them to the [documentation for alias](https://docs.getdbt.com/reference/resource-configs/alias). 

Right now, that page doesn't say that tests are aliasable at all. It should! 

Example code in [this comment](https://github.com/dbt-labs/dbt-core/issues/3626#issuecomment-886694083)

**Comment by runleonarun** [comment]
Thanks for raising this, Joel 🙇🏻‍♀️

**Comment by joellabes** [comment]
Just came up again: https://getdbt.slack.com/archives/C01UM2N7814/p1642764358053000

**Comment by joellabes** [comment]
I don't know who did this, but it's done! https://docs.getdbt.com/reference/resource-properties/tests#define-a-custom-name-for-one-test
