### ISSUE TITLE
Rename the Getting Started Tutorial to the Quickstart Tutorial

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#904]
This better reflects the purpose of the tutorial, and helps to differentiate it from the Fundamentals course. [As discussed in Slack](https://dbt-labs.slack.com/archives/CFQ823PMH/p1636422640022900)

Will also need to set up redirects for existing links, and change references around the rest of the Docs site.

**Comment by runleonarun** [comment]
I think we're going to end up creating warehouse-specific "quickstarts" so I'm going to close this for now. Thank you!
