### ISSUE TITLE
FAQ: why does dbt need a DB connection to compile code? 

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#922]
A reasonably common question on the Slack, and we don't have a canonical link to an answer. 

[Writeup from jerco](https://dbt-labs.slack.com/archives/C017GDLAF7D/p1637749148476900) in the internal slack:

> That's basically it. I'd just add that "introspective queries" also includes populating the relation cache, in order to resolve things like:
> - `is_incremental()`
> - `ref` in `--defer` mode (since it depends on whether the dev version exists in the database)

> jerco  5 minutes ago
> That doesn't get us a ton today, but in a future where materializations can report more of what they're going to do before they do it (i.e. a "dry run" mode), a `compile` task will:
> - be much more valuable
> - still require a database connection

> jerco  4 minutes ago
> If you just want to parse your project and write out `manifest.json`, that can be done with `dbt ls`, without a database connection — the only difference being, the written-out manifest won't include `compiled_sql`

Most recent initiating question from the community Slack: https://getdbt.slack.com/archives/CBSQTAPLG/p1637735870398400

**Comment by runleonarun** [comment]
This would really help the docs, thanks Joel! I have prioritized this issue, but I think we can incorporate this important info in the docs proper. Maybe also as an FAQ.
