### ISSUE TITLE
Include Databricks in the Spark-focused doc titles

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#935]
Specifically https://docs.getdbt.com/reference/resource-configs/spark-configs and https://docs.getdbt.com/reference/warehouse-profiles/spark-profile

@amychen1776 recommends calling them Databricks & Spark [Profile|Configuration]. I told them I would do it but am making a note so I remember!

**Comment by amychen1776** [comment]
Thank you!

**Comment by amychen1776** [comment]
Closed this issue because of Databricks's owning the adapter announcement
