### ISSUE TITLE
Define user labels like "Member" and "Everyone"

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#973]
## Problem

A team plan user asked if we could specify in documentation the difference between user labels like “Member” and “Everyone” in the directory.

## Extra details

More questions to answer:
* On the Team plan, isn’t the only apparent difference within the “Owner” group?
* Do member and owner roles in enterprise have explicit permission sets? (Seems like no.)
* Feature request: Could we use ones that map to enterprise permissions (Account Admin and Developer...I think...)?

**Comment by lgreene27** [comment]
Currently there is no documentation on what the permissions are that a Member or Owner have. In the UI when you look at these groups there are also no permissions listed, so it looks like they have no permissions, but that's not true. My understanding is that and Owner = Account Admin and has all admin permissions on the account and a Member = Developer. But I honestly do not know if that is true as I don't know any way to verify or test it

In Enterprise accounts (all accounts?), Owner and Member groups exist by default and new users are defaulted to be Members. This can cause confusion and lead to folks having unexpected permissions when they become Members unintentionally.

**Comment by runleonarun** [comment]
Thank you @lgreene27 this is super helpful!

**Comment by runleonarun** [comment]
We have these permissions called out on [this page](https://docs.getdbt.com/docs/collaborate/manage-access/self-service-permissions#overview) now, so I'm going to close this issue!
