### ISSUE TITLE
Create overview page for migration guides

### ISSUE THREAD

**Issue by jasnonaz** [fishtown-analytics/docs.getdbt.com#978]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

Everything in the migration-guides section (which humorously I can't link to, that being the subject of this issue). Example [migration guide](https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-1-0-0)

### What changes are you suggesting?

It would often be helpful for us to be able to link to a single page that contains general information on what migration guides are, how they are used and lists all of the available migration guides. This would be useful for linking to migration guides
- In the docs, for example in #977 I link to the migration guide for v1.0.0, but it would be better to be able to link to an overview page for migration guides
- In the community we can share this when people are asking about migrating without reference to specific versions

**Comment by runleonarun** [comment]
We just upgraded docusaurus and now we can actually do this! Here's [some prior art](https://docs.getdbt.com/docs/dbt-cloud/cloud-overview) when we're ready to address.

**Comment by fernandascovino** [comment]
Hey! This link for a Migration Guide current in the docs isn't working: https://docs.getdbt.com/guides/migration-guide (I think it is the one @jasnonaz said it couldn't link here)

It is referenced on https://docs.getdbt.com/docs/core-versions#version-support-prior-to-v10

The result page is:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/20743819/165786437-c11975b0-3b1a-4a4f-8ef5-47bb133f391b.png">

**Comment by runleonarun** [comment]
@fernandascovino Thanks for bringing this up! It looks like it's missing part of the URL. Here's the correct one: https://docs.getdbt.com/**docs/**guides/migration-guide

I opened a PR to fix: https://github.com/dbt-labs/docs.getdbt.com/pull/1393

**Comment by jtcohen6** [comment]
Oh snap, we did this!

**Comment by runleonarun** [comment]
@jtcohen6 I think there's some weirdness when we add an auto-generated page. We need to add the docs directory. Whereas before, I don't think we needed to do that.

**Comment by gwenwindflower** [comment]
Will be fixed by #1420

**Comment by runleonarun** [comment]
Closing this because migration guides now live here: https://docs.getdbt.com/guides/migration/versions
