### ISSUE TITLE
DBT CLI Tutorial "Create a Project" flow doesn't align with current CLI

### ISSUE THREAD

**Issue by TohnJhomas** [fishtown-analytics/docs.getdbt.com#980]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

Specificlaly this page: https://docs.getdbt.com/tutorial/create-a-project-dbt-cli

### What changes are you suggesting?

When you run `dbt init jaffle-shop` it asks you for all the information given in the `connect to bigquery` section. Looks like it's just slightly outdated for the current CLI, since the CLI install instructions were updated recently.

**Comment by runleonarun** [comment]
Thank you for raising this concern, @TohnJhomas! We have this in our queue and will update it as soon as we can.

**Comment by runleonarun** [comment]
Thank you for opening this issue! We're closing as this section has been revised and updated. Feel free to re-open if we are wrong, or open a new issue if you see anything else! 🙇🏻‍♀️
