### ISSUE TITLE
dbt graph-operations is not mentioned in the dbt run command

### ISSUE THREAD

**Issue by chanansh** [fishtown-analytics/docs.getdbt.com#994]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/reference/commands/run

### What changes are you suggesting?

The page `https://docs.getdbt.com/reference/commands/run`
should link to the page `https://docs.getdbt.com/reference/node-selection/graph-operators`
It should say something like: 
> In order to run model's parents and or children models, see graph-operators

**Comment by runleonarun** [comment]
👋🏻 @chanansh Thank you for your suggestion. It's a good idea. I have it in our queue, but it might be a while before we get a PR open (we're just building out a team to work on docs). You are also welcome to open a PR to address this.  🙇🏻‍♀️

**Comment by brad-meru** [comment]
Working on this for hackathon

**Comment by vishalsingh2972** [comment]
is this issue still open @runleonarun ....I see one PR from @brad-meru has already been merged!

**Comment by runleonarun** [comment]
Great catch @vishalsingh2972! The automation didn't pick that up, so I'll close this issue out.

**Comment by brad-meru** [comment]
Hahah I'd totally forgotten I even contributed to this one. Coalesce 2022 memories...
