### ISSUE TITLE
dbt init profile behavior changed in dbt 1.0.0, 'default' no longer default 'profile' value

### ISSUE THREAD

**Issue by varun-dc** [fishtown-analytics/docs.getdbt.com#995]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/project-configs/profile

### What part(s) of the page would you like to see updated?

> If you are working on more than one project, do not use **`profile: default`** as your profile name (as set by the dbt init command), as it will become hard to manage multiple profiles.

In dbt 1.0.0 I'm seeing different behavior. The `dbt init` command sets the `profile` to the project name, eg `dbt init -s test_project` results in `profile: 'test_project'` not `profile: 'default'`

### Additional information

I'm not quite sure what's the best way to update this line in the document, but it definitely appears invalid now that 1.0.0 is released.

**Comment by runleonarun** [comment]
@varun-dc Thank you for pointing this out! We probably just missed it when updating the docs. 

@jtcohen6 Can we go ahead and remove this line from the docs? It seems like there's new behavior with 1.0.0.

**Comment by jtcohen6** [comment]
Absolutely! The `init` behavior is better now, I'd say :) so that parenthetical can go away
